### ISSUE TITLE
When updating a saved payment method, its line 2 isn't updated when the new value is empty

### ISSUE THREAD

**Issue by a-danae** [Automattic/woocommerce-payments#8158] opened 2024-02-08 16:54 UTC
### Describe the bug

When updating the billing address of a saved payment method, the old value of line2 persists when its new value is an empty string.

### To Reproduce

1. Log in as a shopper, add a product to the cart, and go to the checkout page
2. Use the following address as the billing one
```
28224 Chandra Overpass
Unit 2
Port Janean
New Mexico, 50908, United States
```
3. Enter a new payment method, like `4242424242424242`
4. Check off "Save payment information to my account for future purchases" and place the order
5. Go to the Stripe dashboard page for the customer and locate the saved payment method
7. Notice that line2 of the billing address says "Unit 2". All good
<img width="500" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/41606954/229ead33-630f-44de-b1a4-5172066c95e5">

8. Go to the checkout page again
9. Empty line2 from the billing address by deleting the "Unit 2" string. Change line1 to "123 new street"
10. Select the same saved card and place the order
11. Run the [scheduled action](http://localhost:8082/wp-admin/tools.php?page=action-scheduler) with the hook `wcpay_update_saved_payment_method` for the last order 
12. Go to the Stripe dashboard page for the customer and locate the saved payment method
<img width="500" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/41606954/b3892c64-cabd-494c-b373-69b9f4a6d391">

### Actual behavior
The line2 property of the billing address for the payment method isn't updated.

### Expected behavior
I'd expect the line2 of the billing address to be empty when the latest value for this property is empty.

### Additional context

We retrieve the value for the billing address in `WC_Payments_Utils::get_billing_details_from_order()`. We're filtering out empty values for the billing address [here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-utils.php#L361). The line2 doesn't exist in the array we submit to Stripe via [WC_Payments_Customer_Service::update_payment_method_with_billing_details_from_order()](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-customer-service.php#L279-L296)

**Comment by zmaglica** [comment] 2024-02-15 08:42
This issue impacts the Checkout UI, so assigning to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) @FangedParakeet .
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by FangedParakeet** [comment] 2024-02-15 20:53
Cheers, @zmaglica. Have added this to our triage queue. I wonder if its root cause may be related to #5951. CC @gpressutto5, who has just begun working on said issue, in case there may be some overlap.

**Comment by gpressutto5** [comment] 2024-02-16 16:32
I'll test if this issue is fixed when #5951 is done.

**Comment by gpressutto5** [comment] 2024-02-20 19:44
This happens because we are filtering the address array here.

https://github.com/Automattic/woocommerce-payments/blob/061668fd74959d66d63396072357bd43d83fe07c/includes/class-wc-payments-utils.php#L346-L363

A possible solution would be to filter only optional fields, like `state` and `postal_code`.

**Comment by gpressutto5** [comment] 2024-04-23 17:56
Reintroduced by #8689.
Check Slack thread before attempting to fix this again.
p1713894851258879/1713828072.672819-slack-C06V1EKSTC7

**Closed as completed** 2024-05-09 14:42 UTC
Labels: type: bug, component: checkout, category: core, priority: medium, focus: checkout payments
