### ISSUE TITLE
File not found error during plugin upgrades

### ISSUE THREAD

**Issue by malithsen** [Automattic/woocommerce-payments#6304] opened 2023-05-15 16:15 UTC
### Describe the bug

When a file included in `init_rest_api` is removed, it results in a missing file error during the plugin upgrade process.
This happens because `init_rest_api` of the the old version is invoked during the upgrade but the file it's trying to load is removed in the new version.

### To Reproduce

1. Install WCPay 5.8.1.
2. Go through onboarding.
3. Remove `class-wc-rest-user-exists-controller.php`
4. Build the plugin locally
5. Upgrade the site to the plugin built in step 4
6. Expect the fatal error below. 

```
Failed opening '/srv/users/user217f0884/apps/user217f0884/public/wp-content/plugins/woocommerce-payments/includes/admin/class-wc-rest-user-exists-controller.php' for inclusion (include_path='.:/opt/sp/php7.4/lib/php') in /srv/users/user217f0884/apps/user217f0884/public/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php on line 954

Fatal error: Uncaught Error: Class 'WC_REST_User_Exists_Controller' not found in /srv/users/user217f0884/apps/user217f0884/public/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php:955 Stack trace: #0 /srv/users/user217f0884/apps/user217f0884/public/wp-includes/class-wp-hook.php(308): WC_Payments::init_rest_api(Object(WP_REST_Server)) #1 /srv/users/user217f0884/apps/user217f0884/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #2 /srv/users/user217f0884/apps/user217f0884/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #3 /srv/users/user217f0884/apps/user217f0884/public/wp-includes/rest-api.php(577): do_action('rest_api_init', Object(WP_REST_Server)) #4 /srv/users/user217f0884/apps/user217f0884/public/wp-includes/rest-api.php(535): rest_get_server() #5 /srv/users/user217f0884/apps/user217f0884/public/wp-includes/rest-api.php(2889): rest_do_request(Object(WP_REST_Request)) #6 [internal function]: rest_preload_api_request(Array, '/wc-analytics/r...') #7 /srv/use in /srv/users/user217f0884/apps/user217f0884/public/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php on line 955
```

### Actual behavior

Error shown when upgrading the plugin

### Expected behavior

No errors should be printed

### Additional context

Slack thread: p1684148049557989-slack-CGGCLBN58

Related: https://github.com/Automattic/woocommerce-payments/pull/6303

**Comment by zmaglica** [comment] 2024-01-31 20:29
@alefesouza I noticed that this issue is assigned to you. Are you still planning to work on this issue?

**Comment by htdat** [comment] 2024-02-26 06:23
It seems that the cause is described here paJDYF-aZa-p2#comment-21382

**Closed as completed** 2024-03-25 19:46 UTC
Labels: category: core, focus: woopay, Bug
