### ISSUE TITLE
Billing address extends beyond the bounds of the container on the order success page

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#6833] opened 2023-07-21 01:42 UTC
Order success page for a WooPay transaction, long emails will extend beyond the borders of the billing address container
![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/806aeeeb-4fc9-4162-a44b-7640acfcae11)

**Comment by csmcneill** [comment] 2023-07-21 02:25
This seems to be an issue with the Tsubaki theme:

![Markup on 2023-07-20 at 21:23:07](https://github.com/Automattic/woocommerce-payments/assets/82999806/3940f16b-3c3f-4bd7-a72e-0920ba875378)

I'm unable to replicate this with the Storefront theme:

![Markup on 2023-07-20 at 21:24:45](https://github.com/Automattic/woocommerce-payments/assets/82999806/977e5643-cfef-4dc8-9f53-2e0a987ede51)

**Comment by pierorocca** [comment] 2023-07-21 16:45
Moving this issue over to the WooCommerce repository as @rafaelzaleski confirmed WooPay isn't modifying this part of the order success page.

@csmcneill, love the choice of email. :) While your storefront example doesn't visually cross a boundary, it is extending too far over encroaching on the shipping address column. It could equally benefit from wrapping the text to the next line.

**Comment by zmaglica** [comment] 2024-01-31 20:40
@pierorocca this issue was moved to the Other Teams queue since it is related to Shopper Experience. Feel free to tag other teams or me if you think that it belongs to somewhere else.

**Comment by c-shultz** [comment] 2024-01-31 23:18
I bumped this into the Shopper Experience queue. As a next step, I suggest we:
1. Re-test this to confirm that the issue still exists
2. Close this issue and re-open an issue in WooCommerce core (that would probably still be owned by Shopper Experience)

**Comment by frosso** [comment] 2024-02-29 13:33
To give an update on this - It looks like the email address is moved to a separate line item, which can take the full width of the page:
![Screenshot 2024-02-29 at 2 23 27 PM](https://github.com/Automattic/woocommerce-payments/assets/273592/ede38da1-9809-48c5-a1bf-3d781e30b08a)

The billing address doesn't seem to display the email address on Tsubaki:
![Screenshot 2024-02-29 at 2 25 41 PM](https://github.com/Automattic/woocommerce-payments/assets/273592/3760ade4-11a3-42ed-9048-005b713fe61c)

The same thing is happening on non-WooPay orders:
![Screenshot 2024-02-29 at 2 18 25 PM](https://github.com/Automattic/woocommerce-payments/assets/273592/49895fdd-8722-4b44-ae50-54755a1918cf)

However, on mobile devices, the email doesn't wrap, causing the screen to scroll horizontally:
https://github.com/Automattic/woocommerce-payments/assets/273592/5b4c09ce-8fc3-485c-b18a-4df8ee3384f4
As you can see from the screen recording above, also the "downloads" section is affected.

**Comment by frosso** [comment] 2024-02-29 15:10
I realized that the original screenshot must have been taken from the "My account" page - highlighting that there are a few areas that need fixing when the email is too long.

Mobile:
![308964665-eaa24963-f8a0-41bd-9033-1c24f22b2875](https://github.com/Automattic/woocommerce-payments/assets/273592/8214b805-3de9-4362-bdb8-66ef0168d7a8)
Desktop:
![308964569-4dcf19f8-25de-4e2a-bc2c-ead3a1e5cd80](https://github.com/Automattic/woocommerce-payments/assets/273592/f1b09c19-ec1b-4cba-84c7-7d5ecc7cafdd)

I can confirm this is not WooPayments-specific, but it's theme-specific.

**Comment by frosso** [comment] 2024-02-29 15:50
Fixing for both WC core and Tsubaki:

https://github.com/Automattic/theme-tsubaki/pull/52
https://github.com/woocommerce/woocommerce/pull/45220

Closing here, since it's not WooPayments-related.

**Closed as completed by frosso** 2024-02-29 15:50 UTC
Labels: type: bug, component: checkout, category: core, priority: medium
