### ISSUE TITLE
Order total does not equal transaction value with multicurrency and coupon applied

### ISSUE THREAD

**Issue by nicdwilson** [Automattic/woocommerce-payments#4298] opened 2022-05-29 21:23 UTC
### Describe the bug
A multi-currency site applied a coupon to an order with unexpected results. In this case, the merchant was unable to refund the order since the order amount totaled more than the transaction amount.

### To Reproduce
This has not been reproduced

References:
p1653605858086029-slack-C7U3Y3VMY
5173930-zd-woothemes

### Actual behavior

1. Site shop base currency Euro
2. Transaction currency in Pounds
3. WooCommerce Payments base account in Euros

1. A 100 euro coupon was applied to a Pound denominated purchase
2. This shows as £84 in line item
3. The order subtotal calculation results from an £84 coupon
4. Order subtotal calculation 335 - 84
5. The order total calculation is £251
6. The subtotal presentation of the coupon is £84.25
7. The transaction actual total is £250.75
8. This is presented in WooCommerce  Payments as £250.75
10. A refund carried out resulted in a reject refund of £251 (refund total higher than transaction total)

### Screenshots

![Annotation on 2022-05-30 at 09-16-07](https://user-images.githubusercontent.com/3624025/170891772-8e93e668-8ae4-42c4-b132-fbba2bb82147.png)

<img width="1723" alt="Markup 2022-05-30 at 09 17 18" src="https://user-images.githubusercontent.com/3624025/170891978-5a29449a-6ba1-486a-b48a-5b11842c491b.png">

<img width="881" alt="Markup 2022-05-30 at 09 20 37" src="https://user-images.githubusercontent.com/3624025/170891879-6c2e2493-8e7f-4cbb-92d2-6bfb360a4d0b.png">

### Expected behavior
Order totals equal transaction value

### Additional context
https://github.com/woocommerce/woocommerce/issues/33161
p1653605858086029-slack-C7U3Y3VMY
5173930-zd-woothemes

**Comment by jbordonado** [comment] 2022-06-03 14:04
I tried to reproduce but was not successful.

My first impression is that this sounds like a rounding issue within WooCommerce.
I see that an issue is being worked on here: https://github.com/woocommerce/woocommerce/issues/33161

The refund failed because Stripe detected that the amount to refund was greater than the order's total.
That means we contacted Stripe's API.
So the below check that we do before contacting Stripe was successful on our side (i.e. we didn't notice that the amount was greater than the total, otherwise we'd have shown a popup with that error message): 
https://github.com/Automattic/woocommerce-payments/blob/01355e16d1664ebc54ec764b0a6d327ae31491e8/includes/class-wc-payment-gateway-wcpay.php#L1515-L1520

I had a look in what we do next and if there is a rounding issue, I guess that would be here as I didn't see anything suspicious elsewhere: https://github.com/Automattic/woocommerce-payments/blob/01355e16d1664ebc54ec764b0a6d327ae31491e8/includes/class-wc-payment-gateway-wcpay.php#L1549

Here is what we do to format the amount before sending it to the server endpoint, but that's it I think:

https://github.com/Automattic/woocommerce-payments/blob/01355e16d1664ebc54ec764b0a6d327ae31491e8/includes/class-wc-payments-utils.php#L119-L126

I'm not sure we're doing something wrong on our side. But hard to tell without reproducing properly this strange case..

**Comment by zmaglica** [comment] 2022-07-28 12:51
Asked @nicdwilson for more information. I will update my comment when info is provided.

**Comment by nicdwilson** [comment] 2022-07-28 22:22
Hi @zmaglica As per the original p1653673162896669/1653605858.086029-slack-C7U3Y3VMY this was never reproduced. I agree with @jbordonado  that it may have more to do with core rounding than WC Payments. AvaTax for example experiences similar issues because core rounds coupons differently.

**Comment by zmaglica** [comment] 2022-08-23 10:05
I also haven't been able to reproduce an issue. I will close this issue. Please don't hesitate to reopen it if a similar issue appears. I also take a look at the code that Jordan posted, and it might be an issue there, but reproducing it is a problem and maybe there is an additional plugin that can interfere.

**Closed by zmaglica** 2022-08-23 10:05 UTC
Labels: type: bug, needs feedback, category: core, needs triage
