### ISSUE TITLE
Fix e2e tests for subscriptions and checkout which fail with WC 8.5.0-beta.1

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#7966] opened 2024-01-03 10:15 UTC
### Describe the bug
`WC - beta | wcpay - shopper` and `WC - beta | subscriptions - shopper` are [failing](https://github.com/Automattic/woocommerce-payments/actions/runs/7394021531/job/20117715005).

`WC - beta | wcpay - shopper` needs selector adjustments (p1704202276581069/1704092507.706699-slack-CGGCLBN58).

`WC - beta | subscriptions - shopper` needs selector adjustments (adjusted in https://github.com/Automattic/woocommerce-payments/compare/develop...fix/e2e-selectors) and a bit more investigation for the second failing test (p1704276442739969/1704092507.706699-slack-CGGCLBN58)

In both cases, failing E2E tests are passing manually.

**Comment by jessy-p** [comment] 2024-01-03 18:37
This issue impacts  CI/CD Pipeline so assigning to Harmony (based on team responsibilities Pc2DNy-3z-p2) @deepakpathania. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by deepakpathania** [comment] 2024-01-04 09:45
The relevant teams would take up the failing E2E tests @jessy-p so shouldn't be assigned to Harmony.

**Comment by FangedParakeet** [comment] 2024-01-05 13:42
Since these tests pertain primarily to the checkout, I presume they should plop into the lap of Heisenberg. Timur's investigation suggests that the failures are not due to any changes in our checkout code, but instead caused by stray selectors, which hopefully won't require radical amendments. 

I'm ready to move this into our backlog and can probably pick up from where Timur has left off early next week, if that sounds sound.

**Comment by timur27** [comment] 2024-01-19 11:39
I was fixing e2e pipelines, and I might have fixed the tests described in this issue. Let's put this issue on hold for a moment. I'll get back with the final update once I confirm everything @FangedParakeet.

**Comment by timur27** [comment] 2024-01-19 14:53
Yes, https://github.com/Automattic/woocommerce-payments/pull/8048 inadvertently fixes [`beta` e2e tests](https://github.com/Automattic/woocommerce-payments/actions/runs/7584981172/job/20659841863) described in this PR. It was initially focused on fixing main groups failing on `develop`, but it turns out those were related.

**Closed as completed** 2024-01-19 19:35 UTC
Labels: priority: high, type: technical debt
