### ISSUE TITLE
Inbox notifications on the Overview screen have relative times in UTC

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#4381] opened 2022-06-30 05:30 UTC
### Describe the bug

Inbox notifications displayed on the **Payments → Overview** page appear to display the date the inbox notification was received in UTC leading some strange situations like this one: 

<img width="610.4" alt="Screen Shot 2022-06-29 at 12 06 01 pm" src="https://user-images.githubusercontent.com/8490476/176597668-b3b9ec20-43c2-4980-ab82-b41f2112a0b6.png">

Note my local timezone is UTC+10 and so because this was received just now, it is shown as being received in the future (10hrs from now). This indicates to me that there's some timezone comparison issue going on here. FWIW this issue doesn't impact the notifications shown on the **WC → Home** screen.

### To Reproduce

1. Set your sites local time setting to be UTC +- some amount (eg [UTC+5](https://user-images.githubusercontent.com/8490476/176599212-4eaf3db4-a924-43f3-bf03-b6e61a1c32b9.png))
1. Add the following code snippet to your site to create a dummy notification for testing.
     - Note: that this code snippet is modeled on the notes created by the `WC_Payments_Remote_Note_Service`.
     - It will continue recreating notes if you dismiss the test note so you'll want get rid of it after testing. 😉 
2. Go to **Payments → Overview**. The note will have received time which matches your timezone offset. 
3. Go to **WooCommerce → Home**. The same note won't have the same issue on this screen.

```php
add_action( 'shutdown', function() {
	$note_name       = 'wcpay-issue-4381-test-note';
	$note_data_store = WC_Data_Store::load( 'admin-note' );

	$note_ids = $note_data_store->get_notes_with_name( $note_name );

	if ( ! empty( $note_ids ) ) {
		return;
	}

	$note       = new Automattic\WooCommerce\Admin\Notes\Note();();

	$note->set_title( 'Test note' );
	$note->set_content( 'Test note content' );
	$note->set_content_data( (object) [] );
	$note->set_type( Automattic\WooCommerce\Admin\Notes\Note::E_WC_ADMIN_NOTE_INFORMATIONAL );
	$note->set_name( $note_name );
	$note->set_source( 'woocommerce-payments' );

	$note_data_store->create( $note );
} );
```

### Screenshots

**Payments → Overview**
<img width="610.4" alt="Screen Shot 2022-06-30 at 3 27 16 pm" src="https://user-images.githubusercontent.com/8490476/176599737-cea9e42b-1c0c-4037-8afc-0b3bd4623c64.png">

**WooCommerce → Home**

<img width="610.4" alt="Screen Shot 2022-06-30 at 3 29 40 pm" src="https://user-images.githubusercontent.com/8490476/176599889-093a08eb-467a-45a7-9dd1-feb63fae6114.png">

### Expected behavior

The relative date (`x hours from now`) should take into account the site's local timezone.

**Comment by ismaeldcom** [comment] 2022-11-24 13:58
I'm not sure if it was fixed on `@woocommerce/experimental`, where the date manipulation is done. But I can't reproduce it now.

**Comment by jessy-p** [comment] 2023-02-08 04:05
Updated the code in the testing instructions as it referred to a removed class. Retested again, working fine.
Closing this issue as it is working as expected. @james-allan Please reopen if its still an issue

**Screenshot of note with time updated to UTC+10:**
<img width="792" alt="image" src="https://user-images.githubusercontent.com/32092402/217430729-006239c7-81f7-48d3-8345-15e934becd44.png">

**Closed by jessy-p** 2023-02-08 04:05 UTC
Labels: type: bug, component: account overview page, category: core
