### ISSUE TITLE
Jetpack failed to connect (timeout) sandbox mode

### ISSUE THREAD

**Issue by BenraouaneSoufiane** [Automattic/woocommerce-payments#8637] opened 2024-04-13 10:04 UTC
### Describe the bug
When I'm on the sandbox mode, I'm unable to connect my account to start developping this plugin
### To Reproduce

1. Unable the sandbox mode from your wp config, add: 
define( 'WP_ENVIRONMENT_TYPE', 'staging' );
define( 'WCPAY_DEV_MODE', true );
define('WP_MEMORY_LIMIT', '256M');//also php memory is the same
define( 'JETPACK_DEV_DEBUG', true );
2. Click on payments from your wp dashboard
3. Scroll down to Connect your store'
4. It shows that Jetpack unable to connect to your store time out, curl error 28

### Screenshots
![Capture d’écran 2024-04-13 105942](https://github.com/Automattic/woocommerce-payments/assets/110255764/caf96363-4633-4ea8-af7c-9c281e9f814c)

### Expected behavior
Go to Stripe sandbox mode, validate details,  return to the settings (payment methods appear on the checkout page)

### Additional context
I tried the http_request_timeout filter, but does not work
I'm using the 5.7 test 2
Self hosted apache 2.4, php8.2, poor upload speed

**Comment by csmcneill** [comment] 2024-04-13 23:13
Howdy @BenraouaneSoufiane! It seems like this is a local site. If it's a local site, is it exposed to the internet via [ngrok](https://ngrok.com/) or similar? If it isn't a local site, is it behind HTTP basic auth?

**Comment by BenraouaneSoufiane** [comment] 2024-04-14 09:22
it is selfhosted (locally), not exposed via ngrok or similar, I recently try to edit the default timeout from 10 seconds to 60 (in the http connection manager file) but I still get this error, in reality I increase timeout whatever it is, I did search in files (from my vs code editor), & then tired to increase the values

**Comment by csmcneill** [comment] 2024-04-15 16:44
@BenraouaneSoufiane In this instance, modifying these values won't resolve the issue. WooPayments needs to connect to our servers, so you will need to [expose the site via ngrok or similar](https://arc.net/l/quote/pamovfsp).

Since this is a known and documented requirement when developing WooPayments locally, I will close this issue.

**Closed as not planned by csmcneill** 2024-04-15 16:44 UTC
Labels: type: question

**Comment by BenraouaneSoufiane** [comment] 2024-04-15 17:32
Also not work when expose the site through ngrok

**Comment by csmcneill** [comment] 2024-04-15 21:12
@BenraouaneSoufiane I still would not consider this a bug unless this is something that we can reliably reproduce. Many folks who actively develop WooPayments regularly use WooPayments in a local environment without issue. So far, we have not had any other similar reports that prevent folks from using WooPayments locally.

If you're still running into issues, please contact us at <a href="https://woocommerce.com/my-account/contact-support/">WooCommerce.com > My Account > Support</a>. You may need to create an account before you can access that page.
