### ISSUE TITLE
Multi-Currency issues with zero decimal currencies

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#7724] opened 2023-11-15 18:13 UTC
### Describe the bug
When Multi-Currency was built we worked off of the belief that the [zero decimal currency list provided by Stripe](https://stripe.com/docs/currencies?presentment-currency=US#zero-decimal) were all of the currencies that operated without decimals, however, this is not the case. There are several other currencies that have zero decimal formatting that are not on this list. The primary reason for this list is for currencies that do not have to have the amount multiplied or divided by 100 when dealing with Stripe for transactional purposes:

> All API requests expect amounts to be provided in a currency’s smallest unit. For example, to charge 10 USD, provide an amount value of 1000 (that is, 1000 cents).
> For zero-decimal currencies, still provide amounts as an integer but without multiplying by 100. For example, to charge ¥500, provide an amount value of 500.

The problem is that we use this list in order to define formatting, charm, and rounding for currencies enabled via Multi-Currency. This means that currencies like TWD (New Taiwan dollar) may try to be formatted with two decimals in certain instances when they should be formatted (or rounded) with zero decimals.

The number of decimals for a currency is defined in the [`locale-info.php` file within WooCommerce core](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/i18n/locale-info.php), and this is what is used for most of the formatting in Woo Payments via the [`WC_Payments_Localization_Service` class](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-localization-service.php). This data should be taken into account for use with Multi-Currency, as it will provide the correct number of decimals to be used for a currency.

I also believe that Multi-Currency should move away from the "zero decimal" term and use something like "decimal places" instead, which will allow for a clearer definition of what the decimals are for.

### To Reproduce

> [!Note]
> The steps below reference TWD, but this is the case for any currency with zero decimals and is not on the Stripe defined list.

1. Navigate to WooCommerce > Settings > Multi-Currency.
2. Enable TWD / New Taiwan dollar.
3. Click _Manage_ to manage TWD.
4. Confirm that the Charm and Rounding options are what is shown for 2 decimal currencies like USD, EUR, GBP, etc.
5. Navigate to your store's front end and add an item to your cart.
6. Check out with that item and see the incorrect format for the total on the Order Received page.

### Screenshots
Multi-Currency's manage currency page:
![Multi-Currency's manage currency page](https://github.com/Automattic/woocommerce-payments/assets/4634416/4f32beb9-063d-40a1-965b-92835006497e)

Order received page:
![Order received page](https://github.com/Automattic/woocommerce-payments/assets/4634416/4781f0b2-f959-40f0-ad75-aa0615f65693)

**Comment by htdat** [comment] 2023-11-16 02:15
This issue impacts "Multi-currency", so assigning to Fractal (based on team responsibilities Pc2DNy-3z-p2) cc team lead @bborman22. 

Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by pierorocca** [comment] 2024-01-18 04:44
Noting that there are four, [special case zero-decimal currencies ](https://stripe.com/docs/currencies#special-cases).

TWD does technically have sub-units, 2 decimal currency, though are not typically used in practice. Warrants further research to confirm the issue assumptions.

> The basic unit of the New Taiwan dollar is called a [yuan](https://en.wikipedia.org/wiki/Yuan_(currency)) (圓) and is subdivided into ten [chiao](https://en.wikipedia.org/wiki/Jiao_(currency)) (角), and into 100 [fen](https://en.wikipedia.org/wiki/Fen_(currency)) (分) or cents, although in practice both chiao and fen are never actually used.

**Comment by bborman22** [comment] 2024-04-12 16:28
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/7724?planning-poker) with Zenhub @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo

**Comment by reykjalin** [comment] 2024-04-26 20:56
So I'm unable to reproduce a _part_ of the issue. The front-end amounts are all formatted without decimals for both 0-decimal currencies (e.g. JPY) as well as special case currencies (e.g. ISK and TWD).

However, the charm pricing and rounding options still use decimals when they should be using whole integers! So that _is_ something we need to fix.

For example, look at how JPY rounding and charm pricing options are presented vs. ISK - currencies that both use 0 decimals in practice while ISK is technically a 2-decimal currency:

| JPY | ISK |
|:---:|:---:|
| <img width="815" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/13835680/97f7302e-1b1a-48c7-8624-dde048328e26"> | <img width="815" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/13835680/e4360b38-d62b-4997-9e27-22d98b955344"> |

For ISK the charm pricing and rounding options don't have any meaning. They don't affect the final price at all, so that functionality is completely broken atm.

**Comment by pierorocca** [comment] 2024-04-27 00:12
> For ISK the charm pricing and rounding options don't have any meaning. They don't affect the final price at all, so that functionality is completely broken atm.

Makes sense for ISK and UGX which is also a former decimal currency that's now a zero decimal currency.

**Comment by reykjalin** [comment] 2024-04-27 01:50
> Makes sense for ISK and UGX which is also a former decimal currency that's now a zero decimal currency.

Yeah, they're still treated as 2-decimal currencies with Stripe for historical reason even though they should never be treated as such and you can't actually charge anything with decimal points.

**Comment by reykjalin** [comment] 2024-05-02 00:49
@bborman22 I spent a couple hours trying to remove the concept of zero-decimal currencies from the codebase based on Jesse's feedback, but would need more time than that to do it properly. It's hard to find and test everything in the JS codebase.

The PHP side is actually quite straight-forward, but the JS has various dependencies on props provided by PHP in multiple locations that can be tricky to track down. As a side note having TS across the codebase for this would be _amazing_ here and would make this effort much easier.

For now though you can see where I got in https://github.com/Automattic/woocommerce-payments/pull/8753. Maybe we can pick this up if we ever do decide to spend some time refactoring and improving the MCCY code.

**Comment by bborman22** [comment] 2024-05-02 17:07
@reykjalin Thanks for spiking on that! To capture these items I created an https://github.com/Automattic/woocommerce-payments/issues/8761 which we can use to pick items from during any downtime or HACK weeks or when it gets large enough take on as a project.

**Closed as completed** 2024-05-07 13:57 UTC
Labels: type: bug, priority: low, category: refactor, focus: multi-currency
