### ISSUE TITLE
Refund cannot be completed ; Capture Later Enabled 

### ISSUE THREAD

**Issue by namiokuzono** [Automattic/woocommerce-payments#4333] opened 2022-06-08 15:48 UTC
### Describe the bug

Error message: 

`This payment is not captured yet. To cancel this order, please go to 'Order Actions' > 'Cancel authorization'. To proceed with a refund, please go to 'Order Actions' > 'Capture charge' to charge the payment card, and then trigger a refund via the 'Refund' button.
`
### To Reproduce

This seems to be one-off occurrence. 

- Capture later enabled
- Order is placed
- Tried Refunding, but did not get refunded because it was not captured
- Charge captured
- Tried refunded, but still the refund would not go through 

Hosted on WPcom

### Screenshots

Please see the thread for more information on this:  p1654544236652809-slack-C7U3Y3VMY

### Additional context

Please see ticket 5275505-zen to view SSR.

**Comment by jaxr** [comment] 2022-07-04 20:23
35981152-hc

**Comment by jbordonado** [comment] 2022-09-01 12:52
I could not figure out why this was happening, and I also could not reproduce it.

-------

My observations of the two cases:
- We can see in the Stripe dashboard that the charge was successfully captured, so there's no doubt about that
- When the merchant tries to refund the order, it fails. The corresponding log on Stripe is an API call to capture the charge, which logically fails because the charge is already captured, as mentioned earlier

The piece of code throwing the error that the merchant sees: https://github.com/Automattic/woocommerce-payments/blob/58da1f4086fba4ea6694a5dad71468aad5d68ab3/includes/class-wc-payment-gateway-wcpay.php#L1705-L1711

When executing the `process_refund` function, we especially check that the order doesn't need to be captured before proceeding.

--------

What seems to happen is:
1. The merchant clicks on "Refund" on the order which is already captured
2. We try to capture the charge: it fails, and we enter the `mark_capture_payment_failed` function 

https://github.com/Automattic/woocommerce-payments/blob/58da1f4086fba4ea6694a5dad71468aad5d68ab3/includes/class-wc-payment-gateway-wcpay.php#L2350

which, amongst other things, sets the `_intention_status` metadata to `requires_capture`, meaning that the order, although already captured, is now marked as NOT captured.

3. `process_refund` is executed, and we cannot pass the check regarding the order being captured, hence the mentioned error is thrown.

---------

**Why is there an API call to capture the charge before we get to `process_refund`, when the merchant clicks on the "Refund" button?**
This is the whole issue, trying to capture the charge on a captured order before processing the refund.
But I'm unable to figure out, looking at the code, how that sequence of events is even possible.

From the frontend's perspective, capturing the charge seems only possible from the order's detail page, selecting the action "Capture the charge."
From the backend's perspective, I didn't see any obvious bit of code in the refund flow that might trigger a capture.

So I'm wondering if this could be due to another plugin that hooks into one of the events available during the refund flow.
Looking at the active plugins of the 2 merchants at the time they reached our support team, they have those in common:

> Akismet Anti-Spam: by Automattic
> Contact Form 7 Extension For Mailchimp: by Renzo Johnson
> Contact Form 7: by Takayuki Miyoshi
> Facebook for WooCommerce: by Facebook
> Jetpack: by Automattic
> Kadence WooCommerce Email Designer: by Kadence WP
> Mailchimp for WooCommerce: by Mailchimp
> WooCommerce Payments: by Automattic
> WooCommerce: by Automattic
> WP Mail SMTP: by WPForms
> YITH WooCommerce Wishlist: by YITH

My suggestions for HEs if we get a new report for this error:
- Ask for the full logs during the time of the events (capturing the charge and attempting the refund of the order) to have a clear view on the sequence of calls that is made
- Ask them to disable other plugins and attempt the refund again, in case this is an incompatibility issue
- Please add the findings here, and we will again investigate the new cases

Hopefully, this either solves the problem or helps us figure out this thing.
I'm closing the issue for now.

**Closed by jbordonado** 2022-09-01 12:52 UTC
Labels: type: bug, category: core, needs prioritisation
