### ISSUE TITLE
Console error on Customize page

### ISSUE THREAD

**Issue by cesarcosta99** [Automattic/woocommerce-payments#4836] opened 2022-10-03 20:52 UTC
### Describe the bug

Not really a bug **yet**, but there is an exception thrown when we visit the Customize page. Deactivating the plugin makes the exception go away.

### To Reproduce

1. Open the browser dev tools.
2. Go to `WP Admin > Appearance > Customize`.
3. You should see a JS exception: `TypeError: Cannot read properties of undefined (reading 'isEnabled')`.

### Actual behavior

I didn't notice any strange behaviors besides the exception. However, we should probably address that before it evolves to a real bug.

### Screenshots

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/10233985/193679604-d5fae5e8-6ab8-4829-8654-e5442d2176ef.png">

### Expected behavior

No exceptions.

### Desktop (please complete the following information):

* OS: Mac OS
* Browser Brave
* Version 1.43.93

**Comment by RadoslavGeorgiev** [comment] 2022-10-04 12:09
@cesarcosta99 which versions were you running here? I could not reproduce this locally with WP 6.1-beta2 & neither `trunk` nor `develop`.

**Comment by RadoslavGeorgiev** [comment] 2022-10-06 08:53
Tested on JN, I don't see the same error, but one about Tracks, also coming from `tos.js`. We should definitely add some checks to the file:

![image.png](https://images.zenhubusercontent.com/5f2d57d80f11ae56d6a5daa8/12cf9e06-d590-4c39-bbcc-36af4937f868)

**Comment by zmaglica** [comment] 2024-02-05 10:51
The issue has been resolved by removing the function that caused an error on this pull request: https://github.com/Automattic/woocommerce-payments/pull/8106. Consequently, the pull request I submitted (https://github.com/Automattic/woocommerce-payments/pull/8108) will also be closed, as the function is removed.

**Closed as completed by zmaglica** 2024-02-05 10:51 UTC
Labels: type: bug, status: has pr, component: settings, category: core
