### ISSUE TITLE
Fix navigation and plugin functionality for WP.com ecomm plan sites

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/woocommerce-payments#278] opened 2019-11-20 19:41 UTC
Additional detail:   paJDYF-pS-p2

**Comment by vbelolapotkov** [comment] 2021-12-17 13:34
I think this is not relevant anymore, but would need to double check.

**Comment by frosso** [comment] 2023-06-29 14:01
Just tested this. I can't reproduce the issue reported, and it doesn't look relevant anymore - closing.

**Closed by frosso** 2023-06-29 14:01 UTC
Labels: type: bug, priority: low, needs feedback, category: core
