### ISSUE TITLE
My Account > Subscriptions > View ... Which Card?

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#873] opened 2020-08-31 22:09 UTC
In My account > Subscriptions > View (a subscription), you see that the current payment method is a credit card, but what if the buyer has more than one credit card? It could be helpful to include the last four digits of the card used

![sub-which-card](https://user-images.githubusercontent.com/1595739/91773594-f15bb980-eb9b-11ea-87f4-775f433b6226.png)

**Comment by thenbrent** [comment] 2020-09-01 06:50
> It could be helpful to include the last four digits of the card used

That's what the `'woocommerce_my_subscriptions_payment_method'` filter is for. This is a duplicate of https://github.com/Automattic/woocommerce-payments/issues/699 so I'll close it, but move the descriptions to a comment on there. :)

**Closed by thenbrent** 2020-09-01 06:50 UTC
Labels: Priority: Low
