### ISSUE TITLE
Improve BNPL copy in settings to be enablement-focused

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#8248] opened 2024-02-21 18:58 UTC
### Description

The **Payments > Settings** page serves as a place for merchants to enable or disable payment methods. However, for BNPLs, there is nothing in the settings that:

- Incentivizes merchants to enable them.
- Indicates what the benefits of enabling these payment methods are.
- Distinguishes them from other payment methods.

Currently, the description text for each BNPL reads:

```
Allow customers to pay over time with [method]. Available to all customers paying in [currency].
```

However, this does not clarify:

- What each BNPL method is.
- How it can benefit a merchant.
- How it can benefit customers.

This resulted in a (paraphrased) question:

> Why would I want to enable a payment method that charges me 6%?

Comparatively, the express checkout options have their own section, which has its own descriptive text (not including the descriptive text for each EPM):

```
Let your customers use their favorite express payment methods and digital wallets for faster, more secure checkouts across different parts of your store
```

This text clearly indicates to merchants:

- What express checkouts are.
- How it will benefit a merchant.
- How it will benefit their customers.

### Acceptance criteria

Modify the descriptive text for each BNPL offering so that merchants can best decide which would the best options to enable for their store.

An additional option to consider is to break out BNPLs into their own section that is rendered if an account is in a supported country.

_EDIT: Following instructions in the comment below (https://github.com/Automattic/woocommerce-payments/issues/8248#issuecomment-2278596026)_

1. **Remove the "Available to all customers paying is USD." since that's not technically true and the details are more complex and subject to change.**
2. **Put BNPL methods in their own section like Express Checkouts with an appropriate section ID for deep linking purposes.**
3. **Section copy proposed:**

> ### Buy now, pay later
> Boost sales by offering customers additional 
> buying power, and flexible payment options.
> [Learn more](https://woocommerce.com/document/woopayments/payment-methods/buy-now-pay-later/)

### Testing instructions

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. Observe expected behaviour

### Additional context

Related to pbUcTB-447-p2#bnpl-settings-are-enablement-focused

**Comment by htdat** [comment] 2024-02-22 07:10
This issue impacts `Additional Payment Methods`, so assigning to @Automattic/heisenberg (based on team responsibilities Pc2DNy-3z-p2) cc team lead @FangedParakeet.
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by htdat** [comment] 2024-02-22 07:11
This issue impacts `Additional Payment Methods` and `BNPL`, so assigning to @Automattic/heisenberg (based on team responsibilities Pc2DNy-3z-p2) cc team lead @FangedParakeet.
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by aheckler** [comment] 2024-08-07 09:07
We should prioritize this IMHO since the current copy is inaccurate. :( My fault!

Specifically, the copy now says:

> Allow customers to pay over time with Afterpay. Available to all customers paying in USD.

... but in fact a customer ALSO must use a billing address inside the WooPayments account country of the merchant. (Since cross-border transactions are not allowed.)

**Comment by FangedParakeet** [comment] 2024-08-07 17:03
This should be a relatively lightweight fix, so I'm happy to prioritise it. I just want to specify the criteria here: can we clarify exactly what the new copy should be? CC @pierorocca 🙏

**Comment by pierorocca** [comment] 2024-08-09 16:19
The details about country and currency eligibility are best left in the documentation rather than this small space. It varies by payment method and will change when we and/or the providers start support cross-border and/or multicurrency. In the setting refresh explorations, I've asked that BNPL payment methods are in their own grouping similar to Express Checkouts. That way we could remove the additional detail from each method, have a section title and description, and a Learn more link out to our BNPL section in the documentation. Would that work better overall?

![image](https://github.com/user-attachments/assets/e75230b2-6ca2-41cd-9092-87347962dd0b)

**Comment by pierorocca** [comment] 2024-08-09 19:20
So we'd:

1. Remove the "Available to all customers paying is USD." since that's not technically true and the details are more complex and subject to change. 
2. Put BNPL methods in their own section like Express Checkouts with an appropriate section ID for deep linking purposes.
3. Section copy proposed:

### Buy now, pay later
Boost sales by offering customers additional 
buying power, and flexible payment options.
[Learn more](https://woocommerce.com/document/woopayments/payment-methods/buy-now-pay-later/)

**Comment by FangedParakeet** [comment] 2024-08-12 17:38
Cheers, @pierorocca! Have updated the acceptance criteria in the issue description to reflect your guidance. 🙏

**Comment by pierorocca** [comment] 2024-08-12 17:54
Ty! FYI @nikkivias making an incremental update per previous user flow review feedback.

**Comment by frosso** [comment] 2024-08-13 12:43
@pierorocca how does this look?

![wcpay test_wp-admin_admin php_page=wc-settings tab=checkout section=woocommerce_payments (1)](https://github.com/user-attachments/assets/d7ad9d2e-0a8a-4ab4-bf91-265aab0e2594)

I removed the "Payment methods" heading from the BNPL section. Let me know if you'd rather have me repeat it, instead.

**Comment by pierorocca** [comment] 2024-08-13 15:12
Looks good. The heading doesn't need to be repeated.

Looks like the Link logo is misaligned @frosso?

**Comment by frosso** [comment] 2024-08-13 15:15
> Looks like the Link logo is misaligned @frosso?

Yeah, it looks like a regression from some other change when WooPay is enabled  I see it in `develop` as well. 

![2024-08-13 17 15 16](https://github.com/user-attachments/assets/d6f7fd77-562a-4baa-9ab2-6197a01e60d2)

I'll take a look shortly 👍

**Comment by csmcneill** [comment] 2024-08-13 15:31
@frosso I spotted a comma splice in the BNPL section description:

> Boost sales by offering customers additional buying power, and flexible payment options.

We can resolve this by making it a list...

> Boost sales by offering customers additional buying power, _second benefit here_, and flexible payment options.

...or by removing the comma completely:

> Boost sales by offering customers additional buying power and flexible payment options.

cc @aheckler

**Comment by frosso** [comment] 2024-08-13 15:53
@pierorocca fixed the icon alignment here: https://github.com/Automattic/woocommerce-payments/pull/9255

Is it ok to remove the comma from the description?

**Comment by pierorocca** [comment] 2024-08-13 15:57
Yes definitely.  Good catch Chris!

**Comment by pierorocca** [comment] 2024-08-15 21:55
@frosso will this make it in by the code freeze? A similar inconsistency was found in https://github.com/Automattic/woocommerce-payments/issues/9270 if you don't mind taking a look. The BNPL pricing bubbles add even more variability.

**Comment by pierorocca** [comment] 2024-08-15 22:03
I'm not sure why @frosso, the BNPL pricing bubbles look a lot different on your screenshot vs. in production. I think there's some regression happening.



![Image](https://github.com/user-attachments/assets/075eb6a3-06a2-44ce-a494-0876b1850e8f)

**Comment by frosso** [comment] 2024-08-16 06:35
@pierorocca the shorter description of BNPL allows for the pricing bubbles to expand into one line. Would you like to make any adjustments to the BNPL methods copy to account for it?

**Comment by frosso** [comment] 2024-08-16 06:38
@pierorocca indeed the shorter description of BNPL allows for the pricing bubbles to expand into one line. Would you like to make any adjustments to the BNPL methods copy to account for it?

It should make the code freeze, I'll solicit a review.

**Comment by pierorocca** [comment] 2024-08-16 06:40
I think they should all look consistent. Pulling in @nikkivias for a design perspective. With the current design, it looks super odd to have the same amount of text in the bubble but vastly different shapes and sizes. Imo the bubbles should have their own space independent of the descriptive copy.

**Comment by nikivias** [comment] 2024-08-16 06:59
> Imo the bubbles should have their own space independent of the descriptive copy

Fully agree. I think that means we should add a max width for the payment method copy.

**Comment by frosso** [comment] 2024-08-16 13:50
The pricing bubbles do have different text length - it is dependent on each payment method's pricing (Klarna for example has 3 digits plus the decimal point for the base percentage fee, but other payment methods might just have one digit, like Affirm), but also on each translation (the "From ...." string) and currency (merchants using JPY or other zero-decimal currencies for their Stripe account wouldn't have decimals).

@pierorocca @nikkivias  I'm unclear if we're trying to prioritize having the pricing bubbles show into one line (but payment method descriptions having different widths/heights), or having the payment method descriptions have consistent width (and pricing bubbles of different widths/heights), keeping in mind what I wrote above. Could you please clarify?

**Closed as completed** 2024-08-16 14:29 UTC
Labels: type: enhancement, needs design, priority: medium, focus: checkout payments

**Comment by frosso** [comment] 2024-08-16 14:40
I updated the critical flows to reflect the new settings structure: https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows

@aheckler will update the Woo documentation accordingly

**Comment by pierorocca** [comment] 2024-08-16 16:12
I think we're trying to ensure there's some semblance of a grid system being used to align the content so it has a pleasing visual structure. Shortening the copy has exposed the lack of alignment in the current implementation. It looks randomly sized and mis-aligned to the casual observer.

**Comment by pierorocca** [comment] 2024-08-16 17:49
I was trying to find a good example but this will have to do. 

Despite some of the payment methods having 1 row of text and others having 2, we don't try to make some of the Customize buttons fit into a single line. That would look weird right? 

![image](https://github.com/user-attachments/assets/07471cdb-5bb4-483c-932c-dccdb483799c)

There's only a 3 character difference between the smallest and largest copy. We can fix the bubble size to the maximum needed and allow it to increase in size should translation require the extra space.

Speaking of translation, I switched my admin to Italian and it's all in English still? Do we not support any localization?

To demonstrate, Stripe's behavior and responsive approach works well, even on mobile.

https://github.com/user-attachments/assets/5dcbf806-d1f4-4c0d-8c1b-4eee1764a3c8

Contrast that with WooPayments which looks really bad, except at the smaller breakpoint where the bubble shifts below the copy and back into a grid layout with good alignment.

https://github.com/user-attachments/assets/2813114d-4144-4670-bc6c-5d1efe0270bc

**Comment by frosso** [comment] 2024-08-19 12:03
> Speaking of translation, I switched my admin to Italian and it's all in English still? Do we not support any localization?

I just verified this on a new site, and WooPayments seems to be translated correctly in italian.
<img width="1109" alt="Screenshot 2024-08-19 at 2 01 18 PM" src="https://github.com/user-attachments/assets/f85c7c5b-3f18-4063-8124-e554d4c9bbf0">

I see them being built here: https://translate.wordpress.com/projects/woocommerce/woocommerce-payments/

After changing the language, try and update the language packs on the site - Dashboard -> Updates, there should be an option to update languages for all the plugins/themes.
You _might_ need to install the plugin from WPorg, as well.

**Comment by frosso** [comment] 2024-08-19 12:08
> There's only a 3 character difference between the smallest and largest copy. We can fix the bubble size to the maximum needed and allow it to increase in size should translation require the extra space.


It sounds like we should prioritize the pricing bubble's width, so they show into one line and their text doesn't wrap? (image for reference)

![Screenshot 2024-08-19 at 2 09 27 PM](https://github.com/user-attachments/assets/d84908bc-e82c-4136-bcee-821c9fa13844)

Please do let me know if I misunderstood!

**Comment by pierorocca** [comment] 2024-08-19 17:32
@frosso that could work! Once the breakpoint is hit, that same single row bubble gets relocated to below the descriptive copy. That's more consistent than the current approach.

It still bugs me that the bubbles are all not the same width. @nikkivias what are your thoughts overall?
