### ISSUE TITLE
Payment method is not updated in renewal order on subscription renewal retry

### ISSUE THREAD

**Issue by denho** [Automattic/woocommerce-payments#2813] opened 2021-08-30 15:43 UTC
### Describe the bug
When using WC Subscriptions renewal retry rules, the pending renewal order is not updated with the latest payment method chosen for subscription.

### To Reproduce
1. Install WC Subscriptions and [enable retry system in it](https://docs.woocommerce.com/document/subscriptions/failed-payment-retry/#section-1).
1. Purchase a subscription product, which will create a subscription.
2. Attach a new card to account, which will fail to be charged. For example, this one`4000000000000341`.
3. Select the previously attached failing card as a payment method for the subscription. 
<img src="https://user-images.githubusercontent.com/2803994/131364022-ab32975a-b12d-4412-9242-bbe2cd9c1a85.png" width="300">
4. Renew subscription manually  <img src="https://user-images.githubusercontent.com/2803994/131364107-569ad542-8d72-4473-aa39-5281902c2d8c.png" width="300">

4. Confirm the renewal failed and pending renewal order has been created.
5. Attach a valid card on account that will successfully charge, e.g. `4242424242424242`.
3. Update the subscription with the new card.
4. Trigger renewal retry
    - Go to Action Scheduler actions and filter the pending `woocommerce_scheduled_subscription_payment_retry` actions https://woocommerce.test/wp-admin/tools.php?page=action-scheduler&status=pending&s=woocommerce_scheduled_subscription_payment_retry&action=-1&paged=1&action2=-1
    - Locate the action for the pending renewal order by order id in the argument and click run ![image](https://user-images.githubusercontent.com/2803994/131365154-8061909a-48a0-40b9-b55f-e1fa00e5a013.png)
6. Confirm the payment for the renewal order failed again.

### Actual behavior
The renewal order wasn't updated with the latest card on subscription, and payment failed.

### Expected behavior
The renewal order should have been updated with the latest card on subscription, and payment should have succeeded.

### Additional context
WooCommerce Payments should probably hook into `wcs_copy_payment_meta_to_order` filter to provide appropriate payment meta when copying payment method from subscription to order in `wcs_copy_payment_method_to_order` function.

**Comment by haszari** [comment] 2022-05-25 04:39
My guess is that this is an edge case / advanced use case so is low priority.

@denho How important is this to WooCommerce.com use case? (I'm assuming this is a need on WCCOM)

@james-allan (second opinion) Does this sound like a bug or a feature request?

**Comment by haszari** [comment] 2022-05-25 20:32
Thanks @denho  – does this issue come up regularly on WCCOM – do you have an idea of how often this causes issues?

**Comment by james-allan** [comment] 2022-05-25 23:06
In WC Subscriptions there is code that should copy the latest payment method from the subscription to the renewal order before attempting to retry the payment. You can find it [here](https://github.com/woocommerce/woocommerce-subscriptions/blob/4.3.0/includes/payment-retry/class-wcs-retry-manager.php#L346-L347). 

If this issue is still occurring then it might be specifically about how WC Payments payment meta is stored that is causing the method we're using not to work. 

Given this is existing functionality that isn't working consistantly, I too would consider this a bug.

**Comment by haszari** [comment] 2022-05-25 23:09
Thanks @james-allan ! Bumping up to `high` based on your diagnosis ("this should work").

**Comment by haszari** [comment] 2022-05-25 23:10
Next steps: 

1. Reproduce this issue on a test site to confirm. 
2. If confirmed start debugging the cause.

**Comment by denho** [comment] 2022-05-26 19:34
> Thanks @denho  – does this issue come up regularly on WCCOM – do you have an idea of how often this causes issues?

This is happening on every renewal retry. We [had fixed](https://github.com/Automattic/woocommerce.com/pull/11127) it on WCCOM on our own back in Aug 2021. Without that, we couldn't start using WooCommerce Payments. This is a critical bug for us.

> If this issue is still occurring then it might be specifically about how WC Payments payment meta is stored that is causing the method we're using not to work.

Exactly. My suggestion on how to fix that is in the issue description:
> WooCommerce Payments should probably hook into `wcs_copy_payment_meta_to_order` filter to provide appropriate payment meta when copying payment method from subscription to order in `wcs_copy_payment_method_to_order` function.

**Comment by shendy-a8c** [comment] 2022-06-06 06:00
@denho this fix will be included in `4.3.0` release.

**Closed** 2022-06-06 05:59 UTC
Labels: type: bug, priority: high, component: saved cards and subscriptions, category: core
