### ISSUE TITLE
Apple Pay: variable virtual products require a shipping address and a choice of a shipping method

### ISSUE THREAD

**Issue by grig-23** [Automattic/woocommerce-payments#6714] opened 2023-07-08 13:43 UTC
### Describe the bug
With Apple Pay (I assume the same may or may not be true for Google Pay), variable virtual products require a shipping address and a choice of shipping method.

### To Reproduce

1. Create a variable product, tick "virtual" checkboxes in all variations.
2. On the product page, click "buy with Apple Pay"
3. A shipping address will be a required field, and a shipping method selection will be presented.
4. If we attempt to purchase a simple virtual product via Apple Pay, the shipping address information/selection is not present and there is no selection of a shipping method.

### Actual behavior
With a virtual variable product, a shipping address selection option will be a displayed in Apple Pay, and a shipping method selection will be presented.

### Screenshots

Variable:
<img width="396" alt="Screenshot 2023-07-08 at 15 40 19" src="https://github.com/Automattic/woocommerce-payments/assets/13084901/97e5dcb4-dfe6-4f1b-9ff7-2cc2962eee2b">

Simple:
<img width="396" alt="Screenshot 2023-07-08 at 15 41 38" src="https://github.com/Automattic/woocommerce-payments/assets/13084901/bb44cc49-6527-4201-b7bf-db65d21c70f4">

### Expected behavior

If a variation is virtual, no shipping address selection should be presented, and no shipping method selection should be offered.

### Desktop (please complete the following information):

* OS: MacOS Ventura 13.4.1 
* Browser Safari 
* Version 16.5.1 (18615.2.9.11.7)

### Additional context
Reported in 6514010-zen

**Comment by csmcneill** [comment] 2023-07-10 00:33
@grig-23 Can you reproduce this in [Stripe](https://woocommerce.com/products/stripe/?aff=10486&cid=1131038) or [WooCommerce Square](https://woocommerce.com/products/square/?aff=10486&cid=1131038)?

**Comment by grig-23** [comment] 2023-07-10 07:11
> @grig-23 Can you reproduce this in [Stripe](https://woocommerce.com/products/stripe/?aff=10486&cid=1131038) or [WooCommerce Square](https://woocommerce.com/products/square/?aff=10486&cid=1131038)?

Yes, I can replicate this with the Stripe extension, haven't tested with Square.

**Comment by htdat** [comment] 2023-07-12 22:57
This issue impacts `Additional Payment Methods (including Apple Pay / Google Pay)`, so assigning to team Fusion (@anu-rock as team lead) (based on team responsibilities Pc2DNy-3z-p2). Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by anu-rock** [comment] 2023-07-14 11:06
Moved this to Fusion's backlog. Thanks, @htdat.

**Comment by zoemyers** [comment] 2023-08-01 21:40
6604527-zd - since this affects something as common as virtual variable products, can we get a higher priority on this? Merchant is complaining this is costing them money.

**Comment by anu-rock** [comment] 2023-08-02 06:34
@zoemyers Do we know how many merchants are affected by this? Are they open to using alternative payment methods in the meantime?

**Comment by zoemyers** [comment] 2023-08-02 14:01
Lots of merchants use Apple pay and variable virtual products and it would affect all of them, there are other payment methods but the end result is customer frustration and lost sales if the customer only can use Apple Pay. I'm not the PA so I don't have L*r access to pull interaction data for specific figures. I just hope this'll be considered for a higher priority, not necessarily highest.

**Comment by anu-rock** [comment] 2023-08-03 08:21
@zoemyers I've marked it as high priority. We'll try and pick it up soon.

**Closed as completed** 2023-10-03 12:06 UTC
Labels: type: bug, priority: high, component: payment request button
