### ISSUE TITLE
Dispute overview box improvements

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#5981] opened 2023-04-05 13:16 UTC
This issue stems from the WC Pay audit call on disputes: paJDYF-7sM-p2

The **Dispute overview** box, pictured below, could use some improvements.

<img width="715" alt="Screenshot taken on 2023-04-05 at 13 06 21 UTC@2x" src="https://user-images.githubusercontent.com/5512652/230089415-389f3eb9-5546-4b67-ac6f-0f50a3f982bf.png">

Specifically:

- We should [link out to our docs](https://woocommerce.com/document/woocommerce-payments/fraud-and-disputes/managing-disputes-with-woocommerce-payments/) on how to respond to disputes and what kind of evidence to submit.
- We should display the dispute fee so that merchants understand the full "cost" of the dispute.

Mockup:

![Screenshot taken on 2023-04-05 at 13 10 02 UTC@2x](https://user-images.githubusercontent.com/5512652/230090418-3d388e2c-7241-42ba-a3e5-7506ab923401.png)

We should do the same thing on the **Challenge dispute** box too, once the merchant clicks the **Challenge dispute** button.

<img width="762" alt="Screenshot taken on 2023-04-05 at 13 11 05 UTC@2x" src="https://user-images.githubusercontent.com/5512652/230090757-06366fb2-dcf5-438c-bdc5-bde328e6d937.png">

**Comment by haszari** [comment] 2023-09-19 01:58
I _think_ we're addressing this in current disputes project (highlighting disputes & driving action from transaction details screen - pdjTHR-2PC-p2). 

If so, we can close this when the project ships. 

Here are some related issues in progress:

- #6974
- #6925
- #6926
- #6927

> We should display the dispute fee so that merchants understand the full "cost" of the dispute.

This is likely addressed by #6974.

> We should [link out to our docs](https://woocommerce.com/document/woocommerce-payments/fraud-and-disputes/managing-disputes-with-woocommerce-payments/) on how to respond to disputes and what kind of evidence to submit

There are various docs links, action buttons and in-product guidance in progress on the above issues. 

I'm not 100% clear on one thing – I think we are removing the `Dispute detail` page (in above screenshots), since it's clearer to show dispute info in the context of the transaction (detail page). I'll check with team and if so I think we can close this.

**Comment by haszari** [comment] 2023-09-19 02:27
> I'm not 100% clear on one thing – I think we are removing the Dispute detail page (in above screenshots), since it's clearer to show dispute info in the context of the transaction (detail page). I'll check with team and if so I think we can close this.

Confirmed!

- #6883

Closing. @aheckler keep an ear on our project and please open an issue if we don't address these gaps (or there are others!)

**Comment by haszari** [comment] 2023-09-19 02:28
Note: the change will likely release in WCPay 6.6 (Oct 2023).

**Closed as completed by haszari** 2023-09-19 02:27 UTC
Labels: component: disputes, category: projects, needs triage
