### ISSUE TITLE
`invalid_request_error` breaks subscription renewals using SEPA payment method

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#3776] opened 2022-02-10 01:39 UTC
### Describe the bug
We've had a report from a merchant via customer support that subscriptions (recurring) payments are failing with SEPA payment method. Thanks @jrodger @felipelousantos cc @madisoncmiller 

Store is using WooCommerce Subscriptions extension with WCPay.

Here's an example request (details removed) and error message:

```
**Request** 400 ERR | POST | /v1/payment_intents
**Request body** 
{
  "amount": "xxxx",
  "currency": "eur",
  "confirm": "true",
  "payment_method": "pm_1234",
  "customer": "cus_2345",
  "capture_method": "automatic",
  "metadata": {
    "customer_name": "Xx Yyyy",
    "customer_email": "a@b.com",
    "site_url": "https://____.com",
    "order_id": "1234",
    "order_key": "wc_order_4567",
    "payment_type": "recurring"
  },
  "description": "------",
  "payment_method_types": {
    "0": "card"
  },
  "off_session": "true",
  "expand": {
    "0": "charges.data.balance_transaction"
  },
  "application_fee_amount": "123"
}

**Error response** invalid_request_error
The PaymentMethod provided (sepa_debit) is not allowed for this PaymentIntent. Please attach a PaymentMethod of one of the following types: card. Alternatively, update the allowed payment_method_types for this PaymentIntent to include "sepa_debit".
```

Linking in some Stripe docs relating to SEPA:

- https://stripe.com/docs/payments/sepa-debit/accept-a-payment
- https://stripe.com/docs/sources/sepa-debit

Internal reference: p1643974407798379-slack-C02BW3Z8SHK p1643785082212209-slack-C7U3Y3VMY

### To Reproduce
I don't have reproduce details and haven't tried reproducing as I'm unfamiliar with SEPA and don't know how to test it locally.

Next step would be for someone familiar with SEPA to reproduce this issue to find out if it's unique to this store or more common.

I imagine the steps are something like:

1. Enable and onboard to WCPay.
2. Activate WooCommerce Subscriptions and create a subscription product.
3. Activate / enable SEPA (via UPE?).
4. Purchase a subscription as a customer. 
5. Wait for renewal or trigger early renewal.
6. Renewal fails with error.

**Comment by haszari** [comment] 2022-02-10 01:40
@shendy-a8c (current Helix porter) Can you investigate and see if you can reproduce this?

**Comment by haszari** [comment] 2022-02-10 01:53
See also possibly related question about iDEAL + WooCommerce Subscriptions: https://github.com/Automattic/woocommerce-payments/issues/3546

**Comment by pauljacobson** [comment] 2022-02-10 07:43
We have similar reports in 4740622-zen and in 4765714-zen. This may also be related to #3233

**Comment by sverleis** [comment] 2022-07-22 07:56
Same issue with 5358797-zen.

**Comment by haszari** [comment] 2022-07-25 23:33
Tagging has high priority based on merchant insight from @Luminus in #3546 .

**Comment by shrutimoorthy** [comment] 2023-03-23 13:18
Similar report in 6065983-zen

**Comment by Brianmitchtay** [comment] 2023-04-03 20:32
Seeing another case of this in 6170094-zen

**Comment by Brianmitchtay** [comment] 2023-04-04 17:07
I've taken some time looking into this and will give the caveat that I'm not a dev so not certain that I'm onto the right thread here, but given the lack of action on this wanted to try and move it forward.

User in 6170094-zen says that all SEPA renewal payments are failing, but that initial payments via SEPA are successful. 

Looking over their account I see that the customer is properly created and that the SEPA payment method is correctly set up for re-use.

However, when the request for the renewal payment is being made, it seems that the only `payment_method_types` included in the request must be `Card` given the error message

```
The PaymentMethod provided (sepa_debit) is not allowed for this PaymentIntent. Please attach a PaymentMethod of one of the following types: card
```

Looking over the request itself I actually don't see `payment_method_types`  included in it at all, but I'm not sure if I'm just misunderstanding something here. However, other payment intents from this merchant's site begin with the array of enabled payment methods.

```
{
  "payment_method_types": {
    "0": "card",
    "1": "sepa_debit"
  },
```

This isn't included in the failing request at all from what I can tell.

In setting up a testing site to reproduce this I came up against the fact that because we've closed the beta for SEPA payments, my testing account didn't get SEPA as a payment option..

![kmIJFN.png](https://user-images.githubusercontent.com/45057772/229864966-04032387-2f23-42c0-8fd0-bc23cd2a6c35.png)

I'm not certain, but wondering whether when the SEPA beta was closed, that change has somehow prevented the gateway from passing a check and returning as active, so it's not being included as an available payment method type in these recurring payment attempts?

Let me know if there's a way I can enable the SEPA method for my testing site, or how else I can move this forward.

**Comment by WEBLAZER** [comment] 2023-04-05 08:28
Hi there, I have a client with the same issu. If needed, he is ok to give an access to his website to someone at Automattic
 if it can help to solve this issu. Let me know.

**Comment by csmcneill** [comment] 2023-04-09 19:24
> I have a client with the same issu. If needed, he is ok to give an access to his website to someone at Automattic
if it can help to solve this issu.

It is unlikely that this issue can be resolved by accessing the site. I would recommend subscribing to this issue so that you can stay up-to-date with any progress made.

**Comment by csmcneill** [comment] 2023-04-09 19:25
6091810-zen shared:

> My customer want to pay with SEPA. Usually, they do not have to refill their data, it is already stored.
> 
> Of course I could ask them to switch to creditcard. But to be honest, my customer mostly do not have this and it is a very delicate issue for them. That´s why they´ve chosen SEPA.
> 
> And the subscriptions work with credit card as I can see at the other accounts. Right now 16 accounts are affected by this SEPA-problem.

**Comment by jtobiesen** [comment] 2023-04-12 13:38
Another example here: 6179674-zen

**Comment by marissaexplores** [comment] 2023-04-13 13:29
[6196861-zen](6196861-zd-woothemes)

**Comment by Mailyss2** [comment] 2023-04-13 13:40
I have the same problem,  when the request for the renewal payment is being made, it seems that the only payment_method_types included in the request must be Card

The PaymentMethod provided (sepa_debit) is not allowed for this PaymentIntent. Please attach a PaymentMethod of one of the following types: card

However, the SEPA method is the main payment method used since the launch of our e-commerce site. Our customers can enter their bank details without worries, but nothing during the renewal payment... The SEPA does not work. The bug would come from PaymentIntent. 

Do you know if there is any news on the progress of the treatment of the issue ?

**Comment by namiokuzono** [comment] 2023-04-17 21:01
Reported via 6210245-zen — I've also tested this flow on my staging site, and I am able to reproduce this.

Steps are as follows: 

- Enable WC PAY
- Activate WooCommerce Subscriptions and create a subscription product.
- Activate/enable SEPA
- Purchase a subscription as a customer.
- Run Scheduled action job by looking up sub #
- Renewal order fails with the error message: ` A payment of €100.00 failed to complete with the following message: Error: The PaymentMethod provided (sepa_debit) is not allowed for this PaymentIntent. Please attach a PaymentMethod of one of the following types: card. Alternatively, update the allowed payment_method_types for this PaymentIntent to include "sepa_debit". `

Here is the Log https://shrtm.nu/b1Z

**Comment by kalessil** [comment] 2023-04-18 12:30
👀

**Comment by kalessil** [comment] 2023-04-18 12:57
To keep things linked, supporting saved payment methods by SEPA was introduced in https://github.com/Automattic/woocommerce-payments/issues/1471, but as more foundational work is required for SEPA we'll make SEPA unavailable for subscriptions as per pchH0V-18S-p2#comment-1311

**Comment by grig-23** [comment] 2023-04-22 12:41
6225648-zen

**Comment by igorhereira** [comment] 2023-04-24 19:28
6226311-zen

**Comment by solstudioim** [comment] 2023-04-28 09:29
Another merchant experiences that same problem: 6242925-zd-woothemes

Was able to replicate too using Nami's steps

**Comment by csmcneill** [comment] 2023-05-07 16:16
Likely 6268978-zen

**Comment by kgeorgee** [comment] 2023-05-08 11:11
6263861-zen

**Comment by kaushikasomaiya** [comment] 2023-05-26 09:50
6282520-zen

**Comment by kalessil** [comment] 2023-08-11 09:23
https://github.com/Automattic/woocommerce-payments/pull/6965

**Comment by frosso** [comment] 2023-08-30 07:39
SEPA support for subscription payments will come to a later date, the solution will be revisited once SEPA becomes widely available.

It can take up to 14 business days to receive notification on the success or failure of a payment with SEPA. Woo Subscriptions' [renewal process](https://href.li/?https://woocommerce.com/document/subscriptions/renewal-process/#the-renewal-process) is designed with the assumption that payment notification is near immediate (or at least within 24 hours).

Additional context: paJDYF-9Ud-p2#comment-20540

**Comment by frosso** [comment] 2024-02-06 15:36
@FangedParakeet I can confirm that SEPA is disabled for subscription products ( also code ref: https://github.com/Automattic/woocommerce-payments/blob/37ef8921f11337be59fac8f5c24ceed6b99f82dd/includes/payment-methods/class-sepa-payment-method.php#L30-L30 )
![Screenshot 2024-02-06 at 4 14 46 PM](https://github.com/Automattic/woocommerce-payments/assets/273592/4ffaa6eb-3096-4725-94c0-fffdc5fca579)

Manual renewal with card payments works as expected.

Changing the `is_reusable` flag to `false` _does_ make SEPA appear at checkout when a subscription product is present.
![Screenshot 2024-02-06 at 4 37 22 PM](https://github.com/Automattic/woocommerce-payments/assets/273592/efbc31ea-d3d5-4e63-9e73-906df4fba571)
 However, besides toggling the flag's value, it seems that additional work is needed to ensure that SEPA subscriptions are currently processed.
Subscriptions will remain "on hold", despite the related Stripe charge succeeding.
WooPayments Server & WooPayments client logs didn't reveal anything useful.

Since it seems that the original issue isn't reproducible anymore, I think we can close the ticket and open a different one once we decide to move forward with SEPA support for subscription products.

**Closed by frosso** 2024-02-06 15:36 UTC
Labels: type: bug, component: upe, category: core, component: wc subscriptions integration, priority: medium
