### ISSUE TITLE
WooPay express pay button disregards `wcpay_payment_request_is_product_supported` filter

### ISSUE THREAD

**Issue by peterwilsoncc** [Automattic/woocommerce-payments#7629] opened 2023-11-06 03:37 UTC
### Describe the bug

In #3325 the filter `wcpay_payment_request_is_product_supported` was introduced to allow extensions to prevent the display of express pay buttons on product pages.

This is helpful for extensions requiring additional data during the checkout process, for example ticketed items.

Unfortunately the WooPay payment gateway bypasses this setting so doesn't allow for extensions to disable the feature on product pages.

### To Reproduce

1. Set up a US based store
2. Enable WooPay, Apple/Google express pay buttons
3. Create a simple product
4. Visit the product page in Google Chrome, both the Google and Woo payment buttons display
5. Add the one line plugin `add_filter( 'wcpay_payment_request_is_product_supported', '__return_false' );` to disable express pay options on the product pages
6. Reload the product page in Google Chrome
   - the Google Pay button does not display, as expected
   - the WooPay button continues to display, unexpected

_Remember to remove the plugin after testing to save yourself frustration later._

### Actual behavior

The WooPay express pay button displays on product pages without regard to the filter.

### Screenshots

**With plugin in reproduction steps**

![Screen Shot 2023-11-06 at 2 35 50 pm](https://github.com/Automattic/woocommerce-payments/assets/519727/23f89453-9823-4b9e-b722-a37c3dca8bed)

**Without plugin in reproduction steps**

![Screen Shot 2023-11-06 at 2 30 57 pm](https://github.com/Automattic/woocommerce-payments/assets/519727/bfa140ae-1b4a-46d3-b2a7-16025ab3fe18)

### Expected behavior

WooPay express pay button to follow the lead of the filter.

### Desktop (please complete the following information):

* OS: macOS
* Browser: Chrome
* Version 119

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context

Discovered while testing https://github.com/woocommerce/woocommerce-box-office/pull/466

**Comment by htdat** [comment] 2023-11-06 07:33
This issue impacts "Compatibility" for WooPay, so assigning to Axiom (based on team responsibilities Pc2DNy-3z-p2) cc team lead @LCmry. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by peterwilsoncc** [comment] 2023-11-06 23:04
I didn't realise at the time, I'm afraid, but it's possible this also affects the Stripe Link express pay button too. I was unable to get the Link button to display on a simple product but it now occurs to me that it may be due to geographic limitations.

**Comment by c-shultz** [comment] 2023-11-08 16:17
Adding to our queue, but when we look into this, let's look at the root cause of the compatibility issues with Box Office and other extensions. Maybe we can address this by fixing compatibility instead of introducing the filter to hide it? Does @Automattic/axiom's work on the pay for order flow impact this?

**Comment by hsingyuc** [comment] 2023-11-10 13:23
Yes, this hook would be useful and no, this won't affect the pay-for-order flow.   This only affects the product page and the pay-for-order flow is only on the checkout page.

**Comment by pierorocca** [comment] 2024-05-15 19:40
Going to close this out as WooPay compatibility compared to Apple and Google compatibility are vastly different. We may need a separate way for a developer to declare incompatibility with WooPay

**Closed as completed by pierorocca** 2024-05-15 19:40 UTC
Labels: priority: medium, focus: woopay, Bug
