### ISSUE TITLE
Tax is calculated twice for virtual products if Apple/Google Pay is used on product pages

### ISSUE THREAD

**Issue by grig-23** [Automattic/woocommerce-payments#7577] opened 2023-10-29 12:56 UTC
### Describe the bug
With certain tax settings, tax is calculated twice for virtual products if Apple/Google Pay is used on product pages.

### To Reproduce

Settings:

<img width="1607" alt="Screenshot 2023-10-29 at 13 45 52" src="https://github.com/Automattic/woocommerce-payments/assets/13084901/c8569b06-86c0-4f4c-b43d-8d02eb684f20">

<img width="1451" alt="Screenshot 2023-10-29 at 13 46 07" src="https://github.com/Automattic/woocommerce-payments/assets/13084901/14e34f21-19b0-4c7a-b618-34a0b009656c">

<img width="1615" alt="Screenshot 2023-10-29 at 13 46 55" src="https://github.com/Automattic/woocommerce-payments/assets/13084901/b0ff1eaf-5bce-4329-96eb-a6f80c13a427">

Product settings:

<img width="1635" alt="Screenshot 2023-10-29 at 13 48 53" src="https://github.com/Automattic/woocommerce-payments/assets/13084901/50cf667e-cdca-4e4d-8fad-1319396d2d7f">

1. Open a browser that works with Apple or Google Pay set up.
2. Click the Apple or Google Pay button on the product page.
3. The tax is already included into the product price but it's added again in the Apple/Google Pay window on the product page:

<img width="674" alt="Screenshot 2023-10-29 at 13 50 02" src="https://github.com/Automattic/woocommerce-payments/assets/13084901/a781d63a-2dd8-4075-96a3-8492b44f952f">

If a product is not virtual, then tax is added for a couple of seconds and then removed:

<img width="348" alt="Screenshot 2023-10-29 at 13 52 15" src="https://github.com/Automattic/woocommerce-payments/assets/13084901/fc104395-e747-4ed9-b13a-484fde1be329">
<img width="387" alt="Screenshot 2023-10-29 at 13 52 24" src="https://github.com/Automattic/woocommerce-payments/assets/13084901/cdac61d1-2f95-4bb9-95a3-5d045ad83d26">

Also, this doesn't happen on cart or checkout pages.

### Actual behavior

Tax is added on top of the product price. If product is virtual, that price with 2x tax remains displayed in Apple/Google Pay window, while if a product is not virtual - it's only displayed for a few seconds and then correct price is displayed.

### Expected behavior

Tax is already included in product price so shouldn't be included twice.

### Desktop (please complete the following information):

* OS: 13.4.1
* Browser [e.g. chrome, safari] Safari
* Version [e.g. 22] 118.0.5993.88 

### Additional context

7231902-zen

**Comment by htdat** [comment] 2023-10-30 06:39
This issue impacts "Additional Payment Methods (including Apple Pay / Google Pay)", so assigning to Fusion (based on team responsibilities Pc2DNy-3z-p2) cc team lead @anu-rock. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by anu-rock** [comment] 2023-10-31 08:36
Pinging @frosso from Heisenberg who are the new owners of Local and Additional Payment Methods.

**Comment by frosso** [comment] 2023-12-07 15:21
After talking with Guilherme, we noticed that the original estimate I gave to this issue was much lower than expected. I updated it to reflect it.

**Comment by gpressutto5** [comment] 2023-12-08 23:27
### Update

It's been some time since I started working on this issue, and I think it's time to write down what I've learned so far.

First of all, it is important to note that, when the bug happens, the price displayed is greater than the price that is actually charged. This means that the customer will always **pay less than what is displayed**. And the merchant will always **get the correct amount**. And the bug only happens in a very specific scenario, which is why I'm lowering the priority to low.

-----

We have this problem only in Product pages because the price we use to initialize the Payment Request for the product comes from a different method.
The reason the price updates to the correct value for physical products is because another request is required to calculate the shipping costs, and this request updates the price. Digital products don't require shipping, so the price is not updated.
I started by trying to update the price when the order is created, right after the customer clicks the button, to ensure the price is always correct in the end, even if it started wrong. This would not fix the root cause of the problem, but it would help prevent this confusing situation in the future. But I couldn't do this because: _"You cannot update Payment Request options while the payment sheet is showing."_ So I moved on to another approach.

-----

These are the WC options that may affect how taxes are displayed:

- Prices entered with tax: ✅ Yes, inclusive / ❌ No, exclusive 
- Display prices in the shop: ✅ Including tax / ❌ Excluding tax
- Display prices during cart and checkout: ✅ Including tax / ❌ Excluding tax
- Display tax totals: 📝 Itemized / 💲 As a single total
- Calculate tax based on: 🚛 Customer shipping address / 💳 Customer billing address / 🏬 Shop base address

I tested all the combinations of these options (excluding "Calculate tax based on", which was fixed to "Shop base address") and the results are in this [spreadsheet](https://docs.google.com/spreadsheets/d/1Fk5ta7DfRKIUMmA8YfsZH8ZhxAV2VTQY0d8mABUMd0w/edit?usp=sharing).

![image](https://github.com/Automattic/woocommerce-payments/assets/12385501/ef28ae63-f380-4b44-afae-d2d4d2735bb0)

It is easy to notice that the error only happens when the **"Prices entered with tax"** option is set to **"✅ Yes, inclusive"** and **"Display prices during cart and checkout"** is set to **"❌ Excluding tax"**. I'm still working on this but I think that the problem is that this is related to [us using the woocommerce_tax_display_cart option](https://github.com/Automattic/woocommerce-payments/blob/fc0f89dbba6038d48c624a9ab1ce47e809311b70/includes/class-wc-payments-payment-request-button-handler.php#L1520C67-L1520C67), while [`wc_get_price_including_tax` uses the `woocommerce_prices_include_tax` option](https://github.com/woocommerce/woocommerce/blob/1128401778c2f74730a044fecd05b3b11c2b4ef0/plugins/woocommerce/includes/wc-conditional-functions.php#L367C2-L367C2). Simply updating this option won't work because it will affect the prices in the endpoints that should use the cart prices. Now that we know what is causing the problem, the "solution" is simple, but I noticed we don't have any tests for anything related to taxes and Apple Pay, so I'm working on adding them.

> ❗️ Important: When "Calculate tax based on" is set to "Customer shipping address" or "Customer billing address", Default customer location is set to "No location by default", and the customer is not logged in the products will always be displayed excluding tax, even if the "Display prices in the shop" option is set to "Including tax".

-----

### Confusing setting

I also noticed a confusing situation when Prices are entered with tax ✅, Price is displayed in the shop excluding tax ❌, and Price is displayed in the checkout including tax ✅. I don't consider this wrong, because it is obeying the seeting. This is confusing in the regular checkout too, and we already show the "Inconsistent tax setting" warning.

| ![image](https://github.com/Automattic/woocommerce-payments/assets/12385501/4896670c-b6e5-4708-8adc-78d88c24f099) | ![image](https://github.com/Automattic/woocommerce-payments/assets/12385501/ec94ecf0-8f49-4ec4-af9c-a2af0f0dc433) | ![image](https://github.com/Automattic/woocommerce-payments/assets/12385501/15894de5-7024-47b4-a3d6-bdef370b50f2) |
| ---- | ---- | ---- |

-----

### Digital products tax calculation

Now, besides this bug, there's another thing that I need to check and fix if necessary. When the customer is using Apple Pay, the shipping address is used as the billing address as Stripe does not collect a billing address. It works for Physical products because the shipping address is used as the billing address (TODO: test this). For digital products, the shipping/billing address is not collected so we can't calculate tax. We could require a shipping address for Digital product but only offer a "Digital" free shipping method just so we have an address to calculate tax. Anyway, this is just a thought, I need to check if this is really a problem.

**Closed as completed** 2023-12-15 14:51 UTC
Labels: type: bug, priority: low, component: checkout, component: payment request button
