### ISSUE TITLE
Checkout form sections remain blocked on error

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#550] opened 2020-04-03 16:35 UTC
On checkout error:

<img width="803" alt="Screen Shot 2020-04-03 at 12 25 59 PM" src="https://user-images.githubusercontent.com/1867547/78384066-7cae3000-75a7-11ea-9ba1-42b55ba06092.png">

…parts of the form (including the "Place Order" button) remain in a loading state:

<img width="366" alt="Screen Shot 2020-04-03 at 12 26 11 PM" src="https://user-images.githubusercontent.com/1867547/78384137-a0717600-75a7-11ea-8ee9-a23878dd493f.png">

Tested by disconnecting from WCPay server.

Not sure if that's unique to this gateway. I think this handling is actually in WooCommerce core, but haven't looked into it. Tested with Storefront.

**Comment by vbelolapotkov** [comment] 2021-12-27 12:06
Cannot reproduce this anymore. I think it might be fixed with one of the enhancements to form blocking/unblocking behavior.

**Closed by vbelolapotkov** 2021-12-27 12:06 UTC
