### ISSUE TITLE
Orders paid with Apple Pay are shown as credit card payments when HPOS is enabled

### ISSUE THREAD

**Issue by mordeth** [Automattic/woocommerce-payments#8095] opened 2024-01-26 14:48 UTC
### Describe the bug
A merchant reported issue where orders paid with Apple Pay are shown as Credit Card payments. 

### To Reproduce
1. Purchase a product and complete the transaction using Apple Pay.
2. Go to the 'Orders' section and open the most recent order.
3. Confirm that the 'Payment via' label shows Credit card / debit card instead of Apple Pay.

_P.S. I couldn't replicate the issue on my installation. Nevertheless, it can be easily reproduced on the merchant's site._

### Screenshots
<img width="721" alt="Screenshot 2024-01-26 at 16 39 06" src="https://github.com/Automattic/woocommerce-payments/assets/8667118/79b917f7-d60d-4e0c-b39e-c7bd348d9704">

### Additional context
[More context](https://a8c.slack.com/archives/C7U3Y3VMY/p1705863773054239)

**Comment by csmcneill** [comment] 2024-01-29 15:56
I can't reproduce this with a test Apple Pay payment...

![apple pay test](https://github.com/Automattic/woocommerce-payments/assets/82999806/093de2f1-b4c1-445c-9688-9180cc18f9e2)

...or a live Apple Pay payment...

![apple pay live](https://github.com/Automattic/woocommerce-payments/assets/82999806/ab614a12-42b9-4acb-a049-77291025b7b4)

...with just Woo and WooPayments WCPay active:

```
### Active Plugins (2) ###

WooPayments: by Automattic – 7.1.0
WooCommerce: by Automattic – 8.5.2
```

```
### WooPayments ###

Version: 7.1.0
Connected to WPCOM: Yes
WPCOM Blog ID: [redacted]
Account ID: [redacted]
Payment Gateway: Enabled
Test Mode: Disabled
Enabled APMs: card,affirm,klarna,afterpay_clearpay
WooPay: Disabled
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled
```

**Comment by zmaglica** [comment] 2024-01-29 16:08
This issue impacts Apple Pay, so assigning to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) @FangedParakeet. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by csmcneill** [comment] 2024-01-29 16:55
I was finally able to reproduce this. It appears to be an issue with HPOS.

I tried to mirror all of the WooPayments and Woo core settings with my own test site; the only way I could reproduce this is if `WordPress posts storage (legacy)` was enabled. Enabling compatibility mode did not alter the behavior.

Test payment with HPOS enabled:
![wcpay test hpos enabled](https://github.com/Automattic/woocommerce-payments/assets/82999806/a87e4282-43f8-4205-b415-a2cdfdb40701)

Test payment with HPOS disabled:
![wcpay test hpos disabled](https://github.com/Automattic/woocommerce-payments/assets/82999806/da016ce6-4784-46d7-b0ad-ae25f2d37dad)

**Closed as completed** 2024-02-08 16:58 UTC
Labels: type: bug, priority: high, component: payment request button, category: core
