### ISSUE TITLE
Missing ‘Make Payment' button in loan overview page

### ISSUE THREAD

**Issue by shohanhossainnab** [Automattic/woocommerce-payments#8844] opened 2024-05-19 05:58 UTC
### Describe the bug

[This FAQ](https://woocommerce.com/document/woopayments/stripe-capital/faq/#can-i-repay-my-loan-early) doc says there should be a 'make payment' button in a loan overview page, which can be used to repay a loan. It looks like WooPayments never had this option/button. [this](https://github.com/Automattic/woocommerce-payments/pull/3750) is the PR that introduced the "Active loan overview" card, and looking at the commits doesn't indicate that this option was implemented.

### To Reproduce

Go to the Loan Overview page and check if there's a 'Make payment' button.

### Actual behavior

There's no 'Make payment' button.
### Expected behavior

As per the doc, there should be a 'Make payment' button.

**Comment by shohanhossainnab** [comment] 2024-05-19 05:59
8169781-zen

**Comment by haszari** [comment] 2024-05-20 22:07
> [This FAQ](https://woocommerce.com/document/woopayments/stripe-capital/faq/#can-i-repay-my-loan-early) doc says there should be a 'make payment' button in a loan overview page, which can be used to repay a loan.

As I understand it the loan payments are automatically deducted from deposits (payouts) and there's no UI to make an early / manual payment. @shohanhossainnab has the doc been updated? I can't find mention of a `Make payment` button.

Tagging in @souravdebnath1986 for comment - was a manual payment button considered? 

Assuming this is not supported and loans are working as designed, I think we can close this issue.

**Comment by aheckler** [comment] 2024-05-20 22:49
> has the doc been updated? I can't find mention of a Make payment button.

I updated it earlier today. p1716214528566469/1716069916.520689-slack-C03EE4CPPK5

**Comment by haszari** [comment] 2024-08-15 03:12
Closing, there's no mention of `Make payment` button or manual payment on the [FAQ page](https://woocommerce.com/document/woopayments/stripe-capital/faq/#repay-early).

**Closed as not planned by haszari** 2024-08-15 03:12 UTC
Labels: type: bug, needs feedback, focus: capital

**Comment by aheckler** [comment] 2024-08-15 14:42
To clarify: originally the project thread for Capital did include a phase where we'd add the ability for merchants to manually make payments against their financing, but IIRC that phase was skipped/cancelled because Stripe doesn't seem to make that functionality available via API. 

Project thread: paJDYF-2Zt-p2

Stripe docs: https://docs.stripe.com/capital/api-integration

@dougaitken Should we circle back around with Stripe on this one?

**Comment by dougaitken** [comment] 2024-08-20 15:56
No need to circle back to Stripe - adding this into the experience is something we can do ourselves via code.
