### ISSUE TITLE
Add WooCommerce Order ID To Bank Statements

### ISSUE THREAD

**Issue by theabhig** [Automattic/woocommerce-payments#7789] opened 2023-11-27 12:28 UTC
### Description

In 7340232-zd-a8c, the merchant has asked for a feature to be added that the order ID from WooCommerce be added to the statement descriptor for deposits paid out from WooPayments. 

It's somewhat similar to https://github.com/Automattic/woocommerce-payments/issues/5316, where the request is for the trace ID to be added to the WooPayments dashboard. There may be some room for improvement in allowing ways for merchants to reconcile deposits from their orders.

### Additional context

7340232-zd-a8c

**Comment by csmcneill** [comment] 2023-11-27 14:48
Some additional context:
- p1701047344413969/1701047214.279079-slack-C03EE4CPPK5
- p1700139817340369-slack-C3NCP7ZJ6
- p1700157221346599-slack-C2XV6JSJJ

**Comment by RadoslavGeorgiev** [comment] 2023-11-28 09:09
This issue impacts Deposits, so assigning to @Automattic/helix  (based on team responsibilities Pc2DNy-3z-p2).
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by brucealdridge** [comment] 2023-11-29 02:48
@Automattic/fusion This issue seems like a duplicate of #5316 which is in your backlog. 
Based on this I've removed `Deposits` component and adding `Reporting`

**Comment by Beata19** [comment] 2023-12-06 10:47
I am the person who raised this ticket. Going to my business bank and viewing transactions today, I can still see one from 5 December and it does not have any component that would allow me track this payment and link it with the clients. There is a 4-digit number on the transaction but a differend 4-digit number on the Woo order on website. An easy way to link the payment would be by using the same 4-digit number... Is this possible?

**Comment by haszari** [comment] 2023-12-06 20:45
Thanks for following up @Beata19 !

> There is a 4-digit number on the transaction but a different 4-digit number on the Woo order on website.

Can you share screenshots of your Woo dashboard showing the 4-digit deposit ID you expect to see in your bank account? Note that WooPayments deposits (payouts) typically include multiple transactions (orders, refunds, fees etc).

**Comment by Beata19** [comment] 2023-12-06 21:13
Thank you for getting back to me on this, Rua.
I attach two screenshots, one for what I see in my bank transactions on the
account, with lots of references, one of them is a 4-digit number: 0846 and
the second one is from WordPress Woo dashboard with an order, again with
various references, one o them is a 4-digit number: #3687
My query is if it is possible to create a link between the two, the bank
deposit and the Woo order on WordPress, which would allow me to identify
the payment. I thought the 4-digit number could be the option if it was the
same number in both places. You may have another suggestion. At the moment
I am unable to track the transactions meaning that I don't know which
payment is from which client.

Best wishes,
Beata

**Comment by haszari** [comment] 2023-12-06 21:41
@Beata19 looks like those email image attachments didn't make it! Try adding in the GitHub web UI: https://github.com/Automattic/woocommerce-payments/issues/7789

**Comment by Beata19** [comment] 2023-12-06 22:10
Trying another way to send them:
1) first is from my bank account deposit
[image: image.png]

2) second from WordPress Woo order
[image: image.png]

Hope you can see them here.
Thank you,
Beata

**Comment by haszari** [comment] 2023-12-06 22:15
@Beata19 Still no images sorry. On GitHub web UI you can drag and drop image files and they upload => embed automatically.

Go here: https://github.com/Automattic/woocommerce-payments/issues/7789 and add a comment direct!

**Comment by csmcneill** [comment] 2023-12-06 22:28
Hey @Beata19! To expand on Rua's suggestion, GitHub is really responsive when adding screenshots as a comment. Here's what I recommend:

1. Navigate to the issue on GitHub directly at https://github.com/Automattic/woocommerce-payments/issues/7789
2. Scroll to the bottom of the page to find the `Add a comment` text field.
3. Write your text as you wish (if desired) in the text field.
4. Drag and drop the image(s) you wish to share into text field.
5. GitHub will do some work to upload the image(s) and write code for them to be inserted automatically as a comment. It will look like `![file-name](https://github.com/uploaded-file)`
**Optional**: Select the `Preview` option above your comment to see what your comment will look like once it's published.
6. Select the `Comment` button to post.

Here's a GIF of that process:

![CleanShot 2023-12-06 at 16 22 03](https://github.com/Automattic/woocommerce-payments/assets/82999806/df27643a-ff25-4cb4-9718-057a7e847889)

Once you select the `Comment` button, the page will reload with your comment saved. I hope this helps! Let us know if you have any further questions!

**Comment by Beata19** [comment] 2023-12-06 22:50
Ok, it’s getting late here (I am in the UK), but will do it tomorrow
morning,
Thank you - Beata

**Comment by Beata19** [comment] 2023-12-07 10:20
here are the images from the WordPress Woo dashboard and bank transaction:
![order 3687](https://github.com/Automattic/woocommerce-payments/assets/82999806/c29f68f0-0bfa-40df-8d32-537e6df97c91)
![Woo C deposit on bank statement](https://github.com/Automattic/woocommerce-payments/assets/152864274/65c947ff-86dc-4449-8915-73415a35982a)

**Comment by csmcneill** [comment] 2023-12-07 17:10
That looks a lot better, @Beata19! Thank you for sharing!

**Note**: I've taken the liberty of modifying your post a bit to obscure the PaymentIntent ID and the customer's IPv6 address.

Regarding the `#3687` digits in the order:
- This is related to the order number for that particular payment. 
- This is an identifier that is assigned to an order within the core WooCommerce plugin, and it operates independently of WooPayments.
- The number is pulled from how the order is stored in the site's database.
- The number can be changed using plugins, such as [Sequential Order Numbers Pro](https://woo.com/products/sequential-order-numbers-pro/).

Regarding the `0846` digits in the bank transaction:
- This appears to be some information added by your bank.
- Since these digits follow the deposit date of 5 December 2023, it's possible that this could be the time that these funds became available displayed in an `HHMM` format instead of an `HH:MM` format (e.g., 08:46), but I cannot be certain.
- This information does not appear to be related to the deposit of `£34.31` on 5 December 2023 in your provided screenshot, at least based on the information available to us.

I would recommend contacting your financial institution and asking about the `0846` digits and their meaning. While we're experts on our own products, more details about this are best provided by your bank (and more importantly, I'd rather not give you any incorrect information).

**Comment by Beata19** [comment] 2023-12-07 17:50
Hi Chris,
many thanks for getting back to me and for obscuring the details in the
image.

I had spoken to my bank already and they basically say that they don't have
any other information to show me in the deposits made by Woo which would
help me link them to the payment I can see on WordPress. The idea that the
4-digit numbers could be used to link the two was my own.

As you explained that there is no way yo use the 4-digit numbers to locate
the transactions and that they cannot help me track the deposit, is there
any other way Woo can include details of the transaction when making a
deposit to my bank account? All I need is some element of the reference
showing in the deposit to be reflected in the order number on Word Press...

Best wishes,
Beata

**Comment by csmcneill** [comment] 2023-12-07 18:43
> many thanks for getting back to me and for obscuring the details in the
image.

Of course!

> Is there any other way Woo can include details of the transaction when making a deposit to my bank account?

We are exploring options, like including the trace ID in a Woo site's admin dashboard (see #5316 for more details) but we are currently unable to do so as the information has not surfaced via our payment provider's API, which is required for us to accommodate such a request. They plan on surfacing the trace ID via their API in the first half of 2024 ([reference](https://github.com/Automattic/woocommerce-payments/issues/5316#issuecomment-1828313590)), but that is currently our best estimate.

We are also discussing other options internally, but we do not have any additional updates that we can share at the moment. When we do, we will update this issue.

**Comment by Beata19** [comment] 2023-12-07 19:34
Thank you, Chris.
It is good to know that there are some options on the table and
improvements might be available in the new year. Will I have to follow it
on the GitHub or would any changes be communicated in another format?
Bw, Beata

**Comment by csmcneill** [comment] 2023-12-07 19:52
> Will I have to follow it on the GitHub or would any changes be communicated in another format?

Nope! We will reach out to you :) 

In the top comment, you'll see the following:

```
7340232-zd-a8c
```

This is a reference to your original interaction with our team of Happiness Engineers. Once we're able to implement this, a member of our team will reach out to you to let you know — likely as a reply to your original inquiry.

You are definitely more than welcome to stay subscribed to these issues, though, so that you can proactively stay up-to-date with the latest developments. You'll be notified via email as comments are made by individual contributors and when the issues are eventually closed when fixes are implemented.

If you receive an email that says...

```
Closed #xxxx as completed via #yyyy.
```

...that means that the issue (`#xxxx` in the above example) was closed because a modification to the code (often called a "pull request", which would be referenced by the `#yyyy` in the above example) has been approved. When this happens, it means that the approved code change to resolve the issue will likely be released in an upcoming version of WooPayments. I say **likely** because this may not always be the case, as there may be a dependency elsewhere that is required for the change to truly be implemented.

We release new versions of WooPayments on a regular cadence, and our team of Happiness Engineers keeps a watchful eye on the changes in each version. This allows us to notify merchants who may benefit from changes in each version without them having to monitor GitHub :)

**Comment by haszari** [comment] 2023-12-07 19:54
> It's somewhat similar to https://github.com/Automattic/woocommerce-payments/issues/5316, where the request is for the trace ID to be added to the WooPayments dashboard. There may be some room for improvement in allowing ways for merchants to reconcile deposits from their orders.

Re-reading this issue – I was assuming this was the issue requesting a payout trace ID to link payouts/deposits.

> > In 7340232-zd-a8c, the merchant has asked for a feature to be added that the order ID from WooCommerce be added to the statement descriptor for deposits paid out from WooPayments.

I don't think this is possible – orders are not 1:1 associated with deposits. So this feature would need to show multiple (possibly many many) order IDs in each deposit. 

I think this bug should be closed, I don't see a path to implementing this specific fix. We can use #5316 and other issues to track efforts to help link deposits across Woo dashboard => bank statements. 

@souravdebnath1986 let me know what you think – feel free to close issue if you agree.

**Comment by csmcneill** [comment] 2023-12-07 20:12
> I think this bug should be closed

Maybe not yet. I noted this in p1701975234195339-slack-C04DN7Q51KK but I'm sharing my idea here.

I'm not sure what the limitations are, but if we can pass a unique value alongside the [payout statement descriptor](https://stripe.com/docs/connect/payout-statement-descriptors), and we then surface that unique value in wp-admin, it could potentially resolve the issue without relying on the payout trace ID.

I think that the underlying issue here isn't that an order ID should be linked to a deposit. I think that having some information on a bank statement identifying that deposit that also coincides with some information in the deposit details at **Payments > Deposits** would be sufficient.

**Comment by haszari** [comment] 2023-12-07 20:22
> I'm not sure what the limitations are, but if we can pass a unique value alongside the [payout statement descriptor](https://stripe.com/docs/connect/payout-statement-descriptors), and we then surface that unique value in wp-admin, it could potentially resolve the issue without relying on the payout trace ID.

This sounds very similar to the requests behind #5316 – a way to link Woo payout to bank transaction line. 

This issue (based on the title and the discussion) is about linking a deposit to an order – I assume for a store that tends to have low order traffic (1:1 order to payout ratio) which is uncommon.

> I think that the underlying issue here isn't that an order ID should be linked to a deposit. I think that having some information on a bank statement identifying that deposit that also coincides with some information in the deposit details at Payments > Deposits would be sufficient.

IMO that's 100% what #5316 is about.

**Comment by haszari** [comment] 2023-12-15 01:17
Closing – this issue is focused on linking individual orders to deposits. This is an uncommon use case; most deposits include funds from a large number of transactions and orders. 

We (thank you Fusion team!) are looking into ways to better link the deposit to a bank statement line in #5316 

- #5316

**Closed as not planned** 2023-12-15 01:18 UTC
Labels: type: enhancement, component: reporting, priority: medium

**Comment by Beata19** [comment] 2023-12-16 18:10
Hi,
just checking if someone is still looking into this issue?
90% of my transactions are individual transactions, not bulk ones, so it
would be important to have a reference identifying them and linking with
the bookings visible on the website.
I am still very hopeful that you can help.
Best wishes, Beata

**Comment by haszari** [comment] 2023-12-17 19:58
Hi there @Beata19 - thanks for checking in.

This issue has been closed. Linking individual orders to deposits is an uncommon case, so it's not practical to add support for that flow directly. Most stores have many orders included in each deposit, and we can't design a UI that works well for both scenarios.

However, we are looking at ways to more directly link a deposit in WooPayments (admin dashboard) and on bank statements. This should allow you to directly link an order => to a deposit in Woo admin => to a line on your bank statement. 

There's no ETA for when this will be released, if you're interested to follow along, the work is tracked in the following issue:

- #5316
