### ISSUE TITLE
Klarna BNPL messaging appears on products that do not meet the minimum order amount for Klarna

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7530] opened 2023-10-20 22:15 UTC
### Describe the bug
In most of my tests, Klarna will only appear if the cart total is between `1000` and `500000` (e.g., $10.00–$5000.00 USD).

However, if a product is below this minimum amount, the Klarna messaging will still render in the `payment-method-message` DIV in some instances:

- UK account presenting in GBP
- ES account presenting in EUR
- NL account presenting in EUR
- DE account presenting in EUR
- FI account presenting in EUR
- BE account presenting in EUR
- AT account presenting in EUR

Other combinations (e.g., US account presenting in USD) still rendered the `payment-method-message` DIV, but the resulting messaging would not render.

Additionally, when adding the product to the cart from the product page—which renders a `woocommerce-message` DIV denoting a successful addition to the cart—the Klarna messaging wouldn't _always_ display. Sometimes, I would have to empty the cart _or_ navigate to the product page in a way that removed the `woocommerce-message` DIV (e.g., 

### To Reproduce

1. Onboard with a WCPay account based in the Netherlands.
2. Create a product with a price of €1.00 EUR.
3. Enable Klarna on the account.
4. Navigate to the product page.
5. Notice that the Klarna messaging is (very likely) displaying.
6. Add the product to the cart.
**Note**: The Klarna messaging may no longer display if the `[Product name] has been added to your cart!` message is displayed. I've had mixed results here at best.
7. Navigate to the checkout page.
8. Notice that Klarna is not offered as a payment method.
9. Navigate to the cart page.
10. Increase the quantity of the product to 10+.
11. Repeat step 7.
12. Notice that Klarna is now offered as a payment method.

### Actual behavior

Klarna messaging is offered on products that do not qualify for Klarna BNPL.

### Screenshots
![CleanShot 2023-10-20 at 17 04 55@2x](https://github.com/Automattic/woocommerce-payments/assets/82999806/259ab8cf-9a35-4528-afbe-3886eb3edb3d)

![CleanShot 2023-10-20 at 17 06 06@2x](https://github.com/Automattic/woocommerce-payments/assets/82999806/d31bd5e7-bf5b-4b36-8907-8326e51d1dac)

![CleanShot 2023-10-20 at 17 12 25@2x](https://github.com/Automattic/woocommerce-payments/assets/82999806/a85dbe5d-1e91-40aa-a77e-7c725831f7d9)

### Expected behavior

Klarna BNPL messaging on the product pages should only appear if the product meets the minimum amount to be purchased with Klarna BNPL—similar to Affirm.

### Additional context

p1697838411649109-slack-C04VCT34PCP

**Comment by kalessil** [comment] 2023-10-23 08:21
Currently, the available PMs [injected into the messaging element](https://github.com/Automattic/woocommerce-payments/blob/develop/client/product-details/bnpl-site-messaging/index.js#L7) without connection binding to variation.

Propose solution: actualize this [method](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-payment-method-messaging-element.php#L49) (and JS-code accordingly) to inject methods per variation, iterating enabled BNPLs and ensuring the variation price&currency is matching [defined limits](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-klarna-payment-method.php#L35).

**Comment by kalessil** [comment] 2023-10-23 09:00
:top: just an idea. If Stripe correctly handles ranges for other BNPLs inside element, then we should report a bug to Stripe instead of changing our integration.

**Comment by mgascam** [comment] 2023-10-23 16:05
I had a look and it seems that the [Payment Method Messaging Element](https://stripe.com/docs/payments/payment-method-messaging) does not honor the defined limits for Klarna.

This is what I get when I test the different country and currency combinations with the lower limit (1000 cents). Please note that for this tests I'm hardcoding the values in the requests to the Payment Method Messaging Elemen, bypassing the logic we have in place:

| Currency | Country | Amount | Result            |
|----------|---------|--------|-------------------|
| USD      | US      | 1000   | ❌Klarna missing   |
| GBP      | GB      | 1000   | ✅ Klarna listed   |
| EUR      | ES      | 1000   | ✅Klarna listed    |
| EUR      | AT      | 1000   | ✅Klarna listed    |
| EUR      | DE      | 1000   | ✅Klarna listed    |
| EUR      | NL      | 1000   | ✅Klarna listed    |
| EUR      | BE      | 1000   | ✅Klarna listed    |
| EUR      | IT      | 1000   | ❌Klarna missing   |
| EUR      | IE      | 1000   | ❌Klarna missing   |
| EUR      | FI      | 1000   | ❌Klarna missing   |
| DKK      | DK      | 1000   | ✅Klarna listed    |
| NOK      | NO      | 1000   | ✅Klarna listed    |
| SEK      | SE      | 1000   | ✅Klarna listed    |

Notably, with USD and US, Klarna is not rendered by the Stripe messaging element. Same happens to EUR-IT, EUR-IE and EUR-FI.

But things get odd when I test with 1 cent:

| Currency | Country | Amount | Result            |
|----------|---------|--------|-------------------|
| USD      | US      | 1      | ✅Klarna missing   |
| GBP      | GB      | 1      | ✅Klarna missing   |
| EUR      | ES      | 1      | ❌Klarna listed    |
| EUR      | AT      | 1      | ✅Klarna missing   |
| EUR      | DE      | 1      | ✅Klarna missing   |
| EUR      | NL      | 1      | ✅Klarna missing   |
| EUR      | BE      | 1      | ✅Klarna missing   |
| EUR      | IT      | 1      | ✅Klarna missing   |
| EUR      | IE      | 1      | ✅Klarna missing   |
| EUR      | FI      | 1      | ✅Klarna missing   |
| DKK      | DK      | 1      | ✅Klarna missing   |
| NOK      | NO      | 1      | ❌Klarna listed    |
| SEK      | SE      | 1      | ✅Klarna missing   |


All behave as expected, Klarna is not rendered because the amount does not reach the lower limit. With two exceptions: EUR-ES and NOK-NO, where Klarna is rendered by the Stripe messaging element.

We will need to confirm with Stripe if this behavior is by design or maybe there's a bug. If this is by design, then it feels like we don't know the rules behind it.

Anyway, we could follow the approach that Vlad suggested above to check if the amount is within the limits of Klarna before sending it as part of the available payment methods in the store. The way the Stripe messaging element works, it won't render a payment method if it is not included as part of the available payment methods.

Apart from this, we might also need to address a problem with how we determine the country of the customer. Currently we try to get it from the billing address of the customer. But if there's no customer created yet, we fallback to the store's country as informed by a call to `WC()->countries->get_base_country()`. We can try to use the Stripe account country instead.

**Comment by kalessil** [comment] 2023-10-25 07:47
@dmvrtx : I'm thinking of closing the issue and handing it over to Stripe folks to look into. WDYT, ist it a good idea?

**Comment by dmvrtx** [comment] 2023-10-25 09:18
I've got a response from Stripe that it is indeed might be a test mode quirk. Let's see what they will answer after checking specific accounts.

**Comment by kalessil** [comment] 2023-10-25 10:15
👍 , ok.

**Comment by dmvrtx** [comment] 2023-10-27 13:28
Still no confirmation or additional information from Stripe

**Comment by dmvrtx** [comment] 2023-11-07 11:45
Report from Stripe:

> No it is not a test mode glitch...instead, min & max limits from Klarna have indeed updated/ changed in a few markets (like ES) and hence the behavior.
> For example, for ES,
>  - Pay later 30 days has a min of 0 EUR and a max of 500 EUR
>  - Pay in 3 has a min of 0 EUR and a max 4,000 EUR

**Comment by kalessil** [comment] 2023-11-07 14:00
@dmvrtx: is that something we should update on the plugin side? If so, please flag it in the the corresponding Slack channel to ensure all parties are aware of which changes need to be done.

**Comment by csmcneill** [comment] 2023-11-08 02:09
@kalessil @dmvrtx I tested this a bit on an `ES` account.

Pay in 3 messaging will show on a product that is between 0–4.000,00 EUR:

![klarna es 1k pay in 3](https://github.com/Automattic/woocommerce-payments/assets/82999806/9dcf1bee-b328-498b-bbf9-201959a0d7a9)

But it will not show for any product that is over 4.000,00 EUR:

![klarna es 4001 no messaging](https://github.com/Automattic/woocommerce-payments/assets/82999806/24bf24e2-6895-4446-80e6-ce8b8e95de58)

However, a cart that is over 4.000,00 EUR results in Klarna rendering as an option on checkout since the limit in the plugin is 5.000,00 EUR...

https://github.com/Automattic/woocommerce-payments/blob/6e50d8810b026fb923d2e39e612d0b1e34d243e5/includes/payment-methods/class-klarna-payment-method.php#L44-L47

...but the purchase cannot be completed once the customer is directed to Klarna:

![klarna es 4100 eur](https://github.com/Automattic/woocommerce-payments/assets/82999806/582df7bd-479f-4300-8f18-b8f4c8f4560f)

**Comment by csmcneill** [comment] 2023-11-08 02:16
From my vantage point, it appears as though we'll need to get an updated list of minimums/maximums per geo from Stripe/Klarna and make the appropriate adjustments in the plugin. @dannyschwantes can you help us with this request before your AFK?

**Comment by dannyschwantes** [comment] 2023-11-08 16:09
As an update to @csmcneill comment above, here is what we have from Stripe: "this is on our radar and am working with Shalini and our Klarna team to get you all the full list - just as an fyi, we're also pushing to get these added to our external docs similar to Afterpay so that it can be self-service, but this may take a little bit longer." More updates should be shared by Stripe soon and will update.

**Comment by dmvrtx** [comment] 2023-11-09 18:06
Based on the provided information I've created a #7680

Since we have per-currency limits, as opposed to the per-country ones which Stripe sets for Klarna, I'd welcome a sanity check on proposed values there.

**Comment by kalessil** [comment] 2023-11-10 09:48
Thanks @dmvrtx! Can we close this ticket then?

**Comment by dmvrtx** [comment] 2023-11-10 15:43
Closing this ticket as there is no error in the Klarna message element. Payment amount limits will be updated with #7680.

**Closed as completed by dmvrtx** 2023-11-10 15:43 UTC
Labels: type: bug, category: core, component: klarna
