### ISSUE TITLE
[GlobalStep] "Set up payment" task is marked as incomplete even if the KYC flow is completed.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#5769] opened 2023-03-14 14:49 UTC
### Bug Description:
"Set up payment" task is marked as incomplete even if the KYC flow is completed.

### Environment:
Woocommerce Version: WooCommerce 7.4.1
WooCommerce Payments - 5.6.0-test-3
WordPress version: v6.1.1

### PC:
Windows 10,
Chrome(Version 111.0.5563.65)

### Instruction link: 
https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions-for-WC-Payments-5.6.0#add-supports-for-12-new-countries

### Steps To Reproduce:
1. Create any test site using the JN site.
2. Complete the setup wizard using any country as a store address(as above mentioned in the instruction link) and select WC Payments on the Business Details step.
3. On the Home screen select Setup WooCommerce Payments task to trigger KYC flow.
4. After KYC completed and and is redirected to payment task screen.
5. Go through the setup wizard  and completed the onboarding flow.
6. Go to Woocommerce home page.
7. Observe that, "Set up payment" task is marked as incomplete even if the KYC flow is completed.

### Actual Result:
"Set up payment" task is marked as incomplete even if the KYC flow is completed.

### Expected Result:
"Set up payment" task should be marked as complete even if the KYC flow is completed.

### Video:

https://user-images.githubusercontent.com/41110392/225039444-81bb35e3-4f29-4486-ba76-e43e62a78d9b.mp4

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.55 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: wp_
Total Database Size: 6.05MB
Database Data Size: 4.52MB
Database Index Size: 1.53MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.47MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 7
post: 2
product: 18
product_variation: 7
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.11.2
Code Snippets: by Code Snippets Pro – 3.3.0
Companion Plugin: by Osk – 1.29
WooCommerce Payments: by Automattic – 5.6.0-test-3
WooCommerce: by Automattic – 7.4.1 (update to version 7.5.0 is available)

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 5.0.1
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 11.9

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: DKK (kr.)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://printed-rock.jurassic.ninja
Subscriptions-core Library Version: 5.5.0
Subscription Statuses: –
WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: Denmark

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-15 08:27:57 +00:00
Options: ✔
Notes: 39
Onboarding: completed

### WooCommerce Payments ###

Version: 5.6.0-test-3
Connected to WPCOM: Yes
Blog ID: 216662899
Account ID: acct_1MlTGkFlKXrpYzLu

### Action Scheduler ###

Complete: 40
Oldest: 2023-03-14 08:29:00 +0000
Newest: 2023-03-14 09:04:22 +0000

Failed: 1
Oldest: 2023-03-14 08:42:37 +0000
Newest: 2023-03-14 08:42:37 +0000

Pending: 1
Oldest: 2023-03-15 08:29:00 +0000
Newest: 2023-03-15 08:29:00 +0000

### Status report information ###

Generated at: 2023-03-14 14:49:01 +00:00
`

</details>

**Comment by htdat** [comment] 2023-03-17 07:50
Based on p1678850781095109-slack-C04DN7Q51KK and according to Pc2DNy-3z-p2, this falls in Fusion cc @anu-rock . 

Tagging as a part of Gamma Porter duties PcreKM-yM-p2.

**Comment by anu-rock** [comment] 2023-03-17 13:45
Hey @htdat 👋 This issue was actually discussed in p1678784392409209-slack-C011ENB20Q1 and is related to onboarding (falls under Moltres as per Pc2DNy-3z-p2). The one you've linked was about UPE with non-EUR store currency (known behavior, no action needed).

**Comment by htdat** [comment] 2023-03-20 05:24
Thanks for the comment @anu-rock, I got confused somehow.

@Automattic/moltres - could you have a look? Is this issue relevant to this PR https://github.com/Automattic/woocommerce-payments/pull/5766?

**Comment by ismaeldcom** [comment] 2023-03-20 08:40
Hey @htdat, not related with #5766, that task belongs to WC Core, I already checked it on GS help request(p1678793320774289/1678784392.409209-slack-C011ENB20Q1). Added it to our backlog for prioritization 🙂

**Comment by dmallory42** [comment] 2023-06-21 09:14
Tested and this doesn't seem like a bug: 

* After clicking the `Set up Payments` task, I am redirected to the KYC for WooPayments, and when the KYC is complete, I am taken to this page which lists APMs that can be installed.

<img width="1095" alt="Screenshot 2023-06-21 at 10 10 31" src="https://github.com/Automattic/woocommerce-payments/assets/11770181/3e608bd0-dfbb-4761-8cf3-4be7a5776ce9">

* At this point, the task is still marked as incomplete (even though we enabled WooPayments already).
* If I enable one of the APMs, like PayPal/Amazon/Cash on Delivery, the text at the top of the page changes to `You set up payments` and the task is then marked as complete.

<img width="839" alt="Screenshot 2023-06-21 at 10 14 47" src="https://github.com/Automattic/woocommerce-payments/assets/11770181/766ec55e-b989-481c-ae7b-5509b93829cd">

So it seems in order for the task to be marked as complete, first WooPayments needs to be installed, and then at least one other APM needs to be enabled. 

@elizaan36 sorry for the random ping, but I was wondering if you knew whether this is the intended behaviour or not? Thanks!

**Comment by daquinons** [comment] 2023-06-21 10:59
Let's wait for @elizaan36 input but I think that being "Additional" payment options, those should be optional and not the final requirement for marking the task as completed! I think the task should mark it as complete if:

1. WC Payments is installed and no other APM is installed
2. WC Payments is not installed and a APM is installed
3. WC Payments is installed and another APM is installed

From what I can see, seems like we are missing #1, and the one this issue is about?

**Comment by elizaan36** [comment] 2023-06-21 14:42
👋 We just chatted about this in the call but to confirm here, the task should be completed once the first payment method is enabled. So if WCPay is installed and connected the task should be marked as complete.

**Closed as completed** 2023-08-21 10:55 UTC
Labels: type: bug, priority: low, status: has pr, component: onboarding, category: core, needs prioritisation
