### ISSUE TITLE
[GlobalStep] "Payment Request" button fails to display on "Product", "Cart" and "Checkout" page.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#4092] opened 2022-04-05 15:58 UTC
## Bug Description:
"Payment Request" button fails to display on "Product", "Cart" and "Checkout" page.

## Environment:
Woocommerce Version : WooCommerce 6.3.1
WooCommerce  Payments  4.0.0-test-2
WordPress version: v5.9.2

PC:
Windows 10
Chrome(Version 100.0.4896.75) 
Mac OS:
Chrome(Version 100.0.4896.75) 

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Upload and activate theWooCommerce Payments - 4.0.0-test-2 plugin.
1. Add some sample products.
1. Enable Payment Request under Payment > Settings page and save settings.
1. As a Shopper go to Shop page. 
1. Add some products to cart.
1. Go to Cart page.
1. Observe that "Payment Request" button fails to display on "Product", "Cart" and "Checkout" page.

## Actual Result:
"Payment Request" button fails to display on "Product", "Cart" and "Checkout" page.

## Expected Result:
"Payment Request" button should display on "Product", "Cart" and "Checkout" page.

## Screenshot:

![Payment request1](https://user-images.githubusercontent.com/41110392/161796269-f806f083-92f3-4d33-9630-c5e057a36d81.jpg)

![Payment request2](https://user-images.githubusercontent.com/41110392/161796280-d8c9ef8d-410c-4487-8557-1a86400574a1.jpg)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 7.3.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: 5.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.53 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.28
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.3.1
WC Database Prefix: wp_
Total Database Size: 7.23MB
Database Data Size: 5.28MB
Database Index Size: 1.95MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.44MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.39MB + Index: 0.34MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 25
page: 10
post: 2
product: 23
product_variation: 7
revision: 4
shop_coupon: 1
shop_order: 57
shop_order_refund: 7
shop_subscription: 16
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (7) ###

Query Monitor: by John Blackbourn – 3.8.2
Code Snippets: by Code Snippets Pro – 2.14.3
Companion Plugin: by Osk – 1.24
WooCommerce Blocks: by Automattic – 7.3.0
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 4.0.0-test-2
WooCommerce: by Automattic – 6.3.1

### Inactive Plugins (4) ###

Akismet Anti-Spam: by Automattic – 4.2.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 10.7
WooCommerce Subscriptions: by WooCommerce – 4.1.0

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://wealthy-meadowlark.jurassic.ninja
Subscription Statuses: wc-cancelled: 1
wc-active: 15

WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 15
wc-cancelled: 1

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

Cash on delivery: products

### WooCommerce Payments ###

Version: 4.0.0-test-2
Connected to WPCOM: Yes
Blog ID: 205006828
Account ID: acct_1Kl6In2Hr4oEzdWN

### Action Scheduler ###

Complete: 348
Oldest: 2022-04-05 07:07:52 +0000
Newest: 2022-04-05 13:14:51 +0000

Pending: 18
Oldest: 2022-04-05 17:08:29 +0000
Newest: 2022-07-05 13:06:29 +0000

### Status report information ###

Generated at: 2022-04-05 15:50:24 +00:00
`

</details>

**Comment by cesarcosta99** [comment] 2022-04-07 05:31
I could not reproduce this issue consistently using the very same Chrome version (100.0.4896.75). Tried on Mac and PC. It's also tricky to downgrade Chrome securely so I couldn't downgrade to test it on previous versions.

IMO, the inconsistency might be happening between Stripe and Google Pay, so we may want to reach out to them to check.

Relevant thread: p1649156481972239-slack-C011ENB20Q1

cc @vbelolapotkov @naman03malhotra @htdat for visibility.

**Comment by RadoslavGeorgiev** [comment] 2022-04-26 09:20
GlobalStep reported that this is still happening last week.

**Comment by naman03malhotra** [comment] 2022-04-26 09:22
@achyuthajoy since you have already invested time investigating this issue, can you please work with GS and stripe earliest next sprint on this issue.

**Comment by achyuthajoy** [comment] 2022-04-26 10:05
Sure @naman03malhotra 👍

**Comment by achyuthajoy** [comment] 2022-05-02 12:12
Checked with Stripe here - p1651493294260359-slack-C9976E5MJ

Google Pay is working only if the account has valid saved payments. However, using an account without a valid card & cards saved on Google Chrome doesn't display the Google Pay button.

**Comment by achyuthajoy** [comment] 2022-05-03 07:29
Chrome has removed support for browser saved cards since version `100` from the Payment Request API which Stripe uses to enable Google Pay. Hence it's no longer possible to use test cards saved to the browser. 

Instead a valid card should be added to the Google account to test purchases via Google Pay.

Reference - https://blog.chromium.org/2021/10/sunsetting-basic-card-payment-method-in.html

Closing the issue.

**Closed by achyuthajoy** 2022-05-03 07:29 UTC
Labels: type: bug, component: payment request button
