### ISSUE TITLE
No option to disable built-in subscription functionality

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-payments#3572] opened 2021-12-23 00:43 UTC
### Describe the bug
As documented here: https://woocommerce.com/document/payments/subscriptions/#section-3 I expect I can enable/disable built-in subscriptions via advanced settings, but that option seems to be missing even though the store is eligible and in fact has subscriptions on and wants it off.

### To Reproduce

1. Go to Settings/Advanced as documented

### Actual behavior
No option. Had to resort to the options screen and changing _wcpay_feature_subscriptions to 0

### Expected behavior
The setting available as documented.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by brianyu28** [comment] 2022-01-04 22:17
Did this customer have the WooCommerce Subscriptions plugin installed? If so, I think this missing checkbox is intended behavior, since WCPay Subscriptions is always disabled in that case.

**Comment by haszari** [comment] 2022-01-04 23:51
Thanks for reporting @WillBrubaker ! 

There are a couple of things to be aware of with this checkbox.

- Checkbox is not available if the [store location is not USA](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-features.php#L89) (at present - due to USA-only preview feature). 
- Checkbox is not available If WooCommerce Subscriptions is installed and active.

Can you confirm if any of these factors are related to the user report? Adding an SSR would help clarify, and maybe a screenshot/vid of the broken or confusing UI.

See also the discussion on the PR introducing the new checkbox: https://github.com/Automattic/woocommerce-payments/pull/3126

**Comment by deepakpathania** [comment] 2022-02-23 14:50
Closing this since there is no reply from the OP, please re-open in case the issue persists.

**Closed by deepakpathania** 2022-02-23 14:50 UTC
Labels: type: bug, needs feedback, component: wcpay subscriptions
