### ISSUE TITLE
woopay-express-button.css file missing from v 8.3.0

### ISSUE THREAD

**Issue by hayley-king** [Automattic/woocommerce-payments#9534] opened 2024-10-07 14:27 UTC
### Describe the bug

/wp-content/plugins/woocommerce-payments/dist/woopay-express-button.css seems to be missing. There's a 404 error on pages where the WooPay button loads: product detail, cart, checkout 

### To Reproduce

My test site on Storefront with the following active plugins:
- WooCommerce 9.3.3
- WooPayments 8.3.0

1. Enable WooPayments in Sandbox mode
2. Enable WooPay and set to display on the cart, checkout and product pages
3. Visit a product detail page (also cart and checkout)
4. Review the browser console to find the 404 error

### Actual behavior
If using redirection, a 404 error is logged. Unknown whether this is causing any styling issues due to the missing file

### Expected behavior
No 404 errors caused by enabling WooPay. Include css file in the dist directory or remove the reference to the file if it's not needed

### Desktop (please complete the following information):

* OS: MacOS Sonoma 14.6.1
* Browser: Chrome 
* Version: 129.0.6668.90 (Official Build) (arm64)

### Additional context
8838935-zen (slightly different issue but led me to find this bug)
Link to file in the header: https://d.pr/i/jehmTu

**Comment by reykjalin** [comment] 2024-10-07 22:18
Closing, since this is a duplicate of #9406, and was fixed in #9509. The fix should be released with version 8.4.0 of the WooPayments plugin 🙂

**Closed as completed by reykjalin** 2024-10-07 22:18 UTC
Labels: type: bug
