### ISSUE TITLE
Back In Stock Notifications option removed from Product Editor with WooCommerce Payments active

### ISSUE THREAD

**Issue by theabhig** [Automattic/woocommerce-payments#6910] opened 2023-08-03 09:29 UTC
### Describe the bug

With WooCommerce Payments version 6.2.1 and 6.2.2 active, the back-in-stock notification that is added to the product editor using [Back In Stock Notifications](https://woocommerce.com/products/back-in-stock-notifications/) is removed.

### To Reproduce

On an install with just WooCommerce, WooCommerce Payments, and the latest version of Back In Stock Notifications enabled, set up a product that has stock management enabled under "Inventory".

We would expect to see the "Stock notifications" option to appear (see screenshot below).

### Actual behavior

This option does not appear in the product editor but appears once WooCommerce Payments is deactivated.

### Screenshots

With WooCommerce Payments active:

![Annotation on 2023-08-03 at 10-21-53](https://github.com/Automattic/woocommerce-payments/assets/75635198/82ef26cb-e924-4f92-80b0-8277a0dd6a61)

With WooCommerce Payments deactivated and Stripe active instead:

![Annotation-Annotation on 2023-08-03 at 10-20-20 png](https://github.com/Automattic/woocommerce-payments/assets/75635198/abae64eb-db93-473c-bba4-bcbe79b339a2)

### Expected behavior

We would expect the stock notifications option to appear

### Desktop (please complete the following information):

* OS: Man OS Ventura 13.4.1
* Browser: Chrome version 114.0.5735.248 

### Additional context

First reported in 6597422-zen

I was able to replicate this on my test site. Below System Status Report is from my test site (with WC Pay active):

<details><summary>WordPress Environment</summary>
<p>
<pre>
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.0.1
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wp_
Total Database Size: 44.50MB
Database Data Size: 37.73MB
Database Index Size: 6.77MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_commission_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_hits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_extCCFA_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_extCCFA_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_foosales_square_checkouts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_foosales_square_devices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_foosales_square_refunds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 27.38MB + Index: 1.72MB + Engine InnoDB
wp_postmeta: Data: 3.52MB + Index: 1.94MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.27MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcrp_rental_products_rentals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcrs_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_pos_grid_tiles: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_zapier_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_flat_rate_boxes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 2.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

addify_quote: 3
addify_rfq: 1
addify_rfq_fields: 1
attachment: 639
aw_workflow: 3
carts: 10
event_ticket: 7
event_ticket_email: 1
global_product_addon: 1
nav_menu_item: 4
odr_order_bump: 2
odr_template: 1
page: 29
pdr_design_templates: 1
pdr_product_base: 17
post: 1
pos_outlet: 1
pos_receipt: 1
pos_register: 1
pos_temp_order: 1
product: 171
product_variation: 94
revision: 16
shipping_package: 2
shop_bogof_rule: 1
shop_coupon: 11
shop_order: 115
shop_order_refund: 15
shop_subscription: 10
wcpf_item: 4
wcpf_project: 1
wc_booking: 1
wc_membership_plan: 2
wc_order_status: 11
wc_user_membership: 2
wishlist: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Jetpack: by Automattic – 12.5-a.1
WooCommerce Back In Stock Notifications: by WooCommerce – 1.6.3
WooCommerce Payments: by Automattic – 6.2.2
WooCommerce: by Automattic – 7.9.0
WP Mail Logging: by WP Mail Logging Team – 1.12.0

### Inactive Plugins (86) ###

Admin Order Modifier for WooCommerce: by Robot Dwarf – 1.0.3
Affiliate For WooCommerce: by StoreApps – 3.3.1 (update to version 6.20.0 is available)
Affiliate Program For WooCommerce: by E Plugins – 1.2.1
Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Braintree for WooCommerce Payment Gateway: by WooCommerce – 2.6.1 (update to version 3.0.4 is available)
Bundle Builder For WooCommerce: by HighAddons – 1.0.0
Cart Reports for WooCommerce: by WooCommerce – 1.2.10 (update to version 1.3.3 is available)
Code Snippets: by Code Snippets Pro – 2.14.1
Conditional Checkout Fields for WooCommerce: by FME Addons – 1.0.6
Edit Order by Customer: by Addify – 1.0.1
Facebook for WooCommerce: by Facebook – 2.6.27
FooSales for WooCommerce: by FooSales – 1.18.2
Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 2.6.0

Lottery for WooCommerce: by FantasticPlugins – 4.8
Order Bump for WooCommerce: by FantasticPlugins – 1.4
Phone Orders & Payments: by 99w – 1.0.1 (update to version 1.4.0 is available)
Point of Sale for WooCommerce: by Actuality Extensions – 5.4.1 (update to version 6.0.5 is available)
Price By Country: by HighAddons – 1.0.2 (update to version 1.0.6 is available)
Product Designer for WooCommerce: by FantasticPlugins – 1.7
Product Filters for WooCommerce: by WooCommerce – 1.2.5 (update to version 1.4.10 is available)
Quote for WooCommerce: by WPExperts.io – 1.0.0
Rental Products: by 99w – 3.0.5 (update to version 4.3.3 is available)
Request a Quote for WooCommerce: by Addify – 2.4.9
Storefront Powerpack: by WooCommerce – 1.6.1 (update to version 1.6.2 is available)
Tiered Price Table for WooCommerce: by Kolya Lukin – 4.0.0
TikTok: by TikTok – 1.0.9
USPS Simple Shipping for Woocommerce: by dangoodman – 1.5.5
Wholesale For WooCommerce: by wpexpertsio – 1.6.0
WooCommerce 360° Image: by WooCommerce – 1.1.20 (update to version 1.3.0 is available)
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.24 (update to version 1.1.43 is available)
WooCommerce Additional Variation Images: by WooCommerce – 1.9.0 (update to version 2.3.2 is available)
WooCommerce Admin: by WooCommerce – 2.6.5
WooCommerce Advanced Ajax Layered Navigation: by WooCommerce – 1.5.0 (update to version 2.0.1 is available)
WooCommerce Advanced Notifications: by WooCommerce – 1.2.30 (update to version 1.4.1 is available)
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.8 (update to version 1.1.11 is available)
WooCommerce All Products For Subscriptions: by SomewhereWarm – 3.1.26 (update to version 4.1.2 is available)
WooCommerce Blocks: by Automattic – 5.9.0
WooCommerce Bookings: by WooCommerce – 1.15.37 (update to version 2.0.0 is available)
WooCommerce Box Office: by WooCommerce – 1.1.31 (update to version 1.1.54 is available)
WooCommerce Brands: by WooCommerce – 1.6.24 (update to version 1.6.55 is available)
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.31 (update to version 2.2.35 is available)
WooCommerce Buy One Get One Free: by Oscar Gare – 2.1.9 (update to version 4.1.0 is available)
WooCommerce Checkout Field Editor: by WooCommerce – 1.6.1 (update to version 1.7.10 is available)
WooCommerce Composite Products: by SomewhereWarm – 8.1.1 (update to version 8.10.1 is available)
WooCommerce Conditional Shipping and Payments: by WooCommerce – 1.15.2
WooCommerce Currency Converter: by WooCommerce – 1.6.25 (update to version 2.0.2 is available)
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.11.0 (update to version 3.12.0 is available)
WooCommerce Deposits: by WooCommerce – 2.1.6 (update to version 2.1.7 is available)
WooCommerce Distance Rate Shipping: by Automattic – 1.0.26 (update to version 1.3.0 is available)
WooCommerce Dynamic Pricing: by Element Stark – 3.1.24 (update to version 3.2.2 is available)
WooCommerce Flat Rate Box Shipping: by WooCommerce – 2.0.16 (update to version 2.2.0 is available)
WooCommerce Freshdesk: by Automattic – 1.1.27 (update to version 1.3.0 is available)
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.3
WooCommerce Google Analytics Pro: by SkyVerge – 1.10.0 (update to version 2.0.10 is available)
WooCommerce Measurement Price Calculator: by SkyVerge – 3.19.1 (update to version 3.22.0 is available)
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.20 (update to version 4.1.0 is available)
WooCommerce Order Barcodes: by WooCommerce – 1.3.23 (update to version 1.6.5 is available)
WooCommerce Order Status Manager: by SkyVerge – 1.13.2 (update to version 1.15.2 is available)
WooCommerce Payfast Gateway: by WooCommerce – 1.5.4 (update to version 1.5.7 is available)
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce Points and Rewards: by WooCommerce – 1.7.38
WooCommerce Pre-Orders: by WooCommerce – 1.5.30 (update to version 2.0.3 is available)
WooCommerce Product Add-ons: by WooCommerce – 6.4.4
WooCommerce Product Bundles: by SomewhereWarm – 6.8.0 (update to version 6.22.2 is available)
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.41 (update to version 1.10.60 is available)
WooCommerce Product Table: by Codup – 1.2.5.4
WooCommerce Product Vendors: by WooCommerce – 2.1.49 (update to version 2.1.80 is available)
WooCommerce Quick View: by WooCommerce – 1.4.0 (update to version 1.7.0 is available)
WooCommerce Referral System: by Codup.io – 1.3.7.6 (update to version 1.3.9.24 is available)
WooCommerce Sale Flash Pro: by WooCommerce – 1.2.20 (update to version 1.3.0 is available)
WooCommerce Shipping & Tax: by WooCommerce – 1.25.18 (update to version 2.3.1 is available)
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.13 (update to version 2.5.0 is available)
WooCommerce Slack: by WooCommerce – 1.2.8 (update to version 1.3.0 is available)
WooCommerce Smart Coupons: by StoreApps – 4.17.5 (update to version 8.2.0 is available)
WooCommerce Software Add-On: by WooCommerce – 1.7.19 (update to version 1.9.1 is available)
WooCommerce Square: by WooCommerce – 4.1.0
WooCommerce Store Catalog PDF Download: by WooCommerce – 1.10.27 (update to version 2.1.1 is available)
WooCommerce Store Credit: by Themesquad – 3.6.1 (update to version 4.3.2 is available)
WooCommerce Stripe Gateway: by WooCommerce – 7.4.2
WooCommerce Subscriptions: by WooCommerce – 3.0.13 (update to version 5.3.1 is available)
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.30 (update to version 3.1.1 is available)
WooCommerce USPS Shipping: by WooCommerce – 4.4.50 (update to version 4.7.1 is available)
WooCommerce WishLists: by Element Stark – 2.2.4 (update to version 2.2.10 is available)
WooCommerce Zapier: by OM4 – 2.0.7 (update to version 2.7.2 is available)
Woo Product Table PRO: by WooBeWoo – 1.4.4
WP STAGING: by WP-STAGING – 2.8.8

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP STAGING Optimizer: by René Hermenau – 1.4.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
lottery (lottery)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)
wbb_bundle_builder (wbb_bundle_builder)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #5 - /shop/
Basket: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #107 - /lost-license/

### Theme ###

Name: Storefront
Version: 4.4.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: -----
Subscriptions-core Library Version: 6.0.0
Subscription Statuses: wc-on-hold: 5
wc-cancelled: 1
wc-active: 3
wc-expired: 1

WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No

### Store Setup ###

Country / State: United Kingdom

### Subscriptions by Payment Gateway ###

other: wc-active: 1
wc-cancelled: 1
wc-expired: 1
wc-on-hold: 1

WooPayments: wc-active: 1
wc-on-hold: 4

### Payment Gateway Support ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

Direct bank transfer: products

### Back In Stock ###

Database Version: 1.6.3
Loopback Test: ✔

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-04 06:16:48 +00:00
Options: ✔
Notes: 166
Onboarding: completed

### WooCommerce Payments ###

Version: 6.2.2
Connected to WPCOM: Yes
Blog ID: ---
Account ID: ---

### Action Scheduler ###

Canceled: 2
Oldest: 2023-07-22 05:32:33 +0000
Newest: 2023-08-03 06:33:27 +0000

Complete: 95
Oldest: 2023-07-03 12:43:09 +0000
Newest: 2023-08-03 09:23:56 +0000

Failed: 14
Oldest: 2021-06-14 11:03:07 +0000
Newest: 2023-08-03 09:13:21 +0000

Pending: 1
Oldest: 2023-08-04 06:30:05 +0000
Newest: 2023-08-04 06:30:05 +0000

### Status report information ###

Generated at: 2023-08-03 09:28:10 +00:00
</pre>

</p>
</details>

**Comment by csmcneill** [comment] 2023-08-03 23:16
My tests confirm that this only occurs when WCPay is enabled if WCPay Subs is enabled. Disabling WCPay Subs at **Payments > Settings** resolves the issue.

Additionally, if I install and activate WC Subs without WCPay active, this same issue occurs—which makes me believe that this is related to subs core.

**Comment by csmcneill** [comment] 2023-08-03 23:24
There is a `display: none;` option for this specific element:

![Markup on 2023-08-03 at 18:19:39](https://github.com/Automattic/woocommerce-payments/assets/82999806/5f8f0a13-f232-4bb5-8c45-440706451b64)

If I comment this out via my browser's developer tools (GIF [here](https://justfortestingwcpay.com/wp-content/uploads/2023/08/Screen-Capture-on-2023-08-03-at-18-21-35.gif)—it's too big to upload), it shows as expected.

It seems like when WCPay Subs or WC Subs are enabled, this is hidden programmatically.

**Comment by htdat** [comment] 2023-08-04 06:21
This issue seems to be caused by `WCPay Subscription`, so assigning to @Automattic/quark  (based on team responsibilities Pc2DNy-3z-p2) cc @diegocurbelo as team lead.

Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by thenbrent** [comment] 2023-08-09 01:03
The core issue here is being handled here: https://github.com/Automattic/woocommerce-subscriptions-core/issues/190

**Comment by htdat** [comment] 2023-10-30 06:56
The core issue was fixed. I am closing this issue.

**Closed as completed by htdat** 2023-10-30 06:56 UTC
Labels: type: bug, needs feedback, component: wcpay subscriptions, needs triage
