### ISSUE TITLE
3DS Cards are not saved to Subscriptions if Enable payments via saved cards is unchecked

### ISSUE THREAD

**Issue by AashikP** [Automattic/woocommerce-payments#8611] opened 2024-04-10 04:33 UTC
### Describe the bug

With `Enable payments via saved cards` option unchecked, 3DS cards are not saved to Subscriptions.

### To Reproduce

*   Uncheck `Enable payments via saved cards` under WooPayments settings
*   Use `4000002500003155` to pay for a Subscription product - Complete authentication
*   Notice that the payment method is not saved within the Subscription:
   
    ![image](https://github.com/Automattic/woocommerce-payments/assets/17475174/bde6b525-f0a0-41f1-901f-a4e1ecd5a294)

*   When you enable `Enable payments via saved cards` again, and try to pay for another Subscription product, the card you used is there for payment in the checkout page:

    ![image (1)](https://github.com/Automattic/woocommerce-payments/assets/17475174/43e014ef-a49f-4c42-b89d-490804637718)    

*   So the card is saved somewhere, but not available for the original Subscription
*   Subscription renewals fail due to this:
    ![image (2)](https://github.com/Automattic/woocommerce-payments/assets/17475174/e45e87fa-d0a2-48ee-ba18-23d18f454e87)

### Actual behavior

3DS cards are not saved within the Subscription resulting in renewal failures.

### Expected behavior

3DS cards that can be saved, should be saved within the Subscription for renewals.

### Additional context
Customer report: 7961218-zd-a8c

**Comment by ncsramona** [comment] 2024-04-19 05:53
8037177-zen as well.

_(On that note, both folks who had this issue (so far) are Hungarian. Wondering if it's because most banks have really strict 3DS rules here...? 🤔 )_

**Comment by ncsramona** [comment] 2024-04-19 06:00
8037177-zd-a8c as well.

**Comment by bekekitti** [comment] 2024-05-06 14:01
I have the same issue as well for a month now (contacted support). Do you have any update on when this bug will be fixed? Or maybe any workaround?

**Comment by cnote76** [comment] 2024-05-06 14:06
> I have the same issue as well for a month now (contacted support). Do you have any update on when this bug will be fixed? Or maybe any workaround?

Workaround: turn on "Enable payments via saved cards" (under WooPayments settings)

**Comment by bekekitti** [comment] 2024-05-06 14:08
Yes I have that turned on since the beginning (support also suggested this) but the issue is still the same.

**Comment by cnote76** [comment] 2024-05-06 14:11
> Yes I have that turned on since the beginning (support also suggested this) but the issue is still the same.

Sorry to hear that. For me, it works with that setting turned on, but it's still not ideal, especially if it does not solve the issue for everyone...

**Closed as completed** 2024-05-07 14:31 UTC
Labels: type: bug, priority: high, category: core, focus: checkout payments
