### ISSUE TITLE
Search and Filter Transactions

### ISSUE THREAD

**Issue by SiR-DanieL** [Automattic/woocommerce-payments#535] opened 2020-03-26 08:50 UTC
It would be handy to be able to search transactions by order ID, customer name, customer email, transaction ID, card last 4 digits.

Also, maybe we can filter by card type, month of the transaction, transaction type.

**Comment by dechov** [comment] 2021-06-18 18:41
It's now possible to search by order number, customer name, and email, and to filter by date and transaction type.

Not currently possible to search by card last 4 digits, or to filter by card type.

**Comment by vbelolapotkov** [comment] 2021-12-27 11:56
Duplicate of #156 and #616

**Closed by vbelolapotkov** 2021-12-27 11:56 UTC
Labels: type: enhancement
