### ISSUE TITLE
[GlobalStep] Total Amounts are not displayed in an Explicit format on pages with Cart and Checkout blocks.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#2648] opened 2021-08-03 15:38 UTC
## Bug Description:
Total Amounts are not displayed in an Explicit format on pages with Cart and Checkout blocks.

## Environment:
Woocommerce Version : WooCommerce 5.5.2
WooCommerce Payments - 2.8.0-rc3.

PC:
Windows 10, Mac 10.14.6
Chrome(Version 91.0.4472.77) 
Firefox(Version 88.0)
Safari: v14.1.2

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Upload and activate the WooCommerce Payments v2.8.0-rc3 plugin. 
1. Complete the setup wizard.
1. Complete the KYC flow.
1. Install and activate WooCommerce Blocks plugin.
1. Create a page with Cart and Checkout blocks.
1. As a shopper add a product to the cart.
1. Visit to Cart and checkout blocks pages.
1. Observe that Total Amounts are not displayed in an Explicit format.

## Actual Result:
Total Amounts are not displayed in an Explicit format on pages with Cart and Checkout blocks.

## Expected Result:
Total Amounts should be displayed in an Explicit format on pages with Cart and Checkout blocks.

## Screenshot:

![#2648_1](https://user-images.githubusercontent.com/41110392/128044794-d3c9b8db-16c5-4873-b88d-50da32fbcd7d.png)
![#2648](https://user-images.githubusercontent.com/41110392/128044806-20331e8c-3f06-4d2f-8fe0-9fd6da8d2258.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 5.5.2
REST API Version: ✔ 5.5.2
WC Blocks Version: ✔ 5.6.0
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.4
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.48 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.21
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.2
WC Database Prefix: wp_
Total Database Size: 5.44MB
Database Data Size: 3.82MB
Database Index Size: 1.62MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.48MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.23MB + Index: 0.20MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 8
post: 2
product: 22
product_variation: 7
revision: 3
shipping_package: 2
shop_order: 28
shop_order_refund: 3
shop_subscription: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (8) ###

Query Monitor: by John Blackbourn – 3.7.1
Code Snippets: by Code Snippets Pro – 2.14.1
Companion Plugin: by Osk – 1.18
WooCommerce Blocks: by Automattic – 5.6.0
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.8
WooCommerce Payments: by Automattic – 2.8.0-rc
WooCommerce Subscriptions: by WooCommerce – 3.1.3
WooCommerce: by Automattic – 5.5.2

### Inactive Plugins (6) ###

Akismet Anti-Spam: by Automattic – 4.1.10
Google Listings and Ads: by WooCommerce – 1.3.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 9.9.1
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
MailPoet 3 (New): by MailPoet – 3.65.1

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://sensible-snow.jurassic.ninja
Subscription Statuses: wc-active: 4
WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 4

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
tokenization
add_payment_method

### Action Scheduler ###

Complete: 164
Oldest: 2021-08-03 10:59:32 +0000
Newest: 2021-08-03 15:24:05 +0000

Failed: 1
Oldest: –
Newest: –

Pending: 8
Oldest: 2021-08-04 13:25:31 +0000
Newest: 2021-11-01 11:51:41 +0000

### Status report information ###

Generated at: 2021-08-03 15:24:08 +00:00
`

</details>

**Comment by tpaksu** [comment] 2021-11-15 12:14
This issue has been discussed with different teams, and different ways of modifying values from outside the plugin has been proposed, It's still being discussed what the method should be used in WCPay to alter a place in Gutenberg Blocks plugin block. The previous attempts of the fixes were all not backwards compatible, or had security concerns. This issue will get updates after a decision is made and the solution is ready to ship.

**Comment by tpaksu** [comment] 2022-01-17 14:06
Closed the related PR's because it may be better handled by team Rubik, because they are more capable of their repository and will know how to proceed.

**Comment by bborman22** [comment] 2024-01-22 20:03
As we're getting caught up on some of the existing multi-currency issues, I confirmed that this issue is still present and has a lot of background and existing discussion. Some of the most relevant discussion is in this https://github.com/woocommerce/woocommerce-blocks/pull/4756 PR. While I was in there I just wanted to look into where this is handled on the shortcode side and found that `WC_Payments_Explicit_Price_Formatter` is handling this with the `woocommerce_cart_total` filter. Just noting this here so that when this work comes around we have some additional context.

**Comment by reykjalin** [comment] 2024-04-10 01:47
The `CurrencyFormatter` available in [the Blocks REST extension interface](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/rest-api/extend-rest-api-formatters.md#currencyformatter) seems like the right place to start here.

**Comment by reykjalin** [comment] 2024-04-10 01:54
It's also possible that the [`totalValue`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-block/available-filters/totals-footer-item.md#totalvalue) Total Footer Item filter is sufficient. It may be necessary to also use the `CurrencyFormatter` interface to modify the Store API currency response, but this filter alone should be a good start.

**Comment by bborman22** [comment] 2024-04-12 19:00
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/2648?planning-poker) with Zenhub @reykjalin

**Comment by reykjalin** [comment] 2024-04-13 05:18
Turns out the [`totalValue`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/docs/third-party-developers/extensibility/checkout-block/available-filters/totals-footer-item.md#totalvalue) filter is being released with WC version 8.8, so this is pretty fortuitous timing 🙂 

We can add the filter without breaking any functionality in WC 8.6 and 8.7 🎉

**Closed** 2024-04-17 18:10 UTC
Labels: type: bug, priority: high, focus: multi-currency
