### ISSUE TITLE
Duplicate charge for same order, possible race condition issue

### ISSUE THREAD

**Issue by tijosh** [Automattic/woocommerce-payments#4358] opened 2022-06-18 21:10 UTC
p1655250992560569-slack-C7U3Y3VMY

Site info

<details>
```
WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.8.1
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

Server Info: LiteSpeed
PHP Version: 7.4.28
PHP Post Max Size: 32 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 10.3.34-MariaDB-log-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Active Plugins (32) ###

VaultPress: by Automattic – 2.2.1
AdRotate: by Arnan de Gans – 5.8.25
Akismet Anti-Spam: by Automattic – 4.2.4
ATUM Export Pro: by Stock Management Labs™ – 1.4.4
ATUM Product Levels: by Stock Management Labs™ – 1.7.9
ATUM Inventory Management for WooCommerce: by Stock Management Labs™ – 1.9.18.1
Autoptimize: by Frank Goossens (futtta) – 3.0.4
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: by codewoogeek – 3.0
GTM4WP: by Thomas Geiger – 1.15.2
FancyBox for WordPress: by Colorlib – 3.3.3
Webcraftic Assets manager: by Webcraftic  – 2.1.5
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
Jetpack: by Automattic – 11.0
Multiple Packages for WooCommerce: by Erica Dion – 1.1
My Custom Functions: by Space X-Chimp – 4.51
Printful Integration for WooCommerce: by Printful – 2.1.33
Really Simple SSL: by Really Simple Plugins – 5.3.2
Smart Logo Showcase Lite: by AccessPress Themes – 1.1.9
Duplicate Variations for WooCommerce: by Emran Ahmed – 2.0.4
W3 Total Cache: by BoldGrid – 2.2.1
WebP Converter for Media: by Mateusz Gbiorczyk – 4.3.6
WooCommerce Blocks: by Automattic – 7.8.1
Country Based Restrictions for WooCommerce: by zorem – 3.2
WooCommerce Advanced Free Shipping: by Jeroen Sormani – 1.1.4
WooCommerce Payments: by Automattic – 4.2.1
WooCommerce Shipping & Tax: by WooCommerce – 1.26.0
WooCommerce UPS Shipping: by WooCommerce – 3.3.0
WooCommerce USPS Shipping: by WooCommerce – 4.4.74
WooCommerce Wholesale Prices: by Rymera Web Co – 2.1.4
WooCommerce: by Automattic – 6.5.1
Yoast SEO: by Team Yoast – 19.1
Smush: by WPMU DEV – 3.9.11

### Inactive Plugins (0) ###


### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
install.php: install.php
maintenance.php: maintenance.php

### Must Use Plugins (3) ###

assets-manager.php: by  – 1.0.9
Health Check Troubleshooting Mode: by  – 1.7.2
SSO: by Garth Mortensen
Mike Hansen – 0.1
```
</details>

**Comment by deepakpathania** [comment] 2022-06-24 10:49
Please add a little more details to the issue for it to be prioritized effectively.
cc @shendy-a8c who looked into the thread.

**Comment by ldr2273** [comment] 2022-06-24 22:22
Just following up here to add that this user has not had any issues since configuring their caching plugin to exclude the checkout page.

**Comment by deepakpathania** [comment] 2022-06-27 07:06
> this user has not had any issues since configuring their caching plugin to exclude the checkout page.

@shendy-a8c Is it safe to close the issue then or do we need to investigate this further?

**Comment by achyuthajoy** [comment] 2022-07-12 10:30
@shendy-a8c Based on the above comments, should the issue be closed or kept open?

**Comment by shendy-a8c** [comment] 2022-07-14 06:23
I think this issue can be closed because per @ldr2273's [comment](https://github.com/Automattic/woocommerce-payments/issues/4358#issuecomment-1165988223), the problem might be caused by checkout page being cached.

**Closed by shendy-a8c** 2022-07-14 06:23 UTC
Labels: type: bug, needs feedback, category: core
