### ISSUE TITLE
Order ID available in JSON but replaced with N/A on transaction pages

### ISSUE THREAD

**Issue by nicdwilson** [Automattic/woocommerce-payments#4752] opened 2022-09-13 05:46 UTC
### Describe the bug
Transaction report drops Order ID and replaces it with N/A

### Actual behaviour

In 5552143-zen transactions in the Transaction Screen, and in the Deposit > Transactions screen are losing their relationship with Order IDs and Subscription IDs. Clicking through on the transaction provides a detail screen containing order an subscription IDs. The customer name does not contain a hyperlink

This is despite JSON have the order ID available, the order ID and subscription ID acting correctly on detail pages, and all data in the Express dashboard correctly linking to order ID.

### Screenshots

![dF8g1k.png](https://user-images.githubusercontent.com/3624025/189817149-9cdb6313-ddbd-4482-a864-3bd7c76b6c92.png)

![ox5hSN.png](https://user-images.githubusercontent.com/3624025/189818315-89a18a6a-505f-4e82-91fc-d81545bb7038.png)

![![aXO2YC.png](https://user-images.githubusercontent.com/3624025/189818923-c3085484-0610-4d90-af90-97643d38356a.png)](![aXO2YC.png](https://user-images.githubusercontent.com/3624025/189818923-c3085484-0610-4d90-af90-97643d38356a.png)+) 
Full Size: ![aXO2YC.png](https://user-images.githubusercontent.com/3624025/189818923-c3085484-0610-4d90-af90-97643d38356a.png)

### Expected behavior
Order IDs, Subscription IDs and customer name links working consistently.

Also seen in 5533923-zen

**Comment by ibndawood** [comment] 2022-09-13 13:57
Hello @jessy-p & @nicdwilson,

I was looking into this ticket: 5552143-zen and decided to take a deep dive into this issue. I found the source of the issue. I have submitted a PR explaining the cause and the fix.

Here is my PR: https://github.com/Automattic/woocommerce-payments/pull/4757

Let me know what you think.

**Comment by Brianmitchtay** [comment] 2022-09-13 18:38
Seeing this in 5554142-zen as well. 

This user is also seeing order numbers not match with their orders in the store when they export a CSV of transactions. Not sure if the two could be related.

**Comment by Brianmitchtay** [comment] 2022-09-13 18:49
Also seeing this in 5554142-zen. 

In this case the user is also seeing order numbers being exported incorrectly when they export a list of the transactions to CSV. Not sure if it could be related, but seems like it could be.

**Comment by jessy-p** [comment] 2022-09-15 12:07
Closed via #4763 and released via patch release v4.7.2

**Closed as completed by jessy-p** 2022-09-15 12:07 UTC
Labels: type: bug, priority: critical, category: core
