### ISSUE TITLE
Allow reconciliation of bank statements & daily deposits - e.g. show deposit `Payout trace ID` in Woo admin dashboard, or other unique ID to link

### ISSUE THREAD

**Issue by nicdwilson** [Automattic/woocommerce-payments#5316] opened 2022-12-20 01:29 UTC
### Description

In 5789782-zen a new merchant with a fairly busy site has asked if there is any way to provide additional information to allow easy reconciliation of bank statements to deposits.

The bank statement contains the `Payout trace ID`.

The `Payout trace ID` is not available in reporting on the site, nor is it available via the `payout.paid` event. But would be quite helpful for merchants' accounts departments trying to match up daily deposits with their bank statements, especially considering that pending periods sometimes make matching by date alone tricky.

### Additional information ( added by @nagpai )

* Related changes needed on the server - https://github.com/Automattic/transact-platform-server/issues/6838 . This will need to be addressed to support changes for the client-side changes.

**Comment by jessy-p** [comment] 2023-02-02 08:41
@Automattic/helix

**Comment by haszari** [comment] 2023-02-12 19:49
If we can get this ID from the API, seems like a great idea to include in the UI somewhere. Or any other value that would help clearly identify WCPay deposits (in general, or specific deposit instances). 

I couldn't find mention of it in the Stripe docs, except [`Transfer/payout ID` in Balance report](https://support.stripe.com/questions/payout-reporting-options).

FYI Sourav – let's consider this in upcoming deposits project(s).

**Comment by souravdebnath1986** [comment] 2023-02-12 23:27
This falls in the [reporting enhancements](https://airtable.com/appvDVeZKPRtBGEfC/tblTRenCZfGFNMXYC/viw0LVRFFCrAVAMtw/rec3CBGFA1uCiKVsc?blocks=hide) bucket for this year.

**Comment by haszari** [comment] 2023-02-13 00:45
Thanks @souravdebnath1986 ! 

> This falls in the reporting L2 bucket.
> Provide basic reporting capabilities for merchants to support discovery, settlement reconciliation and delivery preferences 

Since we're planning feature projects in this area later in the year, perhaps we can close this issue.

**Comment by haszari** [comment] 2023-02-14 22:04
Removing from maintenance board & adding `projects` label based on @souravdebnath1986 comment above. 

There's a possibility that adding this payout ID in the UI will help make the deposits UI & flow easier to merchants to understand (i.e. inspire trust). If so we could consider this for upcoming deposits UI refresh project.

**Comment by brucealdridge** [comment] 2023-10-18 00:54
@Automattic/fusion This issue mentions deposits but falls under the future reporting project. Can you consider it as part of your roadmap?

**Comment by anu-rock** [comment] 2023-10-31 08:23
@brucealdridge Thanks for the ping. Are we talking about the deposits CSV report here?

**Comment by brucealdridge** [comment] 2023-11-02 02:12
>  Are we talking about the deposits CSV report here?

@anu-rock The issue specifically mentions the UI. I'd imagine it could also appear in the deposits CSV report.

**Comment by anu-rock** [comment] 2023-11-02 09:02
@brucealdridge Thanks for confirming. Added it to Fusion's backlog.

**Comment by haszari** [comment] 2023-11-21 00:56
Removed `deposits` label since this will be handled by Fusion as part of reporting.

**Comment by jtobiesen** [comment] 2023-11-23 12:13
Another request in 7340232-zd-a8c.
This merchant specifically requested to have information about the order numbers included in each associated deposit, somehow reflected in the payout.

**Comment by nicdwilson** [comment] 2023-11-27 00:57
7311071-zd-a8c

**Comment by csmcneill** [comment] 2023-11-27 17:36
> If we can get this ID from the API, seems like a great idea to include in the UI somewhere.

Stripe has indicated that they will be surfacing the trace ID via the API in 1H2024. They'll include us in the beta.

**Comment by souravdebnath1986** [comment] 2023-12-11 05:26
We are picking this up as part of p7fD6U-b70-p2 to include a deposit_id in the Transaction Report. We will also do a fast follow to update this id as part of the Deposit Report to aid reconciliation of Deposit to cash as seen in the bank statement. cc: @anu-rock

**Comment by haszari** [comment] 2023-12-15 01:25
The ideal solution to this would include a deposit ID of some kind (e.g. `payout trace ID`) in both the Woo admin dashboard AND the merchant's bank statement. 

@mordeth  @anu-rock  Could you investigate that as part of your effort on this issue? If it's challenging or you hit a blocker, feel free to reach out to myself or @souravdebnath1986 , we can add a follow up issue if necessary.

**Comment by SirDarcanos** [comment] 2023-12-19 07:34
Merchant here from A8C, I also have this issue with the Trade ID missing from WC Pay and it makes my life a nightmare. An extensive discussion about the issue is in Slack: p1702963566265379-slack-C3NCP7ZJ6

**Comment by wpniall** [comment] 2023-12-22 06:42
Another report in 7481087-zen

**Comment by haszari** [comment] 2024-05-03 04:02
Removing `priority: high` as this is an enhancement and no work planned in next 2 weeks.

**Comment by haszari** [comment] 2024-05-15 04:16
FYI @souravdebnath1986 I've reset this to `low` since it is an enhancement. It is a valuable enhancement for sure but unlikely to be prioritised over bugs.

**Comment by lynnjat7** [comment] 2024-09-25 15:53
Another report of this causing accounting issues for EU customers: 8779859-zen

**Comment by carlcarvesstone** [comment] 2024-09-25 23:21
Good Folks,

Small businesses, or non-profits, who do not have an accounting team (our non-profit supports stone sculptors), often pay for an actual accountant or bookkeeper outside the organization to do the bank reconciliations, for reasons of accuracy, trust, and transparency (and more likely the lack of accounting skills within the non-profit).

The lack of a deposit ID/REF causes some additional amount of outside fees to be paid as a work around to not having this feature. I see it as a hidden cost of using your product.  For the small non-profit, for which I volunteer, our accountant/bookkeeper estimated, given our range of transaction activity,  $300-$800 per year to do the deposit reconciliation work for our organization.  This is an additional cost to our non-profit due to the lack of this feature.

If the deposit ID feature were implemented the level of effort for reconciliation is close to zero. Please see this as closing the loop on customer satisfaction and removing your customer's need to report to their board/treasurer why the Woo package is causing additional expense, and making it expensive to have a clean audit. I felt pretty embarrassed about explaining my choice of Woo and the additional costs, and of course gives me pause in recommending Woo for small organizations.

I have no idea the number of small organizations like ours that use Woo, so I have no way to judge benefit and multiplier effect of getting this done (our previous web site software ID/refs were provided).

Looking forward to a solution.
Thanks

**Comment by haszari** [comment] 2024-11-12 22:31
This enhancement was blocked because we (WooPayments) didn't have access to the Payout Trace ID in the Stripe API … however … 

> Stripe has indicated that they will be surfacing the trace ID via the API in 1H2024. They'll include us in the beta.

Looks like this is now documented as a [preview feature in the Stripe API](https://docs.stripe.com/api/payouts/object):

![Image](https://github.com/user-attachments/assets/262b62fb-c89e-49bc-8878-fe54833506d9)

So I'll remove `blocked`, we can investigate and see if this is available.

**Comment by haszari** [comment] 2024-11-14 02:39
Bumping this to `high`, it's important and 🤞🏻  hopefully feasible!

**Comment by nagpai** [comment] 2024-11-15 16:38
I did a quick check of a recent payouts for a few accounts and found that the `Trace ID` is still not exposed via the `payout.paid` webhook.

In a few cases I do see the `trace_id` object, but it's status is stuck at `pending` with value `nil` 

<img src="https://github.com/user-attachments/assets/93ea0ff1-1ac1-482f-8867-3f5dd8959bc7" width="500px" />
 
I have followed up with Stripe on p1731688692196839-slack-C9976E5MJ to see if there is any change, or anything that they need to enabled for us.

**Comment by haszari** [comment] 2024-11-17 20:18
> Looks like this is now documented as a [preview feature in the Stripe API](https://docs.stripe.com/api/payouts/object)

> I did a quick check of a recent payouts for a few accounts and found that the Trace ID is still not exposed via the payout.paid webhook.

> I have followed up with Stripe on p1731688692196839-slack-C9976E5MJ to see if there is any change, or anything that they need to enabled for us.

Note from that thread – `trace_id` is only available for US and CA merchant accounts. So if we implement it will not be displayed for all merchants – inconsistent experience.

**Comment by carlcarvesstone** [comment] 2024-11-18 04:40
This feature lowers the cost of ownership and fulfills regulatory compliance for those Woo users who have access to this feature. Cost of ownership and compliance is a high priority and merchants will sort out the limitations of interface to gain the advantage.

**Comment by nagpai** [comment] 2024-11-18 05:59
>Note from that thread – trace_id is only available for US and CA merchant accounts. So if we implement it will not be displayed for all merchants – inconsistent experience.

The `trace_id` is shown with status as `pending` and value as `null` even for US accounts. I have asked for a further check -p1731906278347669/1731688692.196839-slack-C9976E5MJ

**Comment by nagpai** [comment] 2024-11-19 17:33
Marking as blocked, since we are awaiting a reply from Stripe 

>The trace_id is shown with status as pending and value as null even for US accounts. I have asked for a further check -[p1731906278347669/1731688692.196839-slack-C9976E5MJ](https://href.li/?https://a8c.slack.com/archives/C9976E5MJ/p1731906278347669?thread_ts=1731688692.196839)

**Comment by nagpai** [comment] 2024-11-26 11:49
Stripe has replied confirming the `trace_id` is now available for payouts ( from November 21, 2024 ) 

I did a quick check and found it visible on transactions on a US, UK and a German account too!

**Comment by nagpai** [comment] 2024-12-02 12:10
@carlcarvesstone  , @SiR-DanieL - Happy to share that a `Bank reference key` will be available within the payout reports ( view and CSV export ). This will help you reconcile your bank statements!  This will be released in WooPayments 8.6.0 within the next few days.

**Comment by nagpai** [comment] 2024-12-02 12:13
>Note from that thread – trace_id is only available for US and CA merchant accounts. So if we implement it will not be displayed for all merchants – inconsistent experience.

@haszari - At the time of checking, I was able to see this for all countries, which is good! There is a fallback of `N/A` in case there is no `trace_id` in the Stripe webhook.

**Comment by nagpai** [comment] 2024-12-09 04:38
Reopening issue for a minor change in the label `Bank reference key` to `Bank reference ID` based on feedback from @aheckler . Ref: p1733483582646479/1732857021.096589-slack-C02BW3Z8SHK

**Comment by nagpai** [comment] 2024-12-10 08:36
Closing the original issue here and moving the renaming task to its own issue - https://github.com/Automattic/woocommerce-payments/issues/9909

**Closed as completed by nagpai** 2024-12-10 08:36 UTC
Labels: type: enhancement, priority: high, category: core, focus: payouts
