### ISSUE TITLE
WooCommerce Settings - Payments sometimes generates a blank screen.

### ISSUE THREAD

**Issue by nixiack** [Automattic/woocommerce-payments#2842] opened 2021-09-03 02:13 UTC
### Describe the bug
Two different 'instances' or types, but they are related so keeping to the same bug:

1) When setting up WC Pay in an Atomic site, sometimes the WC Pay connect/settings page is blank.  The URL for the settings page is:

https://sitehere.com/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect

2) When going to **WooCommerce > Settings > Payments** sometimes it redirects to the same blank page.
 

### To Reproduce

**For the first part of the issue**
1. Set up WooCommerce Payments on a demo AT site.
2. Click on the `Setup` option after installing WC Pay.
3. Occasionally it will produce a blank page when directed to the URL /wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect

**For the second part of the issue**

This one is more readily shown.  
1. After installing WC Pay _but not completing the setup_ go to **WooCommerce > Settings > Payments**.
2. The URL of **Payments** will redirect from /wp-admin/admin.php?page=wc-settings&tab=checkout to /wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect and produce a blank screen.  May take a few tries to make it happen.

### Screenshots
You can see here with WC Payments disabled, the Checkout URL is directing to the correct area:

![screenshot]( https://d.pr/QaL8tM+) **Image Link:**  https://d.pr/QaL8tM

The URL for Payments in WC Settings changes and looks like it redirects to the blank box others have been seeing after the Payments area is being clicked on.  I think it is trying to go to WooCommerce Payments instead of the normal `Checkout` area.  I did not see anything in the Console regarding `Errors` when doing this, nor did I see anything amiss in the elements.  I just noticed that it redirected to WC Pay.

### Expected behavior
When going to **WooCommerce > Settings > Payments** the Payment gateways should show by default, not WC Pay.

When setting up WC Pay, it should not engage a blank screen.

### Desktop (please complete the following information):

* OS: Mag Big Sur Ver. 11.4 (20F71)
* Browser Chrome
* Version Version 92.0.4515.159 (Official Build) (x86_64)

### Additional context
I was able to see that at the top of the Payments area is a setting for JUST WooCommerce Payments, and then 'All payment methods' even though WC Payments is showing and accessible via the normal 'set up' /etc.

![screenshot](https://d.pr/i/vkuDcD+) **Image Link:** https://d.pr/i/vkuDcD

It is possible when the `Payments` area is being selected that it is defaulting to this first section for WC Pay instead of showing the normal Gateways.  Since it is not set up it is skipping ahead to the `Finish Pay` section which cannot load, and is blank. 

Brief Slack conversation [here](https://a8c.slack.com/archives/C3NCP7ZJ6/p1630577903241700).

**Comment by naman03malhotra** [comment] 2022-05-20 12:39
Closing as there are no reports linked to this issue.

**Comment by sverleis** [comment] 2022-08-19 07:22
I've been able to replicate this on a local site to a similar effect, but it takes effect on the entire WooCommerce Home page for a site.

**Installed extensions:**
- Gutenberg `13.9.0`
- WooCommerce `6.8.1`
- WP Log Viewer `1.2.1`
- WooCommerce Payments `4.6.0` (optional)

**WP Log Viewer** breaks **Gutenberg**, which in turn breaks the **WooCommerce** onboarding page, which includes all **WooCommerce Payments** pages. 

Disabling 'WP Log Viewer' fixes the issue.
If the user disables 'Gutenberg' and the issue is resolved, then it may be, like here, another extension causing Gutenberg to break.

**Comment by naman03malhotra** [comment] 2022-08-19 07:45
Thanks @sverleis, I am opening it and moving it back to Triage, we'll get it tested.

**Comment by naman03malhotra** [comment] 2022-08-19 07:45
cc @zmaglica

**Comment by zmaglica** [comment] 2022-08-19 13:58
I think that this is not an issue of WooCommerce Payments plugin. WP Log Viewer and Gutenberg (at the moment of writing) are incompatible and breaks the page without WooCommerce Payments plugin. To simulate this, spin a new instance of JN site with mentioned plugins, and you will have white/blank screen during the setup wizard with a bunch of JavaScript errors.

**Comment by jbordonado** [comment] 2022-08-30 12:13
@sverleis As Zvonimir pointed out in [the previous comment](https://github.com/Automattic/woocommerce-payments/issues/2842#issuecomment-1220714623), it looks like a compatibility issue between WooCommerce, WP Log Viewer and Gutenberg plugins. 
The original issue focused more on WooCommerce Payments itself and something going wrong there. Therefore, we are closing the issue again. Thanks for your input, though!

**Closed by jbordonado** 2022-08-30 12:13 UTC
Labels: type: bug, component: settings, needs feedback, component: grouped-settings, category: core
