### ISSUE TITLE
[GlobalStep] PHP error gets triggered on the variable product page upon selecting a variation.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#2081] opened 2021-06-08 15:45 UTC
## Bug Description:
PHP error gets triggered on the variable product page upon selecting a variation.

## Environment:
Woocommerce Version : WooCommerce 5.3
WooCommerce Payments: v2.6.0-test-1 and v2.5.0

PC:
Windows 10, Mac 10.14.6
Chrome(Version 90.0.4430.93) 
Firefox(Version 88.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete setup wizard using United States address as a store address and without selecting WC Payments on Business Details step.
1. Go to Plugins->Add New->Upload plugin.
1. Install and activate WooCommerce Payments plugin v2.6.0.
1. Go to Payments->Set up to trigger KYC flow.
1. Complete the KYC flow.
1. Add Variable products.
1. Go to Variable product page.
1. Select a variation.
1. Observe that PHP error gets triggered on browser console.

## Actual Result:
PHP error gets triggered on the variable product page upon selecting a variation. 

## Expected Result:
User should be able add variable product to the cart without any errors.

## Screenshot:
![#2081](https://user-images.githubusercontent.com/41110392/121216764-d478b300-c89e-11eb-8e9a-86447f922e72.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.

</details>

**Comment by jrodger** [comment] 2021-06-15 17:10
I haven't been able to replicate the issue. It seems to be related to the payment request button (so that needs turning on if you don't have it enabled). The stack trace points to this line:

https://github.com/Automattic/woocommerce-payments/blob/a69307d8963f207749c1a5072c985899dcad1da4/includes/class-wc-payments-payment-request-button-handler.php#L928

So I've tried to get any of those 3 numbers to return something non-numeric but so far no luck. Product price seemed like a good candidate as the base class returns a string, but I can't find a way to inject that with anything that would cause a problem.

Before I close this, can you see anyway to get this to break @ricardo?

**Comment by ricardo** [comment] 2021-06-16 04:48
@jrodger I couldn't get this to break, but after some digging I suspect this warning is triggered on PHP 7.1 specifically [Ref](https://www.php.net/manual/en/migration71.other-changes.php). It doesn't break for me in PHP 7.4 and I had tested other PHP versions before on Ephemeral installations - Unfortunately didn't test PHP 7.1 because it isn't available for Atomic sites in MC.

Also, this should only break if the site has `E_WARNING` notices enabled in their production environment.

We need to reproduce this first, but I guess we can add typecasting to this line to fix the issue.

**Comment by jrodger** [comment] 2021-06-16 08:16
> Also, this should only break if the site has E_WARNING notices enabled in their production environment.

Agree, so not an urgent issue for now.

It looks like that 7.1 warning, but I'd expect it to be triggered on PHP 7.4 as well? I was testing on 7.4 and couldn't replicate either.

@gglobalstep, if you're still able to replicate this in your next round of testing could you also provide:

* The PHP version being used
* A screenshot of the product in wp-admin (the screenshot already provided looks like you're using the hoodie from WooCommerce's sample data?
* The tool you're using to pipe errors to the browser, I can give it a try with that as well just in case I'm looking in the wrong server-side log

**Comment by RadoslavGeorgiev** [comment] 2022-01-25 08:45
@gglobalstep I'm closing this issue for now, as we've not had any new reports for more than half a year. I'd appreciate it if you could confirm this during this or next week's testing, but feel free to re-open the issue at any point.

**Closed by RadoslavGeorgiev** 2022-01-25 08:45 UTC
