### ISSUE TITLE
Spike: Confirm that Analytics queries work with COT / high performance order storage (HPOS), if not, log issues to fix

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [Automattic/woocommerce-payments#4690] opened 2022-09-02 16:18 UTC
https://github.com/Automattic/woocommerce-payments/pull/4677 was just merged to address https://github.com/Automattic/woocommerce-payments/issues/4632. However, at the time of writing, it seems like WC core does not support COT for analytics:

1. Scheduling imports happens on the `save_post` action: https://github.com/woocommerce/woocommerce/blob/cot-main/plugins/woocommerce/src/Internal/Admin/Schedulers/OrdersScheduler.php#L39
2. `OrdersScheduler::get_items()` loads posts exclusively from the `wp_posts` table through direct queries.
3. `Automattic\WooCommerce\Admin\API\Reports\Orders\Stats\DataStore::sync_order()` checks `get_post_type()` before switching to `wc_get_order()` : https://github.com/woocommerce/woocommerce/blob/cot-main/plugins/woocommerce/src/Admin/API/Reports/Orders/Stats/DataStore.php#L477

This means:

1. The sync with `wp_wc_order_stats` is never scheduled, and even if it was, the order would be rejected, because there will be no such post.
2. Manual sync through Analytics > Settings would not work either, because it will be using SQL to look for entries in `wp_posts` .

We should regularly check if this is addressed, and when it is, we should check that the changes from #4677 work. FWIW I already tested this by deleting order data from `wp_posts` and `wp_postmeta` manually after it was synced, and everything worked well. The internal implementation in Analytics uses `wc_get_order` to populate the cache table, so once that sync is triggered, everything should work the same way as it does right now.

**Comment by zmaglica** [comment] 2024-02-14 21:07
This issue impacts Analytics, so assigning to Fusion (based on team responsibilities Pc2DNy-3z-p2) @anu-rock .
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by haszari** [comment] 2024-05-15 03:47
Marking as medium since there don't seem to be any complaints/tickets about this. It is important to confirm that the current analytics features are not broken in HPOS-enabled stores. 

Next steps:

- Retest to confirm if there is any breakage/issue with high-performance order storage (HPOS aka COT). 

Note that analytics / reporting may be revamped in a future project. If there are issues, we would need to confirm priority before fixing.

**Comment by haszari** [comment] 2024-12-18 01:31
Prioritising and adding to `Next`. I'm assuming there's no problem here, but we need to confirm. If there is a problem it's a priority to fix it!

**Comment by brucealdridge** [comment] 2024-12-18 03:53
Closing as not planned after my testing confirmed that this is not an issue.

This issue seems to be related to a problem that used to exist in a feature branch for HPOS (then COT - custom order tables) in WooCommerce Core before it was released to merchants.

Based on my reading of the issue, it sounds like there was a possible bug in WC core (rather than WooPayments).

### Reproduction Steps

1. Ensure HPOS is enabled on your store (I have had HPOS enabled for many-months)
2. Visit WooCommerce Analytics and take note of the numbers
3. Place an order
4. Visit WooCommerce Analytics and see that the numbers have changed based on the new order.


**NB:** In my testing, the details in WooCommerce Analytics took approximately 5 minutes to show up after the order was processed.

**HPOS Settings**
![Image](https://github.com/user-attachments/assets/281b4e66-9025-436c-8309-715f2214441d)

**Before Order Placed (step 2)**
![Before](https://github.com/user-attachments/assets/12c225d5-46ad-4d10-bb71-94091d987dc0)
**After Order Placed (step 4)**
![After](https://github.com/user-attachments/assets/d7629923-90f9-4634-810d-c4b52dd41ce1)

**Closed as not planned by brucealdridge** 2024-12-18 03:53 UTC
Labels: priority: high, status: blocked, category: core, custom order tables, focus: reporting

**Comment by haszari** [comment] 2024-12-18 20:33
Thanks for checking @brucealdridge ! 

> Based on my reading of the issue, it sounds like there was a possible bug in WC core (rather than WooPayments).

Should we log an issue in WooCommerce?

**Comment by brucealdridge** [comment] 2024-12-18 23:20
> Should we log an issue in WooCommerce?

No, based on my testing it works as expected. I don't see any problems. 

This issue was to confirm the query's work, which they do.
