### ISSUE TITLE
WCPay Subscriptions products should not offer unsupported payment gateways

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#3401] opened 2021-11-22 00:23 UTC
### Describe the bug
[WC Pay Subscriptions](https://woocommerce.com/document/payments/subscriptions/) supports payment using WooCommerce Payments gateway only. 

This issue applies to stores that meet all the following criteria:

- Do not have WooCommerce Subscriptions (paid extension).
- Have other payment gateways configured and enabled alongside WCPay.
- Are using WCPay Subscriptions feature to offer subscription products.

Carts that contain Subscription products should only show supported payment methods (WCPay); other gateways should be hidden.

Product page and cart should not show express "Buy now" buttons (e.g. Stripe-powered Apple or Google/Chrome pay, or Paypal buy now).

I've reported this issue in WCPay initially but it may require changes in the relevant payment gateways.

### To Reproduce
Full reproduce steps tbc - I have not reproduced this on a test site yet. 

1. Onboard and enable WCPay with a usa-based store address. 
2. Ensure WCPay Subscriptions feature is enabled.
3. Publish a subscription product.
4. Set up and enable other payment methods (e.g. PayPal).

### Screenshots
Example screenshots from a customer site:

<img width="1193" alt="142784967-90b67d3b-8fd2-4be7-a4eb-bdcfe31ac785" src="https://user-images.githubusercontent.com/235523/142794149-909eef90-6daa-4a47-9caa-e2641b9c9e9d.png">

<img width="1195" alt="142785020-0bb2b7ed-6b0a-4a98-98d2-998123fa8a11" src="https://user-images.githubusercontent.com/235523/142794155-add45501-700f-4435-bd0c-a45a96986dbe.png">

### Expected behavior
Stores using WCPay Subscriptions (without WooCommerce Subscriptions active) should only offer payment via WCPay for orders with subscription products.

**Comment by haszari** [comment] 2021-11-22 00:30
@LCmry FYI: maybe a compatibility issue in PayPal extension. 

@EvanDotPro FYI: maybe a compatibility issue in Stripe extension.

**Comment by chickenn00dle** [comment] 2021-12-09 22:04
Spent some time looking into this on the PayPal extension and at least in this case, the issue appears to be from there. There is a check for whether a product is a subscription here: https://github.com/woocommerce/woocommerce-paypal-payments/blob/5fb4a39ec9f454fd8f4e2f98933d0c310a564034/modules/ppcp-button/src/Assets/SmartButton.php#L170

It looks like this needs updating as the checks in the `has_subscriptions` method don't take into account WCPay Subscriptions.

I'll need to look into Stripe to confirm this is the same there, and if so I'll close this and move the issues to the respective extensions.

If the problem is similar, it might be worth creating a dev doc explaining how to check for subscriptions/products.

**Comment by chickenn00dle** [comment] 2021-12-09 23:09
Looking into Stripe, I am seeing a similar situation. In the case of Stripe, payment request button support for subscription products is declared here: https://github.com/Automattic/woocommerce-gateway-stripe/blob/c2f771fc06cbd526a970c424f599d790bebd68af/includes/payment-methods/class-wc-stripe-payment-request.php#L408-L422

I'm not certain what the best way to approach this would be. My initial thought is the logic for not showing smart buttons for WCPay subscriptions should live within the respective extensions. So essentially move this issue to PP and Stripe. But we would also first need to share a "universal" way to distinguish between a WCPay subscription product and a WC Subscription product. 

I'd love some additional thoughts @haszari

**Comment by haszari** [comment] 2021-12-09 23:44
Thanks for the investigation @chickenn00dle - I wondered if this might be tricky. 

> My initial thought is the logic for not showing smart buttons for WCPay subscriptions should live within the respective extensions. So essentially move this issue to PP and Stripe. But we would also first need to share a "universal" way to distinguish between a WCPay subscription product and a WC Subscription product.

From a WCPay Subscriptions point of view, we don't support payment gateways other than WCPay. So ideally we'll find a way to control this from the WCPay end.

In parallel there's likely to be work to tweak how other plugins integrate with Subscriptions APIs (hooks), in line with your suggestions.

We're planning on looking at compatibility in an upcoming sprint, so I'm happy to defer this for Helix to look at as part of that work. Thanks for the useful research spike!

**Comment by chickenn00dle** [comment] 2021-12-09 23:47
Sounds good to me 👍 

I'll unassign and leave this to y'all then.

**Comment by mattallan** [comment] 2021-12-21 00:54
Just making a note that I've assigned this to myself to take a look at. Thanks for all the notes and investigation @chickenn00dle, much appreciated!!

**Comment by mattallan** [comment] 2021-12-22 08:05
> Determine the APIs (extension points, hooks etc) that are used to show PayPal UI in checkout.

PayPal Payments loads their PayPal Smart Buttons on subscription product pages after checking the following conditions:
 - Is the gateway enabled? (doesn't use WC Settings API to check this)
 - Is the product type not external or grouped?
 - Is vaulting (saved cards/tokens) enabled? (this is required for subscription products)

The biggest cause for this issue is PayPal Payments doesn't check if the gateway is available before it renders these buttons on the page. These conditions/checks are also attached to the `wp` hook and there doesn't appear to be any way unhook this behaviour as it's using an anonymous function i.e.:

```
add_action(
	'wp',
	static function () use ( $container ) {
		if ( is_admin() ) {
			return;
		}
		$smart_button = $container->get( 'button.smart-button' );
		/**
		 * The Smart Button.
		 *
		 * @var SmartButtonInterface $smart_button
		 */
		$smart_button->render_wrapper();
	}
);
```

If the above conditions pass, rendering the PayPal Smart Buttons is attached the following WC Core hooks:
 - Product Page: `woocommerce_single_product_summary`
 - Mini cart: `woocommerce_widget_shopping_cart_after_buttons`
 - Cart Page: `woocommerce_proceed_to_checkout`
 - Checkout Page: `woocommerce_review_order_after_payment`

Because of how PayPal Payments code is written, I can't see anyway to unhook/remove these actions either:

**Possible Solutions?**
 - Fix the issue in PayPal Payments by first checking if the gateway is available before rendering PayPal Smart Buttons.

---

> investigation of other gateways that might have similar issue

I'll create separate issues for these on WCPay repo tomorrow but here's the TL;DR after looking at other payment gateways:

- **PayPal Express Checkout** :yellow_circle: - This plugin's PayPal Smart buttons are also getting displayed on subscription product pages ([screenshot](https://d.pr/i/SXN0SO)) but this is caused by a bug in `subscriptions-core`. I've opened an issue to address this: https://github.com/Automattic/woocommerce-subscriptions-core/issues/81
- **Stripe** :yellow_circle: - Same as above except Stripe is showing Apple Pay and Google Pay buttons on Subscription product pages. This issue will also be fixed with https://github.com/Automattic/woocommerce-subscriptions-core/issues/81
- **Square** :green_circle: - Square doesn't show any Digital Wallet buttons (Apple Pay or Google Pay) because it doesn't support subscription products types.

---

I was really hoping to find a solution we could implement in WCPay or subscriptions core to fix the problem for all payment gateways, but from my investigation this may have to be done on a case-by-case or at the very least, we need all payment gateways to be checking if they're available first before loading features.

**Closed** 2022-01-17 01:16 UTC
Labels: type: bug, size: medium, component: wcpay subscriptions, category: projects, needs subscriptions core update
