### ISSUE TITLE
Missing order notes if order status is changed to Processing or Completed prior to capturing an authorized payment

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7971] opened 2024-01-04 02:20 UTC
### Describe the bug

When auth and capture is enabled, capturing a payment adds two order notes:

1. An indication that the order was captured, including the amount, the currency, and the PaymentIntent ID.
2. The fees for the order.

If an order's status is changed to `Processing` or `Completed` prior to capturing the payment via **Payments > Transactions > Uncaptured**, neither of these notes is added.

### To Reproduce

1. Enable auth and capture.
2. Place an order.
3. Capture the order.
4. Note that there are order notes indicating that the payment was captured and what the fees are for the transaction associated with that order.
5. Repeat step 2.
6. Change the order status for the order created in step 5 to `Processing` or `Completed`.
7. Capture the payment for the order created in step 5 via the **Payments > Transactions > Uncaptured** menu.
8. Review the edit order page for the order created in step 5.
9. Note that no additional order notes have been created.

### Actual behavior

If a payment is captured when the order status is `Processing` or `Completed`, the order notes are not handled in a way that mirrors what happens when there are other statuses (e.g., `On hold` or `Pending payment`).

### Screenshots

Here's an order that was captured while the status was `Pending payment`:
![pending payment 1](https://github.com/Automattic/woocommerce-payments/assets/82999806/d6fa6acd-1879-40b3-a890-18b977089be0)
![pending payment 2](https://github.com/Automattic/woocommerce-payments/assets/82999806/cc12f937-7769-47cd-9156-3a71047ca7a0)

And here's an order that was captured while the status was `Processing`:
![processing 1](https://github.com/Automattic/woocommerce-payments/assets/82999806/c0fffd37-7559-4e2f-b243-88d270f1d621)
![processing 2](https://github.com/Automattic/woocommerce-payments/assets/82999806/96b5fe7e-34e6-4164-9aa4-1f8a0881ee8c)

### Expected behavior
If an order has a status of `Processing` or `Completed` before a payment is captured, the expected order notes should still be added to the order.

**Comment by csmcneill** [comment] 2024-01-04 02:23
This could also be resolved with the second half of https://github.com/Automattic/woocommerce-payments/issues/5712 (capturing an authorized payment when the order status is changed to `Processing` or `Completed`).

**Comment by kalessil** [comment] 2024-01-04 07:49
Transition to `Completed` (or `Shipped`) is the subject of #5712.

But `Processing` is out of scope for #5712 as transition to this status is not an action item for auth&capture - we have no clue what happens with orders in this status. Hence, let's close this ticket as a duplicate of #5712, but feel free to re-surface `Processing` in a P2.

**Closed as completed by kalessil** 2024-01-04 07:49 UTC
Labels: type: bug, category: core
