### ISSUE TITLE
Order number not displayed in WooCommerce Payments Transactions list despite customer being charged successfully - version 3.6.0+

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/woocommerce-payments#3745] opened 2022-02-03 11:50 UTC
### Describe the bug

This issue seems to be a recurrence of the reports in #3440 . Our merchant reported that -

>the WooCommerce status was set to wc-failed even though the orders appear in the WooCommerce Payments transactions and the customers were billed with the appropriate amount. Those orders also do not carry an order ID in the transaction list.

### To Reproduce

As with #3440, this issue seems to be intermittent.

Our merchant confirmed that they updated to version 3.6.0 prior to 1 February 2022.

### Actual behavior

A customer is able to place an order, and is charged for the transaction. The order number appears on the order itself, but not on the corresponding item in the list on **Payments** > **Transactions**.

The transaction has a Stripe payment reference, and the transaction is reflected as successful in the Stripe dashboard.

The customer made the payment using the SOFORT payment method through WooCommerce Payments.

#### Order

![Capture_2022-02-03 at 13 09 49@2x](https://user-images.githubusercontent.com/2912202/152336555-ae69ac24-e0c1-43e9-ad34-e900bfa1befd.png)

#### WooCommerce Payments Transaction description

![Capture_2022-02-03 at 13 08 40](https://user-images.githubusercontent.com/2912202/152336880-ae3b2ddb-c215-4791-a652-02a7eeae81f8.jpeg)

### Expected behavior

Complete order and transaction details ought to be contained in the WooCommerce Payments Transaction description.

### Site information

- WooCommerce Payments: v3.6.1

### Additional context

Ticket: 4743181-zen
Logs: 2b930-pb

**Comment by dreamtooloud** [comment] 2022-02-08 16:15
I might have another instance of this in zd-4761790/hc-5244872

Running WC Pay 3.6.1

**Comment by selectedselections** [comment] 2022-02-24 22:19
Reported again in hc-27866115 / zen-4810137

**Comment by dreamtooloud** [comment] 2022-02-28 17:45
Might have another in hc-34425267/ zd-4819815 (WC Pay 3.7,  order in question was made on February 26th).

**Comment by aheckler** [comment] 2022-03-03 16:49
4826285-zen is this.

**Comment by sukafia** [comment] 2022-04-22 07:15
Another one here: 4963629-zen

**Comment by jessy-p** [comment] 2022-04-26 13:27
I have gone through all the zendesk tickets linked above, and it looks to be same as #3857 
  1. UPE order
  2. Refund button does not appear
  3. In the Order screen, the link is not present on the Payment Intent id.
  4. Payment is completed and is correct on Order Notes, Stripe dashboard and WCPay.
On the first ticket where we collected the logs, we can clearly see from the logs that the function `process_upe_redirect` did not run, which is the cause of #3857.
So I expect this to be fixed when #4131 is released in v4.1.0

**Comment by jessy-p** [comment] 2022-04-26 14:04
Closing issue as fix is available [Update _charge_id in metadata #4131](https://github.com/Automattic/woocommerce-payments/pull/4131)

**Closed by jessy-p** 2022-04-26 14:04 UTC
Labels: type: bug, priority: critical, component: sofort
