### ISSUE TITLE
Subscriptions do not renew if Advanced fraud protection > Order Items Threshold rule is enabled

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#7806] opened 2023-11-29 16:11 UTC
### Describe the bug
If the Advanced fraud protection > Order Items Threshold rule is enabled, then subscription renewals fail. This is due to this chunk of code: 

https://github.com/Automattic/woocommerce-payments/blob/develop/includes/fraud-prevention/class-buyer-fingerprinting-service.php#L64-L91

The code expects `WC()->cart` to exist, but when subscriptions are renewing, it does not. Because of this, not all of the data gets returned. In this instance `fraud_prevention_data_cart_contents` ends up being `null` and is filtered out. When the check then runs at the server level it encounters missing data and fails.

### To Reproduce

1. Purchase a subscription on your site.
2. Navigate to Payments > Settings > Advanced fraud protection.
3. Scroll down to Order Items Threshold, and then enable the filter with the min of 1 and max of 10 and save your settings.
4. Navigate to WooCommerce > Subscriptions.
5. Click into your recent subscription and choose Process renewal from the Subscription actions drop down list, then click Update.
6. You should receive a note that the renewal failed.
7. Logs for the client site will show: 
> 2023-11-29T15:49:18+00:00 INFO Unexpected server error. (wcpay_server_error)
> 2023-11-29T15:49:18+00:00 INFO Error processing subscription renewal: Error: Unexpected server error.
8. Logs on the server will show:
> [29-Nov-2023 15:33:58 UTC] WCPay message: Can't find the data source to compare: item_count
> [29-Nov-2023 15:33:58 UTC] WCPay error_code: wcpay_server_error
> [29-Nov-2023 15:33:58 UTC] WCPay http_response_code: 500
> [29-Nov-2023 15:33:58 UTC] WCPay extra: WCPay\Core\Exceptions\Rule_Engine_Exception: Can't find the data source to compare: item_count in /wcpayserver/wp-content/plugins/woocommerce-payments-server/server/wp-content/rest-api-plugins/endpoints/wcpay/service/class-fraud-ruleset-service.php:265

### Additional context
7376839-zd-a8c - p1701214841768559-slack-C7U3Y3VMY

**Comment by RadoslavGeorgiev** [comment] 2023-11-30 07:56
This issue impacts Risk & Fraud, so assigning to Sigma (based on team responsibilities Pc2DNy-3z-p2) @Automattic/sigma.

Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by tpaksu** [comment] 2023-12-01 07:49
@jessepearson hey! Thanks for creating this issue, I have a question about it, I couldn't reproduce it because it seems like automatic renewals are not supported on my local client/server duo, I understood that from a order notice like this: 

> Payment Method:
> Manual Renewal
>
> Subscription locked to Manual Renewal while the store is in staging mode. Payment method changes will take effect in live mode.

How may I enable it to reproduce before trying to create a solution?

cc @eduardoumpierre

**Comment by eduardoumpierre** [comment] 2023-12-01 10:46
Hey @tpaksu, I could reproduce the issue by following the steps provided by Jesse. As I understood, the subscription renewal is manual, in this case, because we are actively choosing to do it on the subscription details page.

Based on that, I created two pull requests with the one from the server being the preferred option.

https://github.com/Automattic/woocommerce-payments-server/pull/4252 – https://github.com/Automattic/woocommerce-payments/pull/7817

**Comment by tpaksu** [comment] 2023-12-01 11:17
But in the case of manual renewal, the user is redirected to the payment page, its not paid inside an async job, am I correct? It should be happening in the async context to fail I believe. And on the manual payment, it passes for me. No errors.

**Comment by eduardoumpierre** [comment] 2023-12-01 11:21
I think you're following the buyer path, but this issue is related to the admin dashboard. You should try to manually renew the subscription via **WooCommerce > Subscriptions** by clicking on your latest subscription, and then selecting **Process renewal** from the **Subscriptions actions** section.

**Comment by jessepearson** [comment] 2023-12-01 11:24
Something I realized I didn't include is that you need the Woo Subscriptions extension installed in order to replicate the test here, it does not work with Subs built into WooPayments.

**Closed as completed** 2023-12-14 14:24 UTC
Labels: type: bug, priority: critical, category: core, component: fraud & risk tools
