### ISSUE TITLE
Cart contents lost on login at checkout - plugin incompatibility

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#7992] opened 2024-01-08 17:13 UTC
### Describe the bug
When other plugins are active which make requests on behalf of the shopper (i.e. using their cookies), cart contents can be lost when logging in at checkout.

### To Reproduce
Add the following snippet to the bottom of `woocommerce-payments.php`:
```
function do_api_call_w_cookies_on_wp_login() {
	$url = rest_url();
	
	$args = array(
		'cookies'   => $_COOKIE,
		'blocking'  => false,
		'timeout'   => 0.01,
		'sslverify' => apply_filters( 'https_local_ssl_verify', false ),
	);

	$result = wp_remote_get( $url, $args );
}

add_action( 'wp_login',  'do_api_call_w_cookies_on_wp_login' );
```

This simulates another plugin making a request, with the session cookies, during login.

1. Ensure "Allow customers to log into an existing account during checkout" is enabled at WooCommerce > Settings > Accounts & Privacy
2. Ensure you're not logged into the store (or use a private browser session)
3. Add an item to your cart and go to the checkout page
4. Use the `Returning customer? Click here to login` option and login
5. The cart will now be empty

### Actual behavior
Logging in at checkout should not clear the cart.

### Expected behavior
It should be possible to login and checkout with whatever products were in the cart.

### Additional context
The issue appears to have been introduced by this PR (https://github.com/Automattic/woocommerce-payments/pull/819), which handles the use case of creating a new account during a 3DS checkout. The specific line causing us a problem in this particular case is [here](https://github.com/Automattic/woocommerce-payments/blob/a88fb8725e13b60ca30bb3e5ad975bb8083adfa0/includes/class-wc-payment-gateway-wcpay.php#L523).

A possible fix might be to try and be more specific and limit the manipulation of the cookies to only requests attempting to do account creation and a 3DS checkout? At the moment we run the fix in all cases.

For extra context, this issue was discovered as part of an investigation into a Jetpack Sync issue, but since it can be reproduced in isolation, and it could theoretically be an issue for other plugins, it makes sense to fix it in WooPayments (p9dueE-7zI-p2).

**Comment by jessy-p** [comment] 2024-01-08 18:20
Looks to be same as #5491, which was attempted to be fixed by Jetpack and since reverted due to an edge case.
But if we can fix it using a WCPay fix without other side-effects, that would be great. Will prioritise to look into a WCPay fix.

Note: This is an independently reproducible issue. If we can fix this, we might be able to resolve #5491 too.

**Comment by RadoslavGeorgiev** [comment] 2024-01-19 08:35
Gamma will pick this during today's sprint planning session, implementing the proposed solution to limit side-effects to 3DS checkout with registration.

**Closed as completed** 2024-02-01 06:54 UTC
Labels: type: bug, priority: high, status: has pr, impact: high, category: core

**Comment by ralucaStan** [comment] 2024-02-01 13:37
Great to see this issue being fixed. What is the timeline for releasing this fix? Could you also update this ticket https://github.com/woocommerce/woocommerce/issues/34464 with the release plan, some user reports need some updates.

**Comment by htdat** [comment] 2024-02-02 06:04
@ralucaStan Thanks for asking. I am going to update all relevant tickets (issues) including the Woo core issue you've mentioned.
Regarding the timeline, WooPayments 7.2.0 with this fix will be released on 
Feb 14th, 2024. paJDYF-c4R-p2
