### ISSUE TITLE
Subscriptions with a trial period (or initial payment of zero) fail to renew

### ISSUE THREAD

**Issue by nicdwilson** [Automattic/woocommerce-payments#2994] opened 2021-09-24 19:18 UTC
### Describe the bug
If the **Enable payments via saved cards** setting is set to off, a subscription with a parent order value of $0 (ie a subscription with a trial period) will save the "payment method" value correctly and will fail to save the "saved payment method" details, even though the parent order will save the `seti` token value correctly.

### To Reproduce

With WooCommerce, WooCommerce Subscriptions, and WooCommerce Payments

1. Set up a subscription product with a recurring total and a free period
2. Set WooCommerce Payments **Enable payments via saved cards** to off
2. Go through the checkout process with initial payment of zero
3. Trigger or wait for the first renewal payment

### Actual behavior

When the parent order and subscriptioon is created

1. The parent order will save the `seti_` token.
2. The Subscription will display WooCommerce Payments as the payment method
3. The Subscription will display no values in the "saved payment method" dropdown
4. The renewal order will fail

### Screenshots

![Markup on 2021-09-25 at 07:15:45](https://user-images.githubusercontent.com/3624025/134728615-aaf82421-5146-4763-bd68-d06935a1b3b5.png)

<img width="1699" alt="Markup 2021-09-25 at 07 13 35" src="https://user-images.githubusercontent.com/3624025/134728382-a5c8fe44-fa63-4c61-b7f6-7a2415b7b8a1.png">

### Expected behavior

I would expect t**Enable payments via saved cards** not to affect subscriptions

### Additional context

reported in 4318150-zen

**Comment by ricardo** [comment] 2021-09-25 01:41
With UPE enabled, the checkout form won't load. It looks like there was some regression, because this was already implemented in #2424.

The checkout block also doesn't work when UPE is enabled.

cc @FangedParakeet

**Comment by nicdwilson** [comment] 2021-10-04 23:02
4348573-zen

**Comment by namiokuzono** [comment] 2021-12-01 21:11
30840547-hc → 4561824-zen This is an AT site. Same issue with Free trial period → Renewal payment order with no saved payment method.

**Comment by brucealdridge** [comment] 2021-12-05 23:58
Two customer entries are created in stripe. One with name `Name: , Guest` which has the payment method/type allocated. The second customer is created using the correct details from the customer.

![image](https://user-images.githubusercontent.com/57298/144767804-6e4a06eb-a308-4bae-8a3d-ff74f5d553c0.png)

I have replicated this with both with Saved cards enabled and disabled.

**Comment by haszari** [comment] 2021-12-15 03:24
Marking this as medium size for now, until we hone in on a fix.

**Comment by amElnagdy** [comment] 2022-01-11 13:01
4674292-zen. The customer has this option enabled `Enable payments via saved cards`

**Comment by sukafia** [comment] 2022-01-12 11:42
I'm seeing what appears to be a similar issue in 4677566-zen

**Comment by brucealdridge** [comment] 2022-01-13 02:20
> Drive-by thought - is the `Enable payments via saved cards` option problematic or "required" for Subscriptions (e.g. in conjunction with UPE).

I believe a lot of confusion is due to this issue and #3471 being very similar in outcome but from very different sources and some customers may have been seeing a combination of the two issues.
The PR that closed that issue essentially required saved cards regardless of whether `Enable payments via saved cards` was enabled. 

This issue it has been [reproduced](https://github.com/Automattic/woocommerce-payments/issues/2994#issuecomment-986327538) with and without this option enabled.

**Comment by amElnagdy** [comment] 2022-01-13 12:23
Another report: 4677566-zen. Initial payment of $0. The `Enable payments via saved cards` option was **disabled**.

**Comment by thisissandip** [comment] 2022-01-18 07:46
4696165-zen. Renewal failed after 4 week trial period. The `Enable payments via saved cards` option was **enabled**.

**Comment by thracefulton** [comment] 2022-01-19 03:16
In 4699274-zen the same issue occurs with 1-week free trial, and `Enable payments via saved cards` is **enabled**.

**Closed** 2022-01-19 10:09 UTC
Labels: type: bug, priority: high, size: medium, component: saved cards and subscriptions, component: wcpay subscriptions, category: projects

**Comment by aprea** [comment] 2022-01-20 01:45
Hi all 👋, we recently merged [a PR](https://github.com/Automattic/woocommerce-payments/pull/3652) to address this bug. This bug fix will be included in the upcoming WooCommerce Payments 3.6 release.

Unfortunately, it **will not** retroactively fix subscriptions that were created while the bug was active on the store (i.e. stores running WCPay 3.5 or below).

Customers of stores affected by this bug will need to log into their account and manually add their payment details to their subscription.

**Step 1:** Log in to the account that was created for them when initially signing up for the subscription. The customer would've received an email from the store instructing them to set a password for their newly created account.

**Step 2:** While on the "My Account" page, navigate to the "My Subscription" page.

<img width="824" alt="Screen Shot 2022-01-20 at 10 34 10 am" src="https://user-images.githubusercontent.com/1527164/150239390-3a74ccee-bb62-4a61-a521-235583ee14e2.png">

**Step 3:** Click the "Change payment" button.

<img width="827" alt="Screen Shot 2022-01-20 at 10 34 27 am" src="https://user-images.githubusercontent.com/1527164/150239522-a31b796e-e0c6-477c-ad9f-49681285d801.png">

**Step 4:** Enter payment details and click the "Change payment method" button.

<img width="810" alt="Screen Shot 2022-01-20 at 10 35 09 am" src="https://user-images.githubusercontent.com/1527164/150239586-a22b86e4-36ad-456d-89a6-531d5c012707.png">

Once this is completed the store will be able to process subscription renewals automatically as expected.

Please note, that some affected customers may have already completed these steps as stores send a "Customer Renewal Invoice" when an automatic renewal fails, you can find more details about this [in the docs](https://woocommerce.com/document/subscriptions/store-manager-guide/#section-37).

>**Customer Renewal Invoice:** Sent to a customer when the subscription is due for renewal and the renewal requires a manual payment, either because it uses manual renewals or the automatic recurring payment failed. Email contains renewal order information and payment links.

One last thing to note, the `Enable payments via saved cards` setting has no bearing on this bug. Our understanding is that this bug will affect logged-out (guest) customers that purchase subscription products that offer a free trial period.

cc @nicdwilson @namiokuzono @amElnagdy @sukafia @thisissandip @thracefulton 

Please let me know if you have any questions.
