### ISSUE TITLE
Customer's email for previous order is updated with the email from the last purchase

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#6732] opened 2023-07-11 13:47 UTC
### Describe the bug
This affects Stripe Dashboard, but not _WooCommerce -> Orders_ page. It doesn't matter which gateway settings are used. The issue can be reproduced the same way for the legacy card as for any of the available UPEs.

### To Reproduce
1. Purchase a product by using a new `abc@xy.z` email
2. Navigate to Stripe Dashboard -> _Payments_ and check the _Customer_ column
3. The email you provided only once for the latest checkout is propagated to the previous payments as well. 

![image](https://github.com/Automattic/woocommerce-payments/assets/22319444/fc3020cc-5a7e-4202-abe0-79167f9afe37)

### Additional context
* My first guess was that https://github.com/Automattic/woocommerce-payments/issues/6731 is affecting the above-described issue, but after I few tests I clarified that it's not affecting and the issue exists regardless of https://github.com/Automattic/woocommerce-payments/issues/6731 existence.

**Comment by htdat** [comment] 2023-07-12 08:07
IMO, this is not a bug as Stripe Dashboard uses the email attached to its customer object to display in your screenshot.

WCPay updates the customer object associated with the order during the checkout process ((Most relevant change https://github.com/Automattic/woocommerce-payments/pull/5383):
https://github.com/Automattic/woocommerce-payments/blob/39e39847215dba950851d59c7003fac1b800bf80/includes/class-wc-payment-gateway-wcpay.php#L943-L943

On our end, we're adding `customer_email` into the payment intent metadata. In case, we want to know the exact email attached to an order, we would look into the payment intent metadata?
https://github.com/Automattic/woocommerce-payments/blob/39e39847215dba950851d59c7003fac1b800bf80/includes/class-wc-payment-gateway-wcpay.php#L1375-L1376

**Comment by timur27** [comment] 2023-08-07 11:35
@htdat thanks for looking into this! Sorry if I misunderstand your latest comment or if my description isn't clear enough, but the issue I'm facing is that the customer's email used for orders `#2214, #2212 etc` from the screenshot in the description is other than `uniqueemail@used.once`.The problem is that an email used for the latest order overrides emails from all the previous orders on Stripe Dashboard (not in WooCommerce).

If your analysis above considers this and essentially what you mean is that the data used in Stripe Dashboard is taken from the latest order' customer and it's just how it works in the test mode, then it's clear to me and as long as we're fine with such behavior, then it's not a bug. But I'm not sure if I understood you correctly or if I missed anything, so feel free to add any more details if you feel a bit more alignment is needed.

**Comment by htdat** [comment] 2023-08-08 05:00
> If your analysis above considers this and essentially what you mean is that the data used in Stripe Dashboard is taken from the latest order' customer and it's just how it works in the test mode, then it's clear to me... 

Yes, that's right. 
You can visit https://dashboard.stripe.com/acct_XXXXXXXX/test/customers/cus_YYYYY for that specific customer, and click `Edit Information` for the `Actions` button - [screenshot](https://github.com/Automattic/woocommerce-payments/assets/10045087/2b5ebab2-3310-4f9b-9c70-db261517f4f6), and then update the email of this customer to see changes in `Stripe Dashboard -> Payments`. 

> ... and as long as we're fine with such behavior, then it's not a bug.

If we consider it's a bug, it would be a bug on Stripe Dashboard rather than us. 

Anyway, I am going to close this issue now. Feel free to reopen if needed.

**Closed as completed by htdat** 2023-08-08 05:00 UTC
Labels: type: bug, priority: low, category: won't fix, category: core
