### ISSUE TITLE
With Early Access enabled, submitting no credit card details causes checkout shortcode field validation to fail

### ISSUE THREAD

**Issue by nicdwilson** [Automattic/woocommerce-payments#3633] opened 2022-01-13 20:15 UTC
### Describe the bug
When using early access features together with WooCommerce checkout shortcode, if a customer enters no credit card details and submits, a console error is triggered which prevents regular field validation errors from returning.

### To Reproduce

1. Enable WooCommerce Payments Early Access
2. Create a checkout page using the `woocommerce_checkout` shortcode
3. Proceed to checkout
4. Fill in no fields
5. Click submit

### Actual behavior

The console error is triggered

```
Uncaught (in promise) IntegrationError: stripe.confirmPayment(): the `confirmParams.return_url` argument is required unless passing `redirect: 'if_required'`
```

occurs

### Screenshots

<img width="1414" alt="Markup 2022-01-14 at 09 03 18" src="https://user-images.githubusercontent.com/3624025/149401735-e79f4abc-e713-414d-8bf0-3b3beb8ad590.png">

### Expected behavior

A validation error should be displayed to the user (without early access, it displays "Your credit card number is incomplete")

<img width="887" alt="Markup 2022-01-14 at 09 11 34" src="https://user-images.githubusercontent.com/3624025/149402438-0a4e0f0a-96a8-4e69-8ff8-3e6a7ec1350e.png">

### Desktop (please complete the following information):

* OS: Monterey
* Browser Firefox
* Version 96.0b10 

### Additional context

4648565-zen

**Comment by frosso** [comment] 2023-10-12 13:04
I tested this on WooPayments 6.6.0, both Chrome and Firefox.

Added a few products to the cart, then headed to checkout with CC enabled. Clicked "place order" without filling details. I was not able to reproduce this issue anymore.

![Screenshot 2023-10-12 at 2 59 36 PM](https://github.com/Automattic/woocommerce-payments/assets/273592/6152526b-ce6a-4ce6-b62e-0906f0402c51)
![Screenshot 2023-10-12 at 2 59 31 PM](https://github.com/Automattic/woocommerce-payments/assets/273592/4871aa22-9357-4548-9440-46f59cd990f8)

Closing for now, but feel free to re-open if necessary.

**Closed by frosso** 2023-10-12 13:04 UTC
Labels: type: bug, component: upe, category: core, needs prioritisation
