### ISSUE TITLE
Incorrect fees for mixed checkout transactions

### ISSUE THREAD

**Issue by aprea** [Automattic/woocommerce-payments#3868] opened 2022-02-28 00:41 UTC
### Describe the bug
Incorrect fees are being applied to mixed checkout transactions, i.e. when you purchase a subscription product and a regular product in a single transaction.

The 1% subscription transaction fee is applied to the entire transaction. This should only be applied to the subscription portion of the transaction.

<img width="727" alt="Screen Shot 2022-02-28 at 11 29 39 am" src="https://user-images.githubusercontent.com/1527164/155906813-7bef5b9a-1fd3-45e8-b03d-95ae2aedb65f.png">

### To Reproduce

**Prerequisites**
* WC Subscriptions is **not** installed / active.
* WCPay Subscriptions enabled.
* WC Store located in the United States with USD currency.
* Free shipping.
* Taxes disabled.

1. As the merchant, create a regular $100 product.
2. As the merchant, create a $100 p/month simple subscription product.
3. As a shopper, add one of each product to the cart and navigate to checkout.
4. Observe, the checkout total should be $200.
5. Fill in the required fields and complete the checkout.
6. As the merchant, navigate to WP admin then **Payments → Transactions**.
7. Click the most recent transaction to view the details.
8. Observe the transaction total is $200.00 USD.

The fee breakdown is:

>Fee (3.9% + $0.30): $-8.10
>Base fee: 2.9% + $0.30
>Subscription transaction fee: 1%
>Net deposit: $191.90 USD

### Actual behavior
The 1% subscription transaction fee is applied to the entire transaction.

**Actual fee breakdown as per the scenario above**

||calculation|subtotal|
|---|---|---|
|$100 regular product|$100 * 0.039|$3.90|
|$100 subscription product|$100 * 0.039|$3.90|
|$0.30 flat fee|$0.30|$0.30

**Total:** $8.10

### Expected behavior
The 1% subscription transaction fee is only applied to the subscription portion of the transaction.

**Expected fee breakdown as per the scenario above**

||calculation|subtotal|
|---|---|---|
|$100 regular product|$100 * 0.029|$2.90|
|$100 subscription product|$100 * 0.039|$3.90|
|$0.30 flat fee|$0.30|$0.30

**Total:** $7.10

### Additional context
Originally discussed here p1645777998329239-slack-CGGCLBN58

**Comment by haszari** [comment] 2022-02-28 01:00
Closing - this is intended behaviour – 1% fee is applied to the _transaction_ if it is subscription related.

**Closed by haszari** 2022-02-28 01:00 UTC
Labels: type: bug, priority: high, component: wcpay subscriptions, component: application fees, category: projects
