### ISSUE TITLE
Epic: Update Transactions Reports pages to use merchant timezone

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#9064] opened 2024-07-08 14:56 UTC
- Update all Transactions Reports page to use merchant timezone, currently it uses UTC
- Also check, server and client side CSV downloads.
- Ref: pdjTHR-3N2-p2#comment-5426

**Comment by haszari** [comment] 2024-07-10 03:11
Current status:

- All (AFAIK) reports are in UTC, though not labelled. 
- CSVs is in UTC. 
  - There are already issues logged for this inconsistency, need clarity from design/product on this. 
  - We are kinda assuming merchant timezone, kinda based on payment activity widget.
- Payment activity card is in merchant timezone.

**Comment by haszari** [comment] 2024-07-10 03:22
We estimated this based on a few assumptions:

1. We want all dates in list views and CSVs to be in store timezone.
   - The timezone used by activity widget – exploring /confirming if this timezone/setting is right it is out of scope. But we should confirm what setting we are using. We suspect this is user timezone (i.e. observer of the report). 
2. We don't know which need fixes, assuming all.
   - Transactions, disputes, deposits, transaction timeline, capital loans.

**Comment by Jinksi** [comment] 2024-07-10 03:26
We should align with WooCommerce analytics handling of timezones, which appears to use the timezone of the store/site set in WP settings.

**Comment by haszari** [comment] 2024-07-10 03:33
> We should align with WooCommerce analytics handling of timezones, which appears to use the timezone of the store/site set in WP settings.

That would work great for the "sales reps around the world discussing sales numbers" use case!

**Comment by aheckler** [comment] 2024-07-14 08:38
We might also need to adjust whatever transaction batching we use for tax document generation? [This doc](https://woocommerce.com/document/woopayments/taxes/documents/#downloading-an-invoice) mentions that the tax documents use UTC for reports.

> **NOTE:** The transaction data used in the invoice is based on the UTC timezone, which may cause some discrepancies between the transactions list and the invoice.

**Comment by haszari** [comment] 2024-07-18 22:18
Linking in an issue which clearly describes the bug/problem – this issue is a fix/solution, and we ended up deciding on a different approach.

- https://github.com/Automattic/woocommerce-payments-server/issues/5868

**Comment by haszari** [comment] 2024-07-18 22:37
We can probably close this. We still want to do it, but it's a roadmap item, not a bug.

**Comment by haszari** [comment] 2024-07-18 23:38
I'm closing this epic, so we don't get confused :) 

I've added all relevant steps/work to the other epic (UTC approach):

- https://github.com/Automattic/woocommerce-payments-server/issues/5858

**Closed as not planned by haszari** 2024-07-18 23:38 UTC
Labels: focus: reporting
