### ISSUE TITLE
Ensure we display "card declined" to buyers when their card is declined

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#1127] opened 2020-11-24 17:53 UTC
And not merely "Something went wrong. Please contact us to get assistance."

**Comment by leonardola** [comment] 2021-09-29 19:27
Steps to reproduce the error
- Install WooCommerce Block plugin
- Configure it following [this steps](https://docs.woocommerce.com/document/using-the-new-block-based-checkout/#section-2) 
- As a customer try to checkout with this credit card ```4000000000000002```

**Comment by a-danae** [comment] 2021-09-30 01:48
This looks like a duplicate of [this other issue](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4870), isn't it? If it is, I've sent a PR for it.

**Comment by leonardola** [comment] 2021-09-30 12:41
Yep that fixes it too. Tested it now

**Comment by leonardola** [comment] 2021-10-01 13:46
Closing this in favor of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4870

**Closed by leonardola** 2021-10-01 13:46 UTC
Labels: priority: high
