### ISSUE TITLE
WooPay button is disabled when conditions for variable product have not been met

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#6634] opened 2023-06-29 23:13 UTC
### Describe the bug
The WooPay button is in a disabled state if the shopper has not met the requirements for the variable product attributes such as color and logo. The Add to Cart and Google Pay buttons however are always and correctly in an enabled state.

### To Reproduce
1. Enabled WooPay and Apple Pay/GPay on the product page
2. Shop on test site and pick a variable type product
3. Note that WooPay will be disabled while the Google Pay and the Add to cart buttons are enabled. On Blocks the button will look enabled but is not functionally enabled.

### Actual behavior
The WooPay button is in a disabled state until the variable product options are selected.

### Screenshots

https://github.com/Automattic/woocommerce-payments/assets/109928953/818f50b4-8631-4f89-9f37-0819c3b442b7

### Expected behavior
PRBsm including WooPay, should be enabled, and a warning message presented until the required options for the product are selected

### Desktop (please complete the following information):
* Device: MacBook Pro
* Browser: Chrome
 
Note: Above Updated July 5th based on Elizabeth correctly pointing out that enabled, not disabled, is the correct button state.

**Comment by elizaan36** [comment] 2023-07-05 21:38
Hm I don't think the WooPay button should have a disabled state. @stephendharmadi Will you confirm?
I don't think Google Pay provides specs for a disabled state either. In this case I believe the expected behavior would be that making the attempt to checkout with WooPay would present form field errors on the color and logo selections. (i.e. "Choose a color") rather than disabling the button altogether.

From the [Google Pay guidelines](https://developers.google.com/pay/api/web/guides/brand-guidelines),

> **Use Google Pay to initiate payment during cart checkout**
> The Google Pay button brings up the payment sheet. On the payment sheet, customers can only select and confirm a single payment method and shipping address. Be sure to get all the other information that you need before you give customers the option to select the Google Pay button. Other information can include the following:
> - An item's size, color, or quantity.
> - The option to add a gift message or apply a promo code.
> - The ability to choose different shipping speeds and destinations for individual items.
> - If a customer doesn't provide the necessary information, offer real-time feedback to let them know what you need before they can bring up the payment sheet.

> **Add the Google Pay button to the product detail pages in addition to the cart checkout**
You can speed up single-item checkout if you let customers make individual purchases right from your product detail pages. If a customer chooses this option, be sure to exclude any other items they have in their shopping cart because the payment sheet only lets them confirm their payment and shipping information.

**Comment by pierorocca** [comment] 2023-07-05 22:35
You're right @elizaan36. Add to Cart would be the model behavior and it's not disabled and does present a warning modal. Should that be changed to the new buyer notice design? Note the weird placement of the modal and how it overlaps with the browser bookmark menu and the toolbar.

Shortcode:
https://d.pr/v/W0oQns

Blocks:
https://d.pr/v/enWWSi (note WooPay button is not visually in a disabled state on Blocks, but doesn't trigger the info warning on click)

**Comment by stephendharmadi** [comment] 2023-07-06 10:28
I confirmed that we don't have a disabled state for the WooPay button, and the button shouldn't be disabled for whatever reason instead of using the error state to highlight unselected product options.

Also, looking at the current warning modal, I think it should be redesigned. I would recommend adding another variant from the banner that @elizaan36 worked that looks more subtle. I quickly explored how it might look below, let me know what you guys think.

<img width="1500" alt="Product - Desktop - More payment options - Vertical" src="https://github.com/Automattic/woocommerce-payments/assets/110893979/e720e676-d52e-4612-85b5-f20954ff5b92">

**Comment by zmaglica** [comment] 2023-07-07 18:20
This issue impacts WooPay checkout buttons, so assigning to Heisenberg (based on team responsibilities) @bborman22  . Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by elizaan36** [comment] 2023-07-13 17:57
Nice idea to improve this but the error message on the form will depend on what form field errors are triggered consistently between standard and blocks checkout. I don't think it's within scope of this issue to change the form field errors overall.

**Comment by elizaan36** [comment] 2023-07-13 18:03
Could we make this update across all express methods consistently?

**Comment by pierorocca** [comment] 2023-07-13 18:41
>Could we make this update across all express methods consistently?

WooPay is the only button misbehaving in my testing so if we update the WooPay behavior we'll achieve consistency.

Regarding the wonky from the 90s warning message, on Blocks sites could we get this on the platform team's radar? It'd be a natural continuation of Mike Jolley's work to migrate components to the new notification system. 

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/642c61b6-e7e7-4bc1-b1ae-7acd0ccb148c)

**Comment by elizaan36** [comment] 2023-07-14 18:14
> could we get this on the platform team's radar

I can create an issue with the proposal on WCBlocks.

**Comment by pierorocca** [comment] 2023-07-14 18:17
At least in the short term they should fix the modal placement so it's not blocking the toolbar and search bar. Likely the same or similar issue impacting the WooPay 'Continue' button on mobile

**Comment by elizaan36** [comment] 2023-07-14 18:21
To confirm, this is the Product block where the JS modal appears?

**Comment by elizaan36** [comment] 2023-07-14 18:24
I don't think it's a blocks issue, it's a Woo core issue.

**Comment by pierorocca** [comment] 2023-07-14 18:49
> I don't think it's a blocks issue, it's a Woo core issue.

Yes you're right. It's the same modal and issue on both blocks and shortcode.

**Comment by pierorocca** [comment] 2023-07-19 21:51
This also impacts the gift card extension and gift card products. The WooPay button is unaware of the To and From field requirements. @alefesouza

**Comment by pierorocca** [comment] 2023-08-04 17:50
@bummytime could you help place this in the right repo and into maintenance?

**Comment by bummytime** [comment] 2023-08-14 21:59
**Update →** regarding the disabled WooPay button issue specifically, I spun up a conversation with the core team in p1692043367282689-slack-C0E1AV8T0. @frosso can you confirm if adding the `single-add-to-cart-button` class to the WooPay button is something we attempted already?

**Comment by frosso** [comment] 2023-08-14 22:21
> can you confirm if adding the single-add-to-cart-button class to the WooPay button is something we attempted already?

@bummytime I don't believe adding `single_add_to_cart_button ` came up before. [As far as I can see](https://github.com/Automattic/woocommerce-payments/blob/a9919556f5965c5d2fd8bd73b74eb9f23cc3d1cb/client/checkout/woopay/express-button/use-express-checkout-product-handler.js#L126-L135), we are explicitly marking the "WooPay" PRB in a disabled state when the "Add to cart" button is also disabled. So it seems we're intentionally disabling it until a selection is made.
[From what I see here](https://github.com/woocommerce/woocommerce/blob/8.0.1/plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js#L125-L135), it looks like adding the `single_add_to_cart_button` class to the button and removing the checks for the disabled state would be a good solution 👍 

> Note the weird placement of the modal and how it overlaps with the browser bookmark menu and the toolbar.

@pierorocca it looks like the dialog displayed is native of Google Chrome, it's not part of WooCommerce - it isn't possible to move its position. The exact modal can also be seen on a separate site here: https://jsfiddle.net/un1ek8sf/
[The modal is displayed by WC core](https://github.com/woocommerce/woocommerce/blob/8.0.1/plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js#L130).

**Comment by bummytime** [comment] 2023-08-15 15:17
> [From what I see here](https://github.com/woocommerce/woocommerce/blob/8.0.1/plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js#L125-L135), it looks like adding the single_add_to_cart_button class to the button and removing the checks for the disabled state would be a good solution 👍

Let's give this a go and see how it looks @frosso.  Thank you!

**Comment by pierorocca** [comment] 2023-08-15 20:33
@frosso can we move away from using alert() to dialog() or some other stylable element like a jQuery alert and pull in theme global styling for border, color, typography? Alert() is as rudimentary as it gets and it looks old school and unpolished.

cc @elizaan36

**Comment by frosso** [comment] 2023-08-16 10:04
> can we move away from using alert() to dialog() or some other stylable element like a jQuery alert and pull in theme global styling for border, color, typography? Alert() is as rudimentary as it gets and it looks old school and unpolished.

@pierorocca the change would need to be implemented in WC Core. I'm sure it's feasible, but concerns like increased bundle size and testability across the myriad of themes out there come to mind - not to mention support to ensure things don't break.
It would be up to the theme developer to adopt styling these kinds of elements (not all themes adopt good patterns for global styling), and there are themes that are being used today that haven't been updated in a while.

We'd be embarking on a big journey - but it would need to be properly prioritized :) were you able to identify other areas of concern that are displaying `alert`s, which would benefit from this refactor?

**Comment by pierorocca** [comment] 2023-08-16 15:25
For WooPay, the main thing is fixing the disabled state. If an issue hasn't been opened yet with core team for the alert issues, @elizaan36 mentioned above, I can do that. This is worth raising and investigating as both the placement of the alert (system controlled) and that it deviates from a store's theme for key shopping functionality looks unpolished. I'm sure we can provide default styling that's 1000% better than a system altert to bridge any theme or adoption gaps.

**Comment by pierorocca** [comment] 2023-09-05 17:20
I noticed today the disable state is resolved but clicking the WooPay button doesn't invoke the alert. Is this still in-progress? Note I still need to open an enhancement request in the Core repo.


https://github.com/Automattic/woocommerce-payments/assets/109928953/0d29438b-7362-48cf-9fe3-b3281fcbf8ad

**Comment by pierorocca** [comment] 2023-09-13 19:04
Thanks @alefesouza!

**Comment by pierorocca** [comment] 2023-09-18 17:51
@elizaan36, @c-shultz correctly pointed out that the Add to cart button appears in the disabled state by default too. Should Add to cart be enabled or disabled by default in your opinion?

**Closed as completed** 2023-09-25 21:41 UTC
Labels: type: bug, needs design, component: payment request button, needs prioritisation

**Comment by pierorocca** [comment] 2023-09-26 17:36
cc @nikkivias for visibility.

**Comment by LCmry** [comment] 2023-11-02 19:13
@pierorocca what was the consensus on what the WooPay button should do here? I saw there was discussion on the blocks way, but I don't think a decision yet. The WooPay button at this time is functional and it is possible to purchase a variable product without choosing variations, which seems an issue to me. Should this functionality - to keep it disabled along with "add to cart" button until variations chosen - be reinstated?

**Comment by pierorocca** [comment] 2023-11-02 19:35
@LCmry the consensus was to have the button active and if clicked would display the alert modal informing the user they need to select the choices. With the button disabled, there was no way to provide the shopper the instructions.

Now the system alert modal I commented could be improved upon in core even if we had to create our own style if we couldn't pull in global styles.

**Comment by LCmry** [comment] 2023-11-02 19:50
Thanks for the clarification @pierorocca!

> the consensus was to have the button active and if clicked would display the alert modal informing the user they need to select the choices.

I didn't see an issue for this separately. Is there one or shall I make one?

**Comment by pierorocca** [comment] 2023-11-02 21:07
Fixed as part of the compatibility work https://github.com/Automattic/woocommerce-payments/pull/7158 afaik.

**Comment by pierorocca** [comment] 2023-11-02 21:09
> The WooPay button at this time is functional and it is possible to purchase a variable product without choosing variations, which seems an issue to me

If that's current behavior then yes that would be regression and a new issue should be opened. The part about being able to purchase without choosing the variations is the regression part.
