### ISSUE TITLE
Compatibility with Ultimate WooCommerce Gift Cards

### ISSUE THREAD

**Issue by laurendavissmith** [Automattic/woocommerce-payments#3398] opened 2021-11-18 20:41 UTC
We received a customer report today of an incompatibility with both the Free and Pro versions of Ultimate WooCommerce Gift Cards which when activated alongside WC Pay renders the checkout fields inoperable.

The versions of the extensions they tested are:
* Ultimate WooCommerce Gift Cards PRO - 3.1.0
* Ultimate WooCommerce Gift Cards Free - 2.2.1

**Comment by htdat** [comment] 2021-11-22 08:04
Relevant discussion: p1637268196221100/1637249530.186600-slack-CGGCLBN58

@harriswong, @dechov, @Automattic/axiom - y'all more or less involves in this discussion. Would you please update this issue so it's ready to work?

**Comment by brianyu28** [comment] 2021-11-22 22:18
I took a look at this today to try to replicate the issue but wasn't able to — I was able to purchase a gift card (with the free/lite version of Ultimate WooCommerce Gift Cards) using WCPay and then make another purchase with that gift card using WCPay, and I didn't notice any issues with the checkout fields. Was there any additional information from the customer as to what was wrong with the checkout page and/or other details that might help replicate the issue?

**Comment by leonardola** [comment] 2021-11-29 21:02
I also could not reproduce the issue. 
The customer does not seem to be using a default checkout. Also there are some assets that are trying to be loaded from a staging environment that does not exist. 
What theme is the customer using?
Have they tried with the storefront theme? 
Does any errors show on the browser console with wc pay and gift card plugins active? Maybe some broken assets?

**Comment by a-danae** [comment] 2021-11-29 21:37
I'm noticing I left a comment in Slack but not here. FWIW, I couldn't replicate the issue either when I tested it some days ago.

**Comment by htdat** [comment] 2021-12-01 06:30
@brianyu28, @leonardola, @a-danae - Thanks for your input. I am going to close this issue for now.
That said, we can always reopen it and engage with the customer to get more info if needed.

**Closed by htdat** 2021-12-01 06:30 UTC
Labels: type: bug, priority: high, needs feedback, category: core
