### ISSUE TITLE
Error retrieving settings after update to 7.4.0

### ISSUE THREAD

**Issue by cotaricky** [Automattic/woocommerce-payments#8500] opened 2024-03-27 14:34 UTC
### Describe the bug
After updating the plugin to version 7.4.0, I went to the settings of the plugin and I get a "Error retrieving settings." pop-up on the bottom left.

### To Reproduce

1. Update WooPayments to latest version (7.4.0)
2. Go to "WooPayments Settings or WooPayments All paying methods"
3. Get "Error retrieving settings."
4. All previous settings are reset do default.

### Actual behavior
After updating the plugin, I went to the settings of the plugin and I get a "Error retrieving settings." pop-up on the bottom left.

### Screenshots
https://snipboard.io/oQOTwG.jpg

### Expected behavior
After the update, the settings should remain the same and no error should appear.

### Desktop (please complete the following information):

* OS: MacOS
* Browser Chrome
* Version 123.0.6312.59

**Comment by cotaricky** [comment] 2024-03-27 14:39
After this, I rolled back to version 7.3.0 and all my information was there, as you can see on the screenshot attached.

![SCR-20240327-nabc](https://github.com/Automattic/woocommerce-payments/assets/46688224/f5ae1abd-9263-43ea-b5e4-5e824a0e819f)

**Comment by csmcneill** [comment] 2024-03-27 16:03
Howdy @cotaricky! Thanks for reporting this!

I'm glad to hear that reverting to 7.3.0 resolved the issue. However, on my own sites (plural), I'm unable to reproduce the issue. Additionally, we are not seeing any similar reports of merchants encountering this error after updating to 7.4.0.

I'd like to dig into this a bit more, but we'd need to get information about your site and its setup, which we would prefer not to handle on a public forum. Could you please navigate to [Woo.com > My Account > Support](https://woo.com/my-account/contact-support/) and open up a chat or ticket with us so that we can dig into this further? You may need to create an account before you can access that page. 

Please include a link to this GitHub issue so that our Happiness Engineers can have a more complete picture of what's going on :)

**Comment by cotaricky** [comment] 2024-03-27 16:10
Hi @csmcneill! Thank you for the reply. 

I just created a support ticket in Woo.com as you requested. Hope someone can help me out. My store is connected to Woo.com also, so there was no need to create account.

**Comment by csmcneill** [comment] 2024-03-27 16:18
Thanks @cotaricky! We've received your inquiry (reference 7952303-zen) and our team will be in touch soon.

I will leave this issue open for the time being just in case other folks have similar issues.

**Comment by WhiteWard** [comment] 2024-03-28 15:33
I can confirm I'm having the same issue here!

**Comment by timur27** [comment] 2024-03-28 15:53
@WhiteWard could you please check the Network tab and let us know what is the response for `GET /wp-json/wc/v3/payments/settings` request when opening the Settings page? Are there any error messages? If this request is `200`, then it would be helpful to know which request is failing. Thanks for your input!

**Comment by WhiteWard** [comment] 2024-03-28 19:30
All Ok on the endpoint,

The only noticeable error I see is a JS console error:
TypeError: undefined is not an object (evaluating 'l.enabled_payment_method_ids.filter')

The deposits screen flashes for a second but never pulls any data then disappears, but I can still see it using inspect element. Same as OP, rolling back to 7.3 removes this issue.

**Comment by mathistdn** [comment] 2024-04-01 05:57
Having exactly the same issue, I will also get back to 7.3.

**Comment by mathistdn** [comment] 2024-04-01 05:58
The issue also block the access to all the payments pages in the side bar

**Comment by cotaricky** [comment] 2024-04-01 14:06
> Having exactly the same issue, I will also get back to 7.3.

Have you confirmed whether the issue was resolved after rolling back to version 7.3.0?

**Comment by csmcneill** [comment] 2024-04-01 20:21
Howdy @cotaricky @mathistdn @WhiteWard — we've determined that this issue is likely caused by a plugin like the [Brevo - WooCommerce Email Marketing](https://wordpress.org/plugins/woocommerce-sendinblue-newsletter-subscription/) integration. 

With the aforementioned Brevo plugin specifically, we are finding that it is adding the following to the `settings?_locale=user` network response:

```
<input type="hidden" class="ws_opt_in_nonce" name="ws_opt_in_nonce" value="[nonce]">
```

Passing this value through the network response prevents the WooPayments pages from loading. You can test this without the Brevo integration installed by overriding the content of the `settings?_local=user` request...

![CleanShot 2024-04-01 at 15 12 39](https://github.com/Automattic/woocommerce-payments/assets/82999806/47d6c749-a886-4538-9a5c-69a4d2a57d01)

...and removing the `<input>` tag...

![CleanShot 2024-04-01 at 15 13 03](https://github.com/Automattic/woocommerce-payments/assets/82999806/4e52013c-5c86-43e3-871f-12a19c1d02a6)

From there, use `CMD + S` or `CTRL + S` to save your override changes, then refresh the page. It should load as expected.

Alternatively, if the page is loading for you (e.g., you reverted to version 7.3.0 or the Brevo integration is deactivated) you can reproduce this issue by adding any HTML to the request. While `<input>` is added by the Brevo integration, other HTML tags like `<p>` and `<em>` will produce the same issues.

What we suspect is happening here is that the https://github.com/Automattic/woocommerce-payments/commit/6a22e18508beda94b6a70edcc4ea910c44a03a56 commit introduced the `wocommerce_checkout_fields` filter, which is [triggering an opt-in via the Brevo integration](https://plugins.trac.wordpress.org/browser/woocommerce-sendinblue-newsletter-subscription/trunk/src/managers/api-manager.php#L50). 

This is not an issue that can or will address in WooPayments. According to [the WordPress developer Handbook](https://developer.wordpress.org/plugins/hooks/filters/#:~:text=Unlike%20Actions%2C%20filters%20are%20meant%20to%20work%20in%20an%20isolated%20manner%2C%20and%20should%20never%20have%20side%20effects%20such%20as%20affecting%20global%20variables%20and%20output.%20Filters%20expect%20to%20have%20something%20returned%20back%20to%20them.):

> [...] filters are meant to work in an isolated manner, and should never have side effects such as affecting global variables and output.

While we could prevent that from our side by using output buffering before calling the filters, this could lead to other conflicts. As a result, it is best for the developers of the Brevo integration (or similar plugins that may be causing this issue) to resolve this.

Many thanks for all of the reports, as they allowed us to isolate the cause! Given that this is a conflict with a third-party integration and that we will be unable to resolve it within WooPayments specifically, I will close this issue.

**Closed as not planned by csmcneill** 2024-04-01 20:21 UTC
Labels: type: bug, category: core, priority: medium, focus: checkout payments

**Comment by cotaricky** [comment] 2024-04-02 13:45
@csmcneill, I opened a support ticket with the developer to see if it's possible to fix this issue so we could update WooPayments in the near future.

@mathistdn @WhiteWard, maybe you could also open one, so the problem gets picked up by the Brevo team quickly.

Thanks to the people involved in finding out what was the cause of this.
