### ISSUE TITLE
Deposit breakdown should include card reader transfer fee (IPP - in person payments)

### ISSUE THREAD

**Issue by rezzap** [Automattic/woocommerce-payments#6169] opened 2023-04-27 13:47 UTC
### Description
Monthly fees are charged for card reader usages. On the payout breakdown we see this listed as a Transfer fee, but the user does not see this item listed in the deposit breakdown meaning the actual deposit does not add up with the listed items. 

We should make it clearer and expose that charge as part of the deposit breakdown. 

### Acceptance criteria

* First requirement: The deposit breakdown includes the card reader fees counted as 'Transfer' fees. 

### Designs

![Image 2023-04-27 at 2 38 42 pm](https://user-images.githubusercontent.com/10325627/234879634-09fc2fa7-1fef-4c0a-9800-8166d3564f9e.jpg)

### Testing instructions

1. Go to Payments > Deposits for any site that uses a WooCommerce Payment card reader with a monthly fee
2. View the list and search for the Transfer fee
3. If the fee is listed, the feature is working as expected

### Additional context

6217631-zd-woothemes
p1682428333309319-slack-C02HWCJUFU5

**Comment by csmcneill** [comment] 2023-04-28 00:38
This may be a duplicate of https://github.com/Automattic/woocommerce-payments/issues/5283

**Comment by jessy-p** [comment] 2023-05-02 06:03
According to Pc2DNy-3z-p2, this falls in Helix @haszari. Tagging as a part of Gamma Porter duties PcreKM-yM-p2.

**Comment by haszari** [comment] 2023-05-02 20:08
Thanks @jessy-p  👍  – added to our board.

**Comment by haszari** [comment] 2023-05-02 20:11
Noting this is specifically about card reader fees, so could be handled as an in-person payments issue.

**Comment by shendy-a8c** [comment] 2023-06-14 03:42
To whoever works on this issue needs to confirm that this issue is a duplicate of https://github.com/Automattic/woocommerce-payments/issues/5283 and if so, needs to close one of the issues.

**Comment by Jinksi** [comment] 2023-10-17 23:12
Closing as duplicate of #5283

**Closed as not planned by Jinksi** 2023-10-17 23:12 UTC
Labels: component: payouts, component: card present
