### ISSUE TITLE
Clicking on Fraud Protection menu item in wpadmin jumps to another menu

### ISSUE THREAD

**Issue by oneillo** [Automattic/woocommerce-payments#6369] opened 2023-05-24 19:23 UTC
### Describe the bug
Currently, when you click on the `Payments > Fraud protection` menu item in a Woo Express site, it opens up the `Extensions` menu. With the default menu structure, the same menu item opens up the `WooCommerce` menu.

### Screenshots

Here is a GIF showing the behavior on the Woo Express site.

![wooexpress-paymentsfraudprotection-jumps-to-extensions](https://github.com/Automattic/woocommerce-payments/assets/730723/77d2ac61-3015-4c2c-a352-3b23125d8f62)

And here is the same behavior with the default WP menu structure found in the issue linked below.

![240589396-11fcc1c6-e05b-460c-841e-8f909906b442](https://github.com/Automattic/woocommerce-payments/assets/730723/3f4b3c84-1101-4beb-a3c2-bae085b77231)

### Additional context

This was investigated briefly in Automattic/wc-calypso-bridge#1159, where they found the issue was not a result of the ecommerce menu controller.

**Comment by PanosSynetos** [comment] 2023-05-25 07:16
To give some more info, on my site, the Fraud menu item doesn't exist. I could replicate the issue though by going to 

- `wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments`
- scroll down to fraud protection, click on **advanced** then **configure** 
- it goes to `wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Ffraud-protection` which expands the **Extensions** or **WooCommerce** menu item (as described above)

**Comment by zmaglica** [comment] 2023-06-15 12:13
This issue impacts Fraud, so assigning to team Sigma (based on team responsibilities) @dwainm  . Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by jessepearson** [comment] 2023-06-27 12:49
@oneillo There's something that's odd that sticks out about your gif, it shows under Payments that the account/site is not connected to Stripe, which is indicated by the _Finish setup_ option under Payments. One of the first checks before that [menu is added (and then immediately removed)](https://github.com/Automattic/woocommerce-payments/blob/2909c7d617cf15f64407710dfe8fb96a8d6278d8/includes/fraud-prevention/class-fraud-risk-tools.php#L79-L106) is that the Stripe account is connected. I'm wondering if there's something else going on.

I checked with a connected site by following the steps provided by @PanosSynetos , but I could not replicate locally. Is there a page that describes how to get a WooExpress site to test with?

**Comment by oneillo** [comment] 2023-06-27 14:51
Hey @jessepearson - you can get a 14-day trial Woo Express site here: [https://woocommerce.com/express/](https://woocommerce.com/express/). Just click on the `Try for free` CTA to start the process.

**Comment by PanosSynetos** [comment] 2023-06-27 14:53
@jessepearson I have a site that I use for development (and I've got WC Payments setup in dev mode), where the issue is replicated. I can invite you so you can check it out

**Closed as completed** 2023-07-10 14:27 UTC
Labels: type: bug, priority: high, status: has pr, category: core, component: fraud & risk tools
