### ISSUE TITLE
[WooPay Global Theme-ing] Limit availability to shortcode checkout entrypoint

### ISSUE THREAD

**Issue by malithsen** [Automattic/woocommerce-payments#9866] opened 2024-12-02 19:13 UTC
### Description

WooPay checkout theme-ing currently semi-supports all WooPay entrypionts. With this features reduced scope, we want to limit the feature to only be enabled when entering WooPay via the shortcode checkout. 

### Acceptance criteria

* WooPay checkout should use merchant styling when entering WooPay via shortcode checkout in merchant site. This includes both the WooPay button flow and the email input flow.
* WooPay should not inherit merchant styling when entering via any other entrypoint

| Entrypoint | Should be enabled? |
| --- | --- |
| Product Button | ❌  |
| Blocks Cart Button | ❌  |
| Blocks Cart Direct Checkout | ❌  |
| Blocks Checkout Page Button | ❌  |
| Blocks Checkout Page email field | ❌  |
| Shortcode Cart Button | ❌  |
| Shortcode Cart Direct Checkout | ❌  |
| Shortcode Checkout Page Button | ✅ | 
| Shortcode Checkout Page email field | ✅ |

### Additional context

p2: pdpOw2-4xg-p2#comment-4510

**Comment by hsingyuc** [comment] 2024-12-18 19:09
I'm reopening this issue due to I'm able to get theme support from all the entry points.

https://github.com/user-attachments/assets/5235f756-036b-40e1-a6af-ca985c970d60

**Comment by hsingyuc** [comment] 2024-12-18 19:47
I'm closing this issue since I can't reproduce it anymore and log as expected.

**Closed as completed by hsingyuc** 2024-12-18 19:47 UTC
Labels: component: WooPay, focus: woopay
