### ISSUE TITLE
Payment options show `There are no payment methods available. This may be an error on our side. Please contact us if you need any help placing your order.` error

### ISSUE THREAD

**Issue by hsingyuc** [Automattic/woocommerce-payments#8009] opened 2024-01-11 19:12 UTC
### Describe the bug
When checkout with WC Bookings requires confirmation product, the payment options show `There are no payment methods available. This may be an error on our side. Please contact us if you need any help placing your order.` on Blocks checkout.

### To Reproduce
1. Install WC Bookings and create a product that requires confirmation.
2. Checkout with that product and go to block checkout
3. See error shows on the payment options section

### Actual behavior
The payment options shows error `There are no payment methods available. This may be an error on our side. Please contact us if you need any help placing your order.`

### Screenshots

<img width="426" alt="Screenshot 2024-01-10 at 2 18 08 PM" src="https://github.com/Automattic/woocommerce-payments/assets/56378160/12f4bedf-8fef-412a-83bc-4383971468db">

### Expected behavior
It should render the payment option

**Comment by csmcneill** [comment] 2024-01-11 20:59
I'm unable to reproduce this with Bookings 2.0.8, WooPayments 7.0.0, and WooCommerce 8.4.0:

![requires confirmation product edit](https://github.com/Automattic/woocommerce-payments/assets/82999806/be1c1f79-2fd3-45b7-add4-bc305d3104d4)

![check availability](https://github.com/Automattic/woocommerce-payments/assets/82999806/87e36c8c-037b-442d-a599-97867cf292bb)

![confirmation required](https://github.com/Automattic/woocommerce-payments/assets/82999806/80d294b3-51f8-4ebc-9f59-72a76cfd505a)

Note that this last screenshot doesn't render _any_ payment gateway elements. This is also true of my test site that uses Stripe 7.9.0:

![stripe confirmation required](https://github.com/Automattic/woocommerce-payments/assets/82999806/1516546d-a0e2-4d27-96b9-561ddccd02a9)

@hsingyuc I suspect this is an issue with Bookings itself instead of an issue with Bookings + WooPayments, but it's also possible you may be experiencing this issue with a specific branch of WooPayments that I'm also not testing with _or_ there are some other configurations at play.

If you can export your Bookable product and upload it here, I can import it to my site to see if I can reproduce the issue.

To export the product:
1. Navigate to **Products > All Products**.
2. Edit the Bookable product that you can consistently replicate this issue with.
3. Navigate to **Product data > Export**.
4. Select the `Export` button to download a `.zip` file of your Bookable product.
5. Upload the `.zip` here.

[booking-product-227-with-global-rules-2024-01-11.zip](https://github.com/Automattic/woocommerce-payments/files/13908332/booking-product-227-with-global-rules-2024-01-11.zip) is an export of the Bookable product I tested in the screenshots above. You can import it to your site via https://github.com/woocommerce/bookings-helper

Flagging this to @thisissandip as the Bookings PA and @CGA8C / @francoishvz as the WooPayments PAs. I asked some of our WooPayments HEs to help me reproduce this issue at p1705007124539329-slack-C05QSQ0GT0U

**Comment by thisissandip** [comment] 2024-01-12 07:12
@csmcneill @francoishvz @CGA8C This was fixed in the recent release of WooCommerce Bookings (2.8.0) released a day ago.

![Si53zm.png](https://github.com/Automattic/woocommerce-payments/assets/69596988/5f955bfe-9bba-452e-851a-ef8d468787b5)

We can close the issue.

**Closed as completed** 2024-01-12 17:24 UTC
Labels: type: bug, category: core
