### ISSUE TITLE
Apple Pay not shown as payment method for orders when UPE is enabled

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7075] opened 2023-08-28 02:38 UTC
### Describe the bug
When UPE is disabled, the order details at **WooCommerce > Orders** for a payment made with Apple Pay will show:

```
Payment via Apple Pay (WooPayments) [...]
```

However, when UPE is enabled, there is no indication of whether or not an order is paid via Apple Pay. The details will read:

```
Payment via WooPayments [...]
```

### To Reproduce

1. Enable UPE.
2. Place an order.
3. Check the order details in **WooCommerce > Orders**.
4. Disable UPE.
5. Repeat steps 2 and 3.

### Actual behavior
The order details are different for Apple Pay depending on if UPE is enabled or disabled.

### Screenshots

![Markup on 2023-08-27 at 21:35:51](https://github.com/Automattic/woocommerce-payments/assets/82999806/e7ab53df-f269-4651-9dd2-73d8e2b1ad3e)

![Markup on 2023-08-27 at 21:36:40](https://github.com/Automattic/woocommerce-payments/assets/82999806/27b58293-6f9a-47f5-9ac5-c238f3985001)

### Expected behavior

There should be consistency between the details in the **WooCommerce > Orders** page. Ideally, Apple Pay should be identified as being used regardless of whether UPE is enabled or not.

### Additional context

- I could reproduce this in Split and Legacy UPE.
- This likely affects Google Pay, too. I cannot test Google Pay because I am affected by #4083 :(
- Discussion at p1692315035060419-slack-C3NCP7ZJ6

**Comment by frosso** [comment] 2023-08-31 15:53
As a side note: when fixing this we should probably also check the correct behavior for Stripe Link/WooPay.

**Comment by alefesouza** [comment] 2023-10-25 22:41
I could not reproduce this issue anymore, I got "Payment via Apple Pay (WooPayments)" with UPE checkout as expected, maybe it was fixed on the latest WCPay versions.

**Closed as completed by alefesouza** 2023-10-25 22:41 UTC
Labels: type: bug, priority: low, component: payment request button, component: upe
