### ISSUE TITLE
checkout page - Undefined array key 0 - .../class-woocommerce-hpos-orders.php on line 204

### ISSUE THREAD

**Issue by Aljnk** [Automattic/woocommerce-payments#8758] opened 2024-05-02 09:41 UTC
### Describe the bug
( ! ) Warning: Undefined array key 0 in .../wp-content/plugins/woocommerce-payments/vendor/automattic/jetpack-sync/src/modules/class-woocommerce-hpos-orders.php on line 204

[log.txt](https://github.com/woocommerce/woocommerce/files/15186137/log.txt)

### To Reproduce
1. WooPayments is in sandbox mode.
2. Enable WP Debug - define('WP_DEBUG',true); define('WP_DEBUG_DISPLAY',true); @ini_set('display_errors',0); define('SCRIPT_DEBUG',true);
3. Add some products to chart
4. Go to 'checkout page'
5. Scroll down to end of the page
6. See error

### Actual behavior
PHP Warning

### Screenshots
<img width="775" alt="Screenshot_1" src="https://github.com/Automattic/woocommerce-payments/assets/11256478/3b6ff25d-6352-49b7-ad78-f05ef9589e51">

### Expected behavior
Not sure, but maybe - if(isset($args[0])){...

**Comment by aheckler** [comment] 2024-05-02 12:40
@Aljnk I'm unable to reproduce this warning on a test site with the steps you've given above. Some questions that might help us investigate this:

- What theme are you using? Is it publicly available so that we can test with it?
- Does the warning still occur if you use [our free Storefront theme](https://wordpress.org/themes/storefront/)?
- Are you enabling high-performance order storage, and is "compatibility mode" enabled?
- Could you please send us a copy of your site's system status report? You can find it under WooCommerce > Status in the dashboard. Click "Get system report" and then the "Copy for support" button. Once you've done that, paste it into your reply here.

**Comment by Aljnk** [comment] 2024-05-02 13:30
1-2.
<img width="215" alt="Screenshot_3" src="https://github.com/Automattic/woocommerce-payments/assets/11256478/95da5388-975e-4de5-9bec-852ab047333c">

3. HPOS (Yes), "compatibility mode" (No - Now is On - Same)
4.  [SystemStatusReport_2024-05-02T13-22-52.txt](https://github.com/Automattic/woocommerce-payments/files/15188914/SystemStatusReport_2024-05-02T13-22-52.txt)

Steps.
1. Open https://test.pics4biz.com/shop/

2. Select first three products
<img width="897" alt="Screenshot_4" src="https://github.com/Automattic/woocommerce-payments/assets/11256478/5a2463f2-7f3b-4e97-a839-d5cdc2019d23">

3. Open checkout
<img width="599" alt="Screenshot_5" src="https://github.com/Automattic/woocommerce-payments/assets/11256478/2781051d-9bde-490d-a6e3-0e2dd6e6dbe7">

4. Scroll down
<img width="775" alt="Screenshot_1" src="https://github.com/Automattic/woocommerce-payments/assets/11256478/4e523f12-6dad-4c12-8c0b-ee6a2c5ca508">

**Comment by csmcneill** [comment] 2024-05-02 15:31
Thanks for the additional information, @Aljnk!

This error is rooted in Jetpack Sync. Some internal discussions:
- p1712679936228689-slack-C011BCGRMBR
- p1714135104960259-slack-CB37YNEH1
- p1714134001874539-slack-CGGCLBN58

This has been resolved in https://github.com/Automattic/jetpack/pull/37111 but that PR has a milestone of Jetpack 13.3.2. AFAICT, we will need to update the sync package in WooPayments, but that may require Jetpack 13.3.2 to be released first.

**Closed as completed** 2024-05-02 15:33 UTC
Labels: type: bug

**Comment by csmcneill** [comment] 2024-05-03 16:24
@Aljnk just noting that we're working on resolving this issue within WooPayments via https://github.com/Automattic/woocommerce-payments/pull/8763 — we currently expect this to go out in the 7.6.0 release, which is slated for 8 May.

ccing a few folks:
- @gpressutto5 as the 7.6.0 release lead — it looks like @zmaglica is still waiting on a review for https://github.com/Automattic/woocommerce-payments/pull/8763 and the code freeze is in a couple of days.
- @CGA8C / @francoishvz to communicate with affected merchants noted in p1714673073234429/1714134001.874539-slack-CGGCLBN58
