### ISSUE TITLE
Order Status is not updated for Blocked Payments

### ISSUE THREAD

**Issue by thisissandip** [Automattic/woocommerce-payments#4246] opened 2022-05-10 12:43 UTC
### Describe the bug

If payment is blocked (eg. `requested_block_on_incorrect_zip`), then in WooCommerce, the status of the order gets stuck in `Pending Payment`

### To Reproduce

- Place an order that gets blocked and returns `charge.failed` event

### Expected behavior

The status of the order should be updated to Failed.

### Screenshot

<img width="748" alt="Markup 2022-05-10 at 18 12 44" src="https://user-images.githubusercontent.com/69596988/167630980-42eedbad-64cd-453c-82b9-a2a6dd2ca358.png">

### Additional context

As per discussion over here: p1652160056453839/1651805909.385329-slack-C7U3Y3VMY

[The code](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-webhook-processing-service.php) that handles the Stripe events, does not treat the `charge.failed` event to update the order status.

**Comment by jessy-p** [comment] 2022-05-23 17:07
@thisissandip  Tested on Jurassic Ninja site with [test card 4000000000000036 ](https://stripe.com/docs/testing#fraud-prevention) which results in blocked payment, the status changes to Failed after a few seconds (webhook processing) , does not remain stuck as Pending Payment.

![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/a55733cd-ee88-4cc4-a946-4c6496ac29ed)

Could you retest?

**Comment by thisissandip** [comment] 2022-05-26 13:40
Hi @jessy-p!

I tested again in JN and I see that the order status is updated correctly to `Failed`.

<img width="384" alt="Markup 2022-05-26 at 18 57 32" src="https://user-images.githubusercontent.com/69596988/170497191-9c62d029-f975-4f71-a9df-11d3dbdd5166.png">

However, if you check the conversation here: p1651806012248499/1651805909.385329-slack-C7U3Y3VMY Particularly the Issue 1 - Order 63083 (it is mistyped as 53083 in slack). You can see that the order was never updated to failed.

Now, I think this happened because the webhook failed to reach the site to update the order. 

Do you think including a `charge.failed` case over [here](https://github.com/Automattic/woocommerce-payments/blob/a7ec071ba3dec9c9fd7b7f13402b0cd435b68f9b/includes/class-wc-payments-webhook-processing-service.php#L135) can handle such issues as mentioned by @cesarcosta99 on the same slack thread?

**Comment by jbordonado** [comment] 2022-06-01 09:34
We now have a mechanism to store the failed webhooks and process them again later with a cron job, so I would assume the order would still update to a "failed" status, but with some delay in case the webhook could not reach the site.

Regarding the issue, you were both not able to reproduce and I can see that on the client we are handling the `payment_intent.payment_failed` event in which [we update the order status to "failed"](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-webhook-processing-service.php#L344).

I'm not sure also handling the `charge.failed` event would bring something.

From Stripe docs:

charge.failed
`Occurs whenever a failed charge attempt occurs.`

payment_intent.payment_failed
`Occurs when a PaymentIntent has failed the attempt to create a payment method or a payment.`

I made a payment that failed and I received the following events:
-  charge.failed 
- payment_intent.created
- payment_intent.payment_failed

And my order was successfully updated to "failed".

So I think there's no issue here.

In the Slack thread, another issue with the same consequence (stuck to "Pending") was mentioned but it was related to trailing whitespace in the billing email address and this was fixed a few days ago in #4291 

Do we have a clear scenario to reproduce the described issue? @thisissandip 
Otherwise, I think we can close it.

**Comment by thisissandip** [comment] 2022-06-01 10:14
I created this issue based on the above slack discussion and experiencing the same on my test site (which had other plugins as well). 

In JN, I cannot reproduce this anymore just like @jessy-p 

I think it's safe to close this because we cannot reproduce it.

> We now have a mechanism (since early April I think) to store the failed webhooks and process them again later with a cron job, so I would assume the order would still update to a "failed" status, but with some delay in case the webhook could not reach the site.

Thanks for letting me know, I will let the merchants know of the same in case the status is not updated to "Failed" and will keep an eye out if I come across it again.

**Comment by jbordonado** [comment] 2022-06-02 08:15
Yes, please let us know if a similar issue happens again, we will take another look at this. Thanks!

**Closed by jbordonado** 2022-06-02 08:15 UTC
Labels: type: bug, needs feedback, category: core
