### ISSUE TITLE
StripeLink: Move billing email field to top

### ISSUE THREAD

**Issue by dpaun1985** [Automattic/woocommerce-payments#3842] opened 2022-02-23 14:33 UTC
### Description

When Link payment method is enabled, on checkout page, the billing email field should be displayed the first input field in the form.

Reference: #3702

**Comment by dpaun1985** [comment] 2022-02-23 14:34
blocked by #3802

**Comment by kalessil** [comment] 2022-04-29 07:31
@mordeth, is this duplicate of https://github.com/Automattic/woocommerce-payments/issues/3801 ?

**Comment by mordeth** [comment] 2022-04-29 07:33
> @mordeth, is this duplicate of #3801 ?

Yes, that one is a duplicate. Closing it.

**Closed** 2022-04-29 07:33 UTC
Labels: status: blocked, category: projects, component: stripe link
