### ISSUE TITLE
SPIKE: Split UPE <> WC Payments as a platform changes integration

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#5554] opened 2023-02-14 21:10 UTC
## Description

For background information: paJDYF-6ZK-p2

Test the changes between the Split UPE and the WooCommerce Payments as a Platform project, ensuring that there are no major surprises.

**Comment by timur27** [comment] 2023-02-20 11:46
Currently waiting for the latest conflicts to be resolved: p1676889735372369-slack-CGGCLBN58. 
I will start the testing right afterward.

**Comment by timur27** [comment] 2023-03-02 12:06
The changes from WCPay as a Platform phase 1 mainly touched the flows of payment/setup intent creation of the split UPE project. There was also a small change that caused a conflict and was resolved - `testMode` property, that is provided to JS scripts. Below are the results of my testing round. 


**UPE gateway**

:one: Creating a setup intent now uses the new `Create_And_Confirm_Setup_Intention::create()`, whereas `$this->payments_api_client->create_setup_intention` was used before the WCPay as a Platform.
* I went to the _Add payment method_ page and attempted to add a new card as a payment method. The flow ran successfully, `class-upe-payment-gateway.php` invoked `create_setup_intent_ajax`, which, in turn, invoked `Create_Setup_Intention::create();` and the whole process ended up successfully without any errors. ✅

:two: Creating a payment intent now uses `Create_Intention::create()`.
* The page has loaded without errors on the UI with the `create_payment_intent` method. I was able to proceed with the checkout by using a credit card. ✅
* When using any payment method other than the CC and authorizing it as a third party, I get the following error: `py_3MhAQvR3FtIp0bJN1nbngyUx is not a valid Stripe identifier` . If trying to pay once more with the same method, the checkout succeeds but it doesn’t even redirect to the test payment authorization page ❌


**Split UPE gateway**

:one: Creating setup intent works well for CC - I went to the My account and successfully added a new payment method. ✅
:two: Creating a payment intent
The page has loaded without errors on the UI with the `create_payment_intent` method. I was able to proceed with the checkout by using a credit card. ✅
I was also able to checkout with 3-4 different payment methods (giropay, Sofort, P24 and Bancontact) and the process went well. ✅

**Non-UPE**

:one: Setup intent - saved a new card on My account page successfully ✅
:two: Paid with the CC successfully ✅

**Other changes**

:one: `testMode` property, which is supplied for the UPE js scripts, is now provided by `WC_Payments::mode()->is_test();` instead of `$this->gateway->is_in_test_mode();`. It looks good since I can see the test message. ✅

More details on the error that was catched: 
> * When using any payment method other than the CC and authorizing it as a third party, I get the following error: `py_3MhAQvR3FtIp0bJN1nbngyUx is not a valid Stripe identifier` . If trying to pay once more with the same method, the checkout succeeds but it doesn’t even redirect to the test payment authorization page ❌


![image.png](https://images.zenhubusercontent.com/59de7a6cb0222d5de47b4727/004f9480-c276-4e90-a706-5866b11d81cd)


I am able to constantly reproduce it on `develop`, but at the same time, I can't reproduce it on `trunk`. I reverted WCPay as Platform commit on my local `develop` and the problem disappeared as well, but I'd like someone to confirm this, as my local became quite messy at that point due to some conflicts. 



@FangedParakeet @mdmoore this issue is no-code so there is no PR, but I'd like to ask someone of you to review my report above, try to reproduce the error I caught and perform another round of testing on your side to make sure there are no more issues.

**Comment by FangedParakeet** [comment] 2023-03-04 00:32
>When using any payment method other than the CC and authorizing it as a third party, I get the following error: py_3MhAQvR3FtIp0bJN1nbngyUx is not a valid Stripe identifier . If trying to pay once more with the same method, the checkout succeeds but it doesn’t even redirect to the test payment authorization page ❌

I wasn't able to replicate this, be that fortunate or unfortunate. I had a pretty comprehensive read through [the PR diff](https://github.com/Automattic/woocommerce-payments/pull/5321/files) and after double-checking the code, I couldn't really find anything greatly out of place. There hasn't been too much that has been moved around inexplicably and it does appear to me to be a pretty honest refactor.

The code-changes looked pretty good to me, incorporated our split UPE changes, and after running through the usual checkout flows using additional UPE payment methods in both shortcode and blocks I wasn't able to break anything! 

@timur27, can you give me more details on the error message you found? I'm not greatly familiar with that error message at all, so can't really diagnose on sight alone where it's coming from. I was just testing both the legacy and split UPE gateways on `develop` as well, so it's possible some newer change resolved the issues you were facing. Were you using a specific type of product, payment method, or checkout? Do let me know if I might be doing something improper in my own testing! @mdmoore, have you had any time to take a look at this? Perhaps you could be the tie-breaking vote in deciding whether there are any concerning issues with this WCPay refactor.

**Comment by timur27** [comment] 2023-03-06 11:45
Thanks, @FangedParakeet, for your tests! I was able to reproduce it once again on `develop` with the latest commit from today with a basic Beanie, below is the screen recording: 

https://images.zenhubusercontent.com/173384525/5e1a8a93-5516-45f7-940a-7b54bdf85e47/legacy_upe_checkout.mp4

The error happens [when getting a charge](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/core/server/request/class-get-charge.php#L27) after the payment has been authorized and the error is thrown [here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/core/server/class-request.php#L524-L531).

It seems that the payment intent [doesn't pass the pattern match here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/core/server/class-request.php#L518-L522), as the prefix used for charges, is `ch` and not `pi`. 

I didn't go deeper into the root cause and fix since I'd like to ensure it's a reproducible problem or it's just me who has some wrong assumption or broken setup. I hope this helps, and I agree with you that asking Mike to perform the test on his side would allow us to confirm or deny some of the theories here.

**Comment by FangedParakeet** [comment] 2023-03-06 23:18
Had to poke my nose around a few places, but I eventually found out that it seems GlobalStep encountered this issue as well in #5341. There's also a PR to fix it at #5358 that appears to have been approved and then abandoned. I think [this](https://github.com/Automattic/woocommerce-payments/pull/5358/commits/a7c687e00944dc909201d8b8d6b358b92960b508) is the relevant change that possibly fixes this problem. 

@timur27, can you try this out and let me know if it resolves the issue for you? If so, we can probably look to implement this change ourselves, if the aforementioned PR is indeed frozen in place.

**Comment by timur27** [comment] 2023-03-07 10:17
@FangedParakeet, thanks, I think we now have more data.

To reproduce the issue, one needs to ensure that the store and account currencies are different to cause the conversion of funds. In my case, I've had EUR in _My account -> Account details -> Default currency_ **vs** USD in _wp_admin -> WooCommerce -> Settings -> General -> Currency_ and perform an attempt to checkout with any of the UPE gateways. 

And yes, [the fix](https://github.com/Automattic/woocommerce-payments/pull/5358/commits/a7c687e00944dc909201d8b8d6b358b92960b508) helps.

Hey @RadoslavGeorgiev 👋🏼 Are there any plans to merge [this PR](https://github.com/Automattic/woocommerce-payments/pull/5358)? To be more precise, [these](https://github.com/Automattic/woocommerce-payments/pull/5358/commits/a7c687e00944dc909201d8b8d6b358b92960b508)|[two](https://github.com/Automattic/woocommerce-payments/pull/5358/commits/f03eb5df58c9a671980513b022a75446188cbf18) commits. When testing WCPay as a Platform <-> split UPE integration, we were able to reproduce [this issue](https://github.com/Automattic/woocommerce-payments/issues/5341). We can also raise a separate PR with this fix, but I wanted to confirm with you first if there were any reasons not to merge [this PR](https://github.com/Automattic/woocommerce-payments/pull/5358) yet, which we might be unaware of.

**Comment by RadoslavGeorgiev** [comment] 2023-03-07 11:28
Hey @timur27  and @FangedParakeet 👋 

Sorry for wasting your time with this. I opened the PR right before our meetup in January, and it was somehow forgotten. I'll fix the PR and merge it shortly.

It will fix the issue described in [this comment](#issuecomment-1451763076), and my testing instructions actually explain why @FangedParakeet was not able to reproduce it initially. Makes you wonder the issue was not reported again for more than two months by GS though :\

**Comment by timur27** [comment] 2023-03-07 11:35
@RadoslavGeorgiev Many thanks for such a quick response! It's great we are aligned now. The main reason I contacted you was to look for potential blockers, which could be why the PR was not merged.

That said, don't hesitate to contact us if any input from our side is needed - we're happy to help.

**Comment by RadoslavGeorgiev** [comment] 2023-03-07 12:14
Since you mentioned it, would you mind reviewing https://github.com/Automattic/woocommerce-payments/pull/5358? It's rebased on top of `develop` already, and another 🟢  would be welcome.

FWIW only now I realize that you had [linked this issue in Slack](p1676889735372369-slack-CGGCLBN58) when you started that thread, but I assumed it's here only to track effort. If you are testing in the context of another team's work, please don't hesitate to ping us in the description or some of the comments within the issue, so that we'd get updates. I would have noticed the root cause for the issue five days ago :)

**Comment by timur27** [comment] 2023-03-10 15:04
Another thing that was found and fixed (https://github.com/Automattic/woocommerce-payments/pull/5710) pretty quickly is the WooPay compatibility, which is not directly related to the split UPE but was encountered while managing the state of WCPay with the UPE feature flags.

I will perform another round of testing, and if I recall correctly, @FangedParakeet has such plans as well (but please let me know in case I misunderstood anything).

**Comment by FangedParakeet** [comment] 2023-03-10 23:43
I quickly ran through the usual testing flows for with the legacy, UPE, and split UPE checkouts enabled and wasn't able to uncover anything unusual on `develop` this time. @timur27, let me know if you are still having any issues, after the latest fixes have been merged--or if there's a particular area I should focus my testing on, if I'm missing anything. Cheers!

**Comment by timur27** [comment] 2023-03-17 16:04
I also ran through the usual testing flow and haven't found any error explicitly related to the WCPay as a Platform <-> split UPE work. However, [another issue](https://app.zenhub.com/workspaces/heisenberg-63586f2ec60359001310fa6a/issues/gh/automattic/woocommerce-payments/5808) was found on the _**Pay for order**_ page. It's not related to WCPay as a platform, hence I will be closing this issue.

**Closed as completed** 2023-03-17 16:05 UTC
Labels: type: bug, priority: high, category: core, type: spike
