### ISSUE TITLE
WC Payments setup: WCPayments screen empty state changes

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/woocommerce-payments#1436] opened 2021-03-26 15:15 UTC
**Description:** we're going to start testing some changes in the WCPayments screen empty state, in order to increase the conv. rate to the setup flow

![113186151-e85bc500-921c-11eb-9fef-e0ca07c68cbf](https://user-images.githubusercontent.com/3380168/113270544-7d1ffa80-92d1-11eb-8b7f-e359a63344f3.png)

**Acceptance criteria:**

- [ ] Change the empty state according to the mockup. The learn more link should open the following link in a new tab: https://woocommerce.com/payments/
- [ ] The "finish setup" CTA should redirect the user to the stepper flow: #1439

**Event tracking improvements:**
- Trigger a new `wcadmin_page_view` prop `path` value if the user visits the new welcome screen: `payments_connect_v2`
- Trigger a new event called `wcadmin_wcpay_welcome_finish_setup` when the user clicks "Finish setup"
Event prop: `wpcom_connection` : Yes|No  (identify if the store is already connected to wpcom)
- Trigger a new event called `wcadmin_wcpay_welcome_learn_more` when the user clicks "Learn more"

**Comment by psealock** [comment] 2021-03-29 01:04
Estimate: 2. There doesn't seem to be too much going on with this one, but maybe exiting the normal flow and returning again may incur some changes

**Comment by adrianduffell** [comment] 2021-03-30 03:48
Note: The video will need to be embedded without using woocommerce.com, to meet plugin review guidelines. This was a recent issue for WC Admin https://github.com/woocommerce/woocommerce-admin/issues/6479

**Comment by pmcpinto** [comment] 2021-03-30 09:12
> Note: The video will need to be embedded without using woocommerce.com, to meet plugin review guidelines. This was a recent issue for WC Admin woocommerce/woocommerce-admin#6479

Thanks Adrian. @elizaan36 considering the limitations that we have I'm wondering if we should consider a different approach Also based on Brent's feedback, we should try to avoid mentioning the pricing as this introduces a "maintenance tax" if pricing is updated. Especially now that we're going to have more countries.

**Comment by elizaan36** [comment] 2021-03-30 15:51
No problem, I understand the difficulties with including the video. (Don't want to get into that situation again!😆)

I have an alternative with no video.
![Payments welcome](https://user-images.githubusercontent.com/5121465/113018115-ce02e800-9145-11eb-91f2-eb8ce6ac8f8f.png)

In terms of the copy, I've just gone through and done a review of all the copy, incorporating some new copy from marketing. Let me know what you think.

**Comment by elizaan36** [comment] 2021-03-30 17:07
Here's an alternative that includes steps.

![Welcome screen with steps](https://user-images.githubusercontent.com/5121465/113028130-89c91500-9150-11eb-85cd-c21a157a3bf2.png)

**Comment by pmcpinto** [comment] 2021-03-31 11:24
Looks good to me and I like the alignment with what we have on the Payments task. Thanks!

**Comment by pmcpinto** [comment] 2021-04-01 09:30
@elizaan36 do you think it makes sense to have the "recommended" pill on the welcome screen?

**Comment by pmcpinto** [comment] 2021-04-01 09:35
@adrianduffell just a heads up that I updated the AC and event tracking list.

**Comment by adrianduffell** [comment] 2021-04-01 09:47
Thanks @pmcpinto !

It looks like we'll switch to the alternative design without video?

**Comment by pmcpinto** [comment] 2021-04-01 09:50
Yes. Trying to include video was going to complicate the implementation. We can try that later once we have the a/b test package in place to ship experiments.

**Comment by elizaan36** [comment] 2021-04-01 14:47
> @elizaan36 do you think it makes sense to have the "recommended" pill on the welcome screen?

It's fine either way but I think the recommended pill adds that extra little bit of reassurance.

**Comment by adrianduffell** [comment] 2021-04-05 23:02
I'm going to work on this as a priority this week.

@elizaan36 Do you have some ideas in mind for how this looks on a small sized screen?

**Comment by elizaan36** [comment] 2021-04-06 18:05
Thanks for bringing this up, Adrian - here's a layout for smaller screens. The payment methods and steps will wrap, and the text width will adjust based on the size of the card div. Let me know if you need any more details and I can share in Slack.

![Mobile WooCommerce Payments Welcome](https://user-images.githubusercontent.com/5121465/113757777-9f05ec80-96d8-11eb-9f18-0df663a4f6af.png)

**Comment by adrianduffell** [comment] 2021-04-07 03:07
Wonderful, thanks @elizaan36!

**Comment by adrianduffell** [comment] 2021-04-14 02:35
Just an update: this has taken a little longer than expected because presently the [WooCommerce Packages](https://github.com/woocommerce/woocommerce-admin/tree/main/packages) can't reliably be used in WC Pay. I have been working on some workarounds and should have a PR ready for this soon.

@elizaan36 Do you have a higher res version of the masthead graphics? (logo and the credit card/laptop)

**Comment by elizaan36** [comment] 2021-04-14 14:39
@adrianduffell, I exported the graphics to SVG for better resolution - let me know if you need any higher than what's [in this folder](https://share.getcloudapp.com/geub4lAj). 

Do you need the payment method icons as well? I'm using the ones from this community [Figma file](https://www.figma.com/file/nDsmR3Wzxwzzr43SsaixPG/Payment-Icon-Library-(Community)?node-id=0%3A1&viewport=-11%2C985%2C0.705683708190918) in the designs.

**Comment by adrianduffell** [comment] 2021-04-15 13:26
Thanks @elizaan36 the SVGs look perfect. 

For the payment method icons, I copied the ones added to WC Admin here https://github.com/woocommerce/woocommerce-admin/pull/6766.

**Comment by pmcpinto** [comment] 2021-04-20 16:23
@adrianduffell I just saw that this work was merged, but I want to double-check that this is not going to be shipped in WCPay 2.3, as we're going to a/b test this new screen #1612. And the a/b test probably is only ready for WCPay 2.4

**Comment by adrianduffell** [comment] 2021-04-21 05:45
@pmcpinto I don't think it will be shipped in 2.3 as this release was cut for testing before the merge.

 I've pinged WC Pay folks to confirm and will let you know.

**Comment by adrianduffell** [comment] 2021-04-21 08:32
@pmcpinto Confirmed, it won't be shipped in the 2.3 release 👍

**Comment by pmcpinto** [comment] 2021-04-21 13:43
👍 Thanks for the update!

**Comment by pmcpinto** [comment] 2021-04-22 14:27
@adrianduffell sorry, but we need to add the ToS message in the welcome screen before the "Finish setup" button: By clicking “Finish setup,” you agree to the [Terms of Service](https://wordpress.com/tos)

cc @elizaan36 to confirm the placement

**Comment by elizaan36** [comment] 2021-04-22 16:04
Here's the placement of the TOS. (You can ignore the preview button for now😆) Also, I've replaced the Maestro payment method with GPay in the icon list.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/5121465/115746905-5c8c1300-a35a-11eb-9077-df08bf809088.png">

**Comment by psealock** [comment] 2021-04-23 01:05
The same card used in WC Admin's payments task will be moved over to WC Pay in https://github.com/woocommerce/woocommerce-admin/issues/6850 as part of the effort to power payments tasks via remote config.

At first glance, these cards look identical or at least close enough for the code to be consolidated, so that will be a big win.

**Comment by adrianduffell** [comment] 2021-04-23 01:17
@pmcpinto  @elizaan36 Thanks! I'll work on these changes soon.

**Comment by adrianduffell** [comment] 2021-05-07 11:22
@elizaan36 Sorry I missed there was an icon change on this. Do you have the GPay icon as an SVG file?

**Comment by elizaan36** [comment] 2021-05-07 14:04
just commenting here that Adrian and I chatted in Slack and I shared the GPay icon. Also chatted about potentially replacing the banner artwork with new smaller marketing asset.

**Comment by adrianduffell** [comment] 2021-11-24 13:32
Closing, this was merged in PR https://github.com/Automattic/woocommerce-payments/pull/1746.

**Closed by adrianduffell** 2021-11-24 13:32 UTC
