### ISSUE TITLE
Investigate multiple intents/charge being added to an order

### ISSUE THREAD

**Issue by achyuthajoy** [Automattic/woocommerce-payments#4858] opened 2022-10-07 12:40 UTC
### Describe the bug

We've previously came across multiple cases where multiple intents were added to a order sometimes resulting in duplicate charges. The duplicate charges needed to be refunded manually from Stripe dashboard since the order meta saves only 1 charge id. More info regarding can be found in this p2 - paJDYF-4tz-p2#comment-14360

Reproducing this behavior is hard, but some discussions around this can be found here - p1664973279878509/1664952715.257719-slack-C01BPL3ALGP

### Expected behavior
Only 1 intent should be created for an order

**Comment by rafaelzaleski** [comment] 2022-10-25 19:20
Also reported on 5655361-zd-woothemes (p1666705102019619-slack-C7U3Y3VMY).

**Comment by csmcneill** [comment] 2022-11-02 23:06
Is this a duplicate of #3998 or do we need two separate issues?

If we need two separate issues, it may be best for us to differentiate between them with specific ways to identify whether an affected merchant interaction should be added here or on #3998.

**Comment by deepakpathania** [comment] 2022-11-23 11:57
Early investigation is done and we now have a P2 paJDYF-6wC-p2 with all the details, a project thread will be created to look into the suggested solutions which @htdat will lead, so closing this in favor of that.

**Closed as completed by deepakpathania** 2022-11-23 11:57 UTC
Labels: type: bug, component: checkout, category: core
