### ISSUE TITLE
Avoid console logging "Your card number is incomplete."

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#485] opened 2020-02-27 18:46 UTC
If you click Place Order without giving credit card details we do display an error to the buyer, but there is also a console message we could handle better.

<img width="1425" alt="Screen Shot 2020-02-27 at 10 43 46 AM" src="https://user-images.githubusercontent.com/1595739/75475910-82807800-594e-11ea-8f46-22ff136d1994.png">

Low priority at this point. No order is created.

```
Uncaught (in promise) {code: "incomplete_number", type: "validation_error", message: "Your card number is incomplete."}
```

Props @DustinHartzler

**Comment by KarlisJ** [comment] 2021-11-10 07:55
Can't reproduce the issue anymore. It's been 20 months and the log has been removed at some point. Closing the issue.

**Closed by KarlisJ** 2021-11-10 07:55 UTC
Labels: good first issue, priority: low

**Comment by kalessil** [comment] 2021-11-10 08:04
Great, thanks for looking into it @KarlisJ !
