### ISSUE TITLE
Re-onboarding after disabling Dev Mode

### ISSUE THREAD

**Issue by thenbrent** [Automattic/woocommerce-payments#666] opened 2020-05-19 01:39 UTC
A question that came up in a [recent review](https://github.com/Automattic/woocommerce-payments/pull/660#discussion_r426795983): _can a store re-onboard without issues after disabling Dev Mode_?

Right now, in the readme and [Dev Mode doc](https://docs.woocommerce.com/document/payments/testing/dev-mode/), we recommend only using Dev Mode on a store _that will **never need to process real payments**_.

If a store can onboard a live account after disabling Dev Mode without any negative side effects, we could expand that recommendation.

**Comment by LevinMedia** [comment] 2022-01-28 21:41
@dechov @thenbrent Would it be possible to have a "Delete account" feature in dev mode, so that when a developer is done testing, they could destroy their test account and have a merchant re-onboard using their own details?

**Comment by thenbrent** [comment] 2022-01-31 05:57
Great discussion related to this here: p1643413022442609-slack-CGGCLBN58

**Comment by daquinons** [comment] 2022-11-04 18:02
> Haven't tested this myself, but the "dev to live" case is currently coded as an explicit exception to the rule that prevents re-onboarding, as described in #301.

According to this, it should already be possible to reonboard from dev to live. This issue is about testing that case, and if it's working without any additional change, to modify [the doc](https://docs.woocommerce.com/document/payments/testing/dev-mode/) to make this possibility explicit in them with the help of Payments Ops

**Comment by brandonwanA8C** [comment] 2022-11-08 00:03
I don't have or know the original "requirement for Dev Mode".
But from a Product's perspective, the "Dev Mode" use-case is to allow a user (eg. Builder) to TEST the end-to-end Store to Payments experience without having to use Real KYC info or Real money.

**Comment by dmallory42** [comment] 2022-12-01 14:19
I did some testing on this and I can confirm the current behaviour is as follows:

- After onboarding a new account in dev mode (this used test mode in Stripe Onboarding, as we'd expect), I turned dev mode off.
- When I went back to WCPay, I was taken back to the onboarding screen. 
- This time, when I tried to onboard I needed to use real account details. But everything worked fine.

This seems to be the expected/desired behaviour. Do we think we need to make any modification to the documentation? It does seem to have a [section](https://woocommerce.com/document/woocommerce-payments/testing-and-troubleshooting/testing/dev-mode/#disabling-dev-mode) which discusses this case although perhaps we could make it a bit more transparent.

**Comment by dmallory42** [comment] 2022-12-02 15:16
This was discussed furhter on Slack and a few changes were made to the documentation (p1669982063477309-slack-C03EE4CPPK5).

Closing this issue since it seems to be working as expected.

**Closed by dmallory42** 2022-12-02 15:16 UTC
Labels: type: question, priority: low, needs design, needs feedback, component: onboarding
