### ISSUE TITLE
Call to a member function is_stripe_account_valid() on null

### ISSUE THREAD

**Issue by PrinceOfAbyss** [Automattic/woocommerce-payments#7109] opened 2023-09-01 11:58 UTC
### Describe the bug
Plugin was automatically updated to v6.4.0 yesterday, and the e-shop went down due to a `PHP Fatal error:  Uncaught Error: Call to a member function is_stripe_account_valid() on null`

### To Reproduce
No special steps needed...

### Actual behavior
Technically, the code in `woocommerce-payments/includes/class-wc-payments-tasks.php`, at line 33

		if ( ! WC_Payments::get_account_service()->is_stripe_account_valid() ) {
			return;
		}

causes the bug because `WC_Payments::get_account_service()` isn't initialized in the e-shop. You must first perform a check whether the stripe service is inited.

		if ( WC_Payments::get_account_service() && ! WC_Payments::get_account_service()->is_stripe_account_valid() ) {
			return;
		}

The above would suffice in preventing the bug from occurring.

### Screenshots
Not needed

### Expected behavior
Obvious.

### Desktop (please complete the following information):
Not relevant

### Smartphone (please complete the following information):
Not relevant

### Additional context
N/A

**Comment by csmcneill** [comment] 2023-09-03 15:47
Flagging this to @Jinksi and @shendy-a8c as https://github.com/Automattic/woocommerce-payments/commit/900951661b877a04f8643596e1adf2fa1b69badf was added by y'all on 18 August.

**Comment by Jinksi** [comment] 2023-09-03 21:01
@Automattic/helix Since this causes a fatal, I've marked this as critical.

**Comment by shendy-a8c** [comment] 2023-09-04 04:37
@PrinceOfAbyss thank you for reporting.

I'm still not sure how to reproduce the fatal error because I see that [account service is initialized](https://github.com/Automattic/woocommerce-payments/blob/4db41815253e4afdc5a86e9650db88624874f8ff/includes/class-wc-payments.php#L474) before [we its `is_stripe_account_valid()`](https://github.com/Automattic/woocommerce-payments/blob/4db41815253e4afdc5a86e9650db88624874f8ff/includes/class-wc-payments-tasks.php#L33). I also tried with a clean site install and did not observe the fatal error.

Anyway, it's an easy fix to be more defensive about it, so I opened https://github.com/Automattic/woocommerce-payments/pull/7116.

It's just helpful to understand what we overlooked.

When you said 'e-shop', you're referring to a regular site with WordPress, WooCommerce, and WooPayments installed right? May I know the version of the installed WordPress, WooCommerce, and Jetpack (if installed)?

**Comment by csmcneill** [comment] 2023-09-04 05:08
Hey @shendy-a8c! We saw this in 6757989-zen —here's a stack trace:

```
2023-08-31T23:57:11+00:00 CRITICAL Uncaught Error: Call to a member function is_stripe_account_valid() on null in /[REDACTED]/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-tasks.php:33
Stack trace:
#0 /[REDACTED]/wp-includes/class-wp-hook.php(308): WC_Payments_Tasks::add_task_disputes_need_response()
#1 /[REDACTED]/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#2 /[REDACTED]/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /[REDACTED]/wp-settings.php(623): do_action()
#4 /[REDACTED]/wp-config.php(90): require_once('/[REDACTED]/...')
#5 /[REDACTED]/wp-load.php(50): require_once('/[REDACTED]/...')
#6 /[REDACTED]/wp-blog-header.php(13): require_once('/[REDACTED]/...')
in /[REDACTED]/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-tasks.php on line 33
```

When they joined, they were running:
- Woo 8.0.3
- WP 6.2.2
- WooPayments 6.4.0

I tried rolling back to WP 6.2.2 on a test site and updating to WooPayments 6.4.0, but I was unable to reproduce the issue.

**Comment by PrinceOfAbyss** [comment] 2023-09-04 09:52
Thanks for the quick reply!

@shendy-a8c the versions are:

WooCommerce version: 7.7.0
WordPress version: 6.2.2
Jetpack: 12.1.1
PHP version: 8.0.28

The error log @csmcneill pasted above, is exactly the one I'm getting.

Should you require any more info about the website's specs, please do let me know.

**Comment by kaushikasomaiya** [comment] 2023-09-04 14:32
I've a bit different version:

```
Error Details
=============
An error of type E_ERROR was caused in line 179 of the file public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-checkout.php. 
Error message: Uncaught Error: Call to a member function should_use_stripe_platform_on_checkout_page() on null in public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-checkout.php:179
Stack trace:
#0 public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-upe-checkout.php(146): WCPay\WC_Payments_Checkout->get_payment_fields_js_config()
#1 public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-blocks-payment-method.php(101): WCPay\WC_Payments_UPE_Checkout->get_payment_fields_js_config()
#2 public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/PaymentMethodRegistry.php(62): WC_Payments_Blocks_Payment_Method->get_payment_method_data()
#3 public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/Api.php(93): Automattic\WooCommerce\Blocks\Payments\PaymentMethodRegistry->get_all_registered_script_data()
#4 public_html/wp-includes/class-wp-hook.php(310): Automattic\WooCommerce\Blocks\Payments\Api->add_payment_method_script_data()
#5 public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#6 public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/MiniCart.php(200): do_action()
#8 public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/AbstractBlock.php(100): Automattic\WooCommerce\Blocks\BlockTypes\MiniCart->enqueue_data()
#9 public_html/wp-includes/class-wp-hook.php(310): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->enqueue_editor_assets()
#10 public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#11 public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#12 public_html/wp-admin/edit-form-blocks.php(272): do_action()
#13 public_html/wp-admin/post.php(187): require('/home/u70418726...')
#14 {main}
  thrown
```

6705304-zen

I'll check more and get back with my findings soon.

**Comment by grig-23** [comment] 2023-09-04 15:31
Another one here:

6757289-zen

**Comment by shendy-a8c** [comment] 2023-09-05 04:57
@kaushikasomaiya likely 6705304-zd-a8c is a different problem. Please create a separate issue for it.

**Comment by kaushikasomaiya** [comment] 2023-09-05 06:56
A separate issue has been created here: https://github.com/Automattic/woocommerce-payments/issues/7128

**Comment by Brianmitchtay** [comment] 2023-09-06 01:05
6774723-zen

**Comment by shendy-a8c** [comment] 2023-09-06 05:35
Closing this issue as https://github.com/Automattic/woocommerce-payments/pull/7116 has been merged.

**Closed as completed by shendy-a8c** 2023-09-06 05:35 UTC
Labels: type: bug, priority: critical, status: has pr, component: disputes
