### ISSUE TITLE
Purchase attempts that fail due to an Advanced Fraud rule, create an order with a "Pending" status

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#8353] opened 2024-03-08 01:33 UTC
### Describe the bug
Purchase attempts that fail due to an Advanced Fraud rule, create an order with a "Pending" status. The impact is that there's an order stream of failed transactions intermixing with legitimate pending orders and it pollutes data reporting.

### To Reproduce
1. Enable Advanced Fraud and enable a rule IP Mismatch
2. VPN into a mismatched region
3. Shop and put a simple product into the cart
4. Checkout and place the order
5. Observe the order failed for the shopper
6. In the Merchant Order, note the order note that the transaction failed due to a fraud rule
7. In the Merchant Order note that the Order status is set to "Pending"

![uuRhal.png](https://github.com/Automattic/woocommerce-payments/assets/109928953/04e3faa8-5ab4-41c0-9577-64255a623686)

### Expected behavior
Given issuer declines and Stripe Radar fraud declines result in a "Failed" order status, IMO I would expect the same treatment. This needs to be confirmed.

**Comment by pierorocca** [comment] 2024-03-08 01:44
cc @malithsen for awareness only.

**Comment by malithsen** [comment] 2024-03-08 10:11
Related https://github.com/Automattic/woocommerce-payments-server/issues/4008

**Comment by vbelolapotkov** [comment] 2024-03-08 10:29
Closing this one, because it's expected behavior - a blocked transaction doesn't fail the order, but allows a shopper to try other payment instrument. `Pending payment` is correct order status for such cases - https://woo.com/document/managing-orders/

Confirmed with engineering team: p1709893038744239/1709861937.842109-slack-CGGCLBN58

**Closed as completed by vbelolapotkov** 2024-03-08 10:29 UTC
Labels: type: bug, impact: high, component: fraud & risk tools, focus: fraud tools

**Comment by pierorocca** [comment] 2024-03-08 19:18
> Closing this one, because it's expected behavior - a blocked transaction doesn't fail the order, but allows a shopper to try other payment instrument. Pending payment is correct order status for such cases - https://woo.com/document/managing-orders/

I would appreciate mutual confirmation before closing in the future @vbelolapotkov. 

I don't agree with this assessment for multiple reasons. 

1. Following this logic then ALL orders would be put into "pending payment" status because I could try every payment method sequentially or I could continue to try different credit and debit cards until I run out. Also when there's a risk related failure, error messages are purposefully vague to not tip off fraudsters. So the shopper isn't put in a position of clarity to try again.

2. This use case does not fit into the definition linked. 

"Pending payment — Order received, no payment initiated. Awaiting payment (unpaid)." - A payment method was provided by the shopper and the payment was "initiated" and it failed. To understand why the payment was "initiated" you need to understand the full flow of payments pre-authorization and post-authorization fraud checks.

Roughly the fraud and risk steps done in a typical transaction are:

1. WooPayments **pre-auth** fraud & risk checks & SIFT scoring
2. Stripe **pre-auth** fraud & risk checks (Radar)
3. Issuer fraud checks and **auth** response (decline or approve + useful metadata e.g. approved but zip didn't match). This could also include a 3DS check (SCA) within the auth flow where the user is forced to validate identity.
4. Stripe **post-auth** fraud & risk checks (Radar - they may decide to decline an issuer approved transaction to limit risk)
5. WooPayments **post-auth** fraud & risk checks

2-4 is combined in the auth response message we get from Stripe.

1 & 5 are related to the new WooPayments Advanced fraud rules.

- AVS Mismatch - post-auth
- International IP Address - pre-auth
- IP Address Mismatch - pre-auth
- Address Mismatch (shipping and billing comparison) - pre-auth
- Purchase Price Threshold - pre-auth
- Order Items Threshold - pre-auth
- CVC Verification - post-auth

e.g. if the order item threshold is 5 and a shopper tries to purchase 10, it makes no sense to create the order for 10 and place it into "Payment pending". It should fail and no order created.

e.g. If I'm in Nigeria and the merchant only allows purchases from shoppers in the US, creating the order and setting "Pending payments" again makes no sense. There's no path to resolving the order with that rule in place.

e.g. If I place an order for $1000 and the Purchase Price Threshold is $500, same as above "Pending Payment" does not fit the use case as I can never provide a payment method that will resolve the order as long as the rule is in place.

e.g. If the authorization passed, i.e. payment auth was initiated and returned an approved response, but the CVC did not match and the advanced rule rejected the order, does it make sense to create the order and mark it "Pending Payment"? Payment was initiated so it doesn't fit the definition. In this exact scenario if the bank or Stripe declines because of a CVC mismatch, why would it get different treatment?

Pending Payment is best reserved for use cases like invoiced orders, split payments, pre-orders, deposits, where the shopper has not truly tried to initiate a payment or has only made a partial payment and there's an outstanding balance.

Let's re-open this please to further discuss and can move it to P2 as an RFC as needed.

**Comment by vbelolapotkov** [comment] 2024-03-11 10:16
@pierorocca, thanks for all the details and comments. I don't think I'm the right person to comment on those though.
So I'd suggest discussing it with @mjdeacon and/or the rest of the product team. Once there is a clear decision on what's the expected behavior we'll be able to implement the changes, until then I'd prefer keeping the issue closed, because it's not a bug, but expected behavior of a product.
