### ISSUE TITLE
Refund not possible if order status manually changed to Processing/Completed prior to 'Capture'

### ISSUE THREAD

**Issue by jrick1229** [Automattic/woocommerce-payments#5671] opened 2023-03-06 14:41 UTC
### Describe the bug

If an 'Authorized' order is set manually to 'Processing' or 'Completed' prior to capture, _then_ is captured, the order is never updated to reflect the actual capture. This causes issues with refunds, since the order is now not refundable (as it doesn't believe payment was captured).

### To Reproduce

1. Set WC Pay to authorize
2. Purchase a product
3. Set the 'On hold' order to 'Processing' or 'Completed'
4. Save changes
5. Navigate to WP Admin > Payments > Transactions > Uncaptured, and capture the order. 
6. Note paid status, then navigate back to the order
7. Notice there are no notes pertaining to the capture
8. Click 'Refund' and try to refund the order
9. See that the notice instructs you to first capture the payment, which was already done

### Actual behavior

Payment captured, order is Processing, cannot refund

### Expected behavior

Payment is captured, very specific steps shouldn't be needed to simply refund an order

### Additional context

6000094-zen

**Comment by htdat** [comment] 2023-03-07 02:30
Thanks for the report @jrick1229. I can replicate the bug.

According to Pc2DNy-3z-p2, this falls in @Automattic/pulsar (Auth and Capture). Tagging as a part of Gamma Porter duties PcreKM-yM-p2.

**Comment by htdat** [comment] 2023-03-07 02:31
However, this seems relevant to this issue being worked on by @jessy-p 
https://github.com/Automattic/woocommerce-payments/issues/5603

**Comment by jessy-p** [comment] 2023-03-09 07:41
@htdat  This issue is not related to the Confirmation modal. It is related to the order not getting captured correctly if the status is changed in between manually. I am not sure if the solution should be to prevent changing the status (we have never really done that, these modals are  just giving a warning to the merchant) or allowing the order to be captured correctly, but I prefer the latter. We can check with Product team.

**Comment by htdat** [comment] 2023-03-09 07:46
@jessy-p - your last comment makes sense. Let's leave it for Pulsar then they can decide how to approach the issue, or check with Product team.

**Comment by jessy-p** [comment] 2023-03-10 03:20
I think this new issue might take care of this: #5712

**Comment by htdat** [comment] 2023-03-10 05:56
> I think this new issue might take care of this: https://github.com/Automattic/woocommerce-payments/issues/5712

I am closing this issue as it should be handled in https://github.com/Automattic/woocommerce-payments/issues/5712, especially this part: 

> Changing the status of an authed order to Completed should offer to capture the funds.

**Comment by csmcneill** [comment] 2024-05-15 03:54
Reopening since this was reported in 8192646-zen (further discussion in p1715743396825929-slack-C3NCP7ZJ6)

To reproduce:
1. Place an order while auth + capture is enabled.
2. Change the order status to `Processing` before capturing by either editing the order or bulk editing order statuses.
3. Capture the order from Payments > Transactions > Uncaptured.
4. Try to refund the order from Order details page.
5. See an error:
![CleanShot 2024-05-14 at 22 57 45](https://github.com/Automattic/woocommerce-payments/assets/82999806/80e1cb76-314c-4aa4-b371-a25a0d9904fe)

**Comment by vbelolapotkov** [comment] 2024-06-19 13:27
@deepakpathania routing this one to your team for further investigation and prioritization.

**Comment by RadoslavGeorgiev** [comment] 2024-12-09 14:21
I used the testing instructions from https://github.com/Automattic/woocommerce-payments/issues/5671#issuecomment-2111532300, and managed to reproduce this issue **once**. I tried to understand what's going on, as it seems that the intention status meta of the order is not being updated:

https://github.com/Automattic/woocommerce-payments/blob/737aca04b36720ca54acb7377c65e954dba5c0de/includes/class-wc-payments-order-service.php#L1135

AFAICT, there is no reason for that line to not be reached within an error-free request. However, somehow the meta still indicated an order that is pending capture.

I only did this as a quick investigation while prioritizing issues, and I'm assigning this one a Medium priority. We will need to dig deeper.

**Closed as completed** 2024-12-13 12:51 UTC
Labels: type: bug, category: core, component: authorizations, focus: payments acceptance & processing
