### ISSUE TITLE
Retrying a refund after a failed refund doesn't work

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#2286] opened 2021-06-21 19:25 UTC
When you try refunding an order after a previous refund attempt failed, you get an error from Stripe saying:

> Error: A previous attempt to refund `ch_xxx` to card `card_xxx` failed

This error shouldn't happen. I'm not sure why it happens, but I imagine it has something to do with us possibly trying to use the same refund ID twice? Or maybe we have to delete the failed Stripe refund before we retry a refund?

Aside from that the notice is also sort of useless. It let's the merchant know that something is wrong, but they have no way to fix the issue.

> I did notice another (potential) issue while testing the new changes; if you retry a refund via WCPay after the first refund failed you get this error:
>
> <img width="657" alt="image" src="https://user-images.githubusercontent.com/13835680/122612311-6ee0af80-d072-11eb-9d26-3770c5b63034.png">
>
> I'm not sure if this is just an issue with the test card (which is always supposed to fail a refund) or if we have to somehow clear the failed refund before attempting another refund.
>
> _Originally posted by @reykjalin in https://github.com/Automattic/woocommerce-payments/pull/2167#issuecomment-864256466_

## Reproduction steps

1. Make a purchase with test card `4000 0000 0000 5126`.
2. Navigate to the order screen and click **Refund** to display the refund bar.
3. Attempt a refund through WCPay; notice it's "successful", but fails via webhook.
4. Reload the page
5. Attempt another refund through WCPay; note that you'll see the alert from the screenshot pop up.

**Comment by vbelolapotkov** [comment] 2021-12-21 13:24
duplicate of #2285

**Closed by vbelolapotkov** 2021-12-21 13:24 UTC
Labels: type: bug, good first issue, priority: high, size: medium, category: core
