### ISSUE TITLE
Capital Loan offer's expired link redirects the user to a Jetpack page without any other info.

### ISSUE THREAD

**Issue by zoupkat** [Automattic/woocommerce-payments#9257] opened 2024-08-13 20:41 UTC
When a user is trying to access the link to a Capital Loan offer that has expired, it is not clear to them that the offer has expired and what that means (for example, will they be getting more offers in the future?) -- the link just points the user back to a Jetpack page which is confusing.

The ideal thing would be for the user to be redirected to a page where they can see that the offer has expired and it would also be useful if it lets the user know about the possibility of future opportunities.

_For Automattic Employees Only:_
One report about this came through 8600598-zen
An internal discussion p1723555345318009-slack-C05QSQ0GT0U about this resulted to this bug report.

**Comment by vbelolapotkov** [comment] 2024-08-14 06:11
Thanks for reporting @zoupkat. Personally, I'd treat it as an enhancement in the flow, rather than a bug, but will let the experts to decide on it. @souravdebnath1986 @haszari sending it to you for assessment and prioritization.

**Comment by zoupkat** [comment] 2024-08-14 12:27
Thanks for taking a look @vbelolapotkov !
Doug in the internal discussion link mentioned: "I'd actually open as a bug report since it's a bug that we're not letting the merchant know it's expired". I personally agree with that since the link should at least give the merchant a heads up that the offer has expired. Otherwise, the merchant assumes (rightfully so) that the link is just not working.
That is the reason why we went with marking it as a bug.
IMHO, the experts should consider making it work so that it is clearly stated that the link has expired and to also include the reply to one of the [FAQs here](https://woocommerce.com/woocommerce-stripe-capital/): "If you have additional questions about how the financing program through WooPayments + Stripe Capital works, you can contact our partners at capital-support@stripe.com"

**Comment by nagpai** [comment] 2024-12-03 07:07
I did a quick test using my test site that is currently onboarded on a live account in sandbox mode.  I am not able to replicate the situation where I see a Jetpack page. It looks like an edge case and would be good to capture more reports of similar issues.  More details below: 

1. An offer was created and then expired for my test site.
2. The CTA URL is a click analytics wraparound to the actual landing URL. It should essentially register the click and redirect the URL to the landing link - https://website.com/wp-admin/admin.php?wcpay-loan-offer 

3. This lead to `https://<my website>.com/wp-admin/admin.php?wcpay-loan-offer
4. If I am not signed in, I am shown the wp admin page. If I am signed in, it redirects to a Stripe connect hosted page that my account is not eligible for loan 

<img src="https://github.com/user-attachments/assets/3d0b8981-a295-4fd6-8de5-9f1df032c395" width="500px" />

The message should ideally mention that the offer has expired. This was a forced test, and I will do a separate check with an offer that is allowed to expire on its own. 

I also tried clicking the CTA button on the loan offer emails in Zendesk of a few other live accounts. It leads me successfully to the WP Admin login of that particular site. 


#### Now back to our reported user's issue. 

1. The CTA link on their email is similar to what I had 

2. On clicking or copy-pasting in browser, instead of leading to the WP admin login page, it redirects to https://wordpress.com homepage . If I am already logged in to WordPress.com, it takes me to https://wordpress.com/sites . This indicates some likely issue with Jetpack for the site, where it is probably recognized as a WPcom hosted site (?) .. guessing. 

4. Not sure how much this has a bearing but if I search jetpack debug for `<their-site-address>.com` , there is no site found. However if I check - `www.<their-site-address>.com` , we do see the site! The network admin of the site too shows the URL as `https://www.<their-site-address>.com`.  Maybe disconnecting and reconnecting with the correct URL may help?

**Comment by nagpai** [comment] 2024-12-03 07:15
As a long term solution, we may want to explore showing loan offers within `Payments > Capital Loans`, instead of redirecting users upfront to Stripe connect hosted page.

**Comment by haszari** [comment] 2024-12-03 19:33
Thanks for investigating @nagpai . If this is not reproducible, perhaps we can close (and listen out for any new reports that might come up.

**Comment by nagpai** [comment] 2024-12-04 15:02
Thanks @haszari . I will close the issue for now. It can be reopened if we have more user reports.

**Closed as not planned by nagpai** 2024-12-04 15:02 UTC
Labels: type: bug, priority: medium, focus: capital
