### ISSUE TITLE
Decimal separator problem with multi-currency

### ISSUE THREAD

**Issue by rashedripon** [Automattic/woocommerce-payments#4277] opened 2022-05-19 15:39 UTC
### Describe the bug

When multi-currency is enabled, the decimal value is added automatically in the order values in wp-admin. This creates confusion in a currency like MOP as it wrongly shows `,` in wp-admin order pages but the emails show it differently.

### To Reproduce

1. Set the decimal value in WooCommerce settings to `0`
2. Change the site's default currency to "Macanese Pataca" (MOP)
3. Enable multi-currency in **Payments > Settings** page.
4. Create an order with a product that has a value over `1000` i.e. 1355 while being in MOP currency
5. Check the value of the order in **WooCommerce > Orders** and in the new order email
6. See the difference after deactivating multi-currency in WooCommerce Payments

### Screenshots

On the checkout page:

![If this image fails to load, please visit:](https://d.pr/i/svZUNu+)
Image Link: https://d.pr/i/svZUNu

In email:

![If this image fails to load, please visit:](https://d.pr/i/69M27m+)
Image Link: https://d.pr/i/69M27m

On **wp-admin > WooCommerce > Orders**: notice the decimal separator

![If this image fails to load, please visit:](https://d.pr/i/zamHG3+)
Image Link: https://d.pr/i/zamHG3

On the My Account page:

![If this image fails to load, please visit:](https://d.pr/i/4EVLUO+)
Image Link: https://d.pr/i/4EVLUO

### Actual behavior

When multi-currency is disabled all values show properly:

![If this image fails to load, please visit:](https://d.pr/i/facteV+)
Image Link: https://d.pr/i/facteV

### Expected behavior

A decimal separator should not be added automatically when the decimal value is set to `0` or show it correctly when multi-currency is enabled

### Desktop (please complete the following information):

* Chrome 101 on macOS (Catalina)

### Additional context

Could be related to this report: https://github.com/Automattic/woocommerce-payments/issues/3859

First reported in 5224157-zen

**Comment by ismaeldcom** [comment] 2022-05-27 09:25
I'm trying to determine whether this is a bug. According to our Multi-Currency guidelines (paJDYF-20W-p2) and AFAIK, for the backed we should use the store currency formatting, overriding what's selected in WC Settings (that are intended for the fronted).

We're using WC [currency](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/i18n/currency-info.php) and [locale](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/i18n/locale-info.php) info, and looking at `MOP` there are 2 locales (pt_MO and zh_Hant_MO) plus the default one. The issue here is that, at least I've couldn't find, a way to select `zh_Hant_Mo` as local in WP through the admin area. Although we could enable it defining `WPLANG` in code or DB. So it falls back to default that has [these settings](https://github.com/woocommerce/woocommerce/blob/0f0b2d5064079429f30e52335b66c91fcf081d44/plugins/woocommerce/i18n/currency-info.php#L90-L95) And while using `zh_Hant_Mo`, we get [these settings](https://github.com/woocommerce/woocommerce/blob/0f0b2d5064079429f30e52335b66c91fcf081d44/plugins/woocommerce/i18n/currency-info.php#L66-L71).

The only difference after enabling it manually, is that it will still have 2 decimal places. I wonder if we should consider honoring the WC currency settings for the backend 🤔 

cc @Automattic/sigma

**Comment by tpaksu** [comment] 2022-05-27 09:48
I agree with @ismaeldcom and add some extra context, MC in backend (wp-admin) uses the currency settings for Stripe account currency to keep the visual consistency. It doesn't matter what currency the order is paid with, if Stripe currency is USD, all the currency presentations will use the settings for USD (decimal separator, thousands separator, decimal digits count, symbol direction).

Part from paJDYF-20W-p2:

> In the merchant’s admin we should always render non-store currencies using the story currency format. This will help a merchant scan and comprehend prices more quickly by displaying them in the format they’re most familiar with. It will also create consistency when viewing currencies with different formats.

**Comment by ismaeldcom** [comment] 2022-07-12 07:53
Closing it for now, as it's the expected behavior with our current guidelines (paJDYF-20W-p2) and WC locales.

**Closed by ismaeldcom** 2022-07-12 07:53 UTC
Labels: type: bug, component: customer multi-currency, category: core
