### ISSUE TITLE
Payment Request button + Block checkout compatibility with 3D Secure cards

### ISSUE THREAD

**Issue by ricardo** [Automattic/woocommerce-payments#1544] opened 2021-04-10 00:49 UTC
Implement compatibility with Payment Request buttons + 3D Secure cards in the block checkout.

**Comment by kalessil** [comment] 2021-04-10 07:06
Seems to be a duplicate of #1330.

**Comment by ricardo** [comment] 2021-04-11 21:27
@kalessil, It is. Thanks for flagging! I've looked for the issue but didn't find.

I'll repurpose this issue to fix 3DS compatibility for Payment Request Buttons + Block checkout.

**Closed** 2021-05-06 16:35 UTC
Labels: component: payment request button, priority: high
