### ISSUE TITLE
Subscription payment method cannot be changed to the saved card

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/woocommerce-payments#1185] opened 2020-12-25 14:23 UTC
To reproduce:

1. Purchase subscription product.
2. Go to My account > Add one more payment method.
3. Go to My account > Subscription > Purchased subscription.
4. Try to change payment method to saved on step 2. 
5. Success message is displayed but payment method is not changed.

@luizreis made some good assumptions in the https://github.com/Automattic/woocommerce-payments/pull/1148#issuecomment-750410406

TODO: 

- [ ] Fix the issue
- [ ] Cover with unit/integration tests
- [ ] Add E2E test

**Comment by shendy-a8c** [comment] 2021-02-05 12:23
@vbelolapotkov, for E2E test, do we need to install woocommerce-subscriptions in the environment?
 Would that require 1 more environment parameter that holds the repo of woocommerce-subscriptions similar to `WCP_DEV_TOOLS_REPO`? If so, need to change GH Action as well.
 Or is there any other simpler way?

**Comment by vbelolapotkov** [comment] 2021-02-05 15:56
Let's do two things here: 

1. Move e2e test into own issue.
2. We should be able to install subs plugin from setup script, [like this](https://github.com/Automattic/woocommerce-payments/blob/be5c9193730ba603f03b525e9663fe1d80f96db3/tests/e2e/env/setup.sh#L155-L155). Or if it doesn't work we'll find another way to install it but I'd use subs repo as a last resort measure.

**Comment by shendy-a8c** [comment] 2021-02-05 19:12
Cool. I suspected we could do that but not sure and didn't try because the plugin we're talking about is a paid one.

Created: https://github.com/Automattic/woocommerce-payments/issues/1296

**Comment by luizreis** [comment] 2021-02-11 12:49
I think this bug might be affecting more than just the subscription payment method changes. I tried to purchase a free trial subscription using a saved card, and it could not be renewed. The error was `There is no saved payment token for order #159` and it also happened after applying #1288.

At this point, I'm wondering whether [removing the early return statement](https://github.com/Automattic/woocommerce-payments/blob/master/includes/class-wc-payment-gateway-wcpay.php#L558-L561) that introduced this bug wouldn't be a simpler fix until the more robust changes are addressed in #1289 and #1293.

cc @kalessil - as you're reviewing #1288

**Closed** 2021-02-18 13:59 UTC
Labels: Priority: High, Size S, [Feature] Saved Cards and Subscriptions, [Type] Bug

**Comment by shendy-a8c** [comment] 2021-03-12 07:12
@luizreis, you're right. I didn't end up just [removing the early return statement](https://github.com/Automattic/woocommerce-payments/blob/master/includes/class-wc-payment-gateway-wcpay.php#L558-L561) as there is [more to it to be done](https://github.com/Automattic/woocommerce-payments/pull/1199).

> I tried to purchase a free trial subscription using a saved card, and it could not be renewed. The error was There is no saved payment token for order #159 and it also happened after applying #1288.
Did you create an issue for error? If not, I can, but could you let me know the steps to reproduce the problem?

**Comment by luizreis** [comment] 2021-03-18 16:29
> Did you create an issue for error? If not, I can, but could you let me know the steps to reproduce the problem?

Hey @shendy-a8c, I haven't yet. If you wouldn't mind creating it, the reproduction steps are:

1. Add a card to the customer using the My Account page, or saving it during a regular purchase
2. Create a Subscription with a free trial, which is processed as a $0 order, and use the saved card to pay for it
3. Using the My subscriptions page or the admin subscription view, process an early renewal of that subscription
4. The renewal should fail with a `There is no saved payment token for order` as the token was not added to the subscription order during checkout, which happens because the payment method doesn't have to be saved and the order doesn't have to be paid

Let me know if you're not able to reproduce it or have any questions. Thank you!

**Comment by shendy-a8c** [comment] 2021-03-20 23:50
Thank you @luizreis for the repro steps and @reykjalin for creating [issue 1417](https://github.com/Automattic/woocommerce-payments/issues/1417).
