### ISSUE TITLE
Declined transactions not available in dashboard

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/woocommerce-payments#1063] opened 2020-10-27 20:44 UTC
When there is a declined transaction, the information isn't available to the store owner. **Payments > Transactions** only shows transactions that have contributed to the Stripe account balance, which doesn't include declines.

These transactions aren't part of what comes in via the [endpoint being used](https://stripe.com/docs/api/balance_transactions/list).

This information is important, as there is no context for failed orders unless the Store owner happens to have logging enabled and checks the logs, or they contact support to get the reason for the failure.

It looks like the declines are in the [Payment Intents Object](https://stripe.com/docs/declines#responding-to-failures-api). Could that be tapped for the information?

Reported in 3432242-zen.

**Comment by kalessil** [comment] 2020-10-28 06:54
2 notes here:

- in spite decision to list only succeded transactions, that's makes support and troubleshooting more complex
    - you need to be aware that failed orders are caused by failed transactions
    - theres no way for merchant to check what happened
- failed order also doesn't state clearly that it was failed transaction and what's the actual message was

**Comment by dechov** [comment] 2020-10-28 12:11
As designed, the list only includes items that influence the merchant's balance, directly based on Stripe's definition of balance transactions (though with deposits omitted, and some more precise types) rather than what the customer's perspective of a "transaction" would be. This is why refunds, disputes, etc. are all split out as separate "transactions", and why charges that failed (or haven't been captured yet) do not appear. We should improve the messaging on failed orders, and probably try to address this point of potential confusion re: "transactions", with upfront clarification if nothing else.

**Comment by GeoJunkie** [comment] 2020-10-28 13:11
Thanks for the clarification @dechov ! 

If the failure reason could be added to the order notes, that would help a lot and align with how the Stripe plugin operates.

That information does come back from the API after the attempt. An example from the logs in 3432242-zen:

```
"failure_code": "card_declined",
    "failure_message": "Your card was declined.",
    "fraud_details": {
      "stripe_report": "fraudulent"
    },
```

Could that be used to provide an order note?

**Comment by dechov** [comment] 2020-10-30 20:34
https://github.com/Automattic/woocommerce-payments/issues/489 tracks improving the failed order note – just raised the priority on it. (FYI @LevinMedia)

**Comment by jessy-p** [comment] 2022-03-22 04:46
@dechov  comment above explains the rationale behind the current design.
Better order notes for improved support and troubleshooting for failed orders is covered in #489
Can we close this defect @GeoJunkie ?

**Comment by jessy-p** [comment] 2022-03-29 09:29
Confirmed with author & closing.

**Closed by jessy-p** 2022-03-29 09:29 UTC
Labels: type: enhancement, pr: needs author reply, category: core
