### ISSUE TITLE
Manual refund is created when changing the order status to "Refunded"

### ISSUE THREAD

**Issue by felipelousantos** [Automattic/woocommerce-payments#2814] opened 2021-08-31 03:39 UTC
### Describe the bug

When users change the order status to "Refunded" it creates an odd issue where their customer doesn't get refunded from WooCommerce Payments and the user loses the option for a refund on WooCommerce. 

It even shows the following core message on the order notes creating even more confusion for the users:

> Order status set to refunded. To return funds to the customer you will need to issue a refund through your payment gateway.

### To Reproduce

1. Go to an order paid using WooCommerce Payments
2. Change the status of the order to "Refunded"
3. Try creating a refund using WooCommerce Payments (you shouldn't be able to do so)

### Actual behavior

A manual refund is created on WooCommerce, so the user can't refund using WooCommerce Payments.

### Screenshots

![Annotation on 2021-08-31 at 04-24-23](https://user-images.githubusercontent.com/40555737/131436779-de911479-f4b8-4d4c-a303-64de11ec11a1.png)

### Expected behavior

Some options:
* Remove the manual refund from the status change
* Remove the manual refund, but add a screen/option asking the user if they would like to proceed with a refund on WooCommerce Payments
* Add automatic WooCommerce Payments refund when changing the status

### Additional context

p6q7sZ-9aw-p2

**Comment by gregbe11** [comment] 2021-09-08 11:01
Hi, I'm going through final testing and about to go live with WooCommerce for the first time.

Is the work-around to this issue to first process the refund via WooCommerce Payments and then change the order status to refunded?

**Comment by oaratovskyi** [comment] 2021-09-17 11:45
Hi @gregbe11!
Yes, that's correct. 
If the refund is processed via WooCommerce Payments, the order status will be automatically changed to `Refunded`.
The bug described here is occurring if the status change to `Refunded` goes **before** refund via WooCommerce Payments.

**Comment by gregbe11** [comment] 2021-09-17 11:58
Thanks for your reply, much appreciated. I will ensure to follow the correct procedure!

**Comment by chickenn00dle** [comment] 2021-11-19 22:29
Hey @felipelousantos 👋 

I ran through this process with WCPay along with several other payment gateways (Stripe and PayPal Payments) and the behavior looks to be expected. Specifically, manually changing the order status to refunded will automatically manually refund the order and prevent further refunds to the gateway.

This is in line with what the refunded status is meant to convey - The order has already been refunded: https://woocommerce.com/document/managing-orders/#order-statuses

So a merchant should not be changing the status unless the order has already been refunded. We actually recommend using the refund button for refunds in our docs:
https://woocommerce.com/document/woocommerce-refunds/#automatic-refunds

This could be more clearly explained for the merchant in the plugin, but I don't think this is a bug. Instead, it seems like it could be an enhancement request, and one that should probably live in the WC repo.

Let me know if I've misunderstood the issue here. I'll go ahead and close this for now, but feel free to re-open if necessary.

**Comment by felipelousantos** [comment] 2021-11-19 23:52
Hi @chickenn00dle!

While what you pointed makes sense, there is an issue with this approach because the users shouldn't manually refund when using WooCommerce Payments. WooCommerce Payments even removes the manual refund button when the user tries to refund AFAIK.

The big difference compared with other payments gateways is that the users have an interface to refund if they manually refund the order from their end on WooCommerce. They could go to the Stripe or PayPal dashboard if they manually refund an order, but they can't do the same with WooCommerce Payments.

What do you think would be the best option in case a user changes the order status to Refunded, but still want to refund the order somehow?

I agree with you that it might not make sense to refund automatically when changing the status thinking about how this should work on WooCommerce core, but I also think that we need a solution. :)

**Comment by felipelousantos** [comment] 2022-02-02 12:32
> I'll go ahead and close this for now, but feel free to re-open if necessary.

Considering that we are still waiting for dev feedback here, I'm going to re-open the issue, so we can make sure that we don't miss this.

**Comment by dechov** [comment] 2022-02-08 17:52
We can't hook into the existing status change handling there but maybe we could consider intercepting the [existing hook](https://github.com/woocommerce/woocommerce/blob/f3927c786a62b8bd5ca7ba7c4ef05f2ebdf0b787/plugins/woocommerce/includes/wc-order-functions.php#L797), removing it, and replacing with a more informative order note?

**Comment by LevinMedia** [comment] 2022-02-08 19:12
>What do you think would be the best option in case a user changes the order status to Refunded, but still want to refund the order somehow?

>I agree with you that it might not make sense to refund automatically when changing the status thinking about how this should work on WooCommerce core, but I also think that we need a solution. :)

I'm not sure of the UX off the top of my head, have we checked to see what happens if the merchant manually changes the status from "Refunded" back to "Processing" or another status that permits refunds?

**Comment by thenbrent** [comment] 2022-02-09 01:11
Thanks for reopening this issue @felipelousantos. I hadn't realized there was an open Manual Refund issue still after https://github.com/Automattic/woocommerce-payments/issues/426 was closed.

@dechov @LevinMedia what do you think or just removing the "Refunded" from the available status in this select box (whenever the order isn't refunded)?

That seems equivalent to removing the Manual Refund button that we've done already.

**Comment by LevinMedia** [comment] 2022-02-21 22:18
>what do you think or just removing the "Refunded" from the available status in this select box (whenever the order isn't refunded)?

@thenbrent @dechov  that sounds good 👍

**Comment by jessy-p** [comment] 2022-02-23 18:23
Moving to "Ready for Prioritization" to implement solution confirmed above by @LevinMedia

**Comment by aheckler** [comment] 2022-03-31 09:02
Some related discussion from Slack: p1648137198865869-slack-CGGCLBN58

**Comment by thenbrent** [comment] 2022-04-01 03:18
Some further discussion on the ideal behavior of this button here: paJDYF-3Dl-p2

**Comment by LevinMedia** [comment] 2022-05-04 17:17
Hi all - given the considerations and discussions above ( paJDYF-3Dl-p2 ) I'm on board with using a modal merchant tries to switch the status to "refunded" using the status switcher. 

The modal will prevent the status from being switched immediately. It will present the merchant the choice to either refund the order in full (any remaining funds left on the oder) or cancel the operation. In doing so, it will inform the merchant that they can issue a partial refund using the **_refund button_** in the order details. I've left the option to issue a refund without actually refunding any money out of the experience, since that's essentially the same as a "manual refund" - which is technically prohibited by stripe unless a refund back to the original card used to take payment fails. (this partially why we removed the manual refund button in an earlier issue) This also simplifies the cognitive load that would be presented in the modal, too. 

<img width="1505" alt="Screen Shot 2022-05-04 at 10 05 42 AM" src="https://user-images.githubusercontent.com/4500952/166741591-6f61d28b-22c4-4cc5-9352-0b058863bce7.png">

The entire flow can be viewed using [this Figma prototype](https://www.figma.com/proto/Jrefpu6gwtisZzitLEL1xl/Refund-Bug?page-id=0%3A1&node-id=0%3A1&viewport=241%2C48%2C0.47&scaling=min-zoom&starting-point-node-id=1%3A7&show-proto-sidebar=1&hide-ui=1).

Change the order status from processing to "Refunded" to trigger the modal. 

cc @thenbrent @bradyv @rogermattic @aheckler

**Comment by thenbrent** [comment] 2022-05-05 04:39
Fantastic thanks @LevinMedia!

@jessy-p @zmaglica @RadoslavGeorgiev I see you've each been looking at this issue and its place in the platform backlog recently. This is now ready for engineering.

**Comment by felipelousantos** [comment] 2022-05-15 12:52
5211812-zen

**Comment by jessy-p** [comment] 2022-10-26 18:13
Interactions added in https://github.com/Automattic/woocommerce-payments/pull/4987, which are not covered in the Figma design:

- Merchant clicks on "Refund", a spinner is displayed on the modal until the ajax call returns.
- If the refund is successful, the page is refreshed. (Same as woocommerce core, when Refund button on Edit Order screen is used)
- If there is an error while attempting the refund, an alert is displayed. On dismissing alert, pop-up is closed and the status is reset back to original value (not left as "Refunded" in the dropdown as that might cause unintended direct update).  
- If the order cannot be refunded (already refunded/ proper metadata not present on order to allow refund), a error alert is displayed and the Confirmation Modal will not display. Status remains "Refunded". This is so that merchant can change the status if the order is already refunded.

**Comment by EjayhanFernandes** [comment] 2022-10-30 02:28
[5669088-Zen](5669088-zd-woothemes)

**Comment by EjayhanFernandes** [comment] 2022-11-01 11:31
5672889-zd-woothemes

**Closed** 2022-11-04 16:41 UTC
Labels: type: bug, category: core, needs prioritisation

**Comment by EjayhanFernandes** [comment] 2022-11-11 07:48
5701351-zd-woothemes
