### ISSUE TITLE
Advanced filters throw an error

### ISSUE THREAD

**Issue by nicdwilson** [Automattic/woocommerce-payments#6533] opened 2023-06-14 21:44 UTC
### Describe the bug

Clicking on Transactions > Advanced Filters results in unexpected response

### To Reproduce

1. Go to Payments > Transactions
2. Click on Advanced Filters

### Actual behavior

![dAFUmr.png](https://github.com/Automattic/woocommerce-payments/assets/3624025/3644e5ed-f21c-481c-b527-ce9a8b3327c4)

### Expected behavior

Advanced filters should work

### Desktop (please complete the following information):

* OS: MacOS 13,4
* Browser Firefox
* Version 115.0b4

### Additional context
[6409605-zen](6409605-zd-woothemes)

**Comment by zmaglica** [comment] 2023-06-15 11:17
I wasn't able to reproduce the issue. It is working fine on my end. Are there more steps that is missing? Can you maybe test the issue on your end using JN site?

**Comment by nicdwilson** [comment] 2023-06-19 05:28
Hi @zmaglica This behaviour was reported by the customer in 6409605-zd-woothemes and replicated on a Pressable site. There are no steps to replicate because I simply clicked on the advanced filter, and got the result on my screen which you see in the screenshot above.

I have added creds for the test site to 6409605-zd-woothemes

**Comment by johndcoy** [comment] 2023-06-19 18:39
I'm seeing the same error as @nicdwilson on one Pressable site:

![Screenshot](https://d.pr/i/OPOW7C+)
Screenshot link: https://d.pr/i/OPOW7C

But not on another Pressable site:

![Screenshot](https://d.pr/i/OhhWyl+)
Screenshot link: https://d.pr/i/OhhWyl

The difference between these two sites is the one with the issue has CDN caching enabled and is running PHP 8.1. The one without issues has CDN disabled and is running PHP 7.4

**Comment by mattsherman** [comment] 2023-06-20 10:56
This looks related to an update made in https://github.com/woocommerce/woocommerce/pull/37967 for WooCommerce 7.8.

**Comment by daniyalahmadk** [comment] 2023-06-21 09:50
Another report on this ticket: 6441052-zen. I can replicate the issue on our WCPay pressable staging site:

<img width="638" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/13753012/24195147-7c5f-4653-94d6-5682c7dcdeb7">

**Comment by sarbouw** [comment] 2023-06-21 12:04
6443725-zd

**Comment by felipevelzani** [comment] 2023-06-21 21:53
6452781-zen

**Comment by scotthopkins** [comment] 2023-06-22 06:44
I also have this on my site... for any advanced filter type

Woocommerce 7.8.0
Woocommerce Payments Version 6.0.0
PHP 8.1

![CleanShot 2023-06-22 at 16 43 42](https://github.com/Automattic/woocommerce-payments/assets/998187/47ec17ad-12f1-4927-8fa9-da70811eeb67)

**Comment by druesome** [comment] 2023-06-23 09:08
<s>334584-zen</s>

6423865-zen

I was also able to replicate this on my Atomic site, but strangely, not on my Pressable site.

**Comment by AbhinavSakalle** [comment] 2023-06-23 10:19
Reported in 6457727-zen.

I was able to replicate it on my Pressable site.

**Comment by csmcneill** [comment] 2023-06-27 00:56
Renamed this issue because it does not affect _just_ transaction filters—it also affects dispute filters.

![Markup on 2023-06-26 at 19:40:31](https://github.com/Automattic/woocommerce-payments/assets/82999806/54685f03-b254-434d-9d3f-0a8bf949a5b7)

![Markup on 2023-06-26 at 19:41:42](https://github.com/Automattic/woocommerce-payments/assets/82999806/f2e69208-ad9c-4f1b-80b0-84aaedd46d09)

**Comment by francoishvz** [comment] 2023-06-28 12:24
6474495-zen

**Comment by kyajfx** [comment] 2023-06-28 18:35
Same issue after updating WooCommerce 7.8.1 and WC Payments 6.0
![Screenshot 2023-06-28 223421](https://github.com/Automattic/woocommerce-payments/assets/29586687/556ed118-1e46-4e9d-a9af-f6a30c2fd2fc)

**Comment by melek** [comment] 2023-06-28 18:49
6476791-zen

**Comment by daquinons** [comment] 2023-06-29 06:40
We've been debugging this issue here p1688006903600379-slack-CGGCLBN58

I can confirm WC 7.8 is the root cause of the issue.

My local environment was showing advanced filters with 7.6 perfectly and it wasn't until I updated it to 7.8.1 that it displayed the error.

**Comment by ricardo** [comment] 2023-06-29 14:51
Fixed in https://github.com/Automattic/woocommerce-payments/pull/6617.

**Closed as completed** 2023-06-29 14:50 UTC
Labels: type: bug, priority: high, component: transactions, category: core
