### ISSUE TITLE
"Account details" field cannot be changed

### ISSUE THREAD

**Issue by fluxion8** [Automattic/woocommerce-payments#8727] opened 2024-04-29 09:19 UTC
### Describe the bug
When user connect the Stripe account can not be change it later.

### To Reproduce
Added XCompany stripe account.Then i want to change YCompany stripe account. It's not possible

**Comment by anu-rock** [comment] 2024-05-03 06:30
@fluxion8 Could you add more details (including a screenshot if possible) to describe the issue?

WooPayments expectedly does not allow merchants to change their linked Stripe account or use an existing regular Stripe account. See these public docs:

* https://woocommerce.com/document/woopayments/account-management/#switching-and-deleting-accounts
* https://woocommerce.com/document/woopayments/account-management/existing-stripe-account/

However, it's possible to start over by contacting support.

**Comment by haszari** [comment] 2024-05-12 22:38
This is clearly a feature request – i.e. enhancement, we don't support switching Stripe accounts at present. I've updated the labels, please comment if you think this should be treated as a bug.

IMO definitely a good fit for `focus: account lifecycle`, but I suggest this should be closed (not a bug, can't be prioritised as a fix) and/or added to a product backlog.

@timmy5685 @anu-rock how do y'all manage feature enhancement ideas?

**Comment by anu-rock** [comment] 2024-06-07 10:56
@haszari @timmy5685 I agree about closing this issue as won't fix. Closing.

**Closed as not planned by anu-rock** 2024-06-07 10:56 UTC
Labels: type: enhancement, focus: account lifecycle
