### ISSUE TITLE
Cannot add a new payment method to existing subscriptions

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [Automattic/woocommerce-payments#3771] opened 2022-02-09 14:55 UTC
## How it currently works

https://github.com/Automattic/woocommerce-payments/pull/2386 allowed subscriptions' payment methods to be changed through UPE. It's recommended to see the PR, but __TL;DR:__ When the "Change payment method" form is submitted:

1. The SetupIntent needs to be confirmed, and for that we use Stripe's `confirmSetup` API.
2. Once the intent has been confirmed, the customer is redirected back to the same page, but with a `redirect_status=succeeded` parameter in the URL.
3. Within UPE's `get_payment_fields_js_config()` method, we'll catch that, and add the new payment method to the customer, and __configure JS to select the new payment method__ when the page is loaded.
4. The gateway's `payment_fields()` will proceed, and include the new payment method within the displayed saved payment methods.
5. When the page is loaded, JS will select the new payment method, and properly submit the form.

As described in the original PR, there's an additional step, which is not ideal. That's the case, because `confirmSetup` redirects back with a GET request, but Subscriptions are expecting a POST request.

## What is broken

In https://github.com/Automattic/woocommerce-payments/pull/3718 we had to localize scripts outside of the checkout shortcode, because localization within shortcodes doesn't work with block-based themes and WordPress 5.9.

This broke steps 4-5 from "How it currently works", because `get_payment_fields_js_config` is called after `payment_fields`, and the newly added payment method does not appear on the page for step 4.

### Steps to reproduce

1. Sign up for a subscription
2. Try to change the subscription's payment method (from My Account -> Subscriptions -> [Subscription] -> Change payment) with a new card.
3. You will see that the new payment method is assigned added to the customer, but not assigned to the subscription.

## Ideal scenario

How can we improve this? There are two paths:

1. __Non-redirect payment__ (card, SEPA, etc.):
	1. Use `confirmSetup()`'s `redirect: 'if_required'` parameter in order to avoid the redirect.
	2. Add the Setup Intent details as fields to the form.
	3. Submit the form.
	2. Use the gateway's `process_payment` method, called by `WC_Subscriptions_Change_Payment_Gateway::change_payment_method_via_pay_shortcode()` to create the WC token and assign it to the customer/subscription/order immediately.
2. For __Redirect payment__ (iDeal, Sofort, etc.) we can either keep the way it currently works, as this is a relatively rare case, or manually update the subscription immediately when we receive the confirmation before redirecting to the subscription page with a success notice.

**Comment by shendy-a8c** [comment] 2022-02-09 17:25
Linking this issue with [one](https://github.com/Automattic/woocommerce-payments/issues/3765) that was reported by GlobalStep.

**Comment by brucealdridge** [comment] 2022-03-23 00:14
@RadoslavGeorgiev it looks like #3772 only partially fixes this issue. Are you able to provide an update with what is still outstanding for this issue.

**Comment by zmaglica** [comment] 2022-04-12 07:27
After a lot of testing, the issue could not be reproduced on the current develop branch. I will close this issue for now. Please have no hesitation to open the issue if the issue appears again.

**Closed by zmaglica** 2022-04-12 07:27 UTC
Labels: type: bug, component: saved cards and subscriptions, component: wcpay subscriptions, category: core, needs prioritisation
