### ISSUE TITLE
Same payment intent used for two orders

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-payments#6977] opened 2023-08-11 05:20 UTC
### Describe the bug
A payment intent was used for two different orders. The first transaction didn't complete (Payment request). The second transaction did complete, but for the amount of the first order but was applied to the second order which has a different amount, i.e. the customer was charged an incorrect account.

### To Reproduce

Not entirely sure, but it look like this is the what the user reporting this did
1. Have a configuration that causes "payment request button is not supported in Australia" when trying to use a payment request and try to pay for an order and get the error.
2. Proceed to checkout and try again as the notice suggests (cart contents probably changed between steps 1 & 2)
3. Get charged a different amount than what the order total was
4. Notice that the same payment intent from the first order is used for the second order.

### Actual behavior

Charged the wrong amount (in this case overcharged)
### Expected behavior
To be charged what the checkout page shows I'll be charged

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context
p1691364119113289-slack-C7U3Y3VMY
6626727-zd-a8c

**Comment by RadoslavGeorgiev** [comment] 2023-08-24 09:27
Thank you for the report, @WillBrubaker! I'll try to reproduce this in the next couple of days.

cc @htdat in the context of duplicate charges. Maybe you've already got an idea what might be causing this.

**Comment by zoupkat** [comment] 2023-09-02 14:21
Hi there @RadoslavGeorgiev and/or @htdat !
Any updates on this please?
Thank you!

**Comment by htdat** [comment] 2023-09-05 05:50
@zoupkat - sorry for the late update. I have not had any change to look into this deeply in the previous weeks, but will do that this week. Stay tuned!

**Comment by htdat** [comment] 2023-09-11 06:29
@WillBrubaker and @zoupkat - Sorry for the late response. I am afraid of that I could not shed any new light here, this requires more investigation effort to understand how the issue happened. 

### Some of my observations: 

Looking at Payment Intent logs 31b70-pb, the concerned payment intent had got three `402` (status repsonse) for [confirm](https://stripe.com/docs/api/payment_intents/confirm) requests with these errors before changing to status `succeeded`: 

- Your card was declined.
- Your card was declined. Your request was in live mode, but used a known test card.
- Your card has insufficient funds.

Based on the flow, it's that the site uses either classic UPE or split UPE (without deferrered intent) as it starts with the intent creation **without** the `confirm:true` param. 

The `order_id` metadata of payment intent got updated with `390`, then `392`, and then `390` again.

### Quick thoughts: 

- It's likely that the UPE intent caching is the cause here.
- Since it's related to "payment request", I would ask @Automattic/fusion to have a look and see if they find it a known issue.
- In terms of "duplicate payments", this kind of issue is new to me. It's not any type of known issues:
    - two orders for single intent https://github.com/Automattic/woocommerce-payments/issues/6977
    - two or more intents for one order https://github.com/Automattic/woocommerce-payments/pull/5346 and https://github.com/Automattic/woocommerce-payments/issues/5678
    - two intents for two orders with the same cart content wcpay_paid_for_previous_order

**Comment by ChrissiePollock** [comment] 2023-09-23 17:06
@htdat , @WillBrubaker or @zoupkat - Do we have any updates on this that we can offer the merchant?

**Comment by htdat** [comment] 2023-10-04 04:23
@ChrissiePollock - sorry for the late update. However, at the moment, it's still unclear how this issue exactly happened. I am asking Fusion (one of WooPayments engineering teams) to have a look p1696393293570769-slack-C04DN7Q51KK

**Comment by anu-rock** [comment] 2023-10-12 03:30
@mordeth Could you please share your findings here?

**Comment by mordeth** [comment] 2023-10-13 20:59
I had no success in reproducing the issue. I have checked the payment request button codebase but haven't found any obvious issues. Unfortunately, it is still unclear to me how the same payment intent was used for two orders.

**Comment by pierorocca** [comment] 2024-01-17 22:31
@c-shultz suggest we close this as a one off occurrence on a codebase that has since been sunset with the introduction of dUPE.

**Comment by c-shultz** [comment] 2024-01-17 23:19
>suggest we close this as a one off occurrence on a codebase that has since been sunset with the introduction of dUPE.

Agreed.

**Closed as completed by c-shultz** 2024-01-17 23:19 UTC
Labels: type: bug, priority: low, status: blocked, component: checkout, component: payment request button, category: core
