### ISSUE TITLE
Checkout for free-trial subscription product does not complete correctly

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#3396] opened 2021-11-18 19:31 UTC
### Describe the bug

With the UPE enabled, a checkout for a subscription product with a free-trial appears to complete successfully, but the Order created has incomplete or incorrect information. 

Specific notable errors are that the payment method title on the Order Received page is always "Credit / Debit Card" regardless of the actual payment method type of the saved payment method used--i.e. if we use a saved SEPA payment method, the payment method title after checkout is still "Credit / Debit Card". 

![Wrong payment method title at checkout](https://cdn-std.droplr.net/files/acc_1104206/ETgWr1)
_Checkout with saved SEPA payment method incorrectly titled_

Additionally, if we check the newly created Order, we find that the order status/subtitle is missing the Setup Intent ID.

![Missing seti ID](https://cdn-std.droplr.net/files/acc_1104206/4N8ZWt)
_Incorrect order page with Setup Intent ID missing_

![Expected order](https://cdn-std.droplr.net/files/acc_1104206/hMaEpM)
_Expected order page with Setup Intent ID present_

Free-trial subscription products involve checkouts where no payment is necessary, but payment information must still be collected, so that payments can be processed at a later time. These checkouts rely on using Setup Intents, instead of Payment Intents, to collect payment information without processing a charge. Using a saved payment method involves bypassing the UPE to collect payment information and instead using an existing payment method, by passing the relevant payment method ID as a parameter to the setup intent. Something strange is happening somewhere in this process...

### To Reproduce

1. Enable the UPE with at least cards and SEPA Direct Debit enabled as payment methods. Set site currency to Euros, so that SEPA can be supported at checkout.
2. Create a subscription product with a free-trial.
3. Either complete a checkout and elect to save a payment method or add a payment method from the My Account dashboard, so that we can complete a future checkout using a saved payment method. Save both a card payment method and a SEPA Direct Debit payment method.
4. Add aforementioned subscription product to cart and proceed to checkout. Select Free Shipping option, so that there will be no payment required at checkout.
5. Select saved SEPA payment and select "Sign up now" to complete checkout.
6. Note that payment method on Order Received page is incorrect. Note that on the Order page for this order in WP-Admin, the Setup Intent ID is missing.
7. Repeat Step 4, but this time select a saved card payment method and select "Sign up now" to complete checkout.
8. Note that on the Order page for this order in WP-Admin, the Setup Intent ID is missing.

### Desktop (please complete the following information):

* OS: MacOS
* Browser: Firefox 94.0
* Version: 

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by htdat** [comment] 2021-11-22 07:54
@FangedParakeet - as I understand here, this issue happens for any subscription no matter how it is created, from either the full WooCommerce Subscriptions plugin or WCPay Subscription feature?

**Comment by FangedParakeet** [comment] 2021-11-22 19:56
I wasn't aware of the WCPay Subscription feature, but I have replicated the above using the plain old WooCommerce Subscriptions plugin with the latest `develop` branch of WCPay. I only tested with a simple subscription product, so nothing too fancy, but let me know if you need any more help configuring any of my setup to repeat this issue!

**Comment by htdat** [comment] 2021-11-23 08:54
Thanks @FangedParakeet. I am triaging issues in the current sprint so just want to make sure the issue to add the correct label. If it was related to WCPay Subscriptions, the `component: wcpay subscriptions` would be needed. But it's not the case here. 

> but I have replicated the above using the plain old WooCommerce Subscriptions plugin with the latest develop branch of WCPay. 

👍 If so, you can update this part to your original issue description, then all good!

**Comment by brucealdridge** [comment] 2021-12-05 23:14
I've replicated this bug on standard credit card purchases with WCPay as well.

It creates two customer entries in stripe. One with name `Name: , Guest` which has the payment method/type allocated. The second customer is created using the correct details from the customer.

![image](https://user-images.githubusercontent.com/57298/144767804-6e4a06eb-a308-4bae-8a3d-ff74f5d553c0.png)

**Comment by brucealdridge** [comment] 2021-12-05 23:56
Looks like this is a duplicate of #2994

**Closed** 2021-12-05 23:57 UTC
Labels: type: bug, priority: high, category: duplicate, component: upe, component: wcpay subscriptions, category: projects
