### ISSUE TITLE
[GlobalStep] Apple Pay pop-up box disappears after few seconds on the "Checkout" page.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#8326] opened 2024-03-05 16:19 UTC
### Bug Description:
Apple Pay pop-up box disappears after few seconds on the "Checkout" page.

### Environment:
Woocommerce Version: WooCommerce 8.6.1
WooCommerce Payments: 7.3.0-test-3
WordPress version: v6.4.3

PC:
MacOS 12.3.1
Safari Version 15.6.1

### Steps To Reproduce:
1. Create any test site.
2. Install and activate all the required plugins.
3. Complete WooCommerce Payments KYC flow.
4. Ensure you have UK IP.
5. Add a product to the cart and go to checkout.
6. Click on "Buy with Apple Pay" button.
7. Observe that,  Apple Pay pop-up box disappears after few seconds on the "checkout" page.

### Instruction Link:
https://globalstepp2.wordpress.com/2024/03/04/woopayments-globalstep-call-for-testing-to-be-done-on-mar-5th-2024/#apple-pay-test

### Actual Result:
Apple Pay pop-up box disappears after few seconds on the "Checkout"" page.

### Expected Result:
Apple Pay pop-up box should not disappears after few seconds on the "Checkout" page.

### Video:

https://github.com/Automattic/woocommerce-payments/assets/41110392/cb333203-c113-4300-b0c0-678b5faeee08

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.4.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Total Database Size: 4.44MB
Database Data Size: 2.54MB
Database Index Size: 1.90MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.09MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 18
customize_changeset: 2
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
page: 8
post: 1
product: 13
revision: 4
shop_order: 51
shop_order_refund: 1
wp_global_styles: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
Code Snippets: by Code Snippets Pro – 3.6.2
WordPress.com Editing Toolkit: by Automattic – 4.15083
Gutenberg: by Gutenberg Team – 17.8.0
Jetpack: by Automattic – 13.2-beta
Layout Grid: by Automattic – 1.8.4
Page Optimize: by Automattic – 0.5.5
WooCommerce Payments Dev Tools: by Automattic –
WooPayments: by Automattic – 7.3.0-test-3
WooCommerce: by Automattic – 8.6.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.4
Author URL: https://woo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 7.3.0-test-3
Connected to WPCOM: Yes
WPCOM Blog ID: 223194915
Account ID: acct_1NpIRpFgS7opFvPy
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Not eligible
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-06 09:58:59 +05:30
Options: ✔
Notes: 95
Onboarding: completed

### Action Scheduler ###

Canceled: 6
Oldest: 2024-02-06 18:47:04 +0530
Newest: 2024-03-05 17:58:04 +0530

Complete: 61
Oldest: 2024-02-04 05:30:02 +0530
Newest: 2024-03-05 19:36:06 +0530

Failed: 1
Oldest: 2023-09-06 15:38:01 +0530
Newest: 2023-09-06 15:38:01 +0530

Pending: 1
Oldest: 2024-03-06 16:00:10 +0530
Newest: 2024-03-06 16:00:10 +0530

### Status report information ###

Generated at: 2024-03-05 20:23:53 +05:30
`

</details>

**Comment by cesarcosta99** [comment] 2024-03-06 21:19
Discussed in p1709659817649049/1709659019.485299-slack-CGGCLBN58.

Some people have tried to reproduce this, but no success. At the moment, we suspect that this issue was caused by either:

1. A momentary issue in Apple Pay itself.
2. VPN usage - Apple Pay might block that.
3. Some device, or environment issue. Is Apple Pay working elsewhere that's not WooPayments?

I'm bumping down the priority of the issue since no one can replicate and cc'ing @shendy-a8c and @jessy-p to follow-up on this with GlobalStep in the upcoming testing cycles.

**Comment by vbelolapotkov** [comment] 2024-03-13 18:13
@c-shultz sending this one to you since it relates to Apple Pay.

**Comment by gpressutto5** [comment] 2024-04-01 14:57
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/8326?planning-poker) with Zenhub @FangedParakeet

**Comment by gpressutto5** [comment] 2024-04-01 17:08
We can safely close this issue as this was not reproducible in the previous test: pbPjnJ-25H-p2#comment-1426

**Closed as completed by gpressutto5** 2024-04-01 17:08 UTC
Labels: type: bug, priority: high, focus: checkout payments
