### ISSUE TITLE
Multi-currency: Price does not get updated after changing country in checkout page

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-payments#7492] opened 2023-10-16 19:52 UTC
### Describe the bug
When a customer is in the checkout page and select a country that uses another currency than the default one the price does not get updated to the correct currency. 

### To Reproduce
- Go to /wp-admin > Payments > Scroll down and make sure `Enable Multi-Currency` is enabled
- Go to  /wp-admin > WooCommerce > Multi-currency
- Add a currency other than the default one
- As a shopper go add a product to the cart
- Go to the checkout page
- Change the country to one that uses the new currency
- Notice the currency did not get updated

### Additional context
7174504-zd-a8c

**Comment by csmcneill** [comment] 2023-10-16 20:07
I think this is more of a `type: enhancement` than a `type: bug` issue. I know @jessepearson has worked a ton on multi-currency stuff, so I'd love to get his input.

As far back as I can recall, the customer currency has never changed based on the selected country—and this may be by design. We do have the option to change the currency based on the customer's location via the `Automatically switch customers to their local currency if it has been enabled` setting at **WooCommerce > Settings > Multi-currency**, but this works on geolocation instead of based on customer input.

I also wonder how this would work, since changing the billing country doesn't involve a page refresh for updating most information (e.g., taxes, shipping methods), but a page refresh is likely needed if we'd want it to change the displayed currency.

**Comment by jessepearson** [comment] 2023-10-17 10:37
> As far back as I can recall, the customer currency has never changed based on the selected country—and this may be by design.

Correct, this has never been the case, and I don't think it will ever be the case. If the currency were to change based on country selection, then that would make an assumption that the customer wants to change their currency.

> We do have the option to change the currency based on the customer's location via the Automatically switch customers to their local currency if it has been enabled setting at WooCommerce > Settings > Multi-currency, but this works on geolocation instead of based on customer input.

This is correct, and this will only set the currency on the initial visit. If the customer has changed their currency, it's not going to reset it back to their local currency when they view a new page.

I just went and viewed the ticket and I see this as an active plugin in their SSR: 

```
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.2.0
```

I think they contacted the wrong support about their Multi-Currency issue they were having. Since this seems to be about that plugin and not WooPayments, I am going to close this issue as a `won't fix`.

**Closed as completed by jessepearson** 2023-10-17 10:37 UTC
Labels: type: bug, category: won't fix, component: customer multi-currency
