### ISSUE TITLE
Updating subscription payment method in My Account area doesn't actually change the method.

### ISSUE THREAD

**Issue by melek** [Automattic/woocommerce-payments#3906] opened 2022-03-04 21:02 UTC
### Describe the bug
When updating a subscriptions payment method, the subscription has notes added about the change but the change doesn't actually take place. Then when the subscription is renewed, it uses the old card as long as it is still present on the account.

Some additional points:

- From my testing, removing the old card will fix this (I didn't test this bit extensively; it may default to the default card instead of the customer-chosen one).
- Since this could cause users to be charged on the wrong card, I am setting priority to 'High' to start with. 
- This may be a simpler way to reproduce #3729 or a related bug.

### To Reproduce
I actually had the change work correctly a few times, but here is the procedure has reliably failed for me:

1. Set up two payment methods on the customer account in WooCommerce Payments.
1. Place a new subscription order.
2. Click on My account → Subscriptions → The new subscription.
3. Click 'Change payment'. 
4. Select the other card on the account and save. Note that the payment shows correctly on the customer side.
5. View the subscription on the admin side. Note that the payment shows *incorrectly* when editing the Billing details.
6. Process a renewal. It uses the old card.

### Actual behavior
Customer payment method changes do not work (though they appear to from the front-end), and auto-renewals use the old card.

### Screenshots
After updating the payment method, customer side:
![Screenshot](https://d.pr/i/BZA1gX+.png)
*If you do not see the image, please [click here](https://d.pr/i/BZA1gX).*

Admin side: 
![Screenshot](https://d.pr/i/F1FFph+.png)  
*If you do not see the image, please [click here](https://d.pr/i/F1FFph).*

Transaction on renewal showing incorrect card charged:
![Screenshot](https://d.pr/i/zO42fy+.png)
*If you do not see the image, please [click here](https://d.pr/i/zO42fy).*

After this test, I get the following error when trying to change my payment method again as the customer:
![Screenshot](https://d.pr/i/MB0bYm+.png)
*If you do not see the image, please [click here](https://d.pr/i/MB0bYm).*

### Expected behavior
I would expect the change to simply work and for renewals to proceed with the new card.

### Additional context
Found when investigating 4826140-zen (though this appears to be a different bug than the one the customer found).

**Comment by brucealdridge** [comment] 2022-03-24 21:55
Closing this issue after investigation. Am unable to reproduce with Subscriptions for WooCommerce Payments.
Based on the screenshots it appears that WooCommerce Subscriptions is also installed (`Renew now` button and `Auto renew` toggle), however even with WooCommerce Subscriptions installed I was unable to reproduce.

**Closed by brucealdridge** 2022-03-24 21:55 UTC
Labels: type: bug, priority: high, component: saved cards and subscriptions, category: core, needs prioritisation
