### ISSUE TITLE
Missing order update on Pay for Order failures

### ISSUE THREAD

**Issue by tpaksu** [Automattic/woocommerce-payments#6565] opened 2023-06-21 12:44 UTC
### Describe the bug
For non-UPE, we run `process_payment_for_order` in the gateway, which checks the error type and if it’s blocked by fraud rules, we add a order note and set the metabox type, set the order as failed etc, but it’s missing in the `update_payment_intent_ajax` [call](https://github.com/Automattic/woocommerce-payments/blob/5b3767240e8e33c37d7c937c988fdbcf1efc4a30/includes/payment-methods/class-upe-payment-gateway.php#L155) for UPE. And it doesn’t add meta boxes or set order status. 

### To Reproduce

1. Checkout https://github.com/Automattic/woocommerce-payments/pull/6419 branch if not merged yet. 2. Build the assets using `npm run build`
3. Enable UPE if not enabled.
4. Go to Payments > Settings > Fraud protection 
5. Select "Advanced" and click "Configure"
6. Enable "order items threshold" filter and set minimum required items to 10
7. Create an order to pay for the guest customer, containing one item
8. Open the payment page in an incognito window, pay it with a successful card

### Actual behavior
You should get the block, but nothing is changed on the order. 

### Expected behavior
The order should be marked as _Failed_, a correct fraud meta box should be shown, and a order note should be added, indicating the failure

**Comment by zmaglica** [comment] 2023-06-26 15:54
This issue impacts Fraud & Risk, so assigning to team Sigma (based on team responsibilities) @dwainm  . Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by allie500** [comment] 2023-11-06 20:59
@tpaksu I believe this is no longer an issue. I followed the steps to reproduce and the meta box on the pay for order I created correctly showed 'blocked'. I also had the expected 'blocked' order note.

- Status: pending payment
- Meta box: blocked
- Order note: blocked

> The order should be marked as _Failed,_

My test order that I prepared had its status remain as _pending payment_. I also tested with a flow of a user adding a product to the cart and checking out to trigger the same minimum 10 items rule. The status, meta box, and order note were the same as the pay for order flow: 

- Status: pending payment
- Meta box: blocked
- Order note: blocked

Since blocked payments from different flows (regular checkout, pay for order flow, etc) all keep the status set to pending payment, I think if we want the status set to failed for all blocked payments we should create a different issue. What do you think?

Can you run through the test steps you outlined in the issue description to see if you get the expected behavior now?

**Comment by jessepearson** [comment] 2023-12-18 15:55
@tpaksu I was not able to reproduce this issue, either. After the order failing for the customer, this is what I see in the order itself:

![Screenshot 2023-12-18 at 11 53 42 AM](https://github.com/Automattic/woocommerce-payments/assets/4634416/0eed80a8-3311-4713-be8e-4e7e1d5e4c25)

Closing this issue, please open it again if you can reproduce the issue.

**Closed as completed by jessepearson** 2023-12-18 15:55 UTC
Labels: type: bug, category: core, component: fraud & risk tools
