### ISSUE TITLE
Adding SCA payment method to subscriptions order gives an error.

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#1294] opened 2021-02-05 17:52 UTC
1. Install WooCommerce Subscriptions.
2. Create a subscriptions product.
3. Purchase it.
4. Go to My Account > Subscriptions > Open the subscriptions order > Change payment > Put in new payment that requires SCA, ie `4000002500003155`.
5. Proceed through. If you see a SCA modal, click Complete Authentication.
6. You will see `Error: No such payment_intent: 'seti_abc'` and new payment is not added.

Expected:
Success message instead of error and payment method is added.

**Comment by htdat** [comment] 2021-12-01 08:57
Closing! Duplicate of #2822

**Closed by htdat** 2021-12-01 08:57 UTC
Labels: type: bug, component: saved cards and subscriptions, category: duplicate, category: core
