### ISSUE TITLE
WooPay opt-in is not shown if using a saved card on Checkout block.

### ISSUE THREAD

**Issue by senadir** [Automattic/woocommerce-payments#9236] opened 2024-08-07 21:27 UTC
### Describe the bug
On Checkout block, the WooPay opt-in section is only shown if you're checking out with a new card, using a saved card hides it.

### To Reproduce
0. Disable WooPay.
1. Go to Checkout block, logged in or with account creation enabled.
2. Fill in a card, make sure it's saved (for me it was auto saved), and place an order.
3. Enable WooPay.
4. Go back to Checkout block.
5. Select new card instead of saved one, notice WooPay opt in is visible.
6. Select the saved card, notice it's no longer visible

### Actual behavior
Opt in is hidden.

### Screenshots
Saved Card:
<img width="693" alt="image" src="https://github.com/user-attachments/assets/6d86c3c4-f727-40bb-b40b-b2bf84a2c237">

New Card:
<img width="688" alt="image" src="https://github.com/user-attachments/assets/17f55222-f87c-4895-ba1d-b0205ea5e60d">

### Expected behavior
Opt in should be visible for both.

### Desktop (please complete the following information):

* OS: Mac
* Browser: Chrome
* Version: Latest

### Additional context
I'm not sure how you're checking if that should be shown or not, but it's not shown if Cash for delivery is shown, and that's correct.

I suggest you use the WC payment data store, as it would return the correct gateway for both:

```js
wp.data.select('wc/store/payment').getActivePaymentMethod() // 'woocommerce_payments'
```

You can also check if a saved card is selected by running:

```js
wp.data.select('wc/store/payment').getActiveSavedToken() // '1'
```

This would return the token ID, or `""` if no saved card is selected.

**Comment by pierorocca** [comment] 2024-08-07 21:37
Tagging @leonardola who is currently working on this component on related issues and @nikkivias for awareness.

Historically I don't recall how this is handled and if this is regression. However, we'd want to drive shoppers towards a single central store for their cards and addresses rather than having cards stored for each store.

**Comment by c-shultz** [comment] 2024-08-07 21:41
This is likely an intentional decision. We wouldn't be able to copy an existing saved payment method up to our platform account (unless Stripe has since changed their limitations). Supporting opt-in in this case would mean creating an account without any saved payment methods.

**Comment by pierorocca** [comment] 2024-08-07 21:49
Yeah I threw off @senadir here. This is expected. However, if you click into the credit card field to add a new number the checkbox should appear as the new card can be saved to WooPay. Could you confirm that behavior @senadir? It should work as I recall running into this exact scenario - and then totally forgot about it - a few days ago.

**Comment by pierorocca** [comment] 2024-08-07 21:58
Nadir has confirmed this is working as intended so closing this one out. Sorry about throwing you off there Nadir.

**Comment by senadir** [comment] 2024-08-07 21:58
No problem!

**Closed as completed by pierorocca** 2024-08-07 21:58 UTC
Labels: type: bug, component: checkout, component: WooPay
