### ISSUE TITLE
Use idempotency key to prevent duplicate requests

### ISSUE THREAD

**Issue by chickenn00dle** [Automattic/woocommerce-payments#3352] opened 2021-11-11 18:37 UTC
### Description
In https://github.com/Automattic/woocommerce-payments/pull/3303, we added the Idempotency-Key header to all post requests and added these to request logs.

This is useful for debugging, but it would be nice to also utilize these keys to prevent duplicate requests.

### Acceptance criteria

* Idempotency-Key header is useful for preventing duplicate requests

### Testing instructions

1. Once https://github.com/Automattic/woocommerce-payments/pull/3303 is merged, initialize a POST request by doing something like purchasing a product with WCPay.
2. View the logs for this request and find the Idempotency-Key header

Right now a new key is generated for each request, making this only useful for debugging.

Related to https://github.com/Automattic/woocommerce-payments/issues/530

**Comment by dechov** [comment] 2021-11-19 23:23
FYI we had dealt with some duplicate onboarding requests with a bespoke solution in https://github.com/Automattic/woocommerce-payments/pull/2867 – in the event the solution here makes that one redundant, it can be removed.

Also FYI in case it makes a difference, @ricardo and I found out that if the original request is still in progress, subsequent requests with the same key will _fail_ (not wait to return the same response).

**Comment by RadoslavGeorgiev** [comment] 2022-03-29 10:33
https://github.com/Automattic/woocommerce-payments/issues/3998 is likely a duplicate of this issue.

**Comment by zmaglica** [comment] 2023-07-10 11:01
@diegocurbelo Moving this issue from the Engineering review queue to the Other teams queue since you added it to the Fractal team backlog.

**Comment by vbelolapotkov** [comment] 2024-12-14 08:36
This issue is way too generic, and very old, so might be irrelevant by now. There were obvious issues with duplicate charges which were addressed, and I'm not aware of any other particular cases where the proposed change woudl be helpful. 

So closing the issue for now, but happy to reopen or create a new one if there are more specific problems to solve.

**Closed by vbelolapotkov** 2024-12-14 08:36 UTC
Labels: type: enhancement, needs feedback, category: core, needs prioritisation, focus: misc or unknown
