### ISSUE TITLE
Download button at Payments > Payouts is misaligned

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#9736] opened 2024-11-15 18:42 UTC
### Describe the bug

The `Download` button for various reports has typically been right-aligned (next to the ellipsis menu). However, on the **Payments > Payouts** page, it is misaligned.

Initial investigation suggests the alignment issue is caused by some `justify-content: space-between;` styling for the `.woocommerce-report-table .components-card__header .woocommerce-table__actions` element, but this styling is not present on other pages.

### To Reproduce

1. Log into wp-admin for a site with WooPayments that has processed payouts.
2. Navigate to **Payments > Transactions**.
3. Note the position of the `gridicons-cloud-download` SVG.
4. Navigate to **Payments > Payouts**.
5. Note the position of the `gridicons-cloud-download` SVG is left-aligned.

### Actual behavior

The experience of downloading a report of an account's payout history is dissimilar from downloading other similar reports (e.g., transactions, disputes). We should try to make this experience as consistent as possible.

### Screenshots

![Image](https://github.com/user-attachments/assets/b62b4c69-435b-41ee-8a60-4c3b67116ba3)

![Image](https://github.com/user-attachments/assets/de451c80-20b5-4639-affe-8b354307c392)

### Expected behavior

The experience of locating and downloading reports should be consistent across the entire product.

### Additional context

No user reports AFAIK. Found this issue while performing other tests.

**Comment by haszari** [comment] 2024-12-05 01:41
> The Download button for various reports has typically been right-aligned (next to the ellipsis menu). However, on the Payments > Payouts page, it is misaligned.

Super weird that this is only on payouts view! Small thing but important to fix because it's inconsistent. Could potentially be a signal of deeper problem, these list views should ideally be 100% consistent.

**Comment by Jinksi** [comment] 2024-12-05 02:53
The cause, as spotted by @csmcneill, was introduced in #8996 as a temporary CSS fix when many search terms were active on the Transactions table after clicking through from a Payment Activity Card report (unreleased).

https://github.com/Automattic/woocommerce-payments/blob/1fc7a8ac8d74d2ea7f5b87e5cb6e150324fb4233/client/transactions/list/style.scss#L165

This inadvertently impacted the Payouts list styles.

Since we're removing the need for these styles in #9871, I'll open a new PR that removes them, resolving this issue.

**Closed as completed** 2024-12-16 00:05 UTC
Labels: type: bug, priority: medium, focus: reporting
