### ISSUE TITLE
Analytics comparison percentage is missing when WooCommerce Payments is active

### ISSUE THREAD

**Issue by amElnagdy** [Automattic/woocommerce-payments#3938] opened 2022-03-10 12:37 UTC
### Describe the bug
When WooCommerce Payments plugin is active, the percentages will be missed from the WooCommerce Analytics (core – `Dashboard > Analytics`) pages. 

When WooCommerce Payments is active: no % showing under analytics

![https://d.pr/i/Yia1ml](https://d.pr/i/Yia1ml+) 
Full Size: https://d.pr/i/Yia1ml

When WooCommerce Payments is disabled:

![https://d.pr/i/fdrjYk](https://d.pr/i/fdrjYk+) 
Full Size: https://d.pr/i/fdrjYk

### To Reproduce

1. Deactivate WooCommerce Payments and go to Analytics → Overview and notice the %.
2. Activate WooCommerce Payments and go to the same page and notice that % is disappeared.

### Actual behavior
Comparison percentage is missing

### Expected behavior
Comparison % is there.

### Desktop (please complete the following information):

* OS: reproduced by multiple people.
* Browser reproduced by multiple people.
* Version - reproduced by multiple people.

### Additional context

When WooCommerce Payments is active, the data is there but hidden with CSS

![https://d.pr/i/jkXI8I](https://d.pr/i/jkXI8I+) 
Full Size: https://d.pr/i/jkXI8I

Reported in 4841869-zen

**Comment by zoupkat** [comment] 2023-04-14 13:44
Hello there @jrodger !
Another report on this. 619073-zen
Any news on this bug's future? I see the label "needs prioritisation" but there's been no updates since March 16th,2022.
Thank you!

**Comment by jrodger** [comment] 2023-04-25 14:51
No updates I'm afraid, it is on the backlog but I don't have an ETA to share.

One note for anyone looking at this in the future, we are going through a process of ensuring all our JavaScript dependencies are properly up to date, it is possible this issue will be resolved by that but I haven't investigated enough to be sure.

**Comment by francoishvz** [comment] 2023-12-15 08:23
7402686-zd-a8c

**Comment by zmaglica** [comment] 2024-01-24 15:43
This issue impacts reporting, so assigning to Fusion (based on team responsibilities Pc2DNy-3z-p2) @anu-rock . Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by anu-rock** [comment] 2024-01-30 11:41
@zmaglica Thanks for the ping. I've added it to Fusion's board. We'll prioritize it soon.

P.S. I think you accidentally mentioned Moltres instead of Fusion :)

**Comment by zmaglica** [comment] 2024-01-30 16:10
AH, sorry for the mistake. I corrected it.

**Comment by haszari** [comment] 2024-03-21 00:14
@amElnagdy @francoishvz is this still an issue? I did a quick test and I'm seeing the % values correctly. I'm on WooCommerce 8.7 and WooPayments 7.3.

<img width="2058" alt="Screenshot 2024-03-21 at 1 14 06 PM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/059a3d92-b635-4e88-857f-966d02682df9">

**Comment by AashikP** [comment] 2024-03-21 02:21
@haszari  I am unable to replicate this on the latest version of WooCommerce and WooPayments:

![image](https://github.com/Automattic/woocommerce-payments/assets/17475174/d88a1b26-fe9a-4861-9868-40d558ab2e69)

**Comment by haszari** [comment] 2024-03-21 02:50
Thanks @AashikP ! Closing, if we see any regressions like this we can reopen or make a new issue.

**Closed by haszari** 2024-03-21 02:50 UTC
Labels: type: bug, priority: low, needs feedback, category: core, component: reporting, focus: reporting
