### ISSUE TITLE
[GlobalStep] Randomly, an "Error retrieving" error message is displayed while navigating to "Payments->Transactions/Deposits/Disputes pages.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#1764] opened 2021-05-11 14:32 UTC
## Bug Description:
Randomly, an "Error retrieving" error message is displayed while navigating to "Payments->Transactions/Deposits/Disputes pages.

## Environment:
Woocommerce Version : WooCommerce 5.2.2
WooCommerce Payments: v2.4.0
WordPress version: (v5.7)

**PC:**
Windows 10, Mac 10.14.6
Chrome(Version 90.0.4430.93) 
Firefox(Version 87.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete setup wizard using United States address as a store address and selecting WC Payments on Business Details step.
1. On the Home page select Setup WooCommerce Payments task to trigger KYC flow.
1. Complete the KYC flow.
1. Add some products.
1. Go to frontend and purchase some products.
1. Go to Payments->Transactions/Deposties/Disputes.
1. Observe that "Error retrieving" error message is displayed.

## Actual Result:
Randomly, an "Error retrieving" error message is displayed while navigating to "Payments->Transactions/Deposits/Disputes pages.

## Expected Result:
All the content should get loaded smoothly on Payments->Transactions/Deposits/Disputes pages.

## ScreenShot:
![#1764](https://user-images.githubusercontent.com/41110392/117833643-22949980-b294-11eb-8e02-660a94c40144.png)

WooCommerce->Status->Log 
![#1764_1](https://user-images.githubusercontent.com/41110392/117833805-45bf4900-b294-11eb-9f73-d053fb8b0d0a.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shendy-a8c** [comment] 2021-05-21 09:34
I can't reproduce this problem on my end. I understand it's usually hard to reproduce problem that happens intermittently. I'll close this issue for now, but if it happens again, please raise it again.

**Closed by shendy-a8c** 2021-05-21 09:34 UTC
