### ISSUE TITLE
Payment request buttons render when a product/order is below the minimum purchase price for WCPay

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7523] opened 2023-10-20 02:44 UTC
### Describe the bug

If a product is listed below the minimum `amount` ([more info here](https://stripe.com/docs/currencies#minimum-and-maximum-charge-amounts)), payment request buttons (WooPay, Apple Pay, Google Pay) aka "PRBs" will still render on the product page. Additionally, if the cart is below the minimum purchase price because...

1. The cart value is below WCPay's minimum.
2. There is a coupon or other type of discount that reduces the price to be below the minimum.

...these options will render on the cart and checkout pages. However, these products cannot be purchased unless they meet or exceed the minimum purchase price. This means that customers are provided a "false choice" if we render these PRBs when they are unable to use them successfully.

**Note**: It is probable that Stripe Link is also affected here, but I couldn't get the Stripe Link PRB to load on my test site.

### To Reproduce

1. Create a product that is priced below $0.50 USD.
2. Enable your express payment method(s) (or "EPM") of choice.
3. Ensure that the PRBs render on the product page, cart page, and checkout page.
4. Attempt to purchase the product created in step 1 via the PRB on the product page. 
5. Encounter an error: `The selected payment method requires a total amount of at least $0.50`
**Optional**: Repeat step 4, but attempt the purchase on the cart page and/or checkout page. This will reproduce step 5.
6. Create a product that is priced over $0.50 USD.
7. Create a coupon that will reduce the amount of the product created in step 6 to below $0.50 USD—but above $0.00 USD (e.g., a 99% discount) so that a payment will still need to be rendered.
8. Add the product created in step 6 to your cart.
9. Navigate to the cart and/or checkout page and apply the coupon created in step 7.
10. Attempt to complete a purchase using a PRB.
11. Encounter the same issue as step 5.

### Actual behavior

PRBs load on product pages for products that are below the minimum amount. They also load on the cart and checkout pages for carts that are below the minimum amount. This allows the customer to go through a flow that has a zero chance of success.

### Screenshots

![image](https://github.com/Automattic/woocommerce-payments/assets/82999806/5df2c67d-6e12-42c6-89d0-370363cd6ec1)

![image](https://github.com/Automattic/woocommerce-payments/assets/82999806/03f12e69-bb18-410c-88f9-0a8cfeeddc87)

![Markup on 2023-10-19 at 21:40:04](https://github.com/Automattic/woocommerce-payments/assets/82999806/a619807d-59fe-4914-8158-11a0e8eff571)

![Markup on 2023-10-19 at 21:44:15](https://github.com/Automattic/woocommerce-payments/assets/82999806/54520258-92c2-4c32-abaa-948ff30e8886)

### Expected behavior

It would be a better customer experience and could potentially increase conversions if we did not render these elements at all on the product page if the product is below the minimum amount _and_ the cart/checkout pages if the total order value is below the amount.

### Additional context

p1697747321003519-slack-C03V0SP07SL
p1697750000055619-slack-C022WMN88KG

**Comment by pierorocca** [comment] 2023-10-20 16:22
Due to the $0.50 minimums imposed by us on Stripe, even standard checkout transactions will fail. Hiding the buttons still results in a failed purchase attempt.

To resolve this we'll discuss with Stripe and if the floor limit cannot be removed, we'll pursue an option to allow merchants to bypass processing of <$0.50 payment charges or we'll by default not process the charge (but still approve the order).

**Comment by csmcneill** [comment] 2023-10-20 18:25
I checked some of the other gateways, like [PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/?aff=10486&cid=1131038) and [WooCommerce Square](https://woocommerce.com/products/square/?aff=10486&cid=1131038), and they accept $0.01 transactions (verified via the processor's API documentation).

Until we can resolve this limitation (either by working with Stripe to forego the minimum or finding a way to programmatically allow a merchant to "accept" a transaction that is below the minimum), I still think that we should:
1. Hide PRBs on product pages if the amount is below $0.50
2. Hide PRBs on the cart and checkout pages for carts with an amount below $0.50

While it isn't covered in the scope of this issue, I'm also of the thought that we shouldn't render a card element if a cart amount is below $0.50. From a UX perspective, rendering any of this doesn't benefit the customer if it's just going to result in an error.

**Comment by pierorocca** [comment] 2023-10-23 17:19
> I checked some of the other gateways, like [PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/?aff=10486&cid=1131038) and [WooCommerce Square](https://woocommerce.com/products/square/?aff=10486&cid=1131038), and they accept $0.01 transactions (verified via the processor's API documentation).

That's definitely the norm so am quite shocked Stripe has a floor limit at $0.50 that's mandated. We'll find out more from Stripe and go from there in terms of a solution.

**Comment by jessy-p** [comment] 2023-10-23 18:13
This issue impacts International Expansion, In-Person Payments, Local Payment Methods, and Additional Payment Methods (including Apple Pay / Google Pay), so assigning to Fusion (based on team responsibilities Pc2DNy-3z-p2) @anu-rock. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by pierorocca** [comment] 2023-10-23 18:42
@c-shultz @bummytime  this is a good one to test out the split between BE and ME and how we coordinate issues that span UI and back-end. 

The $0.50 floor limit is not a bug but a Stripe feature, albeit not a very good one. Hiding the payment buttons or the cc component is not an appropriate UX approach as it blocks the sales without giving a shopper (or merchant) a path to success.

In chatting with Keala, she indicated she was going to ask Stripe why the floor limit and if it can be removed. Removing it would solve the issue. I'll follow up today and please hold off on any action until we get an answer.

If they can't remove it, her recommendation which is a good one to consider, is to approve the purchase without processing the payment. This allows the sale to occur and we don't incur any costs to process the payment. We'd still charge the merchant the % + per transaction fee as normal, which would cover the net amount owed to the merchant.

**Comment by pierorocca** [comment] 2023-10-23 20:52
A quick note that this is on the agenda with Stripe on Oct 30th. According to Visa's network rules, creating a discriminatory situation where a minimum forces a shopper to use another payment method is prohibited. Thus we cannot hide the impacted payment options as a solution.

**Comment by c-shultz** [comment] 2023-10-25 15:37
Marking as blocked for now pending your discussion with Stripe @pierorocca

**Comment by pierorocca** [comment] 2023-11-02 20:34
Floor limit is being removed as we don't see any downside to doing so and Stripe is indicating the config change can be made easily. Closing.

**Closed as completed by pierorocca** 2023-11-02 20:34 UTC
Labels: type: enhancement, status: blocked, category: core
