### ISSUE TITLE
Inconsistent Thousand/Decimal Separator Format in Exported Transactions with WooPayments Currency Set to Japanese Yen

### ISSUE THREAD

**Issue by shohanhossainnab** [Automattic/woocommerce-payments#7947] opened 2023-12-28 09:34 UTC
### Describe the bug

If WooPayments currency is set to `Yen,` the transaction report in Payments > Transaction looks fine. However, when exported the `Amount`, `Fees`, and `Net` columns don't maintain the correct format. As a result, the amounts become invalid. This is tested with WooCommerce Payments currency set to Japenese Yen.
### To Reproduce

1. Set WooPayments currency to YEN
2. Make some test orders with the following amounts: 5,550, 20,222, etc
3. Go to Payments > Transactions and notice that the report shows as expected.
4. Now, export the report using the download button.
5. Open the CSV and notice the `Amount`, `Fees`, and `Net` columns.
6. You will notice that 5,550 is exported as 55.50 and so on.

### Actual behavior

When exported, the `Amount`, `Fees`, and `Net` columns don't maintain the correct format.
### Screenshots

<img width="3366" alt="Screenshot on 2023-12-28 at 15:30:53" src="https://github.com/Automattic/woocommerce-payments/assets/73883014/0f43c4a9-06cf-4288-b656-77b93b9b1e78">
<img width="3368" alt="Screenshot on 2023-12-28 at 15:32:13" src="https://github.com/Automattic/woocommerce-payments/assets/73883014/20304a39-ab14-4ceb-931c-9920a48bb196">

### Expected behavior

The exported data should match with the dashboard data.

### Additional context

This has been tested with Japanese currency but I think the issue might impact other currencies except USD and EUR.

**Comment by shohanhossainnab** [comment] 2023-12-28 09:41
It was initially reported in 7461857-zen

**Comment by jessy-p** [comment] 2023-12-29 09:04
This issue impacts  Multi-Currency, so assigning to Fractal (based on team responsibilities Pc2DNy-3z-p2) @bborman22 . Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by bborman22** [comment] 2024-01-02 18:59
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/7947?planning-poker) with Zenhub @cesarcosta99 @lovo-h @rafaelzaleski @ricardo

**Comment by cesarcosta99** [comment] 2024-01-10 19:02
I could not reproduce this issue. See report + exported CSV below.

<img width="1681" alt="Screenshot 2024-01-10 at 15 36 55" src="https://github.com/Automattic/woocommerce-payments/assets/10233985/7c270888-1377-4a36-90c4-06e0ee56853b">

@shohanhossainnab, can you check in your test store that the currency setting is set correctly, as shown below? It'd also be good to check the currency of the Stripe account. I tried to play with the currency setting but it didn't change the output of the CSV.

<img width="600" alt="Screenshot 2024-01-10 at 15 38 24" src="https://github.com/Automattic/woocommerce-payments/assets/10233985/33cb6f46-0516-4043-b0ba-a187c58f37ea">

I'm not sure what else could be affecting the values. Looking [at the code](https://github.com/Automattic/woocommerce-payments/blob/21ee31d4effdff23a1a0ee42dcecee3ccd953378/client/transactions/list/index.tsx#L381-L396) that formats the values for exporting it all looks good.

**Comment by shohanhossainnab** [comment] 2024-01-11 04:50
Thanks for checking @cesarcosta99 It looks like it was fixed in the last release of the extension. Not sure if this was reported somewhere else but everything seems to be working fine after updating to 7.0.0. I think you can still replicate using v6.9.2

**Comment by cesarcosta99** [comment] 2024-01-11 14:09
Thanks @shohanhossainnab, I could reproduce it by downgrading to 6.9.2 and confirmed it's fixed upgrading to 7.0.0. I'm going to close this issue as this has been fixed. Feel free to re-open it if the issue ever comes back.

**Closed as completed by cesarcosta99** 2024-01-11 14:09 UTC
Labels: type: bug, priority: high, component: customer multi-currency
