### ISSUE TITLE
Failed Apple Pay consumed YITH gift card.

### ISSUE THREAD

**Issue by geektzu** [Automattic/woocommerce-payments#7858] opened 2023-12-07 19:58 UTC
### Describe the bug
The Apple Pay transaction failed but the gift card was deemed consumed at the backend.
The WooCommerce front-end still treated the gift card as valid, and the user attempted to use WooPayments to pay via credit card for the difference.

The new sales order only registered the difference paid.
But the Stripe transaction was charged at the total amount (including the gift card value)
Not able to refund the total amount via wp-admin or Woo API.

### To Reproduce
1. Add a YITH gift card to a cart
2. Pay via WooPayments Apple Pay 
3. Simulate a failed Apple Pay transaction
4. Continue to pay via WooPayments credit card

### Actual behavior

Order 110087 was attempted with a redeemed gift card.
Order 110087 failed due to AVS mismatch.
The customer attempted a second order.
Order 110089 was created.
The customer completed the order.

### Screenshots

1. Order 110089
![FireShot Capture 002 - Edit order “Order – November 17, 2023 @ 10_08 AM” ‹ JOOLA USA — WordP_ - joolausa com](https://github.com/Automattic/woocommerce-payments/assets/7579242/a9ab3ec4-0942-484a-b8b3-22fa4e32ac2c)
3. Order 110087
![FireShot Capture 001 - Edit order “Order – November 17, 2023 @ 10_06 AM” ‹ JOOLA USA — WordP_ - joolausa com](https://github.com/Automattic/woocommerce-payments/assets/7579242/24ad03f2-3305-4dd3-b18d-4ef3add2474b)

### Expected behavior

The YITH gift card should not be consumed in order 110087 or
The user should not have been allowed to start another new order (110089) when Apple Pay failed (and the same gift card was still deemed valid by the store frontend).

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context
P2: https://woocustomersuccess.wordpress.com/2023/12/06/journey-to-launch-woopayments-for-joola-usa/

**Comment by geektzu** [comment] 2023-12-07 19:58
@pierorocca

**Comment by csmcneill** [comment] 2023-12-07 20:09
@geektzu A couple of recommendations, please:
1. Remove these screenshots from Droplr.
2. Redact any customer information using solid colors (see pbg9X-gVx-p2 for more details).
3. Embed the updated screenshots in GitHub.

Thank you!

**Comment by pierorocca** [comment] 2023-12-07 22:17
@frosso could you add this to your maintenance queue please? I can't tell if the [YITH extension](https://docs.yithemes.com/yith-woocommerce-gift-cards/) is at issue here or if WooPayments is the problem.

**Comment by frosso** [comment] 2023-12-11 09:51
@pierorocca thanks for the ping - would you have any suggestions on priority? On one hand, this seems to be related to the specific YITH extension, but on the other hand it might be hiding a more serious underlying problem.

**Comment by pierorocca** [comment] 2023-12-11 17:49
@frosso given it's tied to a larger account, see the referenced P2, it'd be great if we can at least determine if it's WooPayments or Yith related and the scope of the problem to then determine and assign priorty. I.e. lacking key info to assess severity.

**Comment by gpressutto5** [comment] 2023-12-28 20:32
> Potential long-term solution: Woo core or WooPayments might need to consider rolling back the gift card if an express payment method fails

WooPayments does not control Gift Cards. Instead, the Gift Card extensions are responsible for rolling back when the order fails. For example:
- YITH Gift Card debits the amount from the card when the order is created, before the payment is processed. Then, if the order status is changed to "failed", the amount is credited back to the card.
- WC Gift Cards only debits the amount from the card when the order status is changed to "processing".

The problem with YITH's logic is that if an error happens and for some reason the order is not updated to "failed", the Gift Card will not get its balance back.
This is not the case here because I can see order 110087 was updated to failed:

![image](https://github.com/Automattic/woocommerce-payments/assets/12385501/43d85a63-e853-4155-9029-9c646dece7b4)

That said, is this still an issue? I couldn't reproduce it locally and found the logic to handle failed orders in YITH Gift Cards source code. This logic was added in version 2.3.0, released on 05 August 2019.

**Comment by gpressutto5** [comment] 2024-01-04 17:41
I'm closing this issue for now. Feel free to re-open it if the problem persists.

**Closed as completed by gpressutto5** 2024-01-04 17:41 UTC
Labels: type: bug, priority: low, component: payment request button
