### ISSUE TITLE
[E2E tests] Introduce a set of smoke tests for the plugin

### ISSUE THREAD

**Issue by deepakpathania** [Automattic/woocommerce-payments#8031] opened 2024-01-17 09:20 UTC
#### Problem statement

The release lead has to spend some time trying to upload the final ZIP and running some basic sanity tests to ensure that the release works as expected. This takes time, is cumbersome for each release, and can be automated.
Also, the current E2E tests do not simulate the ZIP upload flow (we upload via CLI) and might miss any issues that we have during the upload stage considering we silence the CLI output.

#### Acceptance criteria

- Introduce a set of smoke tests that simulate:
    - uploading a fresh plugin via the UI flow.
    - running basic sanity tests (make one payment)
    - upgrading the plugin via the UI flow.

**Comment by vbelolapotkov** [comment] 2024-04-04 14:24
Closing as duplicate of #5643

**Closed as completed by vbelolapotkov** 2024-04-04 14:24 UTC
Labels: type: enhancement, category: e2e, focus: devops
