### ISSUE TITLE
Custom options support was removed from non-production environments on WooCommerce 7.9.0+

### ISSUE THREAD

**Issue by eduardoumpierre** [Automattic/woocommerce-payments#6961] opened 2023-08-09 13:56 UTC
### Describe the bug

We are using the deprecated `updateOptions` to update options directly from the client side, but due to [this change on WooCommerce](https://github.com/woocommerce/woocommerce/blob/a2adac35db93800f4c87d9531a9bb38d3c626e4e/plugins/woocommerce/src/Admin/API/Options.php#L111), it is no longer possible to use the `updateOptions` API as it returns false for non-production environments on WooCommerce 7.9.0+.

The lack of permissions breaks the functionalities that depend on that API, returning the following error when interacting with it:
```json
{
    "code": "woocommerce_rest_cannot_update",
    "message": "Sorry, you cannot manage these options.",
    "data": {
        "status": 403
    }
}
```

Example URL:  http://localhost:8082/wp-json/wc-admin/options?_locale=user

Here is the list of the files that use this API:
- [fraud-risk-tools-banner/index.tsx#L22](https://github.com/Automattic/woocommerce-payments/blob/develop/client/components/fraud-risk-tools-banner/index.tsx#L22)
- [additional-methods-setup/upe-preview-methods-selector/setup-complete-task.js#L78](https://github.com/Automattic/woocommerce-payments/blob/develop/client/additional-methods-setup/upe-preview-methods-selector/setup-complete-task.js#L78)
- [multi-currency-setup/tasks/setup-complete-task/index.js#L24](https://github.com/Automattic/woocommerce-payments/blob/develop/client/multi-currency-setup/tasks/setup-complete-task/index.js#L24)
- [overview/task-list/index.js#L19](https://github.com/Automattic/woocommerce-payments/blob/develop/client/overview/task-list/index.js#L19)
- [settings/fraud-protection/tour/index.tsx#L53](https://github.com/Automattic/woocommerce-payments/blob/develop/client/settings/fraud-protection/tour/index.tsx#L53)
- [payment-methods/capability-request/capability-request-notice.tsx#L118](https://github.com/Automattic/woocommerce-payments/blob/develop/client/payment-methods/capability-request/capability-request-notice.tsx#L118)

### To Reproduce

1. Upgrade WooCommerce to 7.9.0+
2. Open the developer console
3. Go to the **Payments** page on your test site (`/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Foverview`)
4. You should see some 403 errors
5. Click on the "Dismiss" button from the FRT Discoverability Banner

<img width="694" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/16882226/657693aa-cabb-4093-a522-f8850712b616">

6. Refresh the page
7. The FRT Discoverability banner will be visible again due to this issue

### Expected behavior

- The FRT Discoverability Banner shouldn't be visible anymore after clicking on the "Dismiss" button

### Additional context

p1690987421187229-slack-C01B8KNUYSW

**Comment by allie500** [comment] 2023-08-09 19:43
Thanks for opening this issue! I've done a bit of research on it today. I'll be AFK the rest of the week, but let's link up early next week to try and tackle this.

**Comment by RadoslavGeorgiev** [comment] 2023-08-10 09:30
I'm looking into this issues during the Gamma Triage process. AFAICT, @Automattic/sigma is handling it, so I'm moving it to the "Other Teams" queue. Please ping me if this assessment is incorrect.

**Comment by tpaksu** [comment] 2023-09-20 08:30
@eduardoumpierre @allie500 I think it works on the latest version of WC, can you check if it's still the case?

**Comment by tpaksu** [comment] 2023-09-20 08:43
Nevermind, it seems it only works on my machine. Couldn't reproduce it. I'm using the development version of WooCommerce, which I cloned from the monorepo and attached using a volume and a symlink. But I tried installing the production version to reproduce it, still works for me. 

<img width="629" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/3295/dc200104-6f48-4733-970e-0943092cf900">

**Comment by allie500** [comment] 2023-10-18 19:35
**Update:** 
I have opened a draft PR in the Woo Core repo to add these option keys to `get_default_option_permissions` method in Options API as a short term fix. I'm just waiting to hear back from another team about their use of the `updateOptions` API so I can finish the PR changes and open it for review.

**Comment by allie500** [comment] 2023-11-03 17:38
**Update:**
I have also opened a RFC to start a discussion about the best, long term solution for this issue.
paJDYF-bfd-p2

**Comment by allie500** [comment] 2023-11-16 18:42
**Update:**
There is a filter available that we can use to add our options to the Woo Core option allow list. I have re-opened draft PR #7483. I still need to test all the options and write up some testing instructions for code review, but so far the filter works for getting and setting the first option I tested with.

**Closed as completed** 2023-11-17 20:30 UTC
Labels: type: bug, status: has pr, component: settings, category: core, category: devops
