### ISSUE TITLE
Ensure SEPA can work without CC payment method

### ISSUE THREAD

**Issue by superdav42** [Automattic/woocommerce-payments#1615] opened 2021-04-19 15:35 UTC
Currently SEPA breaks down if CC Payment method is disabled. There are probably many issues involved in this problem we just need to investigate and find a solution.

**Comment by harriswong** [comment] 2021-04-27 22:11
When you were testing this, how did you disable CC Payment method please?

**Comment by harriswong** [comment] 2021-04-27 22:47
I got it.

To reproduce
1. Turn off WooCommerce Payments as a whole in `wp-admin/admin.php?page=wc-settings&tab=checkout`
![image](https://user-images.githubusercontent.com/572862/116321779-f8ad8400-a777-11eb-81be-b7af9448568a.png)
2. Checkout with SEPA feature flag on. We will see SEPA as available payment method but we can't enter anything in the input field:
![image](https://user-images.githubusercontent.com/572862/116321903-3d391f80-a778-11eb-9e2c-d0583b91f126.png)

**Comment by harriswong** [comment] 2021-04-28 21:12
Our gateway methods inherit classes from core in the following manner:
```
WC_Settings_API [wc core]
  - WC_Payment_Gateway [wc core]
  	- WC_Payment_Gateway_CC  [wc core, credit card]
  		- WC_Payment_Gateway_WCPay [Gateway class for WooCommerce Payments] 
  			- CC_Payment_Gateway [blank]
  			- Giropay_Payment_Gateway
  			- Sepa_Payment_Gateway
  			- Sofort_Payment_Gateway
 ```

Each of our WCPay payment gateway has its own flag to control enable/disable ([example](https://github.com/Automattic/woocommerce-payments/blob/0ece4e0791971a08e622134ff60d0e417e083392/includes/payment-methods/class-sepa-payment-gateway.php#L31)). I think I am gonna start by pulling “credit card” specific logic from WC_Payment_Gateway_WCPay into CC_Payment_Gateway . If i get these separated, then the settings UI should be able to rely on these enable/disable flags, decoupling the dependency between cc and SEPA.

**Comment by jrodger** [comment] 2021-05-06 10:43
As part of this refactoring, would it makes sense to consider https://github.com/Automattic/woocommerce-payments/issues/1614 as well?

**Comment by harriswong** [comment] 2021-05-14 22:57
Blocked. Waiting on UPE's status.

**Comment by harriswong** [comment] 2021-05-19 15:48
Closing this PR since we are switching to UPE. We no longer need to have multiple payment gateways to hide under "WooCommerce Payments" gateway. 

Ref: https://github.com/Automattic/woocommerce-payments/issues/1826

**Closed by harriswong** 2021-05-19 15:48 UTC
Labels: component: sepa, pr: needs review, status: blocked
