### ISSUE TITLE
Implement "I'm testing" checkbox for admins in checkout form

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#6698] opened 2023-07-06 18:28 UTC
One annoying and potentially tricky issue that comes up on occasion for the Payment Operations team is merchants who "test" WC Pay while in live mode, sometimes with many transactions for large amounts of money. They then refund themselves and expect to get all their money back. However, they don't realize until it's too late that [transaction fees are not refunded](https://woocommerce.com/document/woocommerce-payments/fees-and-debits/why-arent-fees-refunded/).

Latest example is here: p1688207566005969-slack-CJK2SLCJH

Usually we end up refunding the fees out of own pocket, but ideally we could prevent this by adding a checkbox to the checkout form **for admins only** (and maybe other non-customer roles) that would send the transaction through in test mode as a one-off, while keeping the public/customer-facing checkout form in live mode.

A super amateurish mockup:

<img width="635" alt="Screenshot taken on 2023-07-06 at 18 27 01 UTC@2x" src="https://github.com/Automattic/woocommerce-payments/assets/5512652/ee9a4904-e804-4e03-861a-f93e2f747445">

**Comment by aheckler** [comment] 2023-07-06 18:30
Another thought: the merchant isn't going to be entering a test card number either, so if they check this box, we'll have to dynamically rewrite the request to use the `4242` card or some other such test number.

**Comment by aheckler** [comment] 2023-07-06 18:36
cc @pierorocca

**Comment by csmcneill** [comment] 2023-07-06 19:05
What if we could do the inverse for admin roles? 

Meaning, what if we defaulted to the test mode flow for admin users, and they had to select a button to reload the page and render the live payment flow?

Super janky rough mockup:

![Markup on 2023-07-06 at 14:06:01](https://github.com/Automattic/woocommerce-payments/assets/82999806/d70eacb9-f30c-489b-8719-4c1c55ff4849)

**Comment by pierorocca** [comment] 2023-07-06 19:54
> that would send the transaction through in test mode as a one-off, while keeping the public/customer-facing checkout form in live mode.

Did this merchant intend to "test" in Live mode because they wanted to prove it was working for "real" or did they not know they were in Live mode? These are 2 different problems to solve. 

If the former, over the years I've supported many merchants that had a compulsion to test live in production with real cards but not have the transactions settle and hit their ledger. At Amex I had special pure white EMV cards with no embossing. The card would go through auth but it would never capture and settle keeping it off of their ledger and off of Amex's books. It was a unique setup and not one we have access through Stripe.  [Stripe prohibits using real cards to test in live mode](https://stripe.com/docs/testing#use-test-cards). That likely means the card networks also prohibit it.

In Adam's mockup, the issue I see is a merchant is going to input a real card number in test mode and that will get sent along with test API keys and will likely fail or be blocked by Stripe. It's also a violation of Stripe's terms. Having real cards in a test environment creates PCI (payments security standards) issues so it's always prohibited. So if they really, really want to make a transaction in live mode with a real card Stripe prohibits it. It we ignored that, I'd suggest the route of an inline information warning for admins and shop managers that testing in live mode is prohibited and service fees are not refundable with a learn more link.

If the issue is the merchant didn't know they were live, our current banner notifications indicating the site is live or in test mode are barely noticeable. The above notification proposal based on the new [notification system (for blocks)](https://woocheckout.wordpress.com/2023/05/11/shopper-notices-usage-guidelines/) would address this and complement the other "Test" banners that need significant improvement.

Here's the back end notification that only appears on the Payments Settings screen:
![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/e352a26b-a9e5-433c-ba60-ab0077ca1d25)

And the front-end notification that blends in and more critically it doesn't re-appear if the banner is dismissed and the browser closed and re-opened. The dismiss should only be applied for that session.
![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/88e302bb-b0c2-4e3e-b2f4-9d9bacaa0986)

**Comment by aheckler** [comment] 2023-07-06 19:59
> In Adam's mockup, the issue I see is a merchant is going to input a real card number in test mode and that will get sent along with test API keys and will likely fail or be blocked by Stripe.

Yeah, I addressed this in [this comment](https://github.com/Automattic/woocommerce-payments/issues/6698#issuecomment-1624137086), but since the card form is in an iframe, I'm not sure if rewriting the card number like that would even be possible.

**Comment by pierorocca** [comment] 2023-07-06 20:24
I saw that. I don't believe it'll solve for a merchant who is going to try and test in live mode. **IF** they're logged in, they'll ignore switching to test mode or checking the box and the same outcome will happen. If they're a guest, e.g. testing on the kid's tablet or partner's phone, they'll never see the functionality.

From personal experience and from the ticket, he knew he was testing live he just didn't understand the consequences.

**Comment by frosso** [comment] 2023-07-20 09:44
We'd also need to consider how implementing something similar would affect PRBs like Apple Pay/Google Pay & WooPay.

**Comment by htdat** [comment] 2023-07-27 06:47
@frosso - I think Heisenberg would own this issue as it's falling into product area `checkout UI` Pc2DNy-3z-p2? 

--- 

FYI. I am doing triage as part of Gamma Triage process PcreKM-yM-p2.

**Comment by frosso** [comment] 2023-07-27 08:19
@htdat it seems that the "Checkout UI" knowledge that is referred by Pc2DNy-3z-p2 is related to WooPay?

**Comment by pierorocca** [comment] 2023-07-27 16:52
@frosso before any changes are made to this let's connect on the proposal before any coding begins. The above suggestions are well intentioned and may trade one problem that's impacted a handful of merchants while creating the potential to create new problems affecting a broader population of merchants. i.e. let's move with great care and extra checkins with stakeholders on this issue.

**Comment by htdat** [comment] 2023-08-02 02:40
I am going to close this issue based on more information in this convo 
p1690777529502079-slack-C02L752DS0G

If anyone wants to re-open it, feel free to do so and add more thoughts. Thanks everyone.

**Closed as not planned** 2023-08-02 02:40 UTC
Labels: type: enhancement, priority: low, component: checkout
