### ISSUE TITLE
Failed orders should include more info on transaction details page

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#5713] opened 2023-03-09 19:46 UTC
If an order fails for some reason, say insufficient funds, there's a lack of information about that on the transaction details page. Here's an example screenshot:

![Screenshot taken on 2023-03-09 at 19 43 44 UTC@2x](https://user-images.githubusercontent.com/5512652/224136810-29d7e030-691c-4965-8fed-8275091cc894.png)

You can see there that this order, although it failed, has two bits of info present:

- An order number
- A failure/decline reason

Here's the corresponding transaction page under Payments > Transactions:

![Screenshot taken on 2023-03-09 at 19 45 03 UTC@2x](https://user-images.githubusercontent.com/5512652/224137080-d9d9052a-fd4b-43fe-a07c-13d1e2ecbfbc.png)

Not only is the order number missing, but the decline reason is nowhere to be seen.

In the interest of giving our merchants as much info as we can, IMHO we should include this in the transaction detail page.

This idea stems from this post: paJDYF-7eg-p2

**Comment by jessy-p** [comment] 2024-01-23 15:02
This issue impacts Transactions (Auth and Capture), so assigning to Pulsar (based on team responsibilities Pc2DNy-3z-p2) @kalessil. Assigning as part of Gamma Triage process PcreKM-yM-p2.

Tagging as part of re-evaluating older issues in the backlog, please have a look and close if no longer relevant.

**Comment by kalessil** [comment] 2024-02-19 10:57
@mgascam : please re-evaluate.

**Comment by mgascam** [comment] 2024-12-17 12:10
Hi @aheckler, I know some time has passed since you reported this issue, but I was wondering if you could share the steps to reproduce a failed order like the one you described. I'm struggling to recreate it on my end.

For example, when I use a test card that fails due to insufficient funds, I can't get past the checkout step. The order transitions to the "Failed" status, but no payment intent is created on Stripe's end, so I can't access the payment details view.

For context, I'm working on a branch that addresses this issue. It includes unit tests, but I’d like to add testing instructions to verify this flow manually. Unfortunately, I haven’t been able to find a way to trigger it yet, which is why I’m reaching out.

Thanks in advance for your help!

**Comment by aheckler** [comment] 2024-12-17 17:12
@mgascam I tried a couple different ways but I don't see how to replicate that either. :/ @AashikP or @francoishvz may know of a way?

**Comment by AashikP** [comment] 2024-12-18 07:10
I could not replicate this in test mode

<img width="2358" alt="Image" src="https://github.com/user-attachments/assets/2320c06c-259b-4312-8ea6-13928aae4540" />

**Comment by AashikP** [comment] 2024-12-18 07:14
I've seen a conflict in most cases where the order number is not linked. I just realized we also have this latest example for WooPay: p1734327561455129-slack-C7U3Y3VMY

cc @nicdwilson  @reykjalin

**Comment by mgascam** [comment] 2024-12-18 15:29
Thanks for attempting to reproduce the issue, @aheckler and @AashikP. Other folks in Gamma [also couldn't reproduce it](https://github.com/Automattic/woocommerce-payments/pull/9980#pullrequestreview-2511317485). Since this issue was reported quite some time ago, it's possible that the flow has changed, making it harder to replicate, or it could be related to testing mode.

Regardless, we are now including the failure reason in the timeline after [this PR](https://github.com/Automattic/woocommerce-payments/pull/9980) is merged. This will show the failure reason provided by Stripe, which was previously missing. I expect this change will help clarify why transactions fail.

Regarding the order, I didn’t include any changes because we already include it—as long as the order metadata is linked to the payment intent in Stripe, regardless of whether the payment intent fails or not.

**Closed as completed** 2024-12-18 15:39 UTC
Labels: component: timeline and events, category: core, focus: payments acceptance & processing
