### ISSUE TITLE
Setting up a store to have 0 decimal places creates total calculation errors for Additional Payment Methods, including Google Pay and Apple Pay.

### ISSUE THREAD

**Issue by sverleis** [Automattic/woocommerce-payments#6729] opened 2023-07-11 13:06 UTC
### Describe the bug

When a site has been set up to not show decimal places ( **WP Admin → WooCommerce → Settings → General** ), the express checkout options have a bit of a hiccup in calculating the totals, starting off by adding 2 decimal places anyway, causing the product to potentially cost 100 times less.

### To Reproduce

1. Under **WP Admin → WooCommerce → Settings → General**, set the `Currency options` to have **Number of decimals** = `0`.
2. Purchase a product with either Google Pay or Apple Pay
3. Total is incorrect, and only in certain instances, corrects itself.

### Actual behavior

Total is calculated with the incorrect total. In some tests, this does not revert. In others, it adjusts correctly.

### Screenshots

Incorrect: 
![image](https://github.com/Automattic/woocommerce-payments/assets/16252298/e804090a-83a4-4410-9f2e-9c374b0bf219)

Apple correcting after delay
![Screen Capture on 2023-07-11 at 15-02-58](https://github.com/Automattic/woocommerce-payments/assets/16252298/95028909-4a9c-46a6-901a-24eda2023598)

### Expected behavior

When decimals are set to the default 2, there are no calculation issues. 
This should ideally happen when decimal places are not set to 2 units.

### Desktop (please complete the following information):

* OS: macOS 13.4.1 (22F82)
* Browser 
Chrome - Version 114.0.5735.198 (Official Build) (arm64)
Safari - Version 16.5.1 (18615.2.9.11.7)

### Additional context

Linked to 6515204-zen

**Comment by htdat** [comment] 2023-07-12 22:59
This issue impacts `Additional Payment Methods (including Apple Pay / Google Pay)`, so assigning to team Fusion (@anu-rock as team lead) (based on team responsibilities Pc2DNy-3z-p2). Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by anu-rock** [comment] 2023-07-14 11:07
Moved this to Fusion's backlog. Thanks, @htdat.

**Comment by elazzabi** [comment] 2023-07-28 13:39
I couldn't replicate this with GPay, tried a few times with EUR and HUF as suggested:

<img width="354" alt="Screenshot 2023-07-28 at 14 38 45" src="https://github.com/Automattic/woocommerce-payments/assets/12542046/b87d098a-0dc9-473d-b352-57721b92ab68">
<img width="593" alt="Screenshot 2023-07-28 at 14 38 39" src="https://github.com/Automattic/woocommerce-payments/assets/12542046/75bff8a4-917b-4397-954a-286a975a9144">

I'll keep looking

**Comment by pierorocca** [comment] 2023-10-25 17:52
@frosso this would be a good one to check with urgency if it's still reproducible given the potential consequences of a 100 times smaller total.

**Comment by mordeth** [comment] 2023-10-27 10:09
I couldn't replicate this with Apple Pay. I have tried multiple times with JPY, HUF, and EUR without any luck.

<img width="450" alt="Screenshot 2023-10-27 at 13 04 33" src="https://github.com/Automattic/woocommerce-payments/assets/8667118/de4e49cc-1eaa-4d08-b023-66f16affe1d7">

<img width="437" alt="Screenshot 2023-10-27 at 13 04 57" src="https://github.com/Automattic/woocommerce-payments/assets/8667118/200e9c2c-4be1-45e2-801a-a304320b525c">

**Comment by pierorocca** [comment] 2023-10-27 16:10
WooPay had a similar issue that was resolved but I believe the fix was in WooPay code not WooPayments.

https://github.com/Automattic/woocommerce-payments/pull/7055

**Comment by frosso** [comment] 2023-11-14 14:50
Left todo: I see that there are multiple reproduction attempts. Validate if still valid, otherwise close.

**Comment by gpressutto5** [comment] 2023-12-15 18:53
I tried using many different settings and couldn't reproduce.

**Closed as completed by gpressutto5** 2023-12-15 18:53 UTC
Labels: type: bug, component: payment request button
