### ISSUE TITLE
Payment initially succeeds in Stripe, then fails with "The parameter application_fee_amount cannot be updated on a PaymentIntent after a capture has already been made."

### ISSUE THREAD

**Issue by seanbelly** [Automattic/woocommerce-payments#5310] opened 2022-12-19 17:34 UTC
**Describe the bug**

Payment initially succeeds in Stripe, then fails with "The parameter application_fee_amount cannot be updated on a PaymentIntent after a capture has already been made." 

* Seemingly at random, the `.succeeded` webhooks appear not to be arriving.
* The last response received by the site is the payment intent confirmed
* The `payment_intent.succeeded` is not logged on the site
WC Payments say the` payment_intent.succeeded` webhook succeeds (200 response)
Resending it fails without explanation
* `wcpay_track_new_order` appears to have completed without error but there is no corresponding entry in the payments log
* In the site transaction details, no order ID is shown but the payment is shown as authorised: ![lKePjF.png](https://user-images.githubusercontent.com/892040/208472455-8d38efae-3cab-4f50-b1e1-1e7a995ce56f.png)
* The transactions list shows this in multiple cases: ![ipPjAl.png](https://user-images.githubusercontent.com/892040/208472456-4568c00e-fa46-4aec-be5d-e0c25bfe69c1.png)
* We believe the re-used `pi_ `is something of a red herring, created because the previous payment by the same customer failed to complete correctly. 

* Note: Would it be possible to focus on why the payment is not completed and the transaction is not retaining the order ID?

**To Reproduce**

We don't have the steps to reproduce at this time. Please see p1670273606982649-slack-C02C00HCJ8J

**Expected behavior**

Orders should be shown as pending once the payment has cleared, not cancelled. 

**Screenshots**

In the site transaction details, no order ID is shown but the payment is shown as authorized: 

![lKePjF.png](https://user-images.githubusercontent.com/892040/208472455-8d38efae-3cab-4f50-b1e1-1e7a995ce56f.png)

The transactions list shows this in multiple cases: 

![ipPjAl.png](https://user-images.githubusercontent.com/892040/208472456-4568c00e-fa46-4aec-be5d-e0c25bfe69c1.png)

**Environment (please complete the following information):**

 - WP Version: 6.1.1
 - WC Version: 7.1.0
 - Stripe Plugin Version: 7.0.1
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed: 

**Additional context**
5764782-zd-woothemes

Other potential instances: 
5778834-zd-woothemes
5226400-zd-woothemes
5634064-zd-woothemes
5745918-zd-woothemes

**Comment by thisissandip** [comment] 2022-12-22 12:36
5522285-zen 
4883808-zen 
5780095-zen

Pinged for prioritization: p1671712953039099/1670273606.982649-slack-C02C00HCJ8J

**Comment by kaushikasomaiya** [comment] 2022-12-28 12:32
5820514-zen

**Comment by jessy-p** [comment] 2022-12-29 09:07
Marking high priority due to large number of merchant reports

**Comment by RadoslavGeorgiev** [comment] 2023-01-24 09:29
@Automattic/pulsar are you planning to handle this as part of your backlog, as it seems checkout-related?

**Comment by kalessil** [comment] 2023-02-03 08:49
We'll be able to look into the details in ~2 weeks - currently we don't have needed capacity.

**Comment by kalessil** [comment] 2023-03-01 09:24
Intermediate state: It needs to be clarified why, but intent caching in session, which aims to reduce the amount of created intents, uses a processed intent. There are cases when this is combined with undelivered hooks. Still, we don't have a reproducible scenario to pinpoint the exact root cause.

My guesses:
- concurrency: the creation of multiple orders in parallel
- lack of error handling on the client side

I'll go ahead with a draft, which needs know-how from @anu-rock, and address potential flaws I can spot in implementation. As we need a reliable debugging approach here, we have to guess here.

**Comment by kaushikasomaiya** [comment] 2023-04-05 11:33
42250439-hc

> Occurs on purchasing the same product twice

**Comment by maxlaf** [comment] 2023-04-11 18:43
6178735-zen. FWIW, this user only has test mode transactions.

**Comment by kalessil** [comment] 2024-02-19 10:45
Needs to be re-evaluated with regards to duplicate changes prevention work from the last year.

**Comment by kalessil** [comment] 2024-02-28 10:57
I checked the application logs and can not find any recent occurrences of this error.
As the latest report is 10 months old, I'll close the issue: if it surfaces again, feel free to reopen the ticket.

**Closed as completed by kalessil** 2024-02-28 10:57 UTC
Labels: type: bug, priority: high, component: application fees, category: core
