### ISSUE TITLE
Uncaught error in WC_Payments_Admin::construct() referencing incorrect instance

### ISSUE THREAD

**Issue by nerrad** [Automattic/woocommerce-payments#6869] opened 2023-07-27 14:52 UTC
### Describe the bug

See ZH ticket for original report: 6564227-zd-woothemes

The user is reporting this error which triggered the WordPress fatal error protection:

```
An error of type E_ERROR was caused in line 112 of the file /nas/content/live/mayhem/wp-content/plugins/woocommerce-payments/includes/admin/class-wc-payments-admin.php. Error message: Uncaught TypeError: Argument 5 passed to WC_Payments_Admin::__construct() must be an instance of WC_Payments_Incentives_Service, instance of WC_Payments_Order_Service given, called in /nas/content/live/mayhem/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php on line 604 and defined in /nas/content/live/mayhem/wp-content/plugins/woocommerce-payments/includes/admin/class-wc-payments-admin.php:112
Stack trace:
#0 /nas/content/live/mayhem/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php(604): WC_Payments_Admin->__construct(Object(WC_Payments_API_Client), Object(WCPay\Payment_Methods\CC_Payment_Gateway), Object(WC_Payments_Account), Object(WC_Payments_Onboarding_Service), Object(WC_Payments_Order_Service), Object(WC_Payments_Incentives_Service), Object(WCPay\Database_Cache))
#1 /nas/content/live/mayhem/wp-content/plugins/woocommerce-payments/woocommerce-payments.php(153): WC_Payments::init()
#2 /nas/content/live/mayhem/wp-includes/class-wp-hook.php(308): wcpay_init('')
```

### To Reproduce
The user received the WordPress error protection email notifying about the error.

Details about the reported environment:

WordPress version: 6.2.2
Active theme: Flatsome Child (version 3.0)
Current plugin: WooCommerce Payments (version 6.2.0)
PHP version 7.4.33.2

I'm just getting this issue up quickly since it's a fatal. ~I'll spend a bit of time looking into the stack trace and see if I can spot what might trigger it.~

It looks like it was introduce in this PR: https://github.com/Automattic/woocommerce-payments/pull/6373

**Comment by jrodger** [comment] 2023-07-27 15:18
Thanks for reporting this @nerrad. I've reviewed the PR and I agree it's likely the cause of the error. As you mentioned in the ticket, I also suspect this is some unlucky timing during the plugin upgrade (The file with the constructor being updated and the calling code not being updated).

I'd suggest we give this a few days to see if anything else comes to light through the ticket, but then close the issue.

**Comment by nerrad** [comment] 2023-07-27 15:21
Looking through the changes in the PR, the error seems kind of odd, since I see in current code for 6.2.0 `WC_Payments_Incentive_Service` is the 6th argument (not 5th).

I wonder if this error happened during the update process. I'll check with the user and see if they are still experiencing errors.

(jynx, I had this reply in progress when you responded @jrodger :) )

**Comment by nerrad** [comment] 2023-07-27 15:26
The user replied:

> Hi Darren - it is still happening everytime I try to update my plug ins.  I reverted back to an old version of the website, but can't update without this happening.

I'm still working on confirming whether if they let things update and finish whether they are unable to access their admin pages. I still suspect this is just the WordPress email getting triggered.

However, regardless of what they report back, it does look like there's some hardening needing done here to prevent the initialization of the class with the incorrect arguments if the old class is in memory. Even a try/catch block might be useful here (do some graceful error handling)?

**Comment by htdat** [comment] 2023-10-30 07:15
Related https://github.com/Automattic/woocommerce-payments/issues/7464

We (WooPayments teams) are having a topic regarding the same issue paJDYF-aZa-p2

Anyway, since there is no more update, I am going to close this issue.

**Closed as completed by htdat** 2023-10-30 07:15 UTC
Labels: type: bug, category: core, needs triage
