### ISSUE TITLE
WooCommerce Payments asking to "Finish Setup"

### ISSUE THREAD

**Issue by madisoncmiller** [Automattic/woocommerce-payments#2511] opened 2021-07-21 21:44 UTC
Note: We have not been able to reproduce this issue. We have gotten multiple reports of it from customers. Devs gave permission to open an issue. 

Issue: When clicking on "deposits", "transactions", or "disputes" it does not go to the report. Instead, the user gets a finish setup page. When they click the "finish setup" button it goes to the set up dashboard even if they have it configured. Customer can't see the deposit, transaction, or dispute history. 

Issue here: 4163046-zen

Public question here: https://wordpress.org/support/topic/keeps-asking-to-finish-setup/

Slack conversation here with more examples of the issue: p1626553885410700-slack-C7U3Y3VMY

**Comment by stephhjacq** [comment] 2021-07-21 21:47
Another report in 4165121-zen

- User tried reconnecting Jetpack, issue persisted.
- Tried making another admin account with a different email address, was still unable to 'Finish setup'. 

The user needs to access their transaction history for tax reporting, but is unable to view it.

**Comment by darcie** [comment] 2021-07-21 21:49
Report in 4162662-zen  

This site cannot complete setup, despite previously using WooCommerce Payments for some time. All admins are seeing the setup page and cannot access deposits and transactions pages. They have tried connecting in another browser, as well as reconnecting Jetpack.

**Comment by dechov** [comment] 2021-07-21 22:08
Based on the recent timing of reports, it could be linked to https://github.com/Automattic/woocommerce-payments/pull/2275 (released in 2.7.0 last week), which does involve a redirect to the "Finish setup" screen (as reported) _but only if WCPay isn't connected_. However, it's been hard to imagine (and reproduce) how it could possibly appear not connected in such very specific cases only.

Going by [this forum reply](https://wordpress.org/support/topic/keeps-asking-to-finish-setup/#post-14686197), the behavior appears to not depend on the admin user (as I initially thought), but to something more specific about the browser / environment.

**Comment by csmcneill** [comment] 2021-07-21 22:29
Report in 4162412-zen

**Comment by simplysaru** [comment] 2021-07-22 17:24
More reports in 4163020-zen and 4162323-zen

**Comment by selectedselections** [comment] 2021-07-22 17:34
reported in 4164802-zen

**Comment by solstudioim** [comment] 2021-07-23 06:48
Reported in 4157754-Zen as well

The user said: "I confirmed to press that finish setup button. That screen keeps coming up."

**Comment by stephhjacq** [comment] 2021-07-23 15:36
In 4156165-zen, an admin user was created for support to verify what was happening. When I log in with that, I can see the data. When the user logs in with this same account, they see only the last transaction posted, and the 'Finish setup' prompt.

**Comment by stephhjacq** [comment] 2021-07-23 15:40
Another report in 4159847-zen

**Comment by dreamtooloud** [comment] 2021-07-23 18:23
Another report: 4164660-zen

**Comment by htdat** [comment] 2021-07-24 13:05
In 4164660-zen, this customer provided this experience: 
![Screenshot 2021-07-23 105031](https://user-images.githubusercontent.com/10045087/126869240-91132751-ab08-4b16-9b34-3add4f58aa93.jpg)

In 4163046-zen, this text was mentioned: 

> If I click on "deposits", "transactions", or "disputes" I do not get my report. Instead I get:
> 
> "Collect payments, track cash flow, and manage recurring revenue directly from your store's dashboard -- all without setup costs or monthly fees.
> By clicking "Finish," you agree to the Terms of Service"
> 
> with a "Finish Setup" button
> 
> When I click the "finish setup" button it takes me to my dashboard which is completely setup (Plus, I have used these reporting pages previously).

It turns out it's from this PR https://github.com/Automattic/woocommerce-payments/pull/1963
I needed to set up as `treatment` to see the experience above.

**Comment by htdat** [comment] 2021-07-24 13:20
@moon0326 ^ 
Relevant convo p1627132786047600/1626741938.458500-slack-CGGCLBN58

**Comment by jesscga** [comment] 2021-07-24 16:35
Also reported in 4160193-zen

**Comment by dphyled** [comment] 2021-07-26 01:40
In the 4164802-zen ticket reported above by @selectedselections , they provided an admin user for us, and I was able to log  in and view the Deposits/Transactions pages without issues.

**Comment by htdat** [comment] 2021-07-26 04:35
Hi all 👋 

We are able to stop this issue from our end without the need for a new release for the WooCommerce Payments plugin with a few notes: 

1, The issue will be resolved in 2 hours or less for all users having this issue. 
2, In case the issue is not resolved, users can use a plugin like Transients Manager https://wordpress.org/plugins/transients-manager/ and delete this item `abtest_variation_wcpay_empty_state_preview_mode_v1`.

**Comment by theabhig** [comment] 2021-07-26 05:29
Also reported in 4169865-zen

**Comment by theabhig** [comment] 2021-07-26 05:36
Another report in 4170135-zen . Thanks

**Comment by theabhig** [comment] 2021-07-27 04:28
Hi @htdat 👋

I've had a user in 4159847-zen saying they don't have a transient matching that name and the update didn't appear to work on their site but rolling back to 2.6.1 did work for them.

Would that transient item potentially be under any other name?

Thanks!

**Comment by htdat** [comment] 2021-07-27 09:09
Hi @theabhig, 

> Would that transient item potentially be under any other name? 

I've double checked and confirm that this transient name `abtest_variation_wcpay_empty_state_preview_mode_v1` is still correct. 

> I've had a user in 4159847-zen saying they don't have a transient matching that name and the update didn't appear to work on their site but rolling back to 2.6.1 did work for them.
> Also if the update in 2.7.0 didn't work, would there be any actions the user can take to check why?

If no transient matches with `abtest_variation_wcpay_empty_state_preview_mode_v1`, that's good too. I would ask this user to check again if they're still seeing issues with WCPay 2.7.1 or not (we've just released 2.7.1 but it is not to address this issue).

Note: *deleting the transient is only needed if the issue is not automatically resolved.*

**Comment by htdat** [comment] 2021-07-30 01:35
Reopening... as the root cause of this issue is really resolved here #2555

**Closed** 2021-08-02 05:58 UTC
Labels: priority: high, status: has PR, type: bug

**Comment by dechov** [comment] 2021-08-02 19:39
Re-closing due to a) https://github.com/Automattic/woocommerce-payments/pull/2555 being merged and slated for this week's release, and b) no new reports in a week now, or since shortly after the back-end fix – thank you @htdat!

Feel free to re-open if there are reports of the issue still persisting on any plugin version, since an update _should_ be unnecessary for addressing the issue and it would be good to understand if/why that isn't the case.

**Comment by aheckler** [comment] 2021-08-05 17:53
4199194-zen claims to be seeing this issue. I am trying to confirm what version they are on, it might be an old one.

**Comment by htdat** [comment] 2021-08-06 02:26
> 4199194-zen claims to be seeing this issue. I am trying to confirm what version they are on, it might be an old one.

It's a bit misleading but the issue on this ticket is not this GitHub issue.

The error message was "There was a problem redirecting you to the account connection page. Please try again."
![](https://d.pr/i/PCQK4U+)

=> this is different from the error here https://github.com/Automattic/woocommerce-payments/issues/2511#issuecomment-886051004
