### ISSUE TITLE
Fetch data for TotalPaymentsActivity component

### ISSUE THREAD

**Issue by naman03malhotra** [Automattic/woocommerce-payments#8518] opened 2024-03-28 16:19 UTC

**Comment by zmaglica** [comment] 2024-03-30 13:51
@naman03malhotra Could you please fill issue description and apply labels if you can, so we can triage it? Thank you in advance.

**Comment by naman03malhotra** [comment] 2024-04-08 07:54
Hey Zvonimir, thanks for the ping, sorry I missed adding the labels. I've added it now.

**Comment by shendy-a8c** [comment] 2024-04-19 06:59
Looks like this is a duplicate of https://github.com/Automattic/woocommerce-payments/issues/8519. Closing. Let me know if that's not the case, @naman03malhotra .

**Closed as completed by shendy-a8c** 2024-04-19 06:59 UTC
Labels: category: projects, focus: reporting

**Comment by naman03malhotra** [comment] 2024-04-19 07:12
You are right shendy, I missed closing it when I meged the PR.
