### ISSUE TITLE
Transactions list: Add customer currency filter

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#1278] opened 2021-02-04 00:45 UTC
Depends on 498-gh-Automattic/woocommerce-payments-server

Allow filtering by customer currency via advanced filters:

<img width="346" alt="customer-currency-filter" src="https://user-images.githubusercontent.com/1867547/104567859-49f89400-561d-11eb-9849-4d19a12560cc.png">

@LevinMedia in https://github.com/Automattic/woocommerce-payments/issues/1202#issuecomment-763108784:

> The drop down filter should only list currencies that have been used by customers on the store - IE there's a transaction record of such and such a currency.
> 
> Bonus points if we can disable selections if that currency isn't present in the currently selected time period. That way people aren't hunting and pecking through currencies to see what may or may not be there...

As I'd noted in a subsequent [comment](https://github.com/Automattic/woocommerce-payments/issues/1202#issuecomment-765233464) there, we'll need to query all of the orders (or possibly transactions, on the server) for _distinct currencies_, either on page load or when the filter is added. I'm not sure if there's any precedent for the filters UI in that component being dynamically computed (and depending on other filters that have been added) though it seems like it should be _possible_ via the [`onAdvancedFilterAction` prop](https://github.com/woocommerce/woocommerce-admin/blob/d830378e8ca783449c739ab5b770fa819542ade4/packages/components/src/filters/index.js#L192-L195). (Alternatively, the Multi-currency extension – for instance – has its own list of _enabled_ currencies, but that could diverge from currencies that have actually been used.)

**Comment by deepakpathania** [comment] 2022-02-17 16:01
Is this a possible duplicate of [#1341](https://github.com/Automattic/woocommerce-payments/issues/1341)? @dechov If so, we could probably close it since that has been handled or are talking about a different filter here?

**Comment by LevinMedia** [comment] 2022-02-21 22:11
This could still use prioritization

**Closed** 2022-07-11 10:19 UTC
Labels: needs design, size: medium, component: countries currencies localization, component: customer multi-currency, needs prioritisation
