### ISSUE TITLE
WooCommerce Payments Overview Not Loading

### ISSUE THREAD

**Issue by msofnoteris** [Automattic/woocommerce-payments#7102] opened 2023-08-30 13:54 UTC
## 1. Description
When I navigate to the "Payments > Overview" section, the page briefly appears before disappearing.

![image](https://github.com/Automattic/woocommerce-payments/assets/110901333/306ca6c8-48f6-40a2-b8d5-c671db8b0f87)

### 2.1 Frontend/Console

- POST https://www.example.com/wp-json/wp/v2/users/1?_locale=user 403
- GET https://www.example.com/wp-json/wp/v2/users/1?context=edit&_locale=user 403
- POST https://www.example.com/wp-json/wc-admin/options?_locale=user net::ERR_CONNECTION_CLOSED
- GET https://www.example.com/wp-json/jetpack/v4/scan net::ERR_CONNECTION_CLOSED
- GET https://www.example.com/wp-json/wc-admin/options?options=woocommerce_admin_transient_notices_queue%2Cwoocommerce_admin_install_timestamp&_locale=user net::ERR_CONNECTION_CLOSED
- GET https://www.example.com/wp-json/wc-admin/plugins/active?_locale=user net::ERR_CONNECTION_CLOSED
- GET https://www.example.com/wp-content/plugins/woocommerce-payments/assets/images/woopayments.svg?ver=f85a85f7bfa59aaf86c4 net::ERR_CONNECTION_CLOSED
- GET https://www.example.com/wp-json/wc-admin/options?options=woocommerce_ces_tracks_queue&_locale=user net::ERR_CONNECTION_CLOSED
- GET https://www.example.com/wp-json/jetpack/v4/connection?_locale=user net::ERR_CONNECTION_CLOSED
- GET https://www.example.com/wp-json/wc-analytics/products/reviews?page=1&per_page=1&status=hold&_embed=1&_fields%5B0%5D=id&_locale=user net::ERR_CONNECTION_CLOSED
- GET https://www.example.com/wp-json/wc/v3/payments/settings?_locale=user net::ERR_CONNECTION_CLOSED
`

### 2.2 Backend/debug.php
`The Automattic\WooCommerce\Admin\API\Options::update_options function is deprecated since version 6.3.`

### WordPress Environment ###

WordPress address (URL): https://www.example.com
Site address (URL): https://www.example.com
WC Version: 8.0.3
REST API Version: ✔ 8.0.3
WC Blocks Version: ✔ 10.6.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.4.33
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.28
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.3
WC Database Prefix: wp_
Total Database Size: 76.83MB
Database Data Size: 68.54MB
Database Index Size: 8.29MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 6.48MB + Index: 0.19MB + Engine InnoDB
wp_postmeta: Data: 16.39MB + Index: 1.58MB + Engine InnoDB
wp_posts: Data: 17.52MB + Index: 0.25MB + Engine InnoDB
wp_prli_clicks: Data: 0.02MB + Index: 0.19MB + Engine InnoDB
wp_prli_link_metas: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_prli_links: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_shortpixel_folders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shortpixel_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shortpixel_postmeta: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_trp_dictionary_en_us_es_es: Data: 0.30MB + Index: 0.17MB + Engine InnoDB
wp_trp_dictionary_en_us_pt_pt: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
wp_trp_gettext_en_us: Data: 1.52MB + Index: 0.64MB + Engine InnoDB
wp_trp_gettext_es_es: Data: 1.52MB + Index: 0.55MB + Engine InnoDB
wp_trp_gettext_original_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_trp_gettext_original_strings: Data: 1.52MB + Index: 0.41MB + Engine InnoDB
wp_trp_gettext_pt_pt: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
wp_trp_original_meta: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wp_trp_original_strings: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_usermeta: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 1.33MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 10.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.52MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.05MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 90
custom_css: 1
customize_changeset: 1
elementor_library: 81
language_switcher: 4
nav_menu_item: 8
page: 14
post: 5
product: 3
product_variation: 12
revision: 631
shop_order: 58
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

Autocomplete WooCommerce Orders: by QuadLayers – 3.1.3
Coinbase Commerce: by Coinbase Commerce – 1.3
Cookie banner plugin for WordPress – Cookiebot CMP by Usercentrics: by Usercentrics A/S – 4.2.14
Dynamic Month & Year into Posts: by Gaurav Tiwari – 1.3.4
Elementor Pro: by Elementor.com – 3.15.1
Elementor: by Elementor.com – 3.15.3
Site Kit by Google: by Google – 1.108.0
Health Check & Troubleshooting: by The WordPress.org community – 1.7.0
Hide titles on hover: by Jose Mortellaro – 0.0.3
Jetpack: by Automattic – 12.5
NitroPack: by NitroPack Inc. – 1.8.3
SVG Support: by Benbodhi – 2.5.5
TranslatePress - Custom Flags
TranslatePress - Developer: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu – 1.3.1

TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.6.0

WebP Express: by Bjørn Rosell – 0.25.6
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.9 (update to version 1.7.10 is available)
Coinbase Commerce for WooCommerce: by Infinue – 1.2.3
WooCommerce EU VAT Number: by WooCommerce – 2.8.4 (update to version 2.8.7 is available)
WooCommerce Payments: by Automattic – 6.3.2
WooCommerce PayPal Payments: by WooCommerce – 2.2.2
WooCommerce Shipping & Tax: by WooCommerce – 2.3.3
WooCommerce: by Automattic – 8.0.3
Wordfence Security: by Wordfence – 7.10.3
Yoast SEO: by Team Yoast – 21.0
WP File Manager: by mndpsingh287 – 7.2
LiveChat: by LiveChat – 4.5.12

### Inactive Plugins (2) ###

All-in-One WP Migration: by ServMask – 7.76
All-in-One WP Migration Unlimited Extension: by ServMask – 2.52

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.9.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #1979 - /shop/
Cart: #1980 - /cart/
Checkout: #1981 - /checkout/
My account: #1982 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Hello Elementor Child
Version: 1.0.1
Author URL: https://elementor.com/
Child Theme: ✔
Parent Theme Name: Hello Elementor
Parent Theme Version: 2.8.1
Parent Theme Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: GB
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-31 12:46:26 +00:00
Options: ✔
Notes: 98
Onboarding: skipped

### WooCommerce Payments ###

Version: 6.3.2
Connected to WPCOM: Yes
Blog ID: 215848125
Account ID: acct_1MdumYCStyoSp5oH

### Action Scheduler ###

Complete: 188
Oldest: 2023-07-31 03:05:01 +0000
Newest: 2023-08-30 12:30:28 +0000

Failed: 8
Oldest: 2023-02-20 21:34:20 +0000
Newest: 2023-08-30 10:45:34 +0000

Pending: 2
Oldest: 2023-08-30 17:13:34 +0000
Newest: 2023-08-30 17:13:34 +0000

### Status report information ###

Generated at: 2023-08-30 13:46:00 +00:00
`

**Comment by zmaglica** [comment] 2023-09-04 06:51
Hi there.

I apologize for the troubles you have with the WooCommerce Payments plugin. I have noticed that the plugin version you are using is 6.3.2. There is a new version of the plugin (at the moment of writing). Could you please try updating the plugin to the latest version and see if you still encounter the error?

**Comment by msofnoteris** [comment] 2023-09-04 07:36
Hi Zvonimir,

I've taken the step of updating the plugin in question, but unfortunately, the issue still seems to be persisting. I greatly appreciate your assistance in addressing this matter further.

Thank you for your time and consideration.

**Comment by zmaglica** [comment] 2023-09-04 08:56
>Hi Zvonimir,
I've taken the step of updating the plugin in question, but unfortunately, the issue still seems to be persisting. I greatly appreciate your assistance in addressing this matter further.


Could you please provide any console logs you have? Specifically, do you have any error logs from the console besides the 403s?

It's challenging to diagnose the problem without knowing the specific website. If you'd prefer to keep this information confidential, you can open a support ticket [here](https://woocommerce.com/contact-us/) and reference this conversation.

**Note:** Details shared with our customer support remain private and are not publicly accessible as they might be on a repository. This allows us to address your concerns more efficiently and in greater detail.

**Comment by AbhinavSakalle** [comment] 2023-09-06 05:47
Reported in 6775440-zen. Rolling back to 6.3.1 fixed the problem.

**Comment by zmaglica** [comment] 2023-09-25 13:52
I think with the latest version of the plugin we manage to resolve this issue. Could you please try to update the plugin and try again?

**Comment by naman03malhotra** [comment] 2023-10-19 12:28
Closing this for now. Please feel free to open it again with steps to reproduce.

**Closed as completed by naman03malhotra** 2023-10-19 12:28 UTC
Labels: type: bug, category: core
