### ISSUE TITLE
Shoppers receive "order complete" emails when a dispute is closed

### ISSUE THREAD

**Issue by nicdwilson** [Automattic/woocommerce-payments#7928] opened 2023-12-18 22:13 UTC
### Description

When a dispute is opened, the order is automatically placed in on-hold [here](https://github.com/Automattic/woocommerce-payments/blob/dfd571b3be849ad135a32e44014d31f5135322ae/includes/class-wc-payments-order-service.php#L297) and when the dispute is closed, the order is marked as complete [here](https://github.com/Automattic/woocommerce-payments/blob/dfd571b3be849ad135a32e44014d31f5135322ae/includes/class-wc-payments-order-service.php#L333) (where there is a TODO regarding order status).

This retriggers the order completed email. If the order was completed before the dispute was opened, the customer will, on closure of the dispute, receive the email a second time.

## How to reproduce

- Ensure you can see order emails (as shopper). I did this by using a test store (sandbox mode) on Pressable hosting. Could also set up MailHog in local docker environment.
- Purchase something using a [dispute test card](https://stripe.com/docs/testing#disputes). I used `4000000000002685` (triggers `not received` dispute).
- Close the dispute. I closed by [submitting test `winning_evidence`](https://stripe.com/docs/testing#evidence).
- Observe the email received by the shopper - `Your [STORE] order is now complete` (triggered by the dispute close webhook).

### Suggestions for fix

This could be resolved by a filter that would allow a merchant to apply custom statuses to the order, preventing such problems as duplicated emails.

The underlying problem here is that we are using order status for tracking disputes, and this is not directly supported by WooCommerce core (as I understand it). There have been other issues about using a custom status for dispute. May require coordination with core to fix this, though there may be a way to defensively mitigate in WooPayments plugin.

### Related issues (disputed status) & work in progress

- #526
- #714  
- #727

### Additional context

This request comes as a result of https://github.com/Automattic/woocommerce-payments/issues/7885 where the merchant is receiving multiple inquiries triggered by return requests in the Klarna app.

**Comment by CGA8C** [comment] 2023-12-19 17:23
@souravdebnath1986 it looks like you were pinged for Prioritization on [this other issue](https://github.com/Automattic/woocommerce-payments/issues/7885) which is related to this issue. 

Could you look at prioritization for this one at the same time, please? :)

**Comment by RadoslavGeorgiev** [comment] 2023-12-20 15:10
This issue impacts Disputes, similarly to the linked https://github.com/Automattic/woocommerce-payments/issues/7885, so assigning to Helix (based on team responsibilities Pc2DNy-3z-p2) @Automattic/helix.

Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by seanbelly** [comment] 2023-12-22 16:29
Another update from ZD-7401002

> Another thing we have realized now is that partial refunds don’t change status from on hold to partial refund so, people are unable to pay the existing amount. 
> 
> The best thing is just if the orders never come in as inquiries in disputes. That would solve everything.

**Comment by Jinksi** [comment] 2024-01-02 04:13
I've re-titled this issue in an attempt to represent the problem, rather than the solution. Feel free to edit this if I am incorrect.

**Comment by csmcneill** [comment] 2024-01-04 23:26
@Jinksi LGTM! Though I wonder if this is a bug instead of an enhancement 🤔

**Comment by haszari** [comment] 2024-02-08 01:13
Marking as high priority because this email is a jarring experience after a dispute. This might be complex to fix and might need work in core, but it's important to get details like this right for shoppers.

**Comment by haszari** [comment] 2024-02-13 01:53
Tested this to confirm if this is a general problem or if only applies to specific disputes. I reproduced easily, and this confirms that the bug applies to all/most disputes.

Here's how I tested:

- Ensure you can see order emails (as shopper). I did this by using a test store (sandbox mode) on Pressable hosting. Could also set up MailHog in local docker environment.
- Purchase something using a [dispute test card](https://stripe.com/docs/testing#disputes). I used `4000000000002685` (triggers `not received` dispute).
- Close the dispute. I closed by [submitting test `winning_evidence`](https://stripe.com/docs/testing#evidence).
- Observe the email received by the shopper - `Your [STORE] order is now complete` (triggered by the dispute close webhook).

(added these test instructions to issue)

I agree, the order status should not be indiscriminately changed here, and the order completed email would be insensitive / inappropriate depending on the circumstances. Definitely high priority!

**Comment by haszari** [comment] 2024-02-13 02:42
Next steps for this issue would be to investigate how we are using order status in dispute flow now, and propose some ideas/options for how we could improve.

**Closed as completed** 2024-03-04 21:04 UTC
Labels: type: bug, priority: high, component: disputes, category: core
