### ISSUE TITLE
[GlobalStep] "Pay" button in the Apple Pay pop-up does not respond on clicking.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#5505] opened 2023-02-02 10:19 UTC
### Bug Description:
"Pay" button in the Apple Pay pop-up does not respond on clicking.

### Environment:
Woocommerce Version: WooCommerce 7.3.0
WooCommerce  WooCommerce Payments - 5.4.0 test-3
WordPress version: v6.1.1

PC:
MacOS 12.6.1 (Monterey)
Safari Version 15.6.1 (17613.3.9.1.16)

### Steps To Reproduce:
1. Ensure you have UK IP.
2. Make sure that you announce a timeframe for when the test will be performed because we have to set up the custom
   environment for this case.    
3. Go to test site.
4. Upload the provided test version for WooCommerce Payments.
5. Add a product to cart and go to checkout.
6. Cick on "Apple Pay" button.
7. Enter the valid details in Apple pay pop up.
8. Click "Pay"
9. Observe that "Pay" button in the Apple Pay pop-up does not respond on clicking.

### Screenshot:

![#5505](https://user-images.githubusercontent.com/41110392/216298059-aab9a5aa-4900-4929-a5b2-2165678179ef.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.55 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wp_
Total Database Size: 5.54MB
Database Data Size: 4.07MB
Database Index Size: 1.47MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.06MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 7
post: 2
product: 1
shop_order: 9

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 3.11.1
Companion Plugin: by Osk – 1.28
Jetpack: by Automattic – 11.7.1
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 5.4.0
WooCommerce: by Automattic – 7.3.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 5.0.2
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://teenage-whippet.jurassic.ninja
Subscriptions-core Library Version: 5.3.1
Subscription Statuses: –
WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-02-02 12:35:22 +00:00
Options: ✔
Notes: 53
Onboarding: completed

### WooCommerce Payments ###

Version: 5.4.0
Connected to WPCOM: Yes
Blog ID: 213894529
Account ID: acct_1ITcPcR03O9UZoSU

### Action Scheduler ###

Complete: 91
Oldest: 2023-01-03 12:38:21 +0000
Newest: 2023-02-02 10:15:50 +0000

Failed: 1
Oldest: 2023-01-10 15:34:26 +0000
Newest: 2023-01-10 15:34:26 +0000

Pending: 1
Oldest: 2023-02-02 12:07:55 +0000
Newest: 2023-02-02 12:07:55 +0000

### Status report information ###

Generated at: 2023-02-02 10:16:24 +00:00
`

</details>

**Comment by jbordonado** [comment] 2023-02-02 10:25
Slack discussion can be found here: p1675263007473229/1675075719.950599-slack-C011ENB20Q1

I cannot reproduce it, but we're using different MacBook setups, so I'm not sure if it's related.
I'm using MacBook 2021, which only requires a fingerprint check to pay (no need to click on a "Pay" button).
In the screenshot shared, it looks like an older version of MacBook because it required a password input and a click on a "Pay" button.

If someone without a fingerprint button on his MacBook could check if it works for him, that would be nice.
Otherwise, this will be very hard to check and reproduce. And will probably be closed due to not being reproducible.

**Comment by jbordonado** [comment] 2023-02-07 15:35
The UK tester again had an issue this week.
I just found out that the tester has been using a different device for 2 weeks now, which should explain why he has been unable to pay with Apple pay for the past 2 weeks.

New device: MacBook Pro 2020 - macOS 12.0.1 Monterey
Old device: MacBook Air 2020 - macOS 12.3.1 Monterey

**Comment by htdat** [comment] 2023-02-24 02:58
👋 @Automattic/harmony 
I am doing triage for this issue as a part of Platform Porter PcreKM-yM-p2. 
This seems one of your product areas Pc2DNy-3z-p2, could you check and add this to your backlog?

**Comment by deepakpathania** [comment] 2023-02-24 06:38
@htdat While the setup for Apple pay testing does lie under one of our focus areas, any issue that might be around the product area itself isn't our focus. So I am afraid we will not be able to prioritize this in our backlog.

Other than this, I feel this isn't an actual issue since we haven't seen any user complaints around the same but whoever picks it up can triage further.

**Comment by htdat** [comment] 2023-02-24 08:57
Thanks for the feedback @deepakpathania. I am moving this issue to “Engineering review” for for "WooCommerce Payments Backlog".

**Comment by dpaun1985** [comment] 2023-05-25 08:05
Closing this issue as we cannot reproduce it.

**Closed as completed by dpaun1985** 2023-05-25 08:05 UTC
Labels: type: bug, component: alternative payment methods, category: core, needs triage
