### ISSUE TITLE
`Payments > Disputes` should be highlighted when working with disputes

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#6394] opened 2023-05-29 01:07 UTC
### Describe the bug
When a merchant is viewing a dispute detail, or in the process of challenging/accepting/responding, the sidebar nav is incorrect. It should show `Payments > Disputes` as highlighted.

![Screenshot 2023-05-29 at 1 02 21 PM](https://github.com/Automattic/woocommerce-payments/assets/4167300/99afa77d-f2ed-44c9-adcd-e0c7fae04bbc)

(Spotted by @beaulebens  when reviewing WCPay UI)

### To Reproduce
Preconditions: 

- Store setup, payments onboarded, some active disputes. [See flows docs for details of how to simulate a dispute in test mode](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#add-order-notes-and-update-order-status-when-disputes-are-created-or-closed).

1. Go to `Payments > Disputes`. 
2. Click on `Needs response` or in a row to view dispute detail.
3. Notice nav highlighting is missing.

### Additional info
**Note**: in Phase 2 we'll be combining the **Transactions -> Details** and **Disputes → Details** screens, highlighting the **Transactions** nav menu item when viewing. I'll add this info to the issue. paJDYF-9oX-p2#comment-19421

**Comment by Jinksi** [comment] 2023-05-29 02:55
This may be a duplicate of #4312.

**Comment by haszari** [comment] 2023-05-29 03:03
Thanks @Jinksi ! I searched and didn't find … my other issue 🤣 . Maybe we can include these in next sprint as maintenance issues.

I trimmed off the `dispute` stuff from the other issue, so we can fix them independently if that's easier.

- #4312

**Comment by zmaglica** [comment] 2023-05-30 17:02
This issue impacts Disputes, so assigning to Helix (based on team responsibilities) @haszari  . Assigning as part of Gamma Triage process.

**Comment by Jinksi** [comment] 2023-07-10 23:54
**Note**: in Phase 2 we'll be combining the **Transactions -> Details** and **Disputes → Details** screens, highlighting the **Transactions** nav menu item when viewing. paJDYF-9oX-p2#comment-19421

**Closed as completed** 2023-07-19 15:00 UTC
Labels: type: bug, component: disputes, category: core
