### ISSUE TITLE
Subscriptions to charge full amount at sign-up do not renew on synchronise renewal date

### ISSUE THREAD

**Issue by johndcoy** [Automattic/woocommerce-payments#4564] opened 2022-08-11 01:27 UTC
### Describe the bug

When `Never (charge the full recurring amount at sign-up)` is enabled, the subscription fails to renew on the product's Synchronisation renewal date. 

### To Reproduce

1. Create a subscription product.
2. Enabled Synchronisation.
3. Set Prorate First Renewal to `Never (charge the full recurring amount at sign-up)`
4. Purchase a subscription.
5. Renewal does not occur.

### Actual behavior

WCPay Subscriptions with Synchronised renewals is by setting a trial end date, but the `trial_end` is not passed with this prorate option. The action is created as expected but the renewal never occurs: 
<img width="1335" alt="Markup 2022-08-10 at 13 17 06" src="https://user-images.githubusercontent.com/55294242/184049425-381eccc0-1923-4cc6-8979-44cdf98616f6.png">

The subscription then retains a Next Payment date in the past:

<img width="791" alt="Markup 2022-08-10 at 20 25 58" src="https://user-images.githubusercontent.com/55294242/184049593-a83664a2-2944-4770-acda-8f795de6a65e.png">

### Expected behavior

The expectation is for the subscription to renewal on the product's Synchronise renewals date while charging the full amount at sign-up.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context

[Slack Thread](https://a8c.slack.com/archives/CGGCLBN58/p1660131760533269?thread_ts=1659720769.614509&cid=CGGCLBN58)

**Comment by james-allan** [comment] 2022-08-11 01:35
Thanks for creating this @johndcoy! We both had the same idea and I created an issue too. I'm going to close this one as a duplicate of #4565. That issue has a little more dev info. 

Thanks again.

**Closed by james-allan** 2022-08-11 01:35 UTC
Labels: type: bug
