### ISSUE TITLE
Missing customer name on Payment Details page for in-person payments

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#5263] opened 2022-12-08 11:53 UTC
### Describe the bug

Customer details in the summary section on the Payment Details page show blank for in-person (terminal) payments. However, this is not the case for regular card-based payments where customer information is shown as expected.

### To Reproduce

1. Create an in-person payment order from the WC frontend, and capture the authorized payment for this order in Woo mobile app.
2. In WC admin, go to Payments → Transactions, and open the payment captured above.
3. Notice the value under the "Customer" field.

### Actual behavior

The customer value shows as `-`.

### Screenshots

![image](https://user-images.githubusercontent.com/1288616/206441149-87a56375-461c-4b0c-9022-b6ada076bd03.png)

### Expected behavior

The customer name captured in the order's billing details should be displayed like for regular card-based payments.

### Additional context

* p1670399999410699/1669994749.563949-slack-C04DN7Q51KK
* pe5pgL-1sT-p2#comment-1420

### Dev notes

This seems to be how it's done for regular payments. Perhaps we can reuse it for IPP payments?

https://github.com/Automattic/woocommerce-payments/blob/9cca5965847cce5db475d2838f56dbe5b1715eb5/includes/class-wc-payment-gateway-wcpay.php#L906-L917

**Comment by malinajirka** [comment] 2024-01-10 11:41
Potentially a duplicate of https://github.com/Automattic/woocommerce-payments/issues/7740. Wdyt?

**Comment by kalessil** [comment] 2024-01-10 13:28
Yes, that's a duplicate of #7740.

**Closed as completed by kalessil** 2024-01-10 13:28 UTC
Labels: type: bug, component: card present, category: duplicate
