### ISSUE TITLE
Country codes select list in Save my info section hidden behind the section

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#5514] opened 2023-02-02 18:50 UTC
### Describe the bug
Two small issues were encountered during the first round of the split UPE testing. 

1️⃣ The entries available in the select list are partially hidden behind the section. After a user scrolls down/up the page itself and clicks on the select list again, the issue disappears. This is not happening constantly, and I could reproduce it only on the Chrome browser. More details here: paJDYF-6WA-p2#comment-15883.

https://user-images.githubusercontent.com/22319444/216419816-ca6fe316-9f36-46b1-b6f4-6dd507407161.mov

2️⃣ Another thing noticed was described in this comment - paJDYF-6WA-p2#comment-15916. Essentially, the select list blinks for a second and then shows all the possible options as expected. I couldn't reproduce it on my machine, I tried on Chrome, Firefox, and Safari. 

<img width="715" alt="image" src="https://user-images.githubusercontent.com/22319444/216420728-a0be353e-72c7-4feb-b5a6-ff8f533027de.png">

### To Reproduce

1. Enable WooPay
2. Add a product and go to the shortcode page
3. Click the _Save my info_ section
4. Expand the country codes select list and confirm that there is a short blink with an empty list or that the list is hidden behind the section. 
5. Refresh the page and try step 4 multiple times, as the issue is not constantly reproducible

### Desktop (please complete the following information):

* Browser [Chrome]

**Comment by zmaglica** [comment] 2023-02-15 14:43
@frosso is this issue on Heisenberg's radar? I am triaging the WCPay backlog, and we're uncertain if you are going to handle it.

**Comment by frosso** [comment] 2023-02-15 15:00
Hey @zmaglica , thanks for the ping! I can add it to our current sprint 👍

**Comment by gpressutto5** [comment] 2023-02-21 23:08
1️⃣ Is fixed on #5599

-----

2️⃣ I could consistently reproduce it by enabling "Disable cache" and simulating a Slow 3G connection on Chrome's dev tools.

![image](https://user-images.githubusercontent.com/12385501/220470616-5748b6c4-134e-4daf-baa1-1faa3fea5c14.png)

This issue happens because the fonts used by Storefront are being loaded again when the modal opens and on slow connections, it is noticeable the first time it is loaded because it is cached after that.
I confirmed updating Storefront font to a font available locally solves the problem with cache disabled and slow internet.
Adding `display=swap` to [google fonts query args](https://github.com/woocommerce/storefront/blob/trunk/inc/class-storefront.php#L391) masks the problem, but it is not perfect and affects the whole site.

Source Sans Pro (Storefront's default) | Comic Sans MS (Locally available)
---- | ----
![google-fonts](https://user-images.githubusercontent.com/12385501/220475705-3edabc7d-2ad5-423f-a25d-5d460e906d0c.gif) | ![comic-sans](https://user-images.githubusercontent.com/12385501/220474559-2e054269-c789-4aa2-b861-3337156a1e35.gif)

The CSS used to set the font family is from the theme, not from woocommerce-payments. I couldn't find out why it is trying to reload the fonts, but I noticed all fonts loaded after the modal opens have URLs ending with `_mf`.

![image](https://user-images.githubusercontent.com/12385501/220478680-02be46a9-a9f1-4ff8-9cbb-edb399e66cfc.png)

They all have the same [initiator](https://fonts.googleapis.com/css?family=Source+Sans+Pro%3A400%2C300%2C300italic%2C400italic%2C600%2C700%2C900&subset=latin%2Clatin-ext&ver=4.1.1), and the only pattern I could find is they are all non-latin normal 400 fonts.

**Closed as completed** 2023-02-22 15:54 UTC
Labels: type: bug, category: core, component: WooPay, cooldown
