### ISSUE TITLE
Special characters not supported in save payment method helper text

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#7216] opened 2023-09-14 21:20 UTC
Note the ascii code instead of an apostrophe in the site name "Piero's Atomic Site".
![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/daae05b6-2750-4302-9e17-450880994765)

**Comment by pierorocca** [comment] 2023-09-14 21:21
cc @timur27 fyi as to avoid this on the deferred UPE UI.

**Comment by csmcneill** [comment] 2023-09-25 00:49
I've seen this before; it's pulled directly from the DBA on the Stripe dashboard. See acct_1LT92K2EF8r2i5A2 for how it appears in Stripe.

Usually, when a merchant inquires about this, I've recommended that they update the DBA themselves in the Connect dashboard. However, if the account is Individual / Sole Prop, the DBA option won't show in the Stripe dash—which means that they (or more often, we) will have to contact Stripe to change this.

**Comment by gpressutto5** [comment] 2023-10-18 20:03
I noticed that `wcSettings.siteTitle` returns the title with the escaped character and this value is used as initialData for the business_name [here](https://github.com/Automattic/woocommerce-payments/blob/1417f14d71f14ee6f57e340efba7de1b82751d79/client/onboarding/index.tsx#L69), so I think it is the cause.

![image](https://github.com/Automattic/woocommerce-payments/assets/12385501/19d55299-ad8b-4e1b-b799-6e91ff667ff6)

Still, I couldn't confirm because the "Doing business as" (`business_name`) field is not automatically filled. Instead, it is set to the First and Last name I used when onboarding. Did you get this automatically filled for you on your onboarding @pierorocca?

I created woocommerce/woocommerce-blocks#11323 to handle this fix on the woocommerce-blocks repository, and I'm working on a PR there. Do you think we should also add a method here to check if the current business_name has escaped characters and update it on Stripe if it does to fix all existing merchants automatically?

**Comment by pierorocca** [comment] 2023-10-18 20:41
I can't remember as it was over a year ago. I can try creating a new site.

**Comment by gpressutto5** [comment] 2023-10-23 17:47
I couldn't replicate the issue, but it is most likely fixed by woocommerce/woocommerce-blocks#11334.

**Closed as completed by gpressutto5** 2023-10-23 17:47 UTC
Labels: type: bug, priority: low
