### ISSUE TITLE
You cannot confirm this PaymentIntent because it's missing a payment method.

### ISSUE THREAD

**Issue by thenbrent** [Automattic/woocommerce-payments#672] opened 2020-05-20 06:06 UTC
In a similar vein to #487, we have a [user reporting](https://wordpress.org/support/topic/dev-mode/) the following notice:

> You cannot confirm this PaymentIntent because it's missing a payment method. To confirm the PaymentIntent with `cust_xxxx`, specify a payment method attached to this customer along with the customer ID.

The user appears to be using Dev Mode. The associated test account is available in the Stripe dashboard 

Screenshot provided on the ticket

**Comment by deepakpathania** [comment] 2022-02-15 09:48
@thenbrent I don't see an associated ticket with this issue, could you please update the description with the same?

**Comment by thenbrent** [comment] 2022-02-16 05:16
@deepakpathania thanks for flagging, looks like the original content was deleted/edited (likely when we moved the repo to be public). I suspect given the date the original issue was opened, it's referring to this ticket: 3007007-zd-woothemes

It's quite likely this issue no longer exists now.

**Comment by deepakpathania** [comment] 2022-02-17 07:27
Thanks for sharing. Closing this, for now, we can reopen/create a new issue in case the issue is surfaced again.

**Closed by deepakpathania** 2022-02-17 07:27 UTC
Labels: type: bug, needs feedback
