### ISSUE TITLE
[Deposits UI] When looking at `Deposit details`, `Payment details` pages the sidebar nav highlight is incorrect

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#4312] opened 2022-06-02 03:25 UTC
### Describe the bug

<img width="1385" alt="Screen Shot 2022-06-02 at 3 25 28 PM" src="https://user-images.githubusercontent.com/4167300/171546668-cc7958ea-dcad-45d8-9c05-6d0a46cbddb3.png">

The **deposit**, **payment** (transaction) and **dispute** detail pages highlight `Dashboard > Payments` as the current menu item. This is misleading and confusing.

You can get to this page from a variety of places (e.g. overview or deposits list), and wasn't clear to me what I was looking at. 

I think it would be clearer to highlight `Dashboard > Payments > Deposits` since this is a child of the Deposits page. (and Transactions or [Disputes](https://github.com/Automattic/woocommerce-payments/issues/6394), respectively)

Maybe we also need something to make it clear that you're deeply nested, e.g. breadcrumbs in header.

Note: the page title has a nice clear hierarchy, but this is not always visible.

### To Reproduce
1. Setup & onboard WCPay and purchase some product so you have an estimated payout.
1. Click on `Payments`
2. Click on `1 deposit` under `Pending balance` or `Est [date]` under `Next deposit`.

Where am I?

**Comment by haszari** [comment] 2023-02-14 21:46
We should fix this in maintenance or upcoming deposits project. Should be straightforward?

**Comment by Jinksi** [comment] 2023-02-24 05:18
Note that the same issue occurs when viewing an individual Transaction or Dispute.

**Comment by Jinksi** [comment] 2023-02-24 06:29
Upon attempting to solve this and further investigation, this may be a WC core issue/limitation.

I noticed this problem was mentioned in this WC issue, so I asked for advice: https://github.com/woocommerce/woocommerce/issues/34818#issuecomment-1442863143.

[Automatewoo#1196](https://github.com/woocommerce/automatewoo/issues/1196) also mentions that "_WC admin menu does not highlight when viewing its subpages_" with some example workarounds linked.

Next step is to determine whether the workarounds listed are suitable, the pages are being registered with improper args or the issue should be logged in WC repo.

**Comment by elizaan36** [comment] 2023-03-03 03:57
This is an all-Woo problem, not just payments. The issue is the lack of back button (or breadcrumb) in the header but that's currently being solved by the Mothra team. When the new header is implemented in core will WCPay be able to adopt it as well? That would solve the issue afaiu.

**Comment by haszari** [comment] 2023-03-05 21:56
> The issue is the lack of back button (or breadcrumb) in the header but that's currently being solved by the Mothra team.

The other aspect of the issue is the sidebar highlighting – the most correct sidebar item should be highlighted. For example: `Dispute detail` screen should highlight `Payments > Disputes`.

**Comment by elizaan36** [comment] 2023-03-18 15:18
Yes, definitely! Is this being fixed, sorry I missed this comment.

**Comment by haszari** [comment] 2023-03-20 19:13
> The other aspect of the issue is the sidebar highlighting – the most correct sidebar item should be highlighted. For example: Dispute detail screen should highlight Payments > Disputes.

@Jinksi in your investigation did you discover if it is possible to correct the sidebar highlighting? 

I'll change the issue title to focus on the sidebar highlight.

> Yes, definitely! Is this being fixed, sorry I missed this comment.

@elizaan36 I say yes! Unless we can't due to limitations in Woo APIs (in which case we will work to resolve in WC core of course).

**Comment by Jinksi** [comment] 2023-03-20 20:23
It looks like it's an issue shared across WC extensions that should be resolved in WC core.

Otherwise, here is a workaround used by google-listings-and-ads that might be useful as a temporary solution for WCPay: https://github.com/woocommerce/google-listings-and-ads/blob/4e69b169953096774dd0d957ba7a4fcecbbf2a89/js/src/hooks/useLegacyMenuEffect.js#L31. ([relevant comment](https://github.com/woocommerce/woocommerce/issues/34818#issuecomment-1471989015)).

**Comment by haszari** [comment] 2023-03-20 22:38
Thanks @Jinksi .

Can you confirm that the bug is reported and actionable by core team? Let me know the relevant issue and I'll help coordinate to work out when it could be fixed.

**Comment by haszari** [comment] 2023-05-29 03:01
Split off a separate issue for disputes: 

- #6394

Can probably fix these all in one hit but keeping the symptom/reports separate so we don't have to fix them all at once (more incremental => better).

**Comment by Jinksi** [comment] 2023-07-19 23:23
Resolved by #6694.

**Note**: requires WC 8.0.

**Closed by Jinksi** 2023-07-19 23:23 UTC
Labels: type: bug, good first issue, component: deposits, size: small, category: projects, category: core, needs prioritisation
