### ISSUE TITLE
Broken merchant-progressive-onboarding test

### ISSUE THREAD

**Issue by oaratovskyi** [Automattic/woocommerce-payments#9194] opened 2024-07-31 08:08 UTC
### Description
After merging #9171, the progressive onboarding e2e tests started failing. Tests click first type in the dropdown (`Individual`) and first item in the MCC dropdown. It's not possible since we changed first item in the type dropdown to `Company` and it also has subtype (like Sole proprietorship). Without picking the subtype MCC is not available. We should tweak the test.

**Output from the test failure**:
```
Admin merchant progressive onboarding › should pass merchant flow without any errors

    TimeoutError: Element [name="mcc"] not found
    Waiting failed: 3000ms exceeded

      44 | 		);
      45 | 		// pick Software type of goods (MCC)
    > 46 | 		await expect( page ).toClick( '[name="mcc"]' );
         | 		^
      47 | 		await page.waitForSelector(
      48 | 			'[name="mcc"] ~ ul li.wcpay-component-grouped-select-control__item:not(.is-group)'
      49 | 		);

      at tests/e2e/specs/wcpay/merchant/merchant-progressive-onboarding.spec.js:46:3
```

### Additional context
https://github.com/Automattic/woocommerce-payments/actions/runs/10175822140/job/28143976509
Test `tests/e2e/specs/wcpay/merchant/merchant-progressive-onboarding.spec.js`

> [!Important]
> Please, ensure when closing this issue (PR fix) that only one `e2e: broken` label is added and it is accurate.
> - [ ] I confirmed there's only one `e2e: broken` label in this issue and it is accurate.

**Comment by dmallory42** [comment] 2024-08-06 10:14
Confirmed this seems to be fixed on `develop` already, closing.

**Closed as completed by dmallory42** 2024-08-06 10:14 UTC
Labels: category: e2e, focus: account lifecycle, e2e: broken test
