### ISSUE TITLE
Fatal error when upgrading to a version with different constructor arguments

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#4438] opened 2022-07-14 06:18 UTC
### Describe the bug

This bug is discovered when we are requiring new argument for [WC_REST_Payments_Disputes_Controller](https://github.com/Automattic/woocommerce-payments/blob/22966094e33997eaca02be0bc4a542bdb2c28a31/includes/admin/class-wc-rest-payments-disputes-controller.php#L13).

When upgrading to a version that requires 2nd argument, it throws a [fatal error](https://github.com/Automattic/woocommerce-payments/pull/4388#issuecomment-1178482229) as if the 2nd parameter isn't passed.

The fatal error is not too harmless. It's only showing and might alert merchants.

### To Reproduce

1. Install and activate WCPay.
2. Onboard so store is connected to a Stripe account. I see that if store isn't onboarded yet, I don't see the fatal error.
3. Modify `WC_REST_Payments_Disputes_Controller`'s constructor to accept a new argument and pass that argument from [class-wc-payments.php](https://github.com/Automattic/woocommerce-payments/blob/22966094e33997eaca02be0bc4a542bdb2c28a31/includes/class-wc-payments.php#L664).
4. Run `npm run build` on that modified code and install + activate the generated `woocommerce-payments.zip`.

### Actual behavior

A fatal error of too few argument will be thrown.

### Screenshots

<img src="https://user-images.githubusercontent.com/3147296/177906183-1b04eb72-8c27-41d7-bd61-c43158bdec56.png" />

### Expected behavior

No fatal error.

### Additional context

I laid out a more lengthy explanation [here](https://github.com/Automattic/woocommerce-payments/pull/4388#issuecomment-1183977182). tl;dr; looks like the older version of [class-wc-payments.php](https://github.com/Automattic/woocommerce-payments/blob/22966094e33997eaca02be0bc4a542bdb2c28a31/includes/class-wc-payments.php#L664) is executing while `class-wc-rest-payments-disputes-controller.php` is updated with newer version within the same runtime.

I think this [reported problem](https://wordpress.org/support/topic/fatal-error-too-few-arguments-2/) is caused by this same problem due to this [change](https://github.com/Automattic/woocommerce-payments/commit/774f25e4af3f0b7b098e96ae14a65b335b97eb7b#diff-57ee486c4a3ba4bae478eb31255c9a968b5b4eccd04b27f512e4003440d6f821L615).

**Comment by htdat** [comment] 2022-07-18 08:57
Sounds like this P2 is relevant: paJDYF-43G-p2

**Comment by shendy-a8c** [comment] 2022-07-18 23:28
Thank you for pointing that out, @htdat. That link is relevant in a way that when a breaking change (like a new constructor parameter) is introduced we have to consider other parties who might depend on it because they might not be aware and the change will break their code.

What surprised me with this issue is that WCPay itself will break on upgrade. The solution might be to avoid breaking changes, ie by making the new constructor argument optional, even though that is not ideal and a bit unclean.

**Comment by leonardola** [comment] 2023-10-12 20:22
Seems related to #7464 and #7446

**Comment by vbelolapotkov** [comment] 2024-03-13 16:30
@haszari sending this one to your team since the problem is coming from Disputes.

**Comment by haszari** [comment] 2024-03-13 20:22
Thanks @vbelolapotkov – added to Helix's board for prioritisation.

**Comment by jessy-p** [comment] 2024-03-14 11:16
Not specific to disputes, same as #7464 
More information here. paJDYF-aZa-p2

**Comment by haszari** [comment] 2024-03-25 01:04
Thanks @jessy-p. 

> More information here. paJDYF-aZa-p2

Summarising this for clarity. Reminder – P2 links aren't readable and we need to get the relevant context on the issue. 

- During update, WooPayments code is running
- The code is being updated as it runs
- This leads to errors when constructor args change, etc

Closing as a duplicate of #7464

If anyone has more info here, and there's something for Helix to action, please comment & reopen or log a new issue.

**Closed by haszari** 2024-03-25 01:04 UTC
Labels: type: bug, component: disputes, category: engineering, category: core, focus: disputes
