### ISSUE TITLE
[GlobalStep] [Custom Order Tables] "Set up WooCommerce Payments" task fails to complete after KYC flow for default JN site on "Woocommerce > Home" page.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#4559] opened 2022-08-10 07:19 UTC
### Bug Description:
"Set up WooCommerce Payments" task fails to complete after KYC flow for default JN site on "Woocommerce > Home" page.

### Environment:
Woocommerce Version: WooCommerce 6.9.0
WooCommerce  Payments 4.5.1
WordPress version: v6.0.1

PC:
Windows 10
Chrome(Version 104.0.5112.81)

### Steps To Reproduce:
1. Open the JN site "https://envious-firefly.jurassic.ninja/default/wp-admin/"
1. Install and activate all the required plugins.
1. Install and activate WooCommerce.
1. Finish setup wizard using United States address as a store address without selecting WooCommerce Payments on Business Details step.
1. Follow instructions in the docs (https://docs.woocommerce.com/document/payments/#section-2) to manually install and set up WooCommerce Payments.
1. Go to "Woocommerce > Home" page.
1. Click on "Set up WooCommerce Payments".
1. Complete the KYC flow.
1. Go to "Woocommerce > Home" page.
1. Observe that "Set up WooCommerce Payments" task fails to complete after KYC flow for default JN site.

### Actual Result:
"Set up WooCommerce Payments" task fails to complete after KYC flow for default JN site on "Woocommerce > Home" page.

### Expected Result:
"Set up WooCommerce Payments" task should be completed and active after KYC flow for default JN site on "Woocommerce > Home" page.

### Screenshot:

![#4559](https://user-images.githubusercontent.com/41110392/183839468-b68836e6-ef1f-458b-8a5b-950e608a5567.jpg)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 6.9.0
REST API Version: ✔ 6.9.0
WC Blocks Version: ✔ 8.1.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.30
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.0
WC Database Prefix: wp_4_
Total Database Size: 35.35MB
Database Data Size: 20.98MB
Database Index Size: 14.37MB
wp_4_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_4_woocommerce_order_items: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_4_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.73MB + Engine InnoDB
wp_4_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_4_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_actionscheduler_actions: Data: 3.47MB + Index: 2.06MB + Engine InnoDB
wp_4_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_actionscheduler_logs: Data: 2.52MB + Index: 1.92MB + Engine InnoDB
wp_4_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_comments: Data: 2.52MB + Index: 1.23MB + Engine InnoDB
wp_4_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_options: Data: 3.09MB + Index: 0.14MB + Engine InnoDB
wp_4_postmeta: Data: 4.52MB + Index: 6.03MB + Engine InnoDB
wp_4_posts: Data: 1.52MB + Index: 0.45MB + Engine InnoDB
wp_4_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_4_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_4_term_relationships: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_4_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_4_wcs_payment_retries: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_4_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_4_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_wc_order_product_lookup: Data: 0.16MB + Index: 0.19MB + Engine InnoDB
wp_4_wc_order_stats: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_4_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_4_wc_product_attributes_lookup: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wp_4_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_wc_product_meta_lookup: Data: 0.13MB + Index: 0.19MB + Engine InnoDB
wp_4_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_4_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_4_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 14
page: 6
post: 2
product: 303
product_variation: 638
shop_coupon: 1
shop_order: 993
shop_subscription: 215

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (11) ###

WooCommerce Smooth Generator: by Automattic – 1.0.4
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 4.5.1
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.1.0
WooCommerce Subscriptions: by WooCommerce – 4.4.0
WooCommerce: by Automattic – 6.9.0-dev
WP phpMyAdmin: by Puvox.software – 5.2.0.7
NS Cloner - Site Copier: by Never Settle – 4.1.9.3
Code Snippets: by Code Snippets Pro – 3.2.0
WP Console: by Edi Amin – 2.3.1
WooCommerce Blocks: by Automattic – 8.1.0

### Inactive Plugins (5) ###

Companion Plugin: by Osk – 1.27
WooCommerce Beta Tester: by WooCommerce – 2.0.5
WooCommerce Stripe Gateway: by WooCommerce – 6.5.0
WooCommerce Subscriptions Core: by Automattic – 2.1.0
WooCommerce Subscriptions Core: by Automattic – 2.1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.1 (update to version 4.1.2 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://envious-firefly.jurassic.ninja/default
Subscription Statuses: wc-active: 15
wc-pending-cancel: 1
wc-on-hold: 198
wc-cancelled: 1

WooCommerce Account Connected: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

other: wc-active: 15
wc-cancelled: 1
wc-on-hold: 198
wc-pending-cancel: 1

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-08-11 04:09:10 +00:00
Options: ✔
Notes: 56
Onboarding: completed

### WooCommerce Payments ###

Version: 4.5.1
Connected to WPCOM: Yes
Blog ID: 209305955
Account ID: -

### Action Scheduler ###

Canceled: 173
Oldest: 2022-08-01 01:05:40 +0000
Newest: 2022-08-08 23:25:04 +0000

Complete: 6,468
Oldest: 2022-07-29 04:19:18 +0000
Newest: 2022-08-10 07:13:54 +0000

Failed: 56
Oldest: 2022-08-08 12:38:32 +0000
Newest: 2022-08-09 07:14:20 +0000

Pending: 198
Oldest: 2022-08-10 07:18:28 +0000
Newest: 2022-10-31 17:17:51 +0000

### Status report information ###

Generated at: 2022-08-10 07:17:33 +00:00
`

</details>

**Comment by deepakpathania** [comment] 2022-08-23 10:45
I followed the testing instructions and couldn't reproduce the issue. For me, after completing step 8 when going to the WooCommerce home page, the `Set up WooCommerce Payments` step was ticked off, attached screenshots for reference.

- After step 4 (completed setup wizard without WCPay)
<img width="1030" alt="Screenshot 2022-08-23 at 4 03 49 PM" src="https://user-images.githubusercontent.com/68396823/186138971-3cafd107-a37c-4ea1-8e45-f4c941cefee8.png">

- After step 8 (completed KYC flow for WCPay)
<img width="1079" alt="Screenshot 2022-08-23 at 4 12 54 PM" src="https://user-images.githubusercontent.com/68396823/186139047-2c8cabd8-04ed-4660-9df2-6a191db5e1ce.png">

**Comment by RadoslavGeorgiev** [comment] 2022-08-24 11:15
Same for me. I used the latest COT WooCommerce build, but I see the correct state:

<img width="544" alt="image" src="https://user-images.githubusercontent.com/5311119/186405058-bafe5221-ec4f-4cac-9684-4fe09e33bdad.png">

Closing this issue, as two of us are not able to reproduce it.

**Closed by RadoslavGeorgiev** 2022-08-24 11:15 UTC
Labels: type: bug, component: onboarding, category: core, custom order tables
