### ISSUE TITLE
Deposit schedule: Temporarily suspended

### ISSUE THREAD

**Issue by anhtruong1993** [Automattic/woocommerce-payments#4831] opened 2022-10-03 00:49 UTC
It's been 3 weeks since the payout time has passed, but it's still not active.
Please help.
![Screenshot_1](https://user-images.githubusercontent.com/108404042/193484338-e1273068-bd33-4b65-9c14-06ae3b7208d8.png)

**Comment by csmcneill** [comment] 2022-10-03 01:30
Howdy @anhtruong1993,

What you are experiencing may or may not be a bug. I recommend that you [open a support ticket](https://woocommerce.com/my-account/create-a-ticket) so that a member of the WooCommerce support team can help you determine the root cause of this issue. Please provide a copy of [your System Status Report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/) and a link to this issue so that we can better assist you. 

I will close this issue for the time being, but we may reopen it later with more details if we feel it is warranted.

**Closed as completed by csmcneill** 2022-10-03 01:30 UTC
Labels: type: bug

**Comment by anhtruong1993** [comment] 2022-10-03 01:33
I opened the ticket but did not receive any reply, and the time is too long compared to the woocommerce payments docs stated is 7 days, if this is not a bug then what is?

**Comment by csmcneill** [comment] 2022-10-03 01:55
> I opened the ticket but did not receive any reply, and the time is too long compared to the woocommerce payments docs stated is 7 days, if this is not a bug then what is?

@anhtruong1993 Do you have any information that could help me find the ticket on our end? A ticket number or site URL would go a long way toward helping me find your inquiry in our system.

**Comment by csmcneill** [comment] 2022-10-03 02:42
Reached out to see if we can find this ticket using our internal tools: p1664764919746829-slack-CJK2SLCJH

**Comment by csmcneill** [comment] 2022-10-03 13:55
We're unable to locate your ticket or account with the information provided @anhtruong1993.

Please contact us again through a normal support channel and reference this GitHub issue—we'll be glad to help.

**Comment by anhtruong1993** [comment] 2022-10-04 01:54
hi my friend. please check my account.

**Comment by anhtruong1993** [comment] 2022-10-04 01:55
[Edit] personal email removed.

**Comment by csmcneill** [comment] 2022-10-05 00:51
> hi my friend. please check my account.

We were able to find an inquiry in our system with the information provided.

You can respond to our previous message if you'd like more information about your inquiry, or you can create a new ticket at https://woocommerce.com/my-account/create-a-ticket/ 

Please note that GitHub is not a dedicated support channel, and we will be able to assist you more quickly via ticket.

**Comment by dougaitken** [comment] 2022-10-05 11:22
I'm locking this conversation, GitHub is not a support channel. Please reach out to the team directly via WooCommerce.com and reply to any email we've sent.
