### ISSUE TITLE
Error when attempting to fully refund remaining amount after partial refund

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#8210] opened 2024-02-15 11:41 UTC
### Describe the bug
Once an order has been partially refunded, the available option to `Refund in full` under transaction details page returns a `500` with 

```json
{
   "code":"error",
   "message":"Invalid refund amount.",
   "data":null
}
```

### To Reproduce
For an existing order
* perform a partial refund 
* navigate to `Transactions`, select the details of the transaction and attempt to `Refund in full` in the top right corner
* confirm you can see the `There has been an error refunding the payment ${pi}. Please try again later.` notice

### Screenshots
<img width="1588" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/22319444/3db9e185-e4c8-4c52-8b77-2e7098d5b58e">

### Expected behavior
As a user, I'd expect the button to either be hidden or to refund the remaining amount after a partial refund. Further insights from the refunds team are needed, hence I'm adding the `needs feedback` label to this issue.

**Comment by zmaglica** [comment] 2024-02-15 16:58
This issue impacts Refunds, so assigning to Pulsar (based on team responsibilities Pc2DNy-3z-p2) @kalessil 
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by kalessil** [comment] 2024-02-16 09:17
@mgascam, can you please check where the problem is and how complex is to fix it?

**Comment by mgascam** [comment] 2024-02-20 19:10
@kalessil I had a look, sharing my findings:

The request to refund a charge is handled by the [refundCharge](https://github.com/Automattic/woocommerce-payments/blob/f73f0df93f336101ffe995ec47849c0a8a60b589/client/data/payment-intents/actions.ts#L45) action. Since we have access to the `charge` object, we could calculate the pending amount to be refunded (based on [amount_refunded](https://docs.stripe.com/api/charges/object#charge_object-amount_refunded)) and send it as part of the request here:
https://github.com/Automattic/woocommerce-payments/blob/f73f0df93f336101ffe995ec47849c0a8a60b589/client/data/payment-intents/actions.ts#L56

Another option would be to hide the `Refund in full` from the dropdown, using the amount_refunded as a flag to control the visibility in the [PaymentDetailsSummary](https://github.com/Automattic/woocommerce-payments/blob/4d3de90979b5017a7cc3a4f41a0b74bc584ed1cf/client/payment-details/summary/index.tsx#L168) component:
https://github.com/Automattic/woocommerce-payments/blob/4d3de90979b5017a7cc3a4f41a0b74bc584ed1cf/client/payment-details/summary/index.tsx#L557

Any of those options are not complex to implement. If you asked me, I lean towards the first solution, as it seems more convenient for the merchant.

**Comment by kalessil** [comment] 2024-02-21 08:16
Thanks for looking into it @mgascam!

The first option semantics is "Refund what can be refunded"; it's not really "Refund in full." This path creates more complexity, than brings value IMO.

The second approach is not changing semantics, so let's hide 'Refund in fill' if a partial refund already happened.

**Closed as completed** 2024-03-06 12:16 UTC
Labels: type: bug, priority: high, category: projects, component: streamline refunds
