### ISSUE TITLE
Date filter in Transactions page is not clickable

### ISSUE THREAD

**Issue by tsetend** [Automattic/woocommerce-payments#7715] opened 2023-11-14 11:39 UTC
### Bug Description:
The Date filter in the Transactions page of WooCommerce Payments is currently non-clickable, preventing users from filtering transactions based on specific dates.  The user have to type the date manually.

### Steps to Reproduce:

1. Log in to the WordPress admin dashboard.
2. Navigate to WooCommerce > Payments.
3. Click on the "Transactions" tab to view a list of transactions.
4. Observe that the Date filter is not clickable in Advanced filter, and there is no option to select a specific date range. But you can manually type the date.

Short clip: https://d.pr/v/RpeLvM

### Expected Behavior:
The Date filter in the Transactions page should be clickable, allowing users to select a start and end date to filter transactions based on the chosen timeframe. 

### Actual Behavior:
The Date filter is not clickable instead we have to manually type the date

### Additional Information:

Using the latest version of WP, WC and WCPay. Was able to replicate the problem on my end. Reported in 7311488-zen

**Comment by csmcneill** [comment] 2023-11-14 19:51
Hey @tsetend! This is a duplicate of #7679, so I'm closing this :)

**Closed as completed by csmcneill** 2023-11-14 19:51 UTC
Labels: type: bug, priority: low, category: duplicate
