### ISSUE TITLE
Update inline notice component on payments settings

### ISSUE THREAD

**Issue by bradyv** [Automattic/woocommerce-payments#7500] opened 2023-10-17 16:20 UTC
### Describe the bug
The payments settings page is using an older version of the inline notice when there are warnings about the deposit schedule.

### To Reproduce
Go to `Payments -> Settings` and scroll down to `Deposits`

### Screenshots
![screenshot_2023-10-16_at_7 41 07_pm](https://github.com/Automattic/woocommerce-payments/assets/889872/6fdf4a61-6dfc-45fe-bdc6-613f9628dccd)

### Expected behavior
We should update this to use the latest version of the [inline-notice](https://github.com/Automattic/woocommerce-payments/blob/4ea6a98e0872560a10bdadf85fe7cdb2702f6e26/client/components/inline-notice/styles.scss#L19) component.
<img width="1142" alt="Screenshot 2023-10-17 at 09 16 13" src="https://github.com/Automattic/woocommerce-payments/assets/889872/9e6867fd-33be-4507-abe7-6a484cf16320">
<img width="1185" alt="Screenshot 2023-10-17 at 09 16 48" src="https://github.com/Automattic/woocommerce-payments/assets/889872/9e207a78-be66-4a0a-81e5-64c870d28a8e">

**Comment by bradyv** [comment] 2023-10-17 21:26
@haszari Just pinging to put this on Helix's radar. It's very minor but would be nice if we can get it into the next release.

**Comment by haszari** [comment] 2023-10-18 19:07
Good spotting! This is already logged in our maintenance queue. @bradyv if you have any thoughts or details why we should prioritise this sooner (e.g. next sprint / release) please add info to #6424 🙌

Closing this as a duplicate of:

- #6424

**Closed as not planned by haszari** 2023-10-18 19:07 UTC
Labels: type: bug
