### ISSUE TITLE
More prominent visual indication of how to turn off test mode

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#7498] opened 2023-10-17 14:11 UTC
### Description

When using the new onboarding, a merchant has an option to quickly set up a test account to test WooPayments without needing to provide live Stripe details. Although we include a prompt for such users to set up live payments when they are ready, it is halfway through the `Overview` page meaning it's not very prominent. We've had reports of users not being able to find the option, and the general expectation is that it should appear in the Settings page.

I'd like to get input from others on how this should work, but my suggestion would be a `Notice` at the top of both the `Overview` and `Settings` pages informing the user that `WooPayments` is in test mode and prompting them to set up live payments when they are ready.

### Acceptance criteria

* When a user has onboarded in test/dev mode, they should have a more prominent message helping them to set up live payments when ready.

### Additional context

- Slack thread with reports from HE's: p1697481389856479-slack-C03KTTK2YMA

**Comment by daquinons** [comment] 2023-10-18 08:35
Hi @elizaan36 ! Do you have any suggestion about this? 🙏

**Comment by francoishvz** [comment] 2023-10-21 11:43
7189690-zd-a8c

This ticket acually highlights the problem quite well in that there are no indicators as to why Merchants can't turn off Dev Mode when looking at their settings under WooCommerce > Settings > Payments.

It would be great if we could see a visual prompt to explain why they can't disable Dev Mode when they toggle the checkbox in this type of scenario.

Forgive the poorly designed element ;) But you get the idea :) 

![0cJxWC.png](https://github.com/Automattic/woocommerce-payments/assets/104560284/7e0de3d8-16cf-422b-9834-0e991af6be1c)

**Comment by elizaan36** [comment] 2023-10-25 18:08
@bradyv Could you have a look at this and share your thoughts on the best approach? One quick win to solve the problem is to add a prompt in WooPayments settings to enable live payments.

**Comment by bradyv** [comment] 2023-10-26 18:52
Yes I'll go review the flows and put together a recommendation

**Comment by daquinons** [comment] 2023-11-03 14:03
Putting it on hold until we get the design input

**Comment by francoishvz** [comment] 2023-11-09 08:13
Commenting here again because I edited my previous comment.

**Comment by ricardo** [comment] 2023-11-14 16:40
Related:
- 7303068-zd-a8c
- 7268870-zd-a8c

**Comment by daquinons** [comment] 2023-11-17 10:28
Thanks to @bradyv for the Design inputs, this is how we are going to be moving this forward in the scope of this issue:
- Settings prompt, removing the "Test mode" section when an account has been created using "Dev mode"
![image](https://github.com/Automattic/woocommerce-payments/assets/2612426/aa4c7c58-4840-4bbd-81a1-e573879615d9)
- Overview prompt
![image](https://github.com/Automattic/woocommerce-payments/assets/2612426/ac35f8dd-0655-4024-abbc-8148d8b9add9)

Notes:
- The old prompt in "Settings" announcing "test mode" should be kept for those live accounts that enable test mode manually -> It should only be modified for dev mode accounts (in the same situation as when we block the Test mode toggle at the moment)
- The test mode toggle should only be replaced by the new prompt in the dev mode accounts. Live accounts should still display the Test mode section and toggle in Settings
- The copy for both prompts is the same and should be the one that is shown in "Settings prompt" "Revised WooPayments Settings"
- The link to "Learn more" should also be present in the Overview prompt, next to the "Set up payments" button, linking to our documentation https://woo.com/document/woopayments/testing-and-troubleshooting/dev-mode/
- When clicking on the action button of both prompts, the same confirmation modal and deletion of the test account happens as it happens in the current banner
- The current banner will also be removed as part of this issue, but as I just mentioned, its functionality must be the same in the newly added prompts.
- There is a follow-up issue to use the last component in these prompts but also in other areas of WooPayments, but that will be included in a separate issue https://github.com/Automattic/woocommerce-payments/issues/7733

**Closed as completed** 2023-11-29 20:33 UTC
Labels: type: enhancement, priority: high, component: onboarding, component: progressive onboarding
