### ISSUE TITLE
PRB & WooPay Settings UI copy is misaligned

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#8087] opened 2024-01-24 23:03 UTC
Note that the copy in the Theme section, recently updated, is no longer aligned according to the Figma design spec.

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/f4294e81-a5d1-4ebb-b09c-977b056723d0)

**Comment by pierorocca** [comment] 2024-01-24 23:17
Noting that #6470 should take precedence and solve for #8087.

**Comment by zmaglica** [comment] 2024-01-30 10:30
@pierorocca I will mark this issue as blocked until the #6470 is addressed.

**Comment by zmaglica** [comment] 2024-01-30 10:34
While we wait until the linked issue is resolved, I will move this issue into the Other Teams queue and assign it to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) @FangedParakeet. Feel free to tag other teams if you think that this issue belongs to them.

**Comment by frosso** [comment] 2024-02-07 10:14
I couldn't reproduce this misalignment of the help text on either WooPay or GooplePay settings screens.

![Screenshot 2024-02-07 at 10 35 42 AM](https://github.com/Automattic/woocommerce-payments/assets/273592/fa11453c-cf87-469b-8f8c-92a33c30e2ed)
![Screenshot 2024-02-07 at 10 35 39 AM](https://github.com/Automattic/woocommerce-payments/assets/273592/da14948c-2732-4816-869b-3167e77d0f4f)

It turns out that I need to have gutenberg-the-plugin installed and activated to reproduce it.

The issue is due to a change in the underlying CSS of the option box on Gutenberg.
Fix here - it shouldn't block #6470 .

**Closed as completed** 2024-02-07 13:39 UTC
Labels: type: bug, component: checkout, category: core, priority: medium
