### ISSUE TITLE
Capture terminal payment endpoint returns 500 on paid partially-refunded orders

### ISSUE THREAD

**Issue by malinajirka** [Automattic/woocommerce-payments#2390] opened 2021-07-09 13:35 UTC
The `/payments/orders/<id>/capture_terminal_payment` returns 500 and changes payment method from "cash on delivery" to "woocommerce_payments" when the mobile apps try to charge the remaining part of a partially refunded order.

### To Reproduce

1. Customer: Order contains two products - a tshirt ($10) and a hoodie($15) => total $25
2. Merchant: Use Woo Mobile app and charge $25 successfully. 
3. Merchant: Edit this order, refund  $10. 
4. Merchant: Change this order status from `Completed` to `Pending Payment`. 
5. Merchant: Try to charge $10 with Woo Mobile app. 

Video in https://github.com/Automattic/woocommerce-payments/issues/2390#issuecomment-911707272

### Actual behavior

Notice the `capture_terminal_payment` returns 500 and changes the payment method of the order. 7. The detailed error of the REST API request `capture_terminal_payment`:

```json
 error: "wcpay_capture_error"
 message: "Payment capture failed to complete with the following message: Error: The payment could not be captured because the requested capture amount is greater than the authorized amount. If you are trying to collect a tip or over-capture, your account might not be configured for those features. Contact us via https://support.stripe.com/contact/"
 ``` 
### Expected behavior 

There is no error and we can charge normally. 

### Possible solutions

~Check WCPay code ([src](https://github.com/Automattic/woocommerce-payments/blob/103fabc96ceceeadf4e9127cd8ed006c5965b50f/includes/class-wc-payment-gateway-wcpay.php#L1583-L1585)) and handle this case - try to charge $10.~ 

OR we do not allow this flow. Whenever refunding exists in an order, we do not process `capture_chage`, respond with:
- status code `400` 
- and error message `Refunded orders are not processed`. 

The final approach for this issue is based on pdfdoF-8k-p2
Check this issue too https://github.com/Automattic/woocommerce-payments/issues/2846 before implementing a solution.

### Updates: 

_Update on 2021-09-15_: Based on the P2 internal discussion, we agreed that we will block this flow. Updated `Possible solutions` section.

**Comment by kidinov** [comment] 2021-07-09 13:43
Important note to this - it looks like that it's possible to charge more than remain amount. 

Example:

1. Order contains two products - a tshirt ($10) and a hoodie($15) => total $25
2. Refund $10
3. **We can charge 25$**

**Comment by htdat** [comment] 2021-09-02 06:57
@malinajirka and @kidinov  - I think if the order amount is changed, we need to update the amount in its PaymentIntent before really capturing the payment. 

I am trying to replicate the issue but I don't have the real terminal for testing. Therefore, if you can give PaymentIntent IDs with this error, it would be better.

**Comment by htdat** [comment] 2021-09-02 09:04
This is what I've found out so far. I tried to follow up these steps mentioned here #1689 to create a PaymentIntent and call to `/payments/orders/<id>/capture_terminal_payment`. I've found out these things: 

>  changes payment method from "cash on delivery" to "woocommerce_payments" 

This part is expected per these lines: 
https://github.com/Automattic/woocommerce-payments/blob/03bc5c1c9f5d074e8c1a98ef9c1cee22061e2bbe/includes/admin/class-wc-rest-payments-orders-controller.php#L103-L105

---- 

@malinajirka's description: 

> Notice the capture_terminal_payment returns 500 and changes the payment method of the order.

I do not see this 500 error. 

However, I confirm this issue from @kidinov 

> Client (Android for instance) still can charge 25$

It looks like that the issue is here when we should update `amount` of PaymentIntent before we capture the charge (or we can hook into the refund order action, and update PaymentIntent): 

https://github.com/Automattic/woocommerce-payments/blob/03bc5c1c9f5d074e8c1a98ef9c1cee22061e2bbe/includes/admin/class-wc-rest-payments-orders-controller.php#L116-L117

**Comment by malinajirka** [comment] 2021-09-02 10:05
Thanks for looking into this @htdat! 

> I think if the order amount is changed, we need to update the amount in its PaymentIntent before really capturing the payment.

The Android app creates the PaymentIntent after the user clicks on "Collect Payment" button. So if they do a partially refund and then click on the "Collect Payment" button, the PaymentIntent should be created with the correct amount. 
However, we'd expect the backend to check if the charged amount corresponds to the order being paid - overcharges should imho be verified on both the client and the backend -> just to reduce the risk in case of a bug on either side.

> I am trying to replicate the issue but I don't have the real terminal for testing. Therefore, if you can give "PaymentIntent IDs" and your site URLs (or WP.com blog_ids) with this error, it would be better for me to troubleshoot further.

>Notice the capture_terminal_payment returns 500 and changes the payment method of the order.

>>I do not see this 500 error.

I still see the error when the mobile app tries to charge "total - refunded". The app requests $10 charge - it doesn't mention the `totalAmount` at all so I'm not sure if the backend needs to update the PaymentIntent (the PaymentIntent is created by the app not the backend AFAIU).

Example with $45 net payment (redacted auth token):
curl -v -X POST 'https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/154993204/rest-api/?locale=en_US' -H 'Accept-Encoding: gzip' -H 'Authorization: Bearer [REDACTED]' -H 'Connection: Keep-Alive' -H 'Content-Length: 165' -H 'Content-Type: application/json; charset=utf-8' -H 'Host: public-api.wordpress.com' -H 'User-Agent: Mozilla/5.0 (Linux; Android 11; SM-F700F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.159 Mobile Safari/537.36 wc-android/7.4-rc-2' -d '{"path":"/wc/v3/payments/orders/498/capture_terminal_payment/\u0026_method\u003dpost","json":"true","body":"{\"payment_intent_id\":\"pi_3JVCbK2EOyvnrkuA0qhGUqUC\"}"}'


> > changes payment method from "cash on delivery" to "woocommerce_payments"

> This part is expected per these lines:

Could you please expand on this a bit. I don't see how is this expected - the payment method is set to "cash on delivery" and when the user refunds the order, they won't be able to collect the payment until they change the payment method back to "cash on delivery" with the current behavior. I mean it's not a huge issue since this whole scenario is an edge case, but if you could expand on why we want to change the status to "woocommerce_payments" that'd be much appreciated.

**Comment by malinajirka** [comment] 2021-09-02 13:51
Here is a short video with steps mentioned in the description of this PR:
https://cloudup.com/cbwGkvis6xO

**Comment by htdat** [comment] 2021-09-03 09:31
> We outlined next steps here p1630589126069400/1630583880.066400-slack-C025A8VV728
I will write up a more detailed note tomorrow and do neccessary followups then.

1, Updated the issue described here. It turns out that it's more a question about whether or not we accept the flow above. @malinajirka followed up here p1630591782032900-slack-C01B82V67DL
2, Make sure that WCPay handles the maximum charge, which is translated into this issue https://github.com/Automattic/woocommerce-payments/issues/2846 
3, Error wcpay_capture_error should not be 502 or 500. Should be 400., which is similar to Stripe API response - created this issue https://github.com/Automattic/woocommerce-payments/issues/2847

cc @anu-rock

**Comment by htdat** [comment] 2021-09-08 03:14
> Updated the issue described here. It turns out that it's more a question about whether or not we accept the flow above. @malinajirka followed up here p1630591782032900-slack-C01B82V67DL

Update: @malinajirka will raise an internal discussion regarding this - ref p1630921922049800/1630591782.032900-slack-C01B82V67DL

I've added `paid` to this GH issue title to differentiate it from #2846

**Comment by malinajirka** [comment] 2021-09-08 11:20
Internal discussion happening here - pdfdoF-8k-p2. We'll update this issue with the result of the discussion.

**Comment by htdat** [comment] 2021-09-09 02:16
Thanks @malinajirka. 

For team Gamma, I am moving this issue from "In Progress" back to "Product Backlog"

**Comment by htdat** [comment] 2021-09-09 08:10
FYI. I've updated the original description to give it a good structure (steps, actual behavior, expected behavior) and what we're waiting for to continue this issue.

**Comment by kalessil** [comment] 2021-09-21 09:40
Closing as it was split to #2846, #2847

**Closed by kalessil** 2021-09-21 09:40 UTC
Labels: type: bug, priority: low, size: small, [Feature] Card Present
