### ISSUE TITLE
Customer is not notified of failed payment on blocks checkout

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#7792] opened 2023-11-27 13:02 UTC
### Describe the bug

On blocks checkout, customer is not notified of failed payment attempt. They are notified only after they click "pay now" again.

### To Reproduce

- Ensure you have a payment method that requires a redirect, like giropay or EPS
- Add products to the cart
- Go to checkout
- Select giropay as a payment method
- Click "Pay now"
- On the redirected page, click on "Fail test payment"
![Screenshot 2023-11-27 at 1 58 37 PM](https://github.com/Automattic/woocommerce-payments/assets/273592/5c91d415-cefd-42c2-9e4a-ba9cd23a45cb)
- You'll be redirected to the merchant site's block checkout, but with no error message
- Selectig giropay (or any other WooPayments payment method) and clicking "Pay now" again will display the error message that should have been displayed

The issue doesn't affect the shortcode checkout, which behaves as expected.

### Actual behavior

The error message is not displayed on the blocks checkout upon redirect from the auth page. It is displayed only after clicking "Pay now" a second time.

### Screenshots

![Screenshot 2023-11-27 at 1 56 41 PM](https://github.com/Automattic/woocommerce-payments/assets/273592/c2fbeca4-bd38-446b-935e-7dbb12beec2c)

### Expected behavior

The error message should be displayed after the redirect.

**Comment by timur27** [comment] 2023-11-27 13:55
Thanks for reporting this issue @frosso - I can reproduce it with legacy UPE as well.

**Comment by frosso** [comment] 2023-11-28 13:01
_Might_ be related to an upgrade of the blocks/WC plugins

**Comment by brettshumaker** [comment] 2023-12-13 13:56
I can [see in the code](https://github.com/Automattic/woocommerce-payments/blob/56863b221dbdfd9121189fb22303855f16d866d2/includes/payment-methods/class-upe-payment-gateway.php#L743-L746) where the notice is being added to the user session. It looks like the blocks checkout isn't picking that up on page load. I'll keep digging to see if there's anything else we'd be expected to do to surface that notice to the blocks checkout.

**Comment by brettshumaker** [comment] 2023-12-13 17:12
Chatted in Slack with the blocks folks and they think it could be a bug. They've directed me to open an [issue on the blocks repo](https://github.com/woocommerce/woocommerce-blocks/issues/12123).

**Comment by brettshumaker** [comment] 2023-12-14 21:01
Closing as there's no known workaround and once the blocks team implements a fix, our notice should automatically show up.

**Closed as completed by brettshumaker** 2023-12-14 21:01 UTC
Labels: type: bug, priority: high
