### ISSUE TITLE
[GlobalStep] "Base fee" under "Fee details" order note fails to display for UPE payment methods on "Edit Order" page.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#5962] opened 2023-04-04 14:18 UTC
### Bug Description:
"Base fee" under "Fee details" order note fails to display for UPE payment methods on "Edit Order" page.

### Environment:
Woocommerce Version: WooCommerce 7.5.1
WooCommerce Payments - 5.7.0-test-3
WordPress version: v6.2

PC:
Windows 10,
Chrome(Version 111.0.5563.147)
Firefox (Version 111.0.1)

### Steps To Reproduce:
1. Create any test site using the JN site.
2. Install and activate all the required plugins.
3. Enable the UPE "Enable the new WooCommerce Payments checkout experience" on the "Woocommerce >> Payments".
5. Complete the setup.
6. Select any UPE payment (i.e Giropay, Sofort etc) with "Credit card / debit card" on payment method.
7. Click on the save changes.
8. Purchase any product with selected UPE payment method.
9. Navigate to "Woocoomerce > Order" page
15. Observe that "Base fee" under "Fee details" order note fails to display for UPE payment methods on "Edit Order" page.

### Actual Result:
"Base fee" under "Fee details" order note fails to display for UPE payment methods on "Edit Order" page.

### Expected Result:
"Base fee" under "Fee details" order note should be display for UPE payment methods on "Edit Order" page.

### Screenshot:

![#5962](https://user-images.githubusercontent.com/41110392/229822054-732669fa-2fd7-47ba-b723-af6b7ae0f39f.jpg)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.56 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: wp_
Total Database Size: 7.53MB
Database Data Size: 5.30MB
Database Index Size: 2.23MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.16MB + Index: 0.20MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.42MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.41MB + Index: 0.44MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 25
page: 9
post: 2
product: 22
product_variation: 7
revision: 2
shop_coupon: 1
shop_order: 52
shop_order_refund: 5
shop_subscription: 21

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.12.1
Code Snippets: by Code Snippets Pro – 3.3.0
Companion Plugin: by Osk – 1.29
WooCommerce Payments: by Automattic – 5.7.0-test-3
WooCommerce: by Automattic – 7.5.1

### Inactive Plugins (4) ###

Akismet Anti-Spam: by Automattic – 5.1
Hello Dolly: by Matt Mullenweg – 1.7.2
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Subscriptions: by WooCommerce – 5.0.1

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://magellanic-krill.jurassic.ninja
Subscriptions-core Library Version: 5.5.0
Subscription Statuses: wc-cancelled: 1
wc-active: 20

WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 20
wc-cancelled: 1

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

Cash on delivery: products
WooCommerce Payments (giropay): products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-05 06:33:56 +00:00
Options: ✔
Notes: 43
Onboarding: completed

### WooCommerce Payments ###

Version: 5.7.0-test-3
Connected to WPCOM: Yes
Blog ID: 217492506
Account ID: acct_1Mt3UKCSqPY8MKoT

### Action Scheduler ###

Canceled: 14
Oldest: 2023-04-04 07:22:49 +0000
Newest: 2023-04-04 13:07:23 +0000

Complete: 438
Oldest: 2023-04-04 06:34:07 +0000
Newest: 2023-04-04 12:01:29 +0000

Failed: 4
Oldest: 2023-04-04 07:13:57 +0000
Newest: 2023-04-04 13:00:20 +0000

Pending: 22
Oldest: 2023-04-05 06:34:07 +0000
Newest: 2023-06-04 12:34:48 +0000

### Status report information ###

Generated at: 2023-04-04 14:17:12 +00:00
`

</details>

**Comment by leonardola** [comment] 2023-04-14 21:15
I could not reproduce this bug. Tested with stable 5.7.0 version and 5.7.0-test-3

<img width="291" alt="Screenshot 2023-04-14 at 6 14 49 PM" src="https://user-images.githubusercontent.com/6342964/232156129-3f9bc306-aaa1-4069-97d1-1d1bde98c17b.png">

**Comment by jessy-p** [comment] 2023-04-26 18:22
According to Pc2DNy-3z-p2, this falls in Pulsar @kalessil. Tagging as a part of Gamma Porter duties PcreKM-yM-p2.

**Comment by pierorocca** [comment] 2024-01-17 21:56
Closing as legacy UPE has been sunset, was not originally reproducible, and no new instances noted from GS.

**Closed as not planned by pierorocca** 2024-01-17 21:56 UTC
Labels: type: bug, component: checkout, component: upe, category: core
