### ISSUE TITLE
Popover menu on reporting tables is misaligned

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#9870] opened 2024-12-03 05:44 UTC
### Describe the bug

The popover menu present on WooPayments reporting/list view tables is misaligned, resulting in the content of the menu being rendered partially outside the viewport. This impacts the Payouts, Transactions and Disputes list view tables.

This is related to the upstream issue with `@woocommerce/components` `TableCard` that has been fixed in https://github.com/woocommerce/woocommerce/pull/53066. Once this chance has been published in a new `@woocommerce/components` release, this issue should be resolved by `npm install`ing the new version.

![Image](https://github.com/user-attachments/assets/2bd6b813-b7a8-4554-9f9f-934f548913d0)

### To Reproduce

1. Payments → Payouts (or Transactions, Disputes)
2. Click on the three-vertical-dot menu in the top right
3. Notice the menu is misaligned and partially cut-off, outside the viewport

### Screenshots

https://github.com/user-attachments/assets/6bbf54d5-046f-4ef2-a77d-5a7cb37c5dc6

https://github.com/user-attachments/assets/49b1ca4e-948f-45f9-a254-9999449b29e8

https://github.com/user-attachments/assets/d8025c43-0f78-4042-ac2d-b0661459c136

### Desktop (please complete the following information):

* OS: macOS 15.1.1
* Browser: Arc 1.70.0

### Additional context

Observed in #9763.
Related upstream WC PR https://github.com/woocommerce/woocommerce/pull/53066.

**Comment by nagpai** [comment] 2024-12-26 15:43
I tested this with WooCommerce 9.6.0 Beta 1. The issue is resolved with that, and should appear fine once 9.6.0 is released. I am closing this issue here since it is proven that the upstream change will successfully resolve this issue. 

![Image](https://github.com/user-attachments/assets/3b89776f-d468-4cf6-8fc8-69408730a154)

**Closed as completed by nagpai** 2024-12-26 15:43 UTC
Labels: type: bug, priority: medium, focus: reporting
