### ISSUE TITLE
Store WCP fees as order meta

### ISSUE THREAD

**Issue by baddiedev** [Automattic/woocommerce-payments#4445] opened 2022-07-15 20:44 UTC
### Description
WooCommerce Payments fees to be stored in the order meta so that they are visible when viewing an order and can be exported to CSV or accessed by API along with other order meta.

### Acceptance criteria
* The WCP fee would be visible in the 'edit order' screen in the WP admin area.
* The WCP fee would be exportable (as with other order meta) via 3rd party plugins
* The WCP fee would be accessible (as with other order meta) via the WP REST API

### Designs
The UI design changes would be minimal and can be achieved with a single line entry in the order's totals section. Much the same way as the Items Subtotal, Coupons/Vouchers, Order Total and Amount Paid entries already are.

### Additional context
Currently the only way to get order data and meta into a spreadsheet along with the fees information is to export the order data using a 3rd party plugin or the REST API, then download the transactions (via email first for some reason) from Payments -> Transactions, and then somehow reconcile the two reports.

**Comment by htdat** [comment] 2022-07-18 08:37
Thanks for creating this issue @baddiedev. It seems this is a duplicate of https://github.com/Automattic/woocommerce-payments/issues/3257

Therefore, I am closing this now. Feel free to open another issue if you have another request/issue.

**Closed by htdat** 2022-07-18 08:37 UTC
