### ISSUE TITLE
With COT no sync, sorting subscriptions by Next Payment and Last Order Date does not give the correct ordering.

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#4573] opened 2022-08-11 22:18 UTC
### Describe the bug

With custom order table enable but without sync enabled, sorting subscriptions on list admin page by `Next Payment` and `Last Order Date` does not give the correct ordering.

### To Reproduce

1. Install WooCommerce with custom order table feature.
2. Enable custom order table.
3. Go to wp-admin > WooCommerce > Settings > Advanced > Custom data stores > select `Use the WooCommerce orders tables` and uncheck `Keep the posts table and the orders tables synchronized`.
4. Purchase several subscriptions.
5. Go to admin subscriptions list page (wp-admin > WooCommerce > Subscriptions).
6. Click on the column `Next Payment` and `Last Order Date` to order by them ascending and descending.

### Actual behavior

Subscriptions not sorted the correct way.

### Screenshots

![Screen Shot 2022-08-12 at 05 13 06](https://user-images.githubusercontent.com/73803630/184251951-ecbfc8b0-5429-4ccc-9cce-37351bc3fe61.png)
![Screen Shot 2022-08-12 at 05 12 53](https://user-images.githubusercontent.com/73803630/184251956-4bc4a744-b5c3-4d3d-aabe-9bf5dc47a255.png)
![Screen Shot 2022-08-12 at 05 12 33](https://user-images.githubusercontent.com/73803630/184251958-2cb4d338-34e6-481b-a979-e20e5c43770f.png)

### Expected behavior

Subscriptions sorted by the selected column in ascending or descending manner accordingly.

### Additional context

Will be fixed in https://github.com/Automattic/woocommerce-subscriptions-core/issues/200.

**Comment by mattallan** [comment] 2023-02-17 00:59
This issue is caused by a limitation with the new WC Orders ListTable class not being able to support sorting the table by custom fields (like subscription dates).

This has been fixed in WC Core here: https://github.com/woocommerce/woocommerce/pull/36403

**Comment by vbelolapotkov** [comment] 2024-01-29 13:33
Closing based on the comment above.

**Closed by vbelolapotkov** 2024-01-29 13:33 UTC
Labels: type: bug, priority: low, status: blocked, custom order tables
