### ISSUE TITLE
Error when changing subscription payment methods on order-pay to 3DS card

### ISSUE THREAD

**Issue by nicdwilson** [Automattic/woocommerce-payments#9740] opened 2024-11-17 22:51 UTC
### Describe the bug
When using WooPayments and WooCommerce Subscriptions, and using the change payment method option for a specific subscription, the payment method change takes place but an error occurs on the page, giving the customer the impression that the payment method change has not gone through.

This happens when using a card which requires 3DS

The error is `Error: No route was found matching the URL and request method.`

The error can also read `Error processing request. Please try again later`

The error does not occur for non-3DS cards.

The error does not occur in the general change payment method page.

### To Reproduce

1. With a valid subscription, navigate your subscriptions in My Account
2. Click on the view subscription
3. Click on change payment method
4. The /order-pay/XXXX page will open
5. Add a 3DS required test card such as 3220
6. When clearing the 3DS window, the error displays
7. Note that on the subscription and in the account, the payment method change is successful

### Actual behavior
An error is thrown on the page, which makes customers think the process has not been successful. Customers can go through the payment method change process several times as a result.

### Screenshots
![EuSYYy.png](https://github.com/user-attachments/assets/d6fef49c-dc60-4354-baf5-896ea77a392a)

![4H3o5R.png](https://github.com/user-attachments/assets/dadee492-8b29-4de7-b357-f58d073daf8c)

### Expected behavior
The error should not display

### Desktop (please complete the following information):

* OS: MacOS 15
* Browser Firefox/Multiple
* Version 133

### Additional context

8894172-zd-a8c
p1730685641781519-slack-C7U3Y3VMY

**Comment by dmvrtx** [comment] 2024-11-18 15:01
When using a "Twenty Twenty-Five" theme from WordPress 6.7 I can see that "Payment method updated" notice appears _before_ 3DS modal is triggered. And when an error is added on top:

![Image](https://github.com/user-attachments/assets/777c0c72-cb3f-46d2-90ff-0816a77f2f6b)

**Comment by dwainm** [comment] 2024-11-20 08:22
Closing this as duplicate of the error discovered by GS: https://github.com/Automattic/woocommerce-payments/issues/9757

**Closed as completed by dwainm** 2024-11-20 08:22 UTC
Labels: type: bug, focus: payments acceptance & processing
