### ISSUE TITLE
[5.5.0] Products not displaying properly with WCPay enabled

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#5613] opened 2023-02-25 03:43 UTC
### Describe the bug
If a merchant updates to 5.5.0 but they are from a country where WooPay is not available, it can produce a critical error that prevents products from loading properly.

Error:

```
CRITICAL Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /wordpress/plugins/woocommerce-payments/5.5.0/includes/platform-checkout/class-platform-checkout-utilities.php:135
Stack trace:
#0 /wordpress/plugins/woocommerce-payments/5.5.0/includes/platform-checkout/class-platform-checkout-utilities.php(135): in_array('US', NULL, true)
#1 /wordpress/plugins/woocommerce-payments/5.5.0/includes/class-wc-payments-platform-checkout-button-handler.php(489): WCPay\Platform_Checkout\Platform_Checkout_Utilities->is_country_available(Object(WCPay\Payment_Methods\CC_Payment_Gateway))
#2 /wordpress/plugins/woocommerce-payments/5.5.0/includes/class-wc-payments.php(1427): WC_Payments_Platform_Checkout_Button_Handler->should_show_platform_checkout_button()
#3 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): WC_Payments::display_express_checkout_separator_if_necessary('')
#4 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /wordpress/core/6.1.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/plugins/woocommerce/7.4.0/templates/single-product/add-to-cart/variation-add-to-cart-button.php(28): do_action('woocommerce_aft...')
#7 /wordpress/plugins/woocommerce/7.4.0/includes/wc-core-functions.php(345): include('/wordpress/plug...')
#8 /wordpress/plugins/woocommerce/7.4.0/includes/wc-template-functions.php(3085): wc_get_template('single-product/...')
#9 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): woocommerce_single_variation_add_to_cart_button('')
#10 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#11 /wordpress/core/6.1.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#12 /wordpress/plugins/woocommerce/7.4.0/templates/single-product/add-to-cart/variable.php(71): do_action('woocommerce_sin...')
#13 /wordpress/plugins/woocommerce/7.4.0/includes/wc-core-functions.php(345): include('/wordpress/plug...')
#14 /wordpress/plugins/woocommerce/7.4.0/includes/wc-template-functions.php(1748): wc_get_template('single-product/...', Array)
#15 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): woocommerce_variable_add_to_cart('')
#16 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#17 /wordpress/core/6.1.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#18 /wordpress/plugins/woocommerce/7.4.0/includes/wc-template-functions.php(1694): do_action('woocommerce_var...')
#19 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): woocommerce_template_single_add_to_cart('')
#20 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#21 /wordpress/core/6.1.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#22 /wordpress/plugins/woocommerce/7.4.0/templates/content-single-product.php(60): do_action('woocommerce_sin...')
#23 /wordpress/core/6.1.1/wp-includes/template.php(785): require('/wordpress/plug...')
#24 /wordpress/plugins/woocommerce/7.4.0/includes/wc-core-functions.php(284): load_template('/srv/htdocs/wp-...', false)
#25 /wordpress/plugins/woocommerce/7.4.0/templates/single-product.php(37): wc_get_template_part('content', 'single-product')
#26 /wordpress/core/6.1.1/wp-includes/template-loader.php(106): include('/wordpress/plug...')
#27 /wordpress/core/6.1.1/wp-blog-header.php(19): require_once('/wordpress/core...')
#28 /wordpress/core/6.1.1/index.php(17): require('/wordpress/core...')
#29 {main}
  thrown in /wordpress/plugins/woocommerce-payments/5.5.0/includes/platform-checkout/class-platform-checkout-utilities.php on line 135
```

### To Reproduce
I haven't tried to reproduce this personally, but based on discussion in p1677234092205529-slack-C7U3Y3VMY ...

1. Install 5.4.0
2. Onboard with a non-US account
3. Create some products
4. Update to 5.5.0
5. Experience issue on single product pages

There is a PR for this bug (see #5610) but no issue. Creating this so that we can track affected merchants.

**Reverting to 5.4.0 is the current recommended workaround.**

### Additional context

5988845-zd-woothemes
5989903-zd-woothemes
5988845-zd-woothemes
5989452-zd-woothemes
5990920-zd-woothemes
5991011-zd-woothemes

**Comment by Brianmitchtay** [comment] 2023-02-25 03:47
5991011-zd-woothemes
5991016-zd-woothemes

**Comment by csmcneill** [comment] 2023-02-25 03:49
40863891-hc

**Comment by EjayhanFernandes** [comment] 2023-02-25 06:21
5992163-zd-woothemes

**Comment by Brianmitchtay** [comment] 2023-02-25 19:10
41021764-hc

**Comment by mxhassani** [comment] 2023-02-25 19:26
5992106-zd-woothemes 
Downgrading to PHP 7.4 "Fixes it"

**Comment by xue28** [comment] 2023-02-26 06:13
5994260-zen

**Comment by rashedripon** [comment] 2023-02-26 14:03
41040183-hc

**Comment by kaushikasomaiya** [comment] 2023-02-27 06:03
5997111-zen 
5989034-zen
5992092-zen
5996577-zen
5997275-zen
This doesn't seem to be fixed yet so commenting here.

**Comment by druesome** [comment] 2023-02-27 07:59
5991643-zen

**Comment by htdat** [comment] 2023-02-27 08:13
> This doesn't seem to be fixed yet so commenting here.

👋 Hi, the fix for this issue has not been released. WCPay teams are working to release a new version including this fix. p1677482446987009-slack-CGGCLBN58

Update: as a Platform Porter PcreKM-yM-p2, I am putting this issue into pipeline "Triage in progress" for monitoring. I can close this issue when the new version including its fix is released.

**Comment by imodouglas** [comment] 2023-02-27 11:17
15380533-hc

**Comment by imodouglas** [comment] 2023-02-27 11:18
6882063-hc → 5998174-zen

**Comment by lynnjat7** [comment] 2023-02-27 16:12
41078285-hc

**Comment by maxlaf** [comment] 2023-02-27 17:15
5993916-zen

**Comment by Mxchael** [comment] 2023-02-27 20:19
5992692-zen

**Comment by solstudioim** [comment] 2023-02-28 02:26
Reported as well here: HC-24391948

Suggested them to downgrade to WooCommerce Payments version 5.4.0, it worked.

**Comment by htdat** [comment] 2023-02-28 03:12
> Suggested them to downgrade to WooCommerce Payments version 5.4.0, it worked.

While the patch version fixing this issue has not been released yet, that's a good approach. 

Removed this as it's another issue<strike>Also FYI, merchants are now seeing this when editing orders (p1677549075209579-slack-C04RDE70TUJ)</strike>

**Comment by htdat** [comment] 2023-02-28 03:14
Update for HEs: it's also worth following up this p1677467450471249-slack-CB37YNEH1

**Comment by namiokuzono** [comment] 2023-02-28 04:48
6000297-zen

The issue symptoms differ from the reported issue, but the site has the same fatal error log. The issue is that when  WooCommerce Payments 5.5 causes "Proceed to Checkout" and "Place order" to not show on the Cart/Checkout pages.

**Comment by imodouglas** [comment] 2023-02-28 10:28
40620249-hc

The merchant's website stopped loading the product page complete with the error `a fatal error occurred` but they get the same error in the error log.

Rolling back to version 5.4.0 fixed it.

**Comment by lynnjat7** [comment] 2023-02-28 13:20
5986982-zen

**Comment by zoemyers** [comment] 2023-02-28 21:31
40182013-hc

**Comment by dsmithweb-a8c** [comment] 2023-03-01 11:30
40409619-hc

**Comment by neilmccreadie** [comment] 2023-03-01 12:33
3397878-hc

**Comment by NathalyaVides** [comment] 2023-03-01 21:31
5969182-zen

**Comment by maxlaf** [comment] 2023-03-01 22:30
33746786-hc

**Comment by htdat** [comment] 2023-03-02 03:30
FYI. WooCommerce Payments 5.5.1 was released 9 hours ago. 
I am going to close this issue. 

- If a merchant gets the same issue, ensure that they have updated their sites to 5.5.1.
- **If somehow this issue still happens even with 5.5.1, please open a new GitHub issue**.

**Closed as completed by htdat** 2023-03-02 03:30 UTC
Labels: type: bug, component: payment request button, needs triage
