### ISSUE TITLE
Only Apple Pay button shows up in chrome for iOS

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-payments#6676] opened 2023-07-05 16:49 UTC
### Describe the bug
Apple started supporting Apple pay on other browsers a while ago on IOS. Now when a customer visits a site that has Apple and Google pay enabled they only see the Apple pay button. One of the reasons is that our code checks for apple and google pay in a if  else here and other places:

https://github.com/Automattic/woocommerce-payments/blob/0b4603d3394a3a2d2239e5eacc0e751525b7720b/client/payment-request/index.js#L203-L209

To be able to support both buttons at once we need to change the conditionals and probably other places.

### To Reproduce
- Activate Apple and Google Pay on your merchant site
- Visit the page using an iOS device and chrome
- Only apple pay will show up

### Expected behavior
Both Apple and Google pay should show up when both are available for that store and device

### Additional context
Slack thread: p1688322660053339-slack-C7U3Y3VMY
Slack thread: p1663354777831769-slack-C9976E5MJ

**Comment by csmcneill** [comment] 2023-07-07 04:45
Relevant discussion: paJDYF-5zt-p2

**Comment by zmaglica** [comment] 2023-07-07 18:05
This issue impacts Apple Pay, so assigning to Fusion (based on team responsibilities) @anu-rock . Assigning as part of Gamma Triage process PcreKM-yM-p2

**Comment by anu-rock** [comment] 2023-07-10 07:23
Thanks, @zmaglica. I've added it to Fusion's backlog to work on it during our maintenance cycle.

**Comment by pierorocca** [comment] 2023-08-05 16:09
On iOS devices without Apple Pay setup or running lower than iOS 16, shoppers will have no express checkout options.

**Comment by pierorocca** [comment] 2023-08-25 17:14
@anu-rock based on what I'm hearing from Stripe and reading their documentation, using the PRB implementation which is based on W3C, it is not possible to support Google Pay on iOS Chrome. There's a limitation in the current W3C standard. It's only possible by using Stripe's Express Checkout Element which was implemented using direct integrations with Apple and Google rather than the W3C implementation. So I'd be inclined to close this out as it's not a bug, though it wouldn't hurt to remove the unnecessary conditionals from the code.

**Comment by anu-rock** [comment] 2023-08-29 09:35
@pierorocca Thanks a bunch for your research and input. I will mark it as low priority for now and keep it in our backlog to refactor the conditionals.

**Comment by pierorocca** [comment] 2024-04-12 19:47
Closing in favor of the migration to Stripe's Express Checkout Element which unlocks support for this use case. @bborman22 note the bit of code above that filters out the PRBs even though Stripe doesn't render them

**Closed as completed by pierorocca** 2024-04-12 19:47 UTC
Labels: type: enhancement, priority: low, focus: checkout payments
