### ISSUE TITLE
Able to capture cancelled order from Transactions > Uncaptured page

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#5605] opened 2023-02-23 17:08 UTC
### Describe the bug
The listing at Payments > Transactions > Uncaptured shows a listing of orders that have had authorizations done, but they have not been captured. This page does not show the status of the order, so if an order is in Cancelled status, the authorization could be captured here accidentally.

### To Reproduce

1. Enable _Issue an authorization on checkout, and capture later_ under Payments > Settings and then the Transactions section.
2. Place an order in the store.
3. Go to the order in the admin and set it to Cancelled status.
4. Go to Payments > Transactions > Uncaptured.
5. The order will be listed there and you will be able to _Capture_ the payment for it.

### Additional notes

It is possible to go to the order itself and capture the payment through the order actions, as well. This was mentioned in https://github.com/Automattic/woocommerce-payments/issues/173

**Comment by htdat** [comment] 2023-02-24 02:52
👋 @Automattic/pulsar 
I am doing triage for this issue as a part of Platform Porter PcreKM-yM-p2. 
This is one of your product areas Pc2DNy-3z-p2.

**Comment by nagpai** [comment] 2023-04-13 15:58
I am able to successfully reproduce this 

On cancelling a pending capture order, I see that there is no request to cancel the Payment intent sent. Because of this the charge remains open for capture. Once captured, the order status is changed from `Cancelled` to `Processing` 

![image](https://user-images.githubusercontent.com/4162931/231817174-84b94d66-3e83-4c5d-b42c-44d216fa482e.png)

**Comment by kalessil** [comment] 2023-04-14 09:08
More details/desions log: pdjVC1-1vj-p2

**Comment by dmvrtx** [comment] 2023-11-23 09:30
Similar topic: #5712

**Comment by dmvrtx** [comment] 2023-12-19 11:58
Fixed in #7743 by cancelling pending authorization if order is cancelled.

**Closed as completed** 2023-12-19 12:03 UTC
Labels: type: bug, category: core, component: authorizations
