### ISSUE TITLE
stripe.createPaymentMethod() error overrides every other checkout error and is visible to the customer

### ISSUE THREAD

**Issue by cs9k** [Automattic/woocommerce-payments#8270] opened 2024-02-26 18:23 UTC
I'm not sure if this is a new bug introduced by 7.2.0 but it was today where I took full notice and tried to take steps in fixing it

### Describe the bug

When sending an incomplete checkout form with any of the WooPayments payment methods, if the first name and last name fields in the billling address are both left empty, there is an Error from Stripe, which overrides all other errors and prevents the customer from knowing what they actually did wrong/what they actually forgot to provide in their address.

### To Reproduce

1. Put items in your cart
2. Go to the checkout page
3. Leave every field empty
4. Try to pay using any of the WooPayments methods (in our case it was tested with credit card, giropay and Sofort)
5. Receive Stripe error instead of expected "missing required field xyz" error messages

### Actual behavior

Here's the error message, that is displayed inside of the woocommerce-NoticeGroup/woocommerce-NoticeGroup-checkout div:

"You specified "never" for fields.billing_details.name when creating the payment Element, but did not pass params.payment_method_data.billing_details.name when calling stripe.createPaymentMethod(). If you opt out of collecting data via the payment Element using the fields option, the data must be passed in when calling stripe.createPaymentMethod()."

### Screenshots

The error message, that is displayed:
![image](https://github.com/Automattic/woocommerce-payments/assets/13137670/18703804-0010-4460-946d-532003507a12)

The noticeGroup div as it is presented in HTML:
![image](https://github.com/Automattic/woocommerce-payments/assets/13137670/eefc91e0-0a5b-464a-b354-f3d234e1b24a)

stripe-js call to https://r.stripe.com/b (censored as needed)
![image](https://github.com/Automattic/woocommerce-payments/assets/13137670/28dd939c-354a-41a7-ae21-093aec4da617)

### Expected behavior

Obviously the checkout form completeness should be checked before trying to create the Stripe payment Method.
Excuse the german language but here is the error output for the same checkout when trying to use without inputting anything
![image](https://github.com/Automattic/woocommerce-payments/assets/13137670/15ae2f16-7da6-45b4-bcf3-4d6e1d6c8b11)
![image](https://github.com/Automattic/woocommerce-payments/assets/13137670/20f92278-5892-4114-8822-1a8730ad0cb6)

Also the customer has no business with, nor does he want to know the internal errors of the payment method. The customer should only be able to see that he forgot to put his anme in, correct that and go ahead with his order

### Desktop (please complete the following information):

Independent on client device since it's a server issue

### Smartphone (please complete the following information):

Independent on client device since it's a server issue

**Comment by htdat** [comment] 2024-02-27 06:34
@cs9k - thanks for reporting this issue. Based on my testing, this issue has been introduced since WooPayments 7.1.0. 

I tested a few versions <= 7.0.0 and did not see this issue. We will troubleshoot this issue further and update here later.

**Comment by htdat** [comment] 2024-02-27 07:18
@frosso and @timur27 - it seems that this commit 880bfea5855eef69396cc041fdb1ee3975e8bc3b is causing this regression. File `client/checkout/classic/payment-processing.js` of this commit is changed the handling of billing data, which seems relevant to the error here. Could you have a look? 

Anyway, I used git bisect between 7.1.0 (bad) and 7.0.0 (good) to find it out - [log](https://github.com/Automattic/woocommerce-payments/files/14415757/git-bisect.log.bash.zip). I also tested this commit, and another commit right before it for confirmation of the cause.

**Comment by frosso** [comment] 2024-02-27 13:29
During my testing, I noticed that the error presented itself only with an anonymous/new customer, and only when the customer would already fill in the CC fields (leaving the other WC fields empty).

I also noticed that the error is present for card payments and all other payment methods, and only on shortcode checkout (blocks checkout isn't affected).
I noticed that with other payment methods besides CC, even before 880bfea5855eef69396cc041fdb1ee3975e8bc3b, the same error appeared.

I have a fix on https://github.com/Automattic/woocommerce-payments/pull/8276 that fixes the CC behavior.

**Comment by FangedParakeet** [comment] 2024-02-28 01:05
Thanks for the report @cs9k! This issue is a duplicate of #8192, so I am going to close it in favour of the latter, since work has begun and is progressing on said alternate issue. Please feel free to track any further progress on this issue on #8192. 🙏

**Closed as completed by FangedParakeet** 2024-02-28 01:05 UTC
Labels: type: bug, component: checkout
