### ISSUE TITLE
feat: payment element styles on "Add payment method" page

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#8413] opened 2024-03-18 16:00 UTC
### Description

When the payment element is rendered at checkout, we use pass some styles to Stripe. These styles are auto-generated based on the site's look & feel.

The payment element is also rendered on the "Add payment method" page, in the customer's "My account" pages.

If styles have been previously calculated at checkout, those styles will be used by the "My account" page.
However, if no styles are present (e.g.: because the nonce used as cache expired), the default payment element styles will be used.

It would be great to ensure that the styles on the "my account" page could also be auto-generated.

### Acceptance criteria

- Payment Element styles are calculated and used on the "My account" pages

### Designs

N/A

### Testing instructions

- Clear your nonces (or comment out [these lines](https://github.com/Automattic/woocommerce-payments/blob/beff10e730e31ea6c50f2e59eb9072ea82718d30/includes/class-wc-payments-checkout.php#L220-L221))
- As a customer, go to the "Add payment method" page

### Dev notes

Using a separate nonce/cache for the "my account" page would likely be beneficial, rather than reusing the one from checkout.

### Additional context

This issue has been highlighted after working on https://github.com/Automattic/woocommerce-payments/issues/8383

**Comment by zmaglica** [comment] 2024-03-18 19:53
Hi @pierorocca. Could Shopper Experience team work on this issue? I am asking this since I am doing Gamma Triage process PcreKM-yM-p2, and based on the applied label, this issue could be for them.

**Comment by pierorocca** [comment] 2024-03-18 20:53
Thanks @zmaglica yes. If you could add missing `type: bug` or `type: enhancement` labels, the Shopper project board will auto-ingest the issue.

**Comment by danielmx-dev** [comment] 2024-06-19 19:33
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/8413?planning-poker) with Zenhub @FangedParakeet

**Comment by danielmx-dev** [comment] 2024-06-21 15:52
Regarding the following information: 

> If styles have been previously calculated at checkout, those styles will be used by the "My account" page.
However, if no styles are present (e.g.: because the nonce used as cache expired), the default payment element styles will be used.

And:

> This issue has been highlighted after working on https://github.com/Automattic/woocommerce-payments/issues/8383

After trying to reproduce the issue, I wasn't able to do it. It looks like the issue that prevented the styles from being calculated in the Add Payment Method page when the transient didn't exist was fixed in this PR: https://github.com/Automattic/woocommerce-payments/pull/8421

However, the same PR introduced a small regression that prevents the styles from being calculated as intended in the shortcode/classic checkout.

I'll fix the regression and implement the separate transient as part of this issue's work.

**Closed as completed** 2024-06-24 18:14 UTC
Labels: type: enhancement, priority: medium, focus: checkout payments
