### ISSUE TITLE
Jetpack "Return to your site" button redirects to Stripe KYC flow instead of returning to site

### ISSUE THREAD

**Issue by juliaamosova** [Automattic/woocommerce-payments#1033] opened 2020-10-20 20:59 UTC
**Describe the bug**

It seems there is no easy way to go back to the site once started WC Payments setup through the Home Screen Task. 

**To Reproduce**

1. Create a new JN site. 
2. Upload WC 4.7 Beta1. 
3. Complete onboarding (US store + select to install free business extensions).
4. Once on the Home Screen, click on the task to set up WC Payments.
5. You will be presented with the modal to connect to WC.com/Jetpack - complete it. 
6. Next, you will see the beginning of the WC Payments setup process. 
7. At this point, try to go back to the site. The only way to do that seems to be using the browser's back button. 
8. Please see below the gif of what happens - basically, you get back to the WC.com/Jetpack modal - from there you can go back to the site using 2 different ways (through the button and the link) but none of these take you back to the site. Instead, you are taken back to the WC Payments setup modal:

![](http://g.recordit.co/nBteB0H9aj.gif)

**Expected behavior**

I expected to be able to easily go back to the site if I didn't want to set up WC Payments right away. 

**Screenshots**

See gif above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.6
* Browser: Chrome
* Version: 86.0.4240.80 (Official Build) (x86_64)

**Additional context**

N/A.

**Comment by thenbrent** [comment] 2020-10-21 06:00
That flow is on Stripe's side, so we're not able to change it.

We could ask them about having it changed, but I question whether this is a bug, or even design issue. /cc @LevinMedia to weigh in on whether you think we should be asking Stripe to change the design of that flow.

I expect that either Stripe consider the browser's back button to be sufficient for navigation, and/or there is no direct link back to the site to to improve activation / completion rate of the KYC flow.

**Comment by dechov** [comment] 2020-10-21 09:27
@thenbrent That sounds right for the matter of backing out of the Stripe flow, except it looks like the main issue here is that – after doing so – the "Return to your site" button(s) returns you to that Stripe flow instead of your site.

Discussed with @vbelolapotkov briefly and he had pointed out that root issue and also that we could test from our own /connect screen to see if it's the same behavior and not to do with the task list specifically.

We provide a redirect URL to the Jetpack connection flow, which I suppose it expects to always be the merchant's site but in our case is the Stripe OAuth flow. (As implemented, we essentially consider them pieces of a single flow.) One solution could be to redirect back to the site and only _then_ (immediately) to Stripe. cc @DanReyLop

**Comment by thenbrent** [comment] 2020-10-21 11:03
> the "Return to your site" button(s) returns you to that Stripe flow instead of your site.

Ah I totally missed that. Thanks for clarifying.

**Comment by DanReyLop** [comment] 2020-10-22 13:10
> One solution could be to redirect back to the site and only then (immediately) to Stripe.

That's actually what's already happening. [Here's where that redirect URL us set](https://github.com/Automattic/woocommerce-payments/blob/799c01d4fb812a964904067000736581a39566f6/includes/class-wc-payments-account.php#L377-L385). `get_oauth_return_url()` is just the `WooCommerce -> Settings -> Payments -> WCPay` screen (most of the time). The problem is, [this logic](https://github.com/Automattic/woocommerce-payments/blob/799c01d4fb812a964904067000736581a39566f6/includes/class-wc-payments-account.php#L287-L308) immediately redirects to Stripe. Which makes sense. The current URL will be something like `?wcpay-connect=1&wcpay-connect-jetpack-success=1`, and at that point Jetpack will read as connected. The next logical step at that point is to redirect to the KYC flow.

There's no way to tell the Jetpack flow "this is the URL to redirect on success, and this different one is the URL to redirect when clicking the Back button". At least I don't remember that being an option (I would have implemented it that way if I could). So, in order to differentiate one thing from the other, we'd need to set a transient or something similar. Something that can tell us "`wcpay-connect-jetpack-success` is set, Jetpack reads as connected, **and** Jetpack wasn't connected last time this logic was executed".

**Comment by dechov** [comment] 2020-10-23 11:55
Ah, right – thanks. It looks like if they keep going "Back" from the Jetpack flow, it's behaves fine, so I think this issue is essentially about the wording on the Jetpack connection side (though I'm not sure how to improve that).

Just noticed that even in the normal forward flow, Jetpack says "returning to your site" before redirecting to Stripe – not ideal but also not that big of a deal. Redirecting the actual browser interface through the site would be one way to mitigate it, even if it just says "Redirecting to Stripe…" and goes on with it, but it may not be not worth the effort and slower result.

**Comment by dechov** [comment] 2020-10-30 18:58
@DanReyLop If the WooCommerce Payments edition of the Jetpack connection flow is always followed by the Stripe KYC flow, can we just adjust that labeling from "Return to your site" to "Proceed to [something]"?

**Comment by DanReyLop** [comment] 2020-10-30 19:11
>  If the WooCommerce Payments edition of the Jetpack connection flow is always followed by the Stripe KYC flow, can we just adjust that labeling from "Return to your site" to "Proceed to [something]"?

The thing it, the "Return to your site" link just takes you back to your site. The normal use case for that link is that you don't feel like connecting to Jetpack right now. In that case, the links works as it should.

The problem here is this flow:
- WP-Admin, click on Set Up WCPay
- WP.com, connect the account
- Stripe KYC. At this point, decide to go back.

The "go back" using the browser button, in this case, takes you back to the WP.com flow, **even though the site is already connected**. I'd rather not complicate the Calypso flow even more to account for this edge case.

> One solution could be to redirect back to the site and only then (immediately) to Stripe.

This may be the best approach. Right now, the `WP-Admin -> Stripe` redirection after the WP.com flow happens in PHP (using a HTTP `Location: ...` header). It's been a while since I've learnt my PHP/HTML basics, but I think that isn't stored in the browser's history. So using a client-side (JS) redirect may do the trick.

**Comment by dechov** [comment] 2020-10-30 19:22
Oh right – I guess "Return to your site" is still what we want in some cases.

I wouldn't think of this entirely as an edge case, considering that everyone sees "Returning to your site…" right before the redirect to Stripe – not a huge deal, but could leave an uneasy feeling of something unintended having happened.

> redirection after the WP.com flow … isn't stored in the browser's history

Yeah, that's correct I'm pretty sure.

I suppose a JS redirect is the way to go here then, despite complicating the code and slowing down the experience.

**Comment by daquinons** [comment] 2022-11-04 17:57
Seems like after a conversation the best approach for this is to modify the way that we redirect from WP.com to Stripe. Right now it's using PHP and HTTP header, which is not stored in the browser history and clicking on "Returning to your site..." in Stripe redirects again to the KYC in Stripe.

**Comment by ismaeldcom** [comment] 2023-01-17 14:12
As part of the new onboarding experience where we own more parts of the process, Jetpack connection and Stripe KYC will be separated by intermediate onboarding pages. Solving this issue in a better way, because there will be no multiple redirections or inconsistencies in the browser's history.

Doing the JS redirection could be a solution, but it's a bit hacky. And the merchant will still see "Returning to your site…" while being redirected to Stripe. Even if under the hood we're doing a `Jetpack → Merchant's site → Stripe` redirection.

There is no need for an issue, as it will be handled by design in the project. So I'm closing this.

**Comment by daquinons** [comment] 2023-06-05 06:20
I'm reopened this, look at the context of this discussion p1685945492391789/1685937975.463659-slack-C03KTTK2YMA)

**Comment by daquinons** [comment] 2023-08-03 06:53
I haven't been able to reproduce this behavior. I don't know if something changed in Jetpack, or in Stripe (as even the look of the flow from the first message is different!), but now after connecting my account to Jetpack and clicking on "Return to site" in Stripe I'm taken back to the Connect screen in the site.

I've discovered an issue in the progressive onboarding when investigating this one. I'll be opening a new one for it!

**Closed by daquinons** 2023-08-03 06:53 UTC
Labels: type: bug, priority: low, component: onboarding, category: core
