### ISSUE TITLE
Stripe product loses synchronised status when products are deleted/ restored with WC Payments deactivated

### ISSUE THREAD

**Issue by martynmjones** [Automattic/woocommerce-payments#3985] opened 2022-03-18 09:25 UTC
### Describe the bug
By deactivating and reactivating WooCommerce Payments while deleting trashing or restoring a subscription (core) product it's possible for the `active` status on Stripe to become out of sync which prevents customers from being able to purchase that product.

### To Reproduce

1. Create a simple subscription product on a site with WC Payments + Subs core
2. Delete the product which [archives the product in Stripe](https://github.com/Automattic/woocommerce-payments/blob/09e0b1a277280d60ff8bf1e901a67a42dbb23109/includes/subscriptions/class-wc-payments-product-service.php#L320)
3. Deactivate WooCommerce Payments
4. Restore the deleted product from trash
5. Reactivate WooCommerce Payments
6. Attempt to checkout with that subscription product

Because WC Payments was deactivated at the point the product was restored it doesn't get [unarchived on Stripe](https://github.com/Automattic/woocommerce-payments/blob/09e0b1a277280d60ff8bf1e901a67a42dbb23109/includes/subscriptions/class-wc-payments-product-service.php#L337).

### Actual behavior
When attempting to purchase the subscription after that has happened the customer encounters an error message which reads `There was a problem creating your subscription`

### Screenshots
<img width="1194" alt="Markup 2022-03-18 at 08 52 07" src="https://user-images.githubusercontent.com/40762232/158970701-cfc3fc99-c6d8-4387-8b4f-dd07e263af7a.png">

### Expected behavior
As WooCommerce is the product management system in this situation I would expect that I would be able to purchase this subscription product and if the status on Stripe has fallen out of sync that there would be a secondary check to avoid a situation where these products become unusable

### Additional context

4780032-zen

**Comment by haszari** [comment] 2022-04-27 04:34
Looks like we're not handling this edge case very smoothly. Would be good to improve this, though I don't think it's a high priority, as deleting and restoring products from trash is an uncommon merchant flow. 

Is the merchant able to work around this by recreating a new product? That seems like a reasonable workaround, if it's not practical or we get more reports we could raise the priority. 

That said, would be great to make this more robust, e.g. show more useful error messages or ideally unarchive the product automatically.

> Deactivate WooCommerce Payments

Side note: can this issue be reproduced without deactivating & reactivating WCPay? That detail makes it seem like a rare edge case.

**Comment by martynmjones** [comment] 2022-04-27 07:12
Thanks for looking into this @haszari.

> Is the merchant able to work around this by recreating a new product? That seems like a reasonable workaround, if it's not practical or we get more reports we could raise the priority.

As a workaround we had the user delete the product again and then restore it while WC Payments was active to unarchive it on Stripe. After doing that everything worked again as expected and new subscriptions could be created.

> Side note: can this issue be reproduced without deactivating & reactivating WCPay? That detail makes it seem like a rare edge case.

I was not able to reproduce a similar outcome without deactivating WC Payments so it's definitely a rare edge case and not high priority at the moment.

**Comment by haszari** [comment] 2022-04-27 21:09
> I was not able to reproduce a similar outcome without deactivating WC Payments so it's definitely a rare edge case and not high priority at the moment.

Thanks for clarifying @martynmjones ! In that case, we might not need to make any changes to "fix" this. We could possibly clarify in the documentation if it comes up again. 

I'm thinking it's ok to close this issue.

**Comment by martynmjones** [comment] 2022-05-01 09:50
Thanks @haszari! I've flagged this with the docs guild to include in the WC Payments docs

**Closed** 2022-05-01 20:54 UTC
Labels: type: bug, priority: low, type: documentation, component: wcpay subscriptions, category: core
