### ISSUE TITLE
UPE: Purchasing same item twice in a row gives intent error

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#5781] opened 2023-03-15 17:30 UTC
### Describe the bug
If you purchase an item then add the same item to your cart again and try to purchase it again, you get this error:

> Error: The parameter application_fee_amount cannot be updated on a PaymentIntent after a capture has already been made.

### To Reproduce

1. Make sure UPE is enabled in your store.
2. Add a simple product to your cart and complete checkout.
3. Add the item to your cart again and try to complete checkout.
4. Receive error.

### Additional context
May be fixed by #5653

**Comment by htdat** [comment] 2023-03-17 07:44
This seems a duplicate of https://github.com/Automattic/woocommerce-payments/issues/5310

I am closing this one but if you need re-open it, feel free to do so.

--- 

Note: I am doing that as a part of Gamma Porter duties PcreKM-yM-p2.

**Comment by jessepearson** [comment] 2023-03-17 10:52
Just noting that I previously saw #5310 and noticed it was similar and the PR for it might fix this issue, but #5310 has no clear replication steps and speaks about if a payment doesn't initially go through. In the instance in this issue the error happens after you make a purchase, then add the same item to your cart again and try to purchase it again. This should be a whole new session with a whole new intent since everything completed correctly without any failures.

**Comment by htdat** [comment] 2023-03-24 07:55
@jessy-p and I discussed a similar issue and I think it's worth reopening this issue. 

### Steps to replicate: 

- Use split-UPE.
- Check out an order for **a specific item** with a payment method such as card, giropay, sofort, etc.
- Check out again with the same payment method and **the same item**.
- Get the error regarding `application_fee_amount`. 

I tested with legacy-UPE and this issue does not happen with that flow.

### Cause: 

I think that's because [UPE_Split_Payment_Gateway](https://github.com/Automattic/woocommerce-payments/blob/c0f390b120a3acbc4952fe9d9e423ea85d5eebed/includes/payment-methods/class-upe-split-payment-gateway.php#L42-L42) extends `UPE_Payment_Gateway` around [the intent ID caching](https://github.com/Automattic/woocommerce-payments/blob/c0f390b120a3acbc4952fe9d9e423ea85d5eebed/includes/payment-methods/class-upe-split-payment-gateway.php#L366-L492) including this static method `remove_upe_payment_intent_from_session` for having the ability to support all payment methods.

However, this static method is called with `self` within `UPE_Payment_Gateway` classes or directly with the class name `UPE_Payment_Gateway` in `WC_Payment_Gateway_WCPay`. These are usages I could find: 

![Markup on 2023-03-24 at 14:47:24](https://user-images.githubusercontent.com/10045087/227457951-01ed2698-8965-4cc2-89f4-6b6a3d49fb91.png)

With this way, it never reaches out to the extended method: `UPE_Split_Payment_Gateway::remove_upe_payment_intent_from_session`, and then the payment intent cached in session is never cleared up properly in split-UPE. 

### Solution 

I think the simple solution is to change `self` to `$this` within class `UPE_Payment_Gateway`, or simply use `static::remove_upe_payment_intent_from_session`. 
For static calls in `WC_Payment_Gateway_WCPay`, I am not sure the best way to deal with it right now.

**Comment by htdat** [comment] 2023-03-24 08:11
cc @Automattic/heisenberg for looking at this issue. 

@jessepearson - Could you check my steps in my recent comment and confirm?

**Comment by FangedParakeet** [comment] 2023-03-28 05:00
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/5781?planning-poker) with Zenhub @mdmoore @timur27

**Comment by FangedParakeet** [comment] 2023-04-17 22:11
@mdmoore, could you share your vote for the planning points estimate on this issue whenever you've got a spare mo? Cheers!

**Comment by timur27** [comment] 2023-04-21 15:14
I gave it 2SP initially because the cause is well-described, but I'm fine with updating it to 3SP since most of the team chose this estimate, and it seems we still see some unknowns that we might face down the road.

**Comment by mdmoore** [comment] 2023-04-21 20:14
@jessepearson @htdat Are you able to reproduce this on the latest `develop` branch? I've tested under a lot of different conditions and the 2nd payment always processes without the `application_fee` error and [`UPE_Split_Payment_Gateway::remove_upe_payment_intent_from_session`](https://github.com/Automattic/woocommerce-payments/blob/c0f390b120a3acbc4952fe9d9e423ea85d5eebed/includes/payment-methods/class-upe-split-payment-gateway.php#L387) is firing with each payment. Is there some small step missing from the [list here](https://github.com/Automattic/woocommerce-payments/issues/5781#issuecomment-1482393563)?

**Comment by htdat** [comment] 2023-04-24 07:37
@mdmoore - It seems that I missed the important piece - you will need to check out with the same product item so that the cart_hash will be the same. I've updated [my testing steps](https://github.com/Automattic/woocommerce-payments/issues/5781#issuecomment-1482393563), tested again. I confirmed that the issue is still there.

**Comment by jessepearson** [comment] 2023-04-24 12:53
@mdmoore I've just tried to test and I am not getting the error any more, unsure of what changed. I tried logged in and logged out using the same product, as initially described, and I cannot replicate it any more.

**Closed as completed** 2023-05-10 19:47 UTC
Labels: type: bug, component: upe
