### ISSUE TITLE
BNPL messaging displays in incorrect position when Storefront theme is not active

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#7353] opened 2023-10-03 14:40 UTC
### Describe the bug

The BNPL site messaging in the product details page displays in incorrect position when Storefront theme is not active. This issue has been spotted with the Twenty Twenty-Three theme.

### To Reproduce

1. In WP Admin, enable any BNPL payment method
2. As a shopper, navigate to the details page of a product (note: subscriptions are not supported)
3. See error

### Actual behavior

The BNPL site messaging element is misplaced in the product details page.

### Screenshots

<img width="2324" alt="Screenshot 2023-10-03 at 16 36 22" src="https://github.com/Automattic/woocommerce-payments/assets/1553182/f3d3ba1f-7334-4b30-b9af-82feb0989827">

### Expected behavior

The BNPL site messaging element is placed correctly in the product details page.

**Comment by mdmoore** [comment] 2023-12-06 16:38
This occurs with block based themes like Twenty-Twenty Three because the `woocommerce_single_product_summary` action isn't yet hooked to the Product Summary block. This was just taken care of in WooCommerce Blocks [here](https://github.com/woocommerce/woocommerce-blocks/pull/11953) and released in WooCommerce Blocks 11.7.0. WooCommerce Blocks 11.7.0 [will go out with WooCommerce 8.5.0](https://github.com/woocommerce/woocommerce/pull/41876). I've confirmed that the issue is resolved with the latest WC Blocks release. 

With that in mind, I don't think this warrants a fix in WooPayments. Merchants encountering this issue can update to latest WooCommerce and WooCommerce Blocks for an immediate fix. 

@frosso What do you think?

**Comment by frosso** [comment] 2023-12-07 16:00
@mdmoore thanks for investigating it!

It sounds like the fix is available on the new version of WC Blocks. Merchants can update to that or wait for the WC 8.5.0 release.

Good sleuthing, let's close this 👍

**Closed as completed by frosso** 2023-12-07 16:00 UTC
Labels: type: bug, priority: high, category: projects, component: affirm & afterpay
