### ISSUE TITLE
[GlobalStep] PHP Fatal error triggered after clicking 'Change payment method' button using new payment method on "My Account > Subscriptions" page.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#9757] opened 2024-11-19 11:19 UTC
### Bug Description:
PHP Fatal error triggered after clicking 'Change payment method' button using new payment method on "My Account > Subscriptions" page.

### Environment:
Woocommerce Version: WooCommerce  9.5.0-beta.1
WooCommerce Payments: 8.6.0-test-1
WordPress version: v6.7

PC:
Windows 10,
Chrome(Version 131.0.6778.70)
Firefox (Version 132.0.2)

### Steps To Reproduce:
1. Create any test site.
2. Install and activate all the required plugins.
3. Install and activate the Woocommerce version 9.5.0-beta.1 plugin.
4. Install the version of WooCommerce Payments 8.6.0-test-1 plugin.
5. Complete WooCommerce Payments KYC flow.
6. Ensure WooCommerce Subscriptions is installed and active.
7. Follow steps from 'Purchase subscription product'.
8. As a Shopper, navigate to 'My account -> Subscriptions' and open the newly created subscription entry.
9. Observe 3 buttons for 'Actions'. Click 'Change payment' button.
10. In the second block, select 'Use a new payment method' option.
11. Provide 4242424242424242 as the test card number, future expiration date, and a CVC code.
12. Click 'Change payment method' button.
13. Observe that, PHP Fatal error triggered after clicking 'Change payment method' button using new payment method on "My Account > Subscriptions" page.

### Instruction Link:
https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#change-subscription-payment-method-to-a-new-card

### Actual Result:
PHP Fatal error triggered after clicking 'Change payment method' button using new payment method on "My Account > Subscriptions" page.

### Expected Result:
'Payment method updated.' success message should be displayed after clicking 'Change payment method' button using new payment method on "My Account > Subscriptions" page.

### Video:

![Image](https://github.com/user-attachments/assets/5f12293a-ba0e-423f-acd1-a87e35cbb090)

### Fatal Error Log:

[#9757 Fatal error logs.txt](https://github.com/user-attachments/files/17814351/9757.Fatal.error.logs.txt)

Woocommerce bugs uploading format:

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.5.0-beta.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.3.13
PHP Post Max Size: 2 GB
PHP Time Limit: 850
PHP Max Input Vars: 6144
cURL Version: 8.10.1
OpenSSL/3.0.14

SUHOSIN Installed: –
MySQL Version: 10.11.10-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 25
page: 8
post: 2
product: 25
product_variation: 7
revision: 3
shop_coupon: 1
shop_order_placehold: 69
wp_font_face: 36
wp_font_family: 12
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.5
Code Snippets: by Code Snippets Pro – 3.6.5.1
Query Monitor: by John Blackbourn – 3.16.4
WooPayments: by WooCommerce – 8.6.0-test-1
WooCommerce Subscriptions: by WooCommerce – 6.9.0
WooCommerce: by Automattic – 9.5.0-beta.1

### Inactive Plugins (1) ###

WooCommerce Payments Dev Tools: by Automattic –

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 6 MB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 8.6.0-test-1
Connected to WPCOM: Yes
WPCOM Blog ID: 239154141
Account ID: acct_1QMm0gCOswTqyGlV
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Disabled
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Disabled
Documents: Disabled
Logging: Enabled

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://dreamily-select.jurassic.ninja
Subscriptions-core Library Version: 7.7.1
Subscription Statuses: wc-active: 21
wc-cancelled: 1

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooPayments: wc-active: 21
wc-cancelled: 1


### Payment Gateway Support ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout

Daily Cron: ✔ Next scheduled: 2024-11-20 07:35:18 +00:00
Options: ✔
Notes: 60
Onboarding: skipped

### Action Scheduler ###

Canceled: 22
Oldest: 2024-11-19 07:51:20 +0000
Newest: 2024-11-19 11:03:24 +0000

Complete: 484
Oldest: 2024-11-19 07:36:34 +0000
Newest: 2024-11-19 09:36:12 +0000

Failed: 5
Oldest: 2024-11-19 07:44:29 +0000
Newest: 2024-11-19 10:55:55 +0000

Pending: 26
Oldest: 2024-11-19 11:17:36 +0000
Newest: 2025-01-19 09:37:29 +0000


### Status report information ###

Generated at: 2024-11-19 11:17:00 +00:00
```
</details>

**Comment by dwainm** [comment] 2024-11-20 08:22
Also reported here: https://github.com/Automattic/woocommerce-payments/issues/9740

**Comment by dwainm** [comment] 2024-11-20 08:25
cc @deepakpathania or @c-shultz  for the bug might be quite urgent. 

cc @dmallory42 (current release lead).

**Comment by dmallory42** [comment] 2024-11-20 10:36
I tried to replicate this on a couple on JN sites, and I'm seeing a similar but slightly different issue where I can't see the `/my-account/view-subscription` page after purchasing a subscription:

![Image](https://github.com/user-attachments/assets/1d3326ba-e54e-47e3-94ca-48813c261296)

I think this could be related, so sharing my findings here:

# Repro Steps

1. Create any test site.
2. Install and activate all the required plugins.
3. Install and activate the Woocommerce version 9.5.0-beta.1 plugin.
4. Install the version of WooCommerce Payments 8.6.0-test-1 plugin.
5. Complete WooCommerce Payments KYC flow.
6. Ensure WooCommerce Subscriptions is installed and active.
7. Follow steps from 'Purchase subscription product'.
8. As a Shopper, navigate to 'My account -> Subscriptions' and open the newly created subscription entry.
9. You should see a `Page not found` error.

Edit: the issue I saw is specifically occuring when using the _Twenty Twenty Four_ theme. When using a shop theme like StoreFront, the page loads as expected.

**Comment by dmallory42** [comment] 2024-11-20 10:53
I'm now able to reproduce the bug, and can confirm it works as expected on WooPayments 8.5.0, but not on 8.6.0-test-1.

**Comment by c-shultz** [comment] 2024-11-20 16:45
>can confirm it works as expected on WooPayments 8.5.0, but not on 8.6.0-test-1.

I'm flagging this as critical. I'll bring it Slack for a little more visibility and so we can all get clear on ownership and next steps

**Comment by dmallory42** [comment] 2024-11-21 10:26
Noting that this is still reproducible - here is a stack trace from a fresh JN site after the server update to support `seti_` format:

```
2024-11-21T09:15:36+00:00 Critical Uncaught WCPay\Exceptions\API_Exception: Error: No such payment_intent: 'seti_1QNWU4FoBX481L1dHp4XxkZf' in /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-api-client.php:2362  
Additional context
2024-11-21T09:15:58+00:00 Critical Uncaught WCPay\Exceptions\API_Exception: Error: No such payment_intent: 'seti_1QNWU4FoBX481L1dHp4XxkZf' in /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-api-client.php:2362 CONTEXT: {"error":{"type":1,"file":"/srv/htdocs/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-api-client.php","line":2362},"remote-logging":true,"backtrace":["","#0 /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-api-client.php(2156): WC_Payments_API_Client->check_response_for_errors(Array)","#1 /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-api-client.php(246): WC_Payments_API_Client->request(Array, 'intentions/seti...', 'GET')","#2 /srv/htdocs/wp-content/plugins/woocommerce/src/Internal/Orders/PaymentInfo.php(122): WC_Payments_API_Client->get_intent('seti_1QNWU4FoBX...')","#3 /srv/htdocs/wp-content/plugins/woocommerce/src/Internal/Orders/PaymentInfo.php(39): Automattic\WooCommerce\Internal\Orders\PaymentInfo::get_wcpay_card_info(Object(WC_Subscription))","#4 /srv/htdocs/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(608): Automattic\WooCommerce\Internal\Orders\PaymentInfo::get_card_info(Object(WC_Subscription))","#5 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-order.php(2353): WC_Abstract_Order->get_payment_card_info()","#6 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-order.php(2404): WC_Order->add_order_item_totals_payment_method_row(Array, 'excl')","#7 /srv/htdocs/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscription.php(2705): WC_Order->get_order_item_totals('excl')","#8 /srv/htdocs/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/templates/checkout/form-change-payment-method.php(25): WC_Subscription->get_order_item_totals()","#9 /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/srv/htdocs/wp-...')","#10 /srv/htdocs/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-change-payment-gateway.php(201): wc_get_template('checkout/form-c...', Array, '', '/srv/htdocs/wp-...')","#11 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(324): WC_Subscriptions_Change_Payment_Gateway::maybe_replace_pay_shortcode('')","#12 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)","#13 /srv/htdocs/__wp__/wp-includes/plugin.php(517): WP_Hook->do_action(Array)","#14 /srv/htdocs/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(258): do_action('after_woocommer...')","#15 /srv/htdocs/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(61): WC_Shortcode_Checkout::order_pay(66)","#16 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(72): WC_Shortcode_Checkout::output(Array)","#17 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(95): WC_Shortcodes::shortcode_wrapper(Array, Array)","#18 /srv/htdocs/__wp__/wp-includes/shortcodes.php(434): WC_Shortcodes::checkout(Array, '', 'woocommerce_che...')","#19 [internal function]: do_shortcode_tag(Array)","#20 /srv/htdocs/__wp__/wp-includes/shortcodes.php(273): preg_replace_callback('/\\[(\\[?)(woocom...', 'do_shortcode_ta...', '[woocommerce_ch...')","#21 /srv/htdocs/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/Checkout.php(157): do_shortcode('[woocommerce_ch...')","#22 /srv/htdocs/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/AbstractBlock.php(98): Automattic\WooCommerce\Blocks\BlockTypes\Checkout->render(Array, '\n<div class="wp...', Object(WP_Block))","#23 /srv/htdocs/__wp__/wp-includes/class-wp-block.php(537): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback(Array, '\n<div class="wp...', Object(WP_Block))","#24 /srv/htdocs/__wp__/wp-includes/blocks.php(2190): WP_Block->render()","#25 /srv/htdocs/__wp__/wp-includes/blocks.php(2242): render_block(Array)","#26 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(324): do_blocks('<!-- wp:woocomm...')","#27 /srv/htdocs/__wp__/wp-includes/plugin.php(205): WP_Hook->apply_filters('<!-- wp:woocomm...', Array)","#28 /srv/htdocs/__wp__/wp-includes/blocks/post-content.php(50): apply_filters('the_content', '<!-- wp:woocomm...')","#29 /srv/htdocs/__wp__/wp-includes/class-wp-block.php(537): render_block_core_post_content(Array, '<!-- wp:woocomm...', Object(WP_Block))","#30 /srv/htdocs/__wp__/wp-includes/class-wp-block.php(517): WP_Block->render()","#31 /srv/htdocs/__wp__/wp-includes/class-wp-block.php(517): WP_Block->render()","#32 /srv/htdocs/__wp__/wp-includes/blocks.php(2190): WP_Block->render()","#33 /srv/htdocs/__wp__/wp-includes/blocks.php(2242): render_block(Array)","#34 /srv/htdocs/__wp__/wp-includes/block-template.php(263): do_blocks('<!-- wp:templat...')","#35 /srv/htdocs/__wp__/wp-includes/template-canvas.php(12): get_the_block_template_html()","#36 /srv/htdocs/__wp__/wp-includes/template-loader.php(106): include('/srv/htdocs/__w...')","#37 /srv/htdocs/__wp__/wp-blog-header.php(19): require_once('/srv/htdocs/__w...')","#38 /srv/htdocs/__wp__/index.php(17): require('/srv/htdocs/__w...')","#39 {main}","thrown"]}
```

There's a Slack thread here with some discussions/ideas about where the problem may lie: p1732121409466109-slack-CGGCLBN58

**Comment by danielmx-dev** [comment] 2024-12-16 16:01
After looking at the most recent updates from the linked thread, it looks like this issue was resolved by https://github.com/woocommerce/woocommerce/pull/53051

I wasn't able to reproduce the issue with the latest `9.5.0` release.

I'll close this ticket.

**Closed as completed by danielmx-dev** 2024-12-16 16:01 UTC
Labels: type: bug, priority: critical, focus: checkout payments, size: x-small
