### ISSUE TITLE
Connect.JS and Onboarding: Compatibility issue with SiteOrigin and using the classic Widgets settings

### ISSUE THREAD

**Issue by yukikatayama** [Automattic/woocommerce-payments#9448] opened 2024-09-16 21:15 UTC
### Describe the bug
The setup conditions are with WooPayments 8.2.1 + [SiteOrigins Widgets bundle](https://wordpress.org/plugins/so-widgets-bundle/) + using the classic widget settings/layout. When these conditions met, the content in the SiteOrigins Editor widget in the Visual tab is missing. You can only view and edit from the Text tab.

Reported in 8734253-zen

### To Reproduce

1. Install WooPayments 8.2.1
2. Install [SiteOrigins Widgets bundle](https://wordpress.org/plugins/so-widgets-bundle/)
3. If your theme uses block editor, you'll need to add the [Classic Widgets plugin](https://wordpress.org/plugins/classic-widgets/) plugin
4. Go to Appearance > Widgets > add a SiteOrigin Editor widget and add content > Save
5. Edit the widget again and notice Visual tab is empty. Text tab is fine.
6. Now downgrade WooPayments to 8.1.1 and see that Visual tab is working as intended.

### Actual behavior

Content in Visual tab should so for ease of review and editing.

### Screenshots

With WooPayments 8.2.1:

![QcuWlI.gif](https://github.com/user-attachments/assets/6cf3bd61-ec4c-4604-acce-275132c0b132)

With downgraded 8.1.1:

![kQArh5.gif](https://github.com/user-attachments/assets/36cd9ccc-f10e-4af0-b515-6e934ffa64c9)

### Expected behavior

Content saved in the SiteOrigin Editor widget should show up under the Visual tab.

**Comment by nicdwilson** [comment] 2024-09-19 04:03
The error does not affect TinyMCE in the product page, but affects TinyMCE in the widgets when Classic Widgets is active.

It is not restricted to SiteOrigin Widgets, but affects _ any_ TinyMCE window in a widget when Classic Widgets is active.

```
15:57:43.033 Uncaught TypeError: _.pluck is not a function
    setMarkers https://solutiondesign.co.nz/wp-includes/js/mce-view.min.js?ver=6.6.2:2
    <anonymous> https://solutiondesign.co.nz/wp-includes/js/tinymce/plugins/wpview/plugin.min.js?wp-mce-49110-20201110:1
    fire https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    fire https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    $w https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    setContent https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    load https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    bw https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    ww https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    Aw https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    Ow https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    u https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    jt https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    u https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    n https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    onload https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    u https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    jt https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    u https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    loadScripts https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    loadQueue https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    Ow https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    waitFor https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    Ow https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    u https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    jt https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    u https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    n https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    onload https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    u https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    jt https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    u https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    loadScripts https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    loadQueue https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    Ow https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    Ow https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    Bw https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    render https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    n https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    e https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    jt https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    e https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    bind https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    M https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    init https://solutiondesign.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=49110-20201110:2
    initialize https://solutiondesign.co.nz/wp-admin/js/editor.min.js?ver=6.6.2:2
    e https://solutiondesign.co.nz/wp-admin/js/widgets/text-widgets.min.js?ver=6.6.2:2
    initializeEditor https://solutiondesign.co.nz/wp-admin/js/widgets/text-widgets.min.js?ver=6.6.2:2
    n https://solutiondesign.co.nz/wp-admin/js/widgets/text-widgets.min.js?ver=6.6.2:2
    setTimeout handler*n https://solutiondesign.co.nz/wp-admin/js/widgets/text-widgets.min.js?ver=6.6.2:2
    setTimeout handler*n https://solutiondesign.co.nz/wp-admin/js/widgets/text-widgets.min.js?ver=6.6.2:2
    setTimeout handler*n https://solutiondesign.co.nz/wp-admin/js/widgets/text-widgets.min.js?ver=6.6.2:2
    setTimeout handler*n https://solutiondesign.co.nz/wp-admin/js/widgets/text-widgets.min.js?ver=6.6.2:2
    setTimeout handler*n https://solutiondesign.co.nz/wp-admin/js/widgets/text-widgets.min.js?ver=6.6.2:2
    handleWidgetAdded https://solutiondesign.co.nz/wp-admin/js/widgets/text-widgets.min.js?ver=6.6.2:2
    init https://solutiondesign.co.nz/wp-admin/js/widgets/text-widgets.min.js?ver=6.6.2:2
    jQuery 11
    init https://solutiondesign.co.nz/wp-admin/js/widgets/media-widgets.min.js?ver=6.6.2:2
    jQuery 13
mce-view.min.js:2:769


![POrYDv.png](https://github.com/user-attachments/assets/179af044-e0a4-4f09-abf7-ca9994467a07)

**Comment by battouly** [comment] 2024-09-19 21:13
@nicdwilson They confirmed they have the the Classic widgets plugin but don't make extensive use of it.

**Comment by vbelolapotkov** [comment] 2024-09-20 07:54
Thanks for the report and details folks. So far, it's not clear how WooPayments is involved there. We'll investigate and try to reproduce it locally.

**Comment by timur27** [comment] 2024-09-20 18:31
Hi @dmallory42! I've been able to reproduce the issue mentioned in the description above and found that it can be resolved by reverting [this PR](https://github.com/Automattic/woocommerce-payments/pull/9251). It seems like some new library is affecting the functionality, which I think would be hard to predict for us since we’re not testing this plugin when developing WooPayments. Do you happen to have any ideas of what exactly could affect this? Many thanks for your response! :)

**Comment by mouligreenlaw** [comment] 2024-10-02 02:14
Merchant on 8814145-zen confirms that they have Classic Widgets installed on all of their affected sites

**Comment by sverleis** [comment] 2024-11-13 08:20
Follow-up from a merchant, looking to see if this can be worked on, so that they can update their version of WooPayments to the latest version - 9032427-zen

**Comment by dmallory42** [comment] 2024-11-13 08:57
Hi! This issue should hopefully be resolved by #9674 which will land in the 8.5.0 release - we had an issue related to how the connect.js library was imported - this fix should make it so that the library is only loaded as and when it is needed (meaning only on the `/onboarding` endpoint).

I will keep this issue open for now until we confirm that fix helps.

**Comment by anu-rock** [comment] 2024-11-15 10:43
@timur27 @dmallory42 Now that 8.5 is live, could either of you test whether it fixes this issue? I am moving it to our blocked queue until then so we don't miss it.

**Comment by dmallory42** [comment] 2024-11-15 11:38
Tested with WooPayments 8.5.0 following the instructions mentioned above and can confirm it is now working as expected. Thank you for the report, @yukikatayama!

**Closed as completed by dmallory42** 2024-11-15 11:38 UTC
Labels: type: bug, priority: low, focus: account lifecycle
