### ISSUE TITLE
PaymentIntention: Handle all PaymentIntention statuses

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-payments#162] opened 2019-08-01 04:09 UTC
Right now, we handle two types of responses when creating a payment intention:

'requires_action' === $intention->get_status() and not. This is referenced here:

https://github.com/Automattic/woocommerce-payments/pull/133#discussion_r302490548

PR #133 was written to handle either a successful payment intention creation, or a payment intention that requires secure authentication.

There are other statuses available ([doc](https://stripe.com/docs/api/payment_intents/object#payment_intent_object-status)):
- requires_payment_method
- requires_confirmation
- requires_action (handled)
- processing
- requires_capture
- canceled
- succeeded (handled)

Each of these statuses should be handled correctly.

_Note: I added this to milestone 0.3, but it probably belongs elsewhere since it's not related to 3DS etc_

**Comment by vbelolapotkov** [comment] 2021-12-16 12:14
Issue is still relevant but we'd need to figure out how those cases should be handled first.

**Comment by RadoslavGeorgiev** [comment] 2022-03-31 12:47
I looked into the codebase, and we're checking for all of those statuses in one place or another. Considered that we have not noticed any cases where a status is ignored, I think the coverage should be sufficient.

It's important to keep in mind that at the time of writing this issue up, we didn't even support manual capture (see the `requires_capture` status). Since then we seem to be utilizing all states of a Payment Intent.

With this in mind, I'm closing the issue. Handling further scenarios/statuses should be implemented after creating an issue with details and steps to reproduce/expected behavior.

**Closed by RadoslavGeorgiev** 2022-03-31 12:47 UTC
Labels: type: enhancement, needs feedback, category: core
