### ISSUE TITLE
[Multicurrency] Manual Conversion rates to not save in all cases 

### ISSUE THREAD

**Issue by Brianmitchtay** [Automattic/woocommerce-payments#7207] opened 2023-09-14 03:03 UTC
### Describe the bug

For some currencies and on some sites, when setting a manual conversion rate, the old setting prevails after saving.

This issue arose in 6812313-zen where the user could not save a new manual value for the Turkish Lira conversion rate.

### To Reproduce

Thus far we've not been able to replicate this issue in every case, so given your environment, and some aspect we don't yet understand, these directions may or may not work.

1. On a site with WooPayments installed and an account connected, head to the multicurrency settings and add Turkish Lira as a currency option
2. Click on `Manage` 
3. Select a manual exchange rate
4. Set a manual rate that differs from the current one
5. See the settings saved message appear.
6. Refresh and see the setting isn't saved.

### Actual behavior

Under some circumstances the entered manual conversion rate doesn't stick. 

So far we've been able to replicate this in Atomic environments, and on a pressable site. Also only able to replicate it with some currencies and not others.

### Screenshots

Recording of replication here - 
https://github.com/Automattic/woocommerce-payments/assets/45057772/6ee51a6e-7611-4543-b97a-ebb8dc8d0164
It also seems noteworthy that the `TRY?_locale=user` request that fires when the setting is saved has the old value returned in its response, despite having the new one in the request body. I'm not certain whether this is expected or not. 
![Screenshot 2023-09-13 at 6 50 12 PM](https://github.com/Automattic/woocommerce-payments/assets/45057772/4a6ea659-232c-41bd-9d9b-18340e7445e7)

### Expected behavior

When you save a manual conversion rate it should stick.

### Desktop (please complete the following information):

* OS: IOS 13.5.2 
* Browser: Chrome 
* Version 117.0.5938.62

### Additional context

6812313-zen

**Comment by CGA8C** [comment] 2023-09-14 08:15
This is a duplicate of [this issue](https://github.com/Automattic/woocommerce-payments/issues/6857), so I'm going to close this one in favor of the original. :)

**Closed as not planned by CGA8C** 2023-09-14 08:15 UTC
Labels: type: bug, component: customer multi-currency
