### ISSUE TITLE
Let merchant know when the next deposit expected is/includes a Capital Loan disbursement

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#7689] opened 2023-11-10 05:03 UTC
We need to let the merchant know if their next deposit is/includes a capital loan disbursement.

This functionality was removed in #7656 while implementing the new Payments → Overview deposit UI with estimated deposits decoupled from transactions. Tests related to the Capital Loan notice in `client/components/deposits-overview/test/index.tsx` have been skipped in #7656 and should be re-enabled if suitable.

The previous implementation used the hook [`useDepositIncludesLoan`](https://github.com/Automattic/woocommerce-payments/blob/d089aec09e24255158f212e331aa78b5ad040018/client/data/deposits/hooks.ts#L37) – if this hook is deemed to be redundant after resolving this issue, it can be removed.

See PR #5902 for original implementation and testing instructions.

**Comment by brucealdridge** [comment] 2023-11-14 01:49
This likely requires a change on the server to expose this information with deposit estimates removed.

p1699926527378939/1699919221.139419-slack-C045PC0V40G

**Comment by Jinksi** [comment] 2023-11-15 02:12
Zero SP, estimated as part of #7646

**Comment by haszari** [comment] 2023-12-17 22:30
Curious on the priority of this – why did we remove this? How important is it to show the notice?

@souravdebnath1986 keen for your thoughts on priority. 

> Zero SP, estimated as part of #7646

@Jinksi does this still need work or is it completed?  I see that #7646 is now completed, so maybe we need to prioritise this separately. Related question, is this part of project? 

I see this as separate – we could complete the project without fixing this. However might be convenient to fix as part of project (or will need to coordinate with project changes). If we treat this as maintenance then we should estimate & allocate some time to it.

- #7646

**Comment by Jinksi** [comment] 2023-12-17 23:22
I now see this as separate from the project, too.

I'll reset the SP estimate and remove the `category: projects` label to indicate that this is a maintenance issue.

**Comment by haszari** [comment] 2024-01-31 01:59
We still need to prioritise this! The `your next deposit includes a loan` message was working before, so this is arguably a regression.

(It got lost because of `projects` label)

**Comment by souravdebnath1986** [comment] 2024-02-15 03:00
Closing this bug. The merchant ends up getting the loan as a part of their next deposit. Because we have deprecated estimated deposits and related notices, this notice of informing the merchant of their loan being disbursed isnt surfaced. We will handle notices as part of future improvements to Capital or Loans.

**Closed as not planned by souravdebnath1986** 2024-02-15 03:00 UTC
Labels: type: bug, component: capital, priority: medium
