### ISSUE TITLE
Call to a member function is_reusable() on bool in class-wc-payments.php:768 + e is null

### ISSUE THREAD

**Issue by Lockoloop** [Automattic/woocommerce-payments#7482] opened 2023-10-13 16:51 UTC
### Describe the bug
After updating WooCommerce Payments, I get an error the first time I land on the shop or checkout page:
Call to a member function is_reusable() on bool in class-wc-payments.php:768
It doesn't trigger again, but the payments modes show empty frames, and trying to pay triggers a notice "e is null".
Only 3 plugins are active: Woocommerce, Woocommerce Payments, Woocommerce Blocks. Theme is 2023.

### To Reproduce

1. Update to WooCommerce Payments 6.6.0
2. Go to the shop or checkout page; it will say something about a critical error; checking the error log will show the error mentioned above.
3. Reload the page; it will work again but will now display empty payment methods.

### Actual behavior
Fatal error

### Screenshots
![screenshot-woo-payments](https://github.com/Automattic/woocommerce-payments/assets/94473878/011dc75f-2505-4b09-99bf-252a6a5a2455)

### Expected behavior
No errors and no empty payment method.

### Desktop (please complete the following information):

* OS: Windows 10
* Browser Firefox 118.0.2

**Comment by csmcneill** [comment] 2023-10-15 17:17
Howdy @Lockoloop!

We received a similar report (internal ref: 7155799-zen) with a similar error. Here is a partially redacted stack trace from that report:

```
2023-10-12T03:51:43+00:00 CRITICAL Uncaught Error: Call to a member function is_reusable() on bool in /[redacted]/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php:768
Stack trace:
#0 /[redacted]/public_html/wp-includes/class-wp-hook.php(310): WC_Payments::register_gateway()
#1 /[redacted]/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#2 /[redacted]/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(88): apply_filters()
#3 /[redacted]/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(70): WC_Payment_Gateways->init()
#4 /[redacted]/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(43): WC_Payment_Gateways->__construct()
#5 /[redacted]/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(966): WC_Payment_Gateways::instance()
#6 /[redacted]/public_html/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(212): WooCommerce->payment_gateways()
#7 /[redacted]/public_html/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(97): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#8 /[redacted]/public_html/wp-includes/class-wp-hook.php(310): WCML_Currencies_Payment_Gateways->init_gateways()
#9 /[redacted]/public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#10 /[redacted]/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#11 /[redacted]/public_html/wp-settings.php(654): do_action()
#12 /[redacted]/public_html/wp-config.php(123): require_once('/[redacted]/...')
#13 /[redacted]/public_html/wp-load.php(50): require_once('/[redacted]/...')
#14 /[redacted]/public_html/wp-blog-header.php(13): require_once('/[redacted]/...')
#15 /[redacted]/public_html/index.php(17): require('/[redacted]/...')
#16 {main}
thrown in /[redacted]/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php on line 768
```

This stack trace indicates that this error may be a result of a conflict with another plugin on the site—in this case, [WooCommerce Multilingual](https://wordpress.org/plugins/woocommerce-multilingual/).

1. Does your site have WooCommerce Multilingual installed/active?
2. Does the error occur with just WooCommerce, WooPayments, and [a default theme](https://woocommerce.com/products/storefront/?aff=10486&cid=1131038) active?

**Comment by Lockoloop** [comment] 2023-10-15 17:40
- Only 3 plugins are active: Woocommerce, Woocommerce Payments, Woocommerce Blocks. Theme is Twenty twenty Three.
- I only handle translations via Poedit.

**Comment by csmcneill** [comment] 2023-10-15 18:44
Thanks for the information @Lockoloop!

I'm unable to reproduce this on my own site running a similar setup:

![Markup on 2023-10-15 at 13:39:40](https://github.com/Automattic/woocommerce-payments/assets/82999806/8ecea8b7-7b7b-4757-bd2b-480b1eb3af4d)

Since we cannot reproduce this with the steps you've outlined, please contact us at <a href="https://woocommerce.com/my-account/contact-support/">WooCommerce.com > My Account > Support</a> so that a member of our team can connect with you further to debug this issue. You may need to create an account before you can access that page. 

Please include a link to this GitHub issue so that we can keep track of what's already been done. I would also recommend sharing your site's system status report (accessible from **WooCommerce > Status**) and the fatal error log (accessible from **WooCommerce > Status > Logs**) when reaching out to our team so that our Happiness Engineers can best determine what next steps to take.

In the meantime, you may want to try reverting to [version 6.5.1](https://github.com/Automattic/woocommerce-payments/releases/tag/6.5.1) to see if that resolves the issue.

**Comment by Lockoloop** [comment] 2023-10-20 11:35
Ok, I'll contact them, I switched to 6.6.1, same problem: first the fatal error, then the content not showing:
```
[19-Oct-2023 20:15:53 UTC] PHP Fatal error:  Uncaught Error: Call to a member function is_reusable() on bool in /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php:768
Stack trace:
#0 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-includes/class-wp-hook.php(310): WC_Payments::register_gateway()
#1 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#2 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(88): apply_filters()
#3 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(70): WC_Payment_Gateways->init()
#4 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(43): WC_Payment_Gateways->__construct()
#5 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-content/plugins/woocommerce/includes/class-woocommerce.php(966): WC_Payment_Gateways::instance()
#6 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-content/plugins/woocommerce/includes/class-woocommerce.php(176): WooCommerce->payment_gateways()
#7 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-content/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Payments.php(93): WooCommerce->__get()
#8 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-content/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/Payments.php(71): Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\Payments::has_gateways()
#9 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-content/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/WooCommercePayments.php(125): Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\Payments->is_complete()
#10 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-content/plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskList.php(304): Automattic\WooCommerce\Admin\Features\OnboardingTasks\Tasks\WooCommercePayments->can_view()
#11 [internal function]: Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskList->Automattic\WooCommerce\Admin\Features\OnboardingTasks\{closure}()
#12 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-content/plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskList.php(305): array_filter()
#13 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-content/plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskList.php(239): Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskList->get_viewable_tasks()
#14 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-content/plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskLists.php(410): Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskList->is_complete()
#15 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-content/plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskLists.php(432): Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskLists::setup_tasks_remaining()
#16 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-includes/class-wp-hook.php(310): Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskLists::menu_task_count()
#17 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#18 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-includes/plugin.php(517): WP_Hook->do_action()
#19 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-admin/includes/menu.php(161): do_action()
#20 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-admin/menu.php(420): require_once('/home/u100586p1...')
#21 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-admin/admin.php(158): require('/home/u100586p1...')
#22 /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-admin/index.php(10): require_once('/home/u100586p1...')
#23 {main}
  thrown in /home/u100586p107196/domains/lockoloop.nl/public_html/devstage/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php on line 768
```

Also, this JS error:
```
Uncaught (in promise) TypeError: t(...)[e.dataset.paymentMethodType] is undefined
    h https://www.lockoloop.nl/devstage/wp-content/plugins/woocommerce-payments/dist/upe_with_deferred_intent_creation_checkout.js?ver=6.6.1:1
    h https://www.lockoloop.nl/devstage/wp-content/plugins/woocommerce-payments/dist/upe_with_deferred_intent_creation_checkout.js?ver=6.6.1:1
    d https://www.lockoloop.nl/devstage/wp-content/plugins/woocommerce-payments/dist/upe_with_deferred_intent_creation_checkout.js?ver=6.6.1:1
```

**Comment by csmcneill** [comment] 2023-10-20 18:40
Thanks for the additional information @Lockoloop! We've received your inquiry (ref: 7193327-zen) and a Woo Happiness Engineer will respond soon.

In the meantime, I will leave this issue open in case someone else can reproduce it with version 6.6.0, 6.6.1, or 6.6.2 active.

**Comment by htdat** [comment] 2023-10-30 07:07
FYI. This seems related to UPE and dUPE, @timur27 will take a look.
(Ref: p1698072317855819-slack-CGGCLBN58)

**Comment by timur27** [comment] 2023-10-30 11:27
I could reproduce the error on a different screen in the admin panel when the account cache is being refreshed.

<p align="center">
<img width="562" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/22319444/e5a26cd0-c9da-4200-8cb5-1d29d850698a">
</p>

Two things need to be done for the error to occur: 
* This should be a legacy UPE site migrated to deferred intent creation UPE in `6.6.0`. In other words, legacy UPE flag should be enabled. 
* Payment method(s) other than card should be enabled, e.g. `giropay`

The error occurs when the deferred intent creation flag has an unexpected value due to an uninitialized account cache returned from the database.

I don't know the exact reason behind it just yet. At the same time, I'm pretty sure that the issue will be gone after we clean up old UPEs in https://github.com/Automattic/woocommerce-payments/issues/5028, which is added to our current Sprint. 

IMO, we need to focus on cleaning up rather than looking for the issues with feature flags, since they shouldn't be needed anymore starting (hopefully) `6.8.0`.

**Comment by Lockoloop** [comment] 2023-11-17 19:17
So I just updated everything and payment options are still not displayed properly (it seems the fatal error is gone, though).
I cleared my cache, tested with theme 2023, Woocommerce, Woocommerceblocks, Woocommercepayments activated.

**Comment by timur27** [comment] 2023-11-17 23:22
Hey @Lockoloop, thank you for the feedback. I'm sorry to hear the issue still persists. I have a few questions to help us look into this further and I would appreciate your answer.

1. We haven't yet released the new plugin version that includes the fix for this issue. Which plugin version are you using currently? If the answer is `6.8.0`, please feel free to skip the next questions and we'd like to ask you to wait until version `6.9.0` is released and try again.
2. When you navigate to _**Payments -> Settings**_, what payment methods do you see and do you think this list is correct, or you would expect it to have more (or less) payment methods included?
3. Could you please give a bit more context on the behavior you're facing on the checkout page? Are payment methods shown on the page but lack input fields? Is the behavior you're seeing happening only on the first page load or not really? 
4. May I ask you to provide us screenshots from the browser console, if there are any errors on the page load?

I understand that some questions might overlap with those previously asked or with areas you already described in the ticket, but given that the issue changed its behavior (the fatal error is now gone) I'd like to align on the latest state your site has.

**Comment by Lockoloop** [comment] 2023-11-18 14:34
Ah ok, my bad, it's indeed 6.8.0!

**Comment by Lockoloop** [comment] 2023-12-07 13:18
Hey there, just updated to 6.9.0, and it didn't solve the display problem. The console returns this (sorry if some bits are in French):
![image](https://github.com/Automattic/woocommerce-payments/assets/94473878/12ef2629-4546-4a0b-b250-7504cfe51bd9)

To answer your questions: the list is right, and in that respect it shows correctly if we're just talking about the radio buttons; but the div with class "wcpay-upe-element" are all empty (same happens with iDeal or credit card).
![image](https://github.com/Automattic/woocommerce-payments/assets/94473878/4c779efa-f24b-4164-8012-a0976cc9ef84)

**Comment by timur27** [comment] 2023-12-08 12:59
Hey @Lockoloop, sorry to hear your site is still experiencing some problems. Your site is well customized (and it looks just awesome), so I'm not excluding the probability of some conflicts.

I'll let the team know that this issue still requires attention, and we hope to help you out soon.

**Comment by Lockoloop** [comment] 2023-12-08 18:47
Thank you Timur!
But fyi, all the tests were done on a cloned version (lockoloop.nl/devstage) with all plugins turned off and Theme 2024 activated, so there shouldn't be any conflict happening.

**Comment by frosso** [comment] 2023-12-12 09:13
Just as an update - we're internally validating and investigating further

For internal reference: p1702040629248429-slack-CU6SYV31A

**Comment by timur27** [comment] 2024-01-08 14:50
Hey @Lockoloop! We reached out to you through the Woo Support channel (internal ref: 7472463-zd-a8c) and would appreciate it if you could respond there so we can help you further if the problem persists. Thanks!

**Comment by Lockoloop** [comment] 2024-01-08 17:08
Hi Timur, I've only received "Woo Support: Ticket #7472463 received" on December 19th, I don't think I've received anything since then (hoping I haven't deleted it by accident).

**Comment by timur27** [comment] 2024-01-23 13:50
We investigated the issue together with @francoishvz and @frosso. It turned out that the problem was the disabled credit card payment element, which isn't something our system is handling since credit cards should always be enabled by default. I know that errors discussed in this thread were resolved after enabling credit card payment method, which is definitely good news. While the questions related to credit card enablement might remain open given the needs of particular stores, they are expected to be handled separately if appeared. Thus, I'm closing this issue as completed. 

@Lockoloop thanks for your collaboration and patience! Good luck with your store!

**Closed as completed by timur27** 2024-01-23 13:50 UTC
Labels: type: bug, status: blocked, component: checkout, needs feedback, component: upe, priority: medium
