### ISSUE TITLE
WooPay "Save my info" Duplication on Checkout Block when using Autofill causing checkout issues

### ISSUE THREAD

**Issue by EjayhanFernandes** [Automattic/woocommerce-payments#9533] opened 2024-10-07 08:23 UTC
### Describe the bug
When using autofill on Google Chrome (and Safari as well), WooPay's "Save my info" checkbox gets duplicated on the checkout page. This bug occurs inconsistently but can lead to checkout errors. It appears to be related to autofill, specfically when using saved browser addresses that have not been used for a WooPay purchase on the site.

### To Reproduce
1. Ensure WooPayments has WooPay enabled.
2. Use the checkout block on the checkout page.
3. Have a saved address in your browser for autofill (not previously used for a WooPay purchase on the same site you're testing).
4. Add a product that requires shipping to your cart.
5. Proceed to checkout.
6. Under the "Shipping address" section, uncheck "Use same address for billing."
7. Autofill the shipping address, then autofill the billing address.
8. Refresh the checkout page to see the issue.

### Actual behavior
The "Save my info" checkbox appears twice on the checkout page, causing checkout problems and confusion for users.

### Screenshots

https://github.com/user-attachments/assets/a2381b8c-9012-4fae-9823-876eb3b695d5

### Expected behavior

The "Save my info" option should appear once and function as expected without duplication.

### Desktop (please complete the following information):

* OS: macOS Sonoma 14.6.1
* Browser Chrome
* Version 129.0.6668.90

### Additional context
- WooPayments version: 8.3.0
- WooCommerce 9.3.3
- Internal discussion: p1728227833629489-slack-C3NCP7ZJ6
- The above steps is one way I replicated the issue. However, in a report from one user (in 8835251-zd-a8c), I didn't have to uncheck 'Use same address for billing' to replicate the issue:

https://github.com/user-attachments/assets/4066765b-8974-4db4-bf63-23368bb2ead1

- One more thing: ensure that cookies and site data are cleared between replication attempts.
![Image](https://github.com/user-attachments/assets/9388bc53-d16c-4b71-a427-23eb6bfe33a2)

**Comment by a-danae** [comment] 2024-10-14 07:38
Seems a duplicate of https://github.com/Automattic/woocommerce-payments/issues/9410, which would be fixed by https://github.com/Automattic/woocommerce-payments/pull/9531. To be confirmed but leaving a note here for reference.

**Comment by alefesouza** [comment] 2024-10-28 18:36
#9531 fixes checkbox duplication issues.

**Closed as completed by alefesouza** 2024-10-28 18:36 UTC
Labels: priority: high, focus: woopay, Bug
