### ISSUE TITLE
StripeLink Button compatibility with Checkout Field Editor plugin

### ISSUE THREAD

**Issue by nickpagz** [Automattic/woocommerce-payments#5290] opened 2022-12-14 18:23 UTC
### Describe the bug
When using the Checkout Field Editor plugin to customize the Billing Fields, even without making any changes to the `billing_email` field, the Stripe Link button stops working.
This happens because the edited/saved billing fields now saved in the wp_options table becomes the source of truth, overriding the Stripe Link button html added by the WC Payments plugin.

It's possible to manually add the button html in the Checkout Field Editor by adding ` <button class="wcpay-stripelink-modal-trigger"></button>` after the "Email address" in the "Label" column for the `billing_email` field.

However, we then re-introduce the issue which #4704 attempted to solve.

### To Reproduce

1. Set up a new test site and WooCommerce Payments test account in dev mode, and ensure the "Link by Stripe" option is checked on the WooCommerce Payments settings page.
2. Simulate a checkout and look for the "Link" button inside the Billing Email input text box.
3. Install the Checkout Field Editor plugin, go to the **Checkout Fields** setting page, and click **Save Changes** while inside the **Billing Fields** tab. 
4. Refresh the checkout page, the Stripe "Link" button should no longer be visible.

### Actual behavior
The Stripe Link button is not visible on the checkout page when a change is saved in the Billing Fields checkout editor.

### Expected behavior
For the Stripe Link button to be visible regardless of edits made to the billing fields.

### Additional context
Discovered while trying to solve the same issue #4704 fixes on a Team 51 partner site, though still visible as the button html was intentionally added to the billing field to overcome the missing Link button.

**Comment by RadoslavGeorgiev** [comment] 2023-01-24 09:40
@Automattic/pulsar and @Automattic/fusion do either of you have this in your backlog?

**Comment by anu-rock** [comment] 2023-01-25 06:14
@RadoslavGeorgiev Thanks for bringing it up. Issues related to Stripe Link will fall under Fusion's backlog. I'll add it to our backlog so we don't lose track of it.

**Comment by gpressutto5** [comment] 2024-02-08 16:08
Hi @nickpagz! Is this issue still reproducible? I followed the steps listed and even renamed the email field and I still get the Stripe Link button.

![image](https://github.com/Automattic/woocommerce-payments/assets/12385501/29240af8-7872-4bb1-8de9-00a18cd4fa6a)

**Comment by gpressutto5** [comment] 2024-02-15 14:58
I'm closing this issue for now. Feel free to reopen it if the problem still exists.

**Closed as not planned by gpressutto5** 2024-02-15 14:58 UTC
Labels: type: bug, priority: high, component: payment request button, category: core, component: stripe link

**Comment by csmcneill** [comment] 2024-02-15 21:38
Could this issue be related to #6310?

In #6310, the Payment Element does not load with CFE active (at least last I checked in June 2023). If the Payment Element does not load, would that prevent the Link button from loading?

**Comment by gpressutto5** [comment] 2024-02-19 17:54
@csmcneill I also can't reproduce that issue. The card fields render fine when using CFE:

![image](https://github.com/Automattic/woocommerce-payments/assets/12385501/f2718184-368b-4a68-862e-f0338c4dc41d)

@timur27 Do you think these issues were fixed by removing legacy UPE?

**Comment by csmcneill** [comment] 2024-02-20 23:49
@gpressutto5 I can no longer reproduce #6310, so I closed it :)

**Comment by timur27** [comment] 2024-02-21 15:27
Sorry for the late answer @gpressutto5 dUPE refactored this area as well so I wouldn't exclude it impacting the behavior so that we cannot reproduce it anymore.
