### ISSUE TITLE
Fatal errors thrown on the admin Subscriptions table when a subscription doesn't load

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#3596] opened 2022-01-05 04:16 UTC
#### ❗ This issue relates to the WC Subscriptions-core issue: https://github.com/Automattic/woocommerce-subscriptions-core/issues/83

When `wcs_get_subscription` returns `false` for some reason, the subsequent code to render the admin subscription table doesn't handle this well, e.g. `render_shop_subscription_columns` function calls `$the_subscription->get_status()` without checking the function is actually getting a subscription or `output_rows` is calling` $subscription->get_parent_id()`, again without checking if it's actually not getting `false` instead of the subscription object.

This causes a fatal.

## To Reproduce

1. With a subscription with corrupt data (for example an invalid next payment data meta - [like a string](https://user-images.githubusercontent.com/8490476/148148478-30691cb0-e408-403c-98b4-4768dbe83623.png)), view the admin subscriptions table. 

 
### Expected behavior

No errors.

### Actual behavior

Fatal errors

<img width="820" alt="Screen Shot 2022-01-05 at 12 04 38 pm" src="https://user-images.githubusercontent.com/8490476/148159531-5a753f42-be65-4142-8815-92140f2c19f2.png">

## Product impact

- [x] Does this issue affect WooCommerce Subscriptions?
   - 4286-gh-woocommerce/woocommerce-subscriptions

**Comment by james-allan** [comment] 2022-01-05 04:35
Note: this will be fixed in subscriptions-core PR https://github.com/Automattic/woocommerce-subscriptions-core/pull/84/

**Comment by zmaglica** [comment] 2022-01-05 09:05
@james-allan Hi there. Can we close this issue since the problem is related to different project?

**Comment by james-allan** [comment] 2022-01-06 00:19
Hi @zmaglica. Thanks for checking in. :) 

It's one of our processes on Helix to open issues on our stakeholder product repos (WC Payments and WC Subscriptions) when we submit a PR to subscriptions-core (a library-esk repo). These product issues then play the role of being a record of that change in the subscriptions-core repo until we bump the subscriptions-core version in WC Payments. This issue will get closed when we submit the PR to bump that version. 

I hope that makes sense. It's a little confusing but we're happy to hear feedback if you have any. :)

**Closed** 2022-01-13 07:41 UTC
Labels: type: bug, priority: critical, needs feedback, component: wcpay subscriptions, needs subscriptions core update
