### ISSUE TITLE
Card fields do not load when Stripe Link is used with Checkout Field Editor

### ISSUE THREAD

**Issue by daniyalahmadk** [Automattic/woocommerce-payments#6310] opened 2023-05-16 12:10 UTC
### Describe the bug

When using the WooCommerce Payments Link By Stripe payment method in conjunction with the WooCommerce Checkout Field Editor plugin, the credit card form does not load on the checkout page. Instead, only a loading icon is displayed.

The following error is thrown in the browser console:

`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'addEventListener')
`

This error originates from the upe_checkout.js file at the line:

`document.querySelector(".wcpay-stripelink-modal-trigger").addEventListener("click", ...
`

It should be noted that the error in the console is different depending on whether a saved payment method is used or the user is logged in.

### To Reproduce

- Install and activate the WooCommerce Checkout Field Editor plugin.
- Configure the WooCommerce Checkout Field Editor settings (it's not required I think).
- Proceed to the checkout page.
- Observe that the credit card form does not load and only a loading icon is displayed.
- Check the browser console for any error messages.

### Actual behavior
Doesn't disable the card form and only displays the loading icon.

### Screenshots

![image](https://github.com/Automattic/woocommerce-payments/assets/13753012/296065ee-6006-4df8-a8d3-d7d95141d119)

### Expected behavior
Display the card form and don't stuck in loading.

### Additional context

6255577-zen

**Comment by csmcneill** [comment] 2023-05-22 19:19
@daniyalahmadk Can you reproduce this issue when [Checkout Field Editor](https://woocommerce.com/products/woocommerce-checkout-field-editor/?aff=10486&cid=1131038) is active but there are no modifications made to the checkout fields?

**Comment by daniyalahmadk** [comment] 2023-06-13 11:53
@csmcneill I can reproduce the issue even when you **don't** have any modifications made to checkout fields.

**Comment by csmcneill** [comment] 2023-06-15 21:19
Thanks @daniyalahmadk. I can reproduce thisIt's worth noting that one needs to make _some_ modification to the checkout page; reverting the change will still produce the same issue.

I'm finding that this only affects the shortcode checkout; the checkout block is not affected. As a result, this has a couple of workarounds:
1. Use the checkout block (best)
2. Disable Stripe Link (not too great)
3. Disable UPE (which also disables Stripe Link).

Since this has some workarounds, I'll give this a `priority: low` tag. Flagging this to @Automattic/pulsar (cc @dpaun1985) in case the priority needs to be changed.

**Comment by csmcneill** [comment] 2024-02-20 23:49
I can no longer reproduce this issue with WooPayments 7.2.0 and Checkout Field Editor 1.7.12 — so I will be closing this issue as a result.

If this can still be reproduced feel free to reopen :)

**Closed as not planned by csmcneill** 2024-02-20 23:49 UTC
Labels: type: bug, category: core, component: stripe link, priority: medium
