### ISSUE TITLE
UPE Card Fields Hidden with Optimization Plugins

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#5224] opened 2022-12-02 02:01 UTC
### Describe the bug
We’ve been assuming that this issue related to Page Optimize and the issue resolved by [this PR](https://github.com/Automattic/woocommerce-payments/pull/5223) are one in the same—but they are not.

Originally reported here: https://github.com/Automattic/wp-calypso/issues/70676

When UPE is enabled and Page Optimize's `Concatenate scripts` option is enabled, the UPE payment fields are hidden. We also see the following error in the console:

```
Failed to load resource: the server responded with a status of 400 ()
```

This primarily affects AT sites that have Page Optimize enabled by default, but I also was able to reproduce this on a JN site and a Pressable site. Additionally, some users are seeing this with other optimization plugins, like Autooptimize.

Users who use the Checkout Block do not seem to be affected by this, and reverting to 5.0.3 resolves the issue.

### To Reproduce

1. Install WCPay
2. Enable UPE
3. Install Page Optimize
4. Go through the checkout flow
5. The card fields do not appear on checkout

### Actual behavior

If UPE is enabled while Page Optimize's `Concatenate scripts` option is enabled, the UPE payment fields are hidden.

### Workarounds

- Deactivate Page Optimize
- Disable the `Concatenate scripts` option in Page Optimize
- Disabling UPE
- Using the Checkout Block instead of the checkout shortcode
- Revert to 5.0.3

### Screenshots

![Markup on 2022-12-01 at 19:49:08](https://user-images.githubusercontent.com/82999806/205196376-27c3cc5e-1844-4124-9026-7fe47e384238.png)

![Markup on 2022-12-01 at 19:59:12](https://user-images.githubusercontent.com/82999806/205197596-1558287f-fcab-4e86-a26f-f8c0a748288e.png)

### Expected behavior
When Page Optimize's `Concatenate scripts` option is enabled while WCPay's UPE is enabled, the payment fields should be visible.

### Additional context
p1669941900379859-slack-C02FMH4G8
5761513-zen
5757096-zen
5758923-zen
5761476-zen
5757545-zen
5757523-zen
5759602-zen
38424377-hc
23852682-hc
37610181-hc
5752437-zen
5761714-zen
5755679-zen
5761621-zen
37442036-hc
37588704-hc
38433352-hc
5761012-zen
38122494-hc
38401915-hc
38416418-hc
35922428-hc
5756727-zen
5757555-zen
5758129-zen
5758267-zen

**Comment by FangedParakeet** [comment] 2022-12-02 02:16
When the UPE is enabled and Page Optimize is set to concatenate scripts the script that suddenly begins to return a `400` response is `fp_agent.js`, which I believe was introduced in #5071. I think that would explain why rolling back to WCPay v.5.0.3 also resolves this issue.

I'm not yet able to say why this combination causes this outcome nor how to immediately resolve it, but since I am some distance past my EOD, I'll have to leave this breadcrumb in the hopes that this might be a useful clue to help unravel the mystery here for another onlooker. ✌️

**Comment by senff** [comment] 2022-12-02 12:40
38424377-hc reported issue as well. Not an AT site and doesn't have Page Optimize, but they _do_ have Autoptimize. Deactivating that solves the issue.

**Comment by FangedParakeet** [comment] 2022-12-02 14:58
Having looked into this a little further, I've discovered the path of the infection, but not the origin. Basically if [this function](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/utils/fingerprint.js#L2) to get the fingerprint token fails for any reason, the code silently errors out, and [the UPE fails to mount](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/classic/upe.js#L191)--explaining why there are no errors and no payment fields.

However, this process of blocking the payment fields when the fingerprint is missing [is the same in the non-UPE checkout](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/classic/index.js#L198) as well, so I can't explain why this acute affliction is specific to the UPE checkout: I'm not sure _why_ the request only returns a `400` status when the UPE is enabled and the scripts are concatenated by Page Optimizer. Anyways, hopefully this little nugget of wisdom might offer some illumination in getting closer to the murky bottom of this muddy issue.

**Comment by dreamtooloud** [comment] 2022-12-02 18:10
reported in 23852682-hc . AT site. Provided user with work arounds (waiting for confirmation they worked).

**Comment by dreamtooloud** [comment] 2022-12-02 18:25
another report in 37610181-hc. AT site. 

They only sell in the US and only want CC/Debit enabled so I asked them to disabled UPE. This fixed the issue for them.

**Comment by sarbouw** [comment] 2022-12-02 19:05
5752437-zen. AT site, provided workaround.

**Comment by csmcneill** [comment] 2022-12-02 21:36
> I've discovered the path of the infection, but not the origin. Basically if [this function](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/utils/fingerprint.js#L2) to get the fingerprint token fails for any reason, the code silently errors out, and [the UPE fails to mount](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/classic/upe.js#L191)--explaining why there are no errors and no payment fields.

Many thanks @FangedParakeet! Flagging @Automattic/sigma here to see if they may have any additional insight into this.

**Comment by eduardoumpierre** [comment] 2022-12-02 22:44
Thanks for raising and digging into it @FangedParakeet @csmcneill! We're trying to reproduce it, but there's [an open PR](https://github.com/Automattic/woocommerce-payments/pull/5238) with the possible fix.

**Comment by eduardoumpierre** [comment] 2022-12-02 23:11
@allie500 and @dwainm were able to reproduce it and the fix is working fine.

**Comment by dwainm** [comment] 2022-12-03 02:46
Closing this since we've deployed a release that fixes this: version 5.1.2.

**Closed as completed by dwainm** 2022-12-03 02:46 UTC
Labels: type: bug, component: checkout, impact: high, component: upe

**Comment by dwainm** [comment] 2022-12-03 02:47
Also closed the related calypso issue: https://github.com/Automattic/wp-calypso/issues/70676

**Comment by battouly** [comment] 2022-12-03 03:05
Ticket #5761714-zen , AT site, disabled new checkout experience as a workaround.

**Comment by nicdwilson** [comment] 2022-12-03 03:13
5755679-zd-woothemes
5761621-zd-woothemes
37442036-hc

**Comment by dwainm** [comment] 2022-12-03 12:04
Please ask for new tickets to upgrade to version 5.1.2

**Comment by csmcneill** [comment] 2022-12-03 20:08
I informed all of the users reported in this issue and https://github.com/Automattic/wp-calypso/issues/70676
