### ISSUE TITLE
Unable to display "Subscription ID (#)" as title on "My account > Subscriptions" page on WordPress 6.0 with Twenty Twenty-Two theme

### ISSUE THREAD

**Issue by zmaglica** [Automattic/woocommerce-payments#4315] opened 2022-06-03 10:14 UTC
**This issue is a placeholder for tracking impact on WCPay. Please use issue in `subscriptions-core` for all discussion.**

https://github.com/Automattic/woocommerce-subscriptions-core/issues/181

### Describe the bug
When [Twenty Twenty-Two](https://pcm.wordpress.org/themes/twentytwentytwo/) theme is installed and WordPress 6.0 is used, the subscription ID as title is not shown on the account's subscription page.

### To Reproduce

1. Make sure to have WooCommerce Payments configured on WordPress 6.0 with [Twenty Twenty-Two](https://pcm.wordpress.org/themes/twentytwentytwo/) theme
2. Buy subscription
3. Go to My Account > Subscriptions page
4. Notice that there is no Subscription ID (#) as a title

### Actual behavior
Subscription ID (#) should be presented as title

### Screenshots

How it looks like: 
![image](https://user-images.githubusercontent.com/15913573/171834617-9d926615-2236-4aba-aec1-ff4b655ee79a.png)
### Expected behavior

How it should look like:

![image](https://user-images.githubusercontent.com/15913573/171835456-a912b006-4ed5-418e-904b-223327ba65e7.png)

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by haszari** [comment] 2022-06-08 19:59
Tagging this as `high` since it's a regression with default theme and hopefully is not complex to fix.

**Comment by haszari** [comment] 2022-06-08 20:18
Just tested this with WC Subscriptions installed. I

**Comment by haszari** [comment] 2022-06-08 20:18
Just tested this with WC Subscriptions installed. I

**Comment by deepakpathania** [comment] 2022-06-22 07:14
@haszari Since we are using the other issue for discussion now, is it ok to close this one or would you prefer if we keep it open till that is closed? 
cc @zmaglica

**Comment by haszari** [comment] 2022-06-22 20:18
> Since we are using the other issue for discussion now, is it ok to close this one or would you prefer if we keep it open till that is closed?

Please keep this issue open. The bug affects WCPay (and WC Subscriptions) so we should have an open issue in WCPay repo for tracking; subscriptions-core is a code library. Thanks 👏

**Comment by haszari** [comment] 2022-07-07 22:53
This issue is unrelated to subscriptions, all the `My account` subsection titles are broken in Twenty Twenty-Two.

I've reported this to WC core and will close this issue.

- https://github.com/woocommerce/woocommerce/issues/33774

**Closed by haszari** 2022-07-07 22:53 UTC
Labels: type: bug, priority: high, component: saved cards and subscriptions, needs subscriptions core update
