### ISSUE TITLE
fix: WC onboarding breaks when selecting WCPay and Jetpack

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#1663] opened 2021-04-22 02:35 UTC
## Description

The onboarding experience is throwing an error when setting up a new site with Jetpack and WCPay.

## Steps to reproduce
- Go to https://jurassic.ninja/specialops/
- Create a site with WC (but no Jetpack)
![Screen Shot 2021-04-21 at 9 33 29 PM](https://user-images.githubusercontent.com/273592/115647367-42feb300-a2e9-11eb-91b9-90abff3f4616.png)
- Once done, go through the WC onboarding 
- On the "Business details" section, select only Jetpack and WCPay, then click "continue"
- See the error
![Screen Shot 2021-04-21 at 9 35 28 PM](https://user-images.githubusercontent.com/273592/115647507-86592180-a2e9-11eb-8fcf-dab0d3070002.png)

**Comment by waclawjacek** [comment] 2021-04-22 10:18
I am currently investigating this and I'll post the results today. I have already pinpointed the cause to WCPay loading its own version of some of Jetpack's classes, and then Jetpack trying to use these classes.

This can be observed by going to the definition of `Jetpack::is_connection_ready()` in Jetpack and adding this as the first line:

```php
( new ReflectionClass( '\Automattic\Jetpack\Status' ) )->getFileName()
```

**Comment by waclawjacek** [comment] 2021-04-22 11:16
## Testing on WC 5.2.2

The plugin installation screen looks like this:

<img alt="Markup on 2021-04-22 at 13:07:52" src="https://user-images.githubusercontent.com/1759681/115704697-fad4a480-a36b-11eb-9ed7-e01334c671ce.png" height="400">

Both Jetpack and WCPay are installed correctly. The request to install them is:

```
POST /wp-json/wc-admin/plugins/install?_locale=user
[HTTP/2 200 OK 4067ms]

	
plugins	"woocommerce-payments,jetpack"
```

And then, the request to activate the plugins is:

```
POST /wp-json/wc-admin/plugins/activate?_locale=user
[HTTP/2 500 Internal Server Error 484ms]

	
plugins	"woocommerce-payments,jetpack"
```

The error code is 500 and the errors are exactly as described in @frosso's initial post.

The list of installed plugins looks like this after getting the error, indicating that the problem happens when trying to activate Jetpack when WCPay is already active:

<img alt="Markup on 2021-04-22 at 13:11:26" src="https://user-images.githubusercontent.com/1759681/115704988-4ab36b80-a36c-11eb-9982-23a470464e9f.png" height="400">

The same thing happens on WCPay 2.2.0, 2.1.1, and 2.0.0.

## Testing on WC 5.1.0

The plugin installation screen looks like this:

<img alt="Markup on 2021-04-22 at 13:07:04" src="https://user-images.githubusercontent.com/1759681/115705067-5dc63b80-a36c-11eb-9471-a202a602d725.png" height="400">

The error doesn't happen on WooCommerce 5.1.0 and the plugin order is different for both the `install` and `activate` requests:

```
POST /wp-json/wc-admin/plugins/install?_locale=user
[HTTP/2 200 OK 8828ms]

	
plugins	"jetpack,woocommerce-services,woocommerce-payments,facebook-for-woocommerce,mailchimp-for-woocommerce,kliken-marketing-for-google,creative-mail-by-constant-contact"
```

The order of plugins is different in the `install` and `activate` requests here. My guess is that the new onboarding wizard tries to activate the plugins in a different order, resulting in this issue.

However, even if the activation order is different, it shouldn't matter -- action/filter priorities and appropriate conditions should be making sure this doesn't happen.

**Comment by waclawjacek** [comment] 2021-04-22 12:27
@jrodger mentioned that the Jetpack autoloader should always load the latest versions of classes (p1619091754497000/1619091111.496100-slack-CGGCLBN58). After testing with older versions of Jetpack (the current version being `9.6.1`), it turned out that this regression was introduced in `9.6`. `9.5.2` is the last version that is working correctly.

This can be tested by:

1. Installing WooCommerce on a new site (and nothing else).
1. Going through the onboarding flow, selecting WCPay and Jetpack as the plugins to install.
1. The installation will fail but leave this page open.
1. In a new tab, go to the Plugins page. WCPay will be enabled, Jetpack will be installed but disabled.
1. Remove the installed version of Jetpack and replace it with [Jetpack 9.5.2](https://downloads.wordpress.org/plugin/jetpack.9.5.2.zip).
1. Click *Retry* in the tab with the WC onboarding.
1. Setup will continue.

Alternatively, this flow can be tested by first installing Jetpack 9.5.2 (regardless of whether it's active) and then attempting the onboarding in which case there will be no error at any point of the process.

This probably makes this a Jetpack issue so I am opening an issue in the Jetpack repository.

**Closed** 2021-06-03 11:40 UTC
Labels: priority: high, type: bug
