### ISSUE TITLE
Order numbers not showing in transaction lists, order not refundable

### ISSUE THREAD

**Issue by mouligreenlaw** [Automattic/woocommerce-payments#3857] opened 2022-02-24 23:14 UTC
### Describe the bug
Issue #3440 covered transaction details not appearing on orders, and order numbers not showing in the transaction list.
When the above was closed and the fix released in 3.7, user on 4790201-zen reported that, whilst the transaction details are now added to the order details, the order numbers are still not showing in the transaction lists.

### To Reproduce
Check Payments ➔ Transactions via 4790201-zen 

### Actual behavior
Order numbers are not showing in the Transactions list

### Screenshots

![https://d.pr/i/WsaKdE](https://d.pr/i/WsaKdE+) 
Full Size: https://d.pr/i/WsaKdE

### Expected behavior
Order numbers are included in the Transactions list

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context
Discussed this with @jrodger via Slack who requested that this issue be submitted.
https://a8c.slack.com/archives/C7U3Y3VMY/p1643799914196429

**Comment by jrodger** [comment] 2022-03-04 14:31
Thank you for writing this up @mouligreenlaw.

There's one thing we need to check before investigating this further. The behaviour we're seeing here is consistent with what we would expect for a WCPay account involved in a Jetpack IDC (i.e. the order numbers aren't shown because that order doesn't exist on this store).

Can you confirm that new orders (so, orders that exist on the store) also don't appear in the transaction table?

**Comment by billrobbins** [comment] 2022-03-04 20:14
We had another merchant with a block of order numbers that are missing from their transaction list.  These all say `N/A` instead of `-` as in the screenshot above.   4818729-zen

Orders before this and afterward appear in the list fine.  It's a busy site so there are about 250 orders affected over 3 days.  

![missing-orders-in-list](https://user-images.githubusercontent.com/1138631/156834873-af8eb194-5363-4337-91a0-b1afb6470179.png)

**Comment by aheckler** [comment] 2022-03-11 17:59
4845913-zen may be related, but the odd thing about this one is that the orders don't even show up under **WooCommerce > Orders**!!! Asking for creds to dig into this one.

**Comment by amElnagdy** [comment] 2022-03-13 20:13
Another one is here: 4854904-zen

**Comment by amElnagdy** [comment] 2022-03-14 16:36
Another report: 4852182-zen

**Comment by nicdwilson** [comment] 2022-03-16 02:59
Another report: 4845975-zen

`WooCommerce Payments/3.8.2`

1. Order number is missing from transaction list, shows as `N/A`
2. All transaction details are correctly stored in order
3. Order cannot be refunded
4. No unable to recover order exceptions recorded in payment logs - `payment_intent.succeeded` received and processed

**Comment by dreamtooloud** [comment] 2022-03-18 13:58
I have another report of this in **zd-4871103** . 

I did a little looking into the inspect tool and noticed that the refund button was missing completely, adding this to the javascript console resulted in the button showing up:

`<button type="button" class="button button-primary do-api-refund">Refund <span class="wc-order-refund-amount"><span class="woocommerce-Price-amount amount">$0.00</span></span> via WooCommerce Payments</button>`

Not sure what would happen if I clicked the button after adding it via the console (I assume not the expected behaviour of having the refund process?). Oddly, the script for the `refund manually` button does appear in the console, but as expected--it is marked as `hidden`.  Also don't know if it's completely helpful information, since we know the button is missing already xD But wanted to add this information just in case. 

I also added the script for the order number to show under transactions, and then clicked the link that showed and it worked as expected: 

`<a href="https://yoursite.here/wp-admin/post.php?post=1223&amp;action=edit" data-link-type="external">1223</a>`

Again, this information might not be super helpful, since we know these two elements are missing--but figured I'd add it anyway. 

Other notes: 

- This customer has a mix of the `-` and the `n/a` listed in the `Order #` column under `transaction` in their Payments menu. 
- I noticed the user had UPE turned on, which I know was connected to the original issue #3440 .  They don't have any localized payment methods selected, so I asked them to disable it temporarily to see if that helps. 
- I attempted to test UPE on my test site but wasn't able to replicate the issue. I suspect it's because I'm in test mode? 


This merchant is a very high volume merchant, so it is impacting their operations quite a bit.

**Comment by zoupkat** [comment] 2022-03-18 17:47
Another report: 4863536-zen

The Refund button is missing and the WC Pay order number does not become a link (it stays grey):
![https://d.pr/i/UWl3iE](https://d.pr/i/UWl3iE+)
Full Image: https://d.pr/i/UWl3iE

**Comment by kaushikasomaiya** [comment] 2022-03-28 04:36
Possibly 4899132-zen

**Comment by tijosh** [comment] 2022-03-28 15:48
4892956-zen

This one's slightly different, but it seems related to this issue.

Initial charge to the pi_ failed due to failed zip code validation. There was a subsequently successful ch_ charge, though. 

When attempting to refund that successful charge, this order note was added:

> A refund of £10.00 GBP failed to complete: Error: This PaymentIntent (pi_.....) does not have a successful charge to refund.

Confirmed that the transaction in the list is missing the order number:

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/35117248/160437013-cc19231a-c2ac-480f-9b76-5f6957e4a4f6.png">

**Comment by gabrielbonifacio** [comment] 2022-03-30 23:53
Also observed on 4908232-zen

**Comment by nawaz0705** [comment] 2022-04-04 05:04
> 4908232

Observed similar issue on 4914473 - zen

**Comment by neilmccreadie** [comment] 2022-04-08 13:36
> 4892956-zen
> 
> This one's slightly different, but it seems related to this issue.
> 
> Initial charge to the pi_ failed due to failed zip code validation. There was a subsequently successful ch_ charge, though.
> 
> When attempting to refund that successful charge, this order note was added:
> 
> > A refund of £10.00 GBP failed to complete: Error: This PaymentIntent (pi_.....) does not have a successful charge to refund.
> 
> Confirmed that the transaction in the list is missing the order number:
> 
> <img alt="image" width="1084" src="https://user-images.githubusercontent.com/35117248/160437013-cc19231a-c2ac-480f-9b76-5f6957e4a4f6.png">

Same here: 4932303-zen

**Comment by htdat** [comment] 2022-04-12 05:32
From @jessy-p 

>  I have the possible fix and will create PR in the next Sprint.
> 
> (Source: p1649738294145249/1649667648.020739-slack-C01BPL3ALGP)

**Comment by aheckler** [comment] 2022-04-12 18:52
Another example of a refund going wrong in 4932639-zen. Redacted screenshot: 

![Screenshot taken on 2022-04-12 at 18 49 30 UTC@2x](https://user-images.githubusercontent.com/5512652/163032956-bbda48c8-49ae-4ef4-8446-58ed4114c24c.png)

**Comment by aheckler** [comment] 2022-04-20 13:52
4961560-zen

**Comment by wyter** [comment] 2022-05-03 11:02
4964261-zen I've informed them that there's a fix in the coming update.

**Comment by wyter** [comment] 2022-05-11 13:37
5188794-zen I've asked them to update to the latest version of WooCommerce Payments

**Comment by thelogicwizards** [comment] 2022-05-23 22:02
5222342-zen 

Re-opening this issue since it seems like this is still happening even after our update. See the ticket and this user- submitted video for perspective: https://www.loom.com/share/212f7173073c44ffa1e34977655fd48d

**Comment by htdat** [comment] 2022-05-24 02:25
@thelogicwizards - thanks for reporting. As I see this issue happens for subscription orders made by the subscription feature of WCPay. 

@Automattic/helix can you have a deeper look at this issue? The ticket seems to have everything we need to debug (SSR, creds, etc).

**Comment by haszari** [comment] 2022-05-24 21:05
> As I see this issue happens for subscription orders made by the subscription feature of WCPay.

Thanks for letting us know @htdat – I was not aware that this issue was related to subscriptions. Do you know any other information that we could add to the issue?

I see that there's a PR from @jessy-p that fixes this – do we still need to investigate? 

- https://github.com/Automattic/woocommerce-payments/pull/4131

**Comment by htdat** [comment] 2022-05-25 01:53
@haszari - I think yes. The PR #4131 by Jessy was included in WCPay 4.1.0, and the merchant in the comment https://github.com/Automattic/woocommerce-payments/issues/3857#issuecomment-1135179009 has this info in their SSR `WooCommerce Payments: by Automattic – 4.1.0`

**Comment by haszari** [comment] 2022-05-25 01:59
@james-allan (current Helix reviewer) – can you take a look at this and see if there's something subscriptions-related for us to follow up?

@htdat if you have any details about how this relates to subscriptions – please add to the issue to help us understand and investigate.

Also would be good to add a comment to that PR (#4131) to clarify that it doesn't fix the issue. Based on that PR I don't have enough info to understand if it was a "maybe" fix (experiment) or if it was expected to actually fix this.

**Comment by htdat** [comment] 2022-05-25 02:33
As discussed here p1653444370450079-slack-CGGCLBN58, we're going to close this issue again and move this specific comment https://github.com/Automattic/woocommerce-payments/issues/3857#issuecomment-1135179009 to a new issue https://github.com/Automattic/woocommerce-payments/issues/4288

@james-allan - please look at the new issue. Thank you. 
@thelogicwizards - in case, you need to update the merchant, also follow up the new issue.

**Closed by htdat** 2022-05-25 02:33 UTC
Labels: type: bug, priority: high, component: transactions, component: upe, category: core, needs prioritisation
