### ISSUE TITLE
Non UK-issued Card was charged intl fee, but displayed UK-based fee breakdown

### ISSUE THREAD

**Issue by CGA8C** [Automattic/woocommerce-payments#5705] opened 2023-03-09 13:34 UTC
### Describe the bug

The Merchant in 5946860-Zen was charged an International Fee (1.4% + 0.20 + 2%) for a Credit Card with an EU-Issued BIN, but the Order Notes and Transaction Details page displayed only (1.4% + 0.20). 

To be clear, the fee was properly charged according to Stripe's definition (5962182-Zen), and displayed the correct total, but the Fee Breakdown did not display as expected (screenshots below.)

### To Reproduce

It's not clear to me how to reproduce, as this was a specific card issued by JP Morgan Europe. 

The customer was located in the UK, and the card seems to have been issued in the UK, but Stripe reports that the BIN is EU-issued. 

### Actual behavior

The fee International Fee (2%) was charged properly, but Order Notes and Transaction Details showed only the Base Fee (1.4% + 0.20).

### Screenshots
![Markup on 2023-03-09 at 12:23:32 PM](https://user-images.githubusercontent.com/17998077/224037052-5a1352ec-709e-4204-9672-bc87365b5a67.png)
![Markup on 2023-03-09 at 3:27:33 PM](https://user-images.githubusercontent.com/17998077/224037181-03afb6af-a931-42f4-8c0c-6041ec4ef98c.png)

### Expected behavior

The Fee Breakdown should show the appropriate fees (1.4% + 0.2 +2%). 

### Additional context
There has been a large amount of conversation related to this on Slack (Slack-C03EE4CPPK5) that may provide more context.

**Comment by CGA8C** [comment] 2023-03-09 14:02
I've created [this P2](https://wcpay.wordpress.com/2023/03/09/wc-pay-fee-breakdown-display-issue/) to accompany this Report 😄

**Comment by htdat** [comment] 2023-03-10 06:01
According to Pc2DNy-3z-p2, this falls in Pulsar, cc @kalessil. Tagging as a part of Gamma Porter duties PcreKM-yM-p2.

**Comment by nagpai** [comment] 2023-03-10 11:55
This may be related to #3037 and will be investigated when we check that. Thanks for reporting this in detail, @CGA8C !

**Comment by kalessil** [comment] 2023-04-03 12:49
I asked @nagpai to evaluate the case: if it's indeed related to https://github.com/Automattic/woocommerce-payments-server/issues/3037 we should close the issue.

**Comment by nagpai** [comment] 2023-04-04 15:12
On a closer check, it looks like this issue is different from https://github.com/Automattic/woocommerce-payments-server/issues/3037. That issue seems to be about UK cards, currently identified as not different from EU. They are currently not charged an international txn fee, that they should be paying. 

The issue here seems different. The card is Non-EU ( confirmed by Stripe based on its BIN ), and has been levied the additional 2%. However, due to some reason the timeline and order notes do not show the international fee component in break-up. The total fee is shown correctly. 

The issue is difficult to reproduce. Based on these details, should we keep the issue on hold for now until we see some more reports / find a way to reproduce this? @kalessil  WDYT?

**Comment by nagpai** [comment] 2023-04-04 17:08
The Payment intent summary does not seem to capture the Country of the card.  Details seem to be truncated since the transaction is more than 30 days old. Hence unable to confirm for myself, what was the identified country of the card. 

```
 "card": {
      "number": "**** **** **** 1409",
      "exp_month": "01",
      "cvc": "***",
      "exp_year": "28"
    },
```

Whereas on a test site with UK merchant and international (US) card, I see this for a recent transaciton. 

```
"card": {
            "brand": "visa",
            "checks": {
              "address_line1_check": "pass",
              "address_postal_code_check": "pass",
              "cvc_check": "pass"
            },
            "country": "US",
            "exp_month": 2,
            "exp_year": 2042,
            "fingerprint": "GPNBuIQZKl9E7Sku",
            "funding": "credit",
            "installments": null,
            "last4": "4242",
            "mandate": null,
            "moto": null,
            "network": "visa",
            "network_token": {
              "used": false
            },
```

If the issue is observed again, we will need to check the complete card details in the `Payment intend succeeded` log.

**Comment by nagpai** [comment] 2023-04-12 05:45
I am closing this issue for now. We can reopen if the issue occurs again with same or other user.

**Comment by nagpai** [comment] 2023-04-12 05:47
If the issue occurs again, please check the events of the payment on Stripe, and see if there is a country mentioned for the card / PM being used. It should have a country other than UK mentioned there, if there is an international fee charged.

**Comment by nagpai** [comment] 2023-04-17 04:30
Props to @CGA8C for citing another [transaction](https://dashboard.stripe.com/connect/accounts/acct_1MrFzA2HWwQRpgHW/payments/pi_3Mwj7D2HWwQRpgHW0K5lcxAU) related to same bank, but this time it was charged the correct fee ( no international fees ) 

The Payment Intent event details reveal clearly in this case, that the country of the card is `GB`

```
"payment_method_details": {
            "card": {
              "brand": "mastercard",
              "checks": {
                "address_line1_check": "pass",
                "address_postal_code_check": "pass",
                "cvc_check": "pass"
              },
              "country": "GB",
              "exp_month": 6,
              "exp_year": 2025,
              "fingerprint": "HjiF0yssptWgtnAi",
              "funding": "debit",
              "installments": null,
              "last4": "5622",
              "mandate": null,
              "network": "mastercard",
              "network_token": {
                "used": false
              },
```

For the original transaction this country data was truncated, since the transaction was older than 30 days, we have to go with the word of Stripe support that said that the country wasn't `GB`. In the future, if we come across a case of unexpected International fee, we will need to check the country that appears in the Payment method details object within the PI event. ( similar to the example right above )

**Comment by wyter** [comment] 2023-05-01 08:42
@nagpai, I'm reopening this as we've faced a similar issue on 6238474-zen, though the affected country is NL. An international fee was charged for a NL card.

Fee breakdown on the order page - 
![Annotation on 2023-05-01 at 11-40-39](https://user-images.githubusercontent.com/11092629/235430213-0e580a3c-00c7-423e-9a77-a4793fe3f5e6.png)


Fee in Transactions view - 
![Markup 2023-05-01 at 11 25 27](https://user-images.githubusercontent.com/11092629/235430120-a3e100f8-6951-4c10-9cf9-7db904b96dcd.png)

"payment_method_details": {
          "card": {
            "brand": "mastercard",
            "checks": {
              "address_line1_check": "unavailable",
              "address_postal_code_check": "unavailable",
              "cvc_check": "pass"
            },
            "country": "NL",
            "exp_month": 12,
            "exp_year": 2026,
            "fingerprint": "X7EgqUzDjJMm5ezv",
            "funding": "debit",
            "installments": null,
            "last4": "7156",
            "mandate": null,
            "network": "mastercard",
            "network_token": {
              "used": false
            }

**Comment by CGA8C** [comment] 2023-05-02 08:55
Just dropping a [direct link to the transaction](https://dashboard.stripe.com/acct_1MJg14C8mdD0V3U8/payments/pi_3N1EdCC8mdD0V3U8199bywMG) to make troubleshooting a bit easier :)

**Comment by nagpai** [comment] 2023-05-22 05:05
@wyter Thanks for gathering the info and reopening the case. I see there is a ticket already open to Stripe and we will need to wait and see what they say. 

Sorry about my late reply. I was afk when the ticket was reopened and may have missed the ping.

**Comment by nagpai** [comment] 2023-05-25 11:06
While we are still awaiting for a reply from Stripe, @dmvrtx  helped me with an interesting observation. 

For 3DS, the user was redirected to N26 website which is based in Germany, with base in New York as well.  

`"three_ds_method_url": "https://3ds-challenge.n26.com/3ds-method-start?org=NSZ",`

[3DS Event log](https://dashboard.stripe.com/acct_1MJg14C8mdD0V3U8/logs/req_rRYfRol54Vd4V1)

It is not clear why the card was charged an International fee, even if it were German issued ( within Europe ). It could be that customer has card account in a different currency or could be that N26 might issue cards with US BINs, since they have a base in New-York as well. 

N26 website indicates that they also issue Virtual cards, which may probably have a different BIN and seen as a foreign card.

**Comment by paulostp** [comment] 2023-05-26 11:09
@nagpai Stripe threw the ball back to our court and said that WooCommerce is indicating the `application_fee_amount` via the API request. Not sure if there's anything else you would like us to ask their support, please leave a note in the ticket if needed.

**Comment by conschneider** [comment] 2023-06-02 08:28
Hi @nagpai 
Is there anything we can help with for this?

**Comment by CGA8C** [comment] 2023-06-03 10:08
Hey @nagpai, Stripe replied with the above that Paulo mentioned, but that wasn't really what we were looking for. I've instead replied and asked for more information about the card (BIN info, location, etc) so we can narrow down what's going wrong in these situations. 

For the support portion, I've asked WC Pay Ops to refund the difference in fees, because the fees were displayed incorrectly. Once that's handled, that ticket can be closed, as it's not necessary for the Merchant to wait until this issue is fixed. @paulostp @conschneider

**Comment by nagpai** [comment] 2023-06-05 06:17
@CGA8C  Thanks for saving my day :) . Good call on both - asking more details from Stripe, and refund to the merchant. 

Thanks @paulostp  and @conschneider  for pursuing this 🙌 

Request - If I take longer in replying here, do ping me on Slack.

**Comment by CGA8C** [comment] 2023-06-12 12:43
@nagpai We've heard back from Stripe, but I'm not sure this really provides all that much assistance: 

> It's a bit different than our previous BIN issue I worked on with the Woo team but was able to look into this further.

>This BIN for N26 uses a range of numbers following the BIN to determine country, which is common on these virtual bank accounts. Since they allow there to be more than one country under this BIN using this range, it is possible the wrong can sometimes cause the discrepancy you're seeing and providing a country that doesn't match as expected.

>These can be difficult to narrow down or investigate on specific on our end since they're virtual accounts. Unfortunately we aren't able to provide exceptions on these long term given that it's possible this would prevent legitimate cardholders from checking out. 

Does this help at all? Is there anything more I should ask Stripe? 

I've asked if this fee seems like it was charged appropriately from their perspective, even if we're the ones charging it :) 

To me, it seems like we may have two different logic sets working here: one that actually charges the fee in the PI based on BIN or country, and another that's displaying the fee in the Order Notes and throughout the Merchant-Facing portion of WC Pay, which may be getting the country from elsewhere. 

But that's just my non-dev two cents, so I could be completely off-base. :)

**Comment by nagpai** [comment] 2023-06-12 13:10
Thanks @CGA8C ! I did read this reply last Friday, my bad, forgot to add my readings here. 

From what I read in their reply, it is very likely that virtual cards like N26 may end up presenting a country outside the local country ( EU in this case ) , and hence an international fee would apply. From the data we have ( including Stripe ) , it looks like we are unable to conclusively spot the country identified. 

I will check with my team if there is a way to log the country better for investigations like these. For now, I don't see much we can do. It will be nice to capture any other cases too, to see if we get any other patterns.  

I am also trying to find out why was the international fee not shown at all in the breakup. 
p2- pdjVC1-1Bk-p2

**Comment by kalessil** [comment] 2024-02-05 10:20
Marking as blocked, we'll re-iterate with Stripe.

**Comment by RadoslavGeorgiev** [comment] 2024-03-29 10:42
@kalessil what's the next step here, has Stripe already been contacted?

**Comment by kalessil** [comment] 2024-04-02 07:42
Closing: dUPE solved the root cause here.

**Closed as completed by kalessil** 2024-04-02 07:42 UTC
Labels: type: bug, component: timeline and events, component: application fees, focus: payments acceptance & processing
