### ISSUE TITLE
Checkout string on front end - Credit card / Debit card - doesn't get translated.

### ISSUE THREAD

**Issue by luanluta** [Automattic/woocommerce-payments#2835] opened 2021-09-02 13:51 UTC
### Describe the bug
The title for the method of payment appears in English as `Credit card / Debit card`  even though the language file itself contains the translated string in Italian.

### To Reproduce

1. Switch Site language to Italian
2. Update translations from Dashboard > Update > Update translations
3. Notice that translation is updated in back-end: https://d.pr/i/dc6ft2
4. But not on the checkout page: https://d.pr/i/AxoBTL

### Actual behavior
The method of payment title is in English rather than in Italian.

### Screenshots
![](https://d.pr/i/AxoBTL+) 
Full Size: https://d.pr/i/AxoBTL

### Expected behavior
The string should appear in Italian.

### Additional context
The string appears in Italian in the back-end: 

![https://d.pr/i/dc6ft2](https://d.pr/i/dc6ft2+) 
Full Size: https://d.pr/i/dc6ft2

Slack thread: p1630558302117400/1630558122.117300-slack-C7U3Y3VMY
ZD Ticket: 4264335-zd-woothemes

For some reason, the title is always pulled from [this line](https://github.com/Automattic/woocommerce-payments/blob/dfab42ec7b0eef7896b4b7837bc6f45e7da89960/includes/payment-methods/class-cc-payment-method.php#L25) even though the language file itself contains the translated string.

Possibly related: https://github.com/Automattic/woocommerce-payments/issues/1894

**Comment by KarlisJ** [comment] 2021-11-03 08:09
I've been able to reproduce the issue only using v2.8.2 and the behavior is inconsistent. I suspect there has been a problem within the release cycle. 

For the user encountering the issue, I'd suggest upgrading the plugin's version which will force to update translation files.

**Comment by melek** [comment] 2021-11-26 21:24
@KarlisJ We've encountered this bug with a couple French speaking customers lately, and was able to reproduce it on the first try on Woo Payments (latest version, 3.3.0).

Uninstalling and reinstalling the plugin did not resolve the issue, and as it is the latest version updating isn't an option. I also couldn't Reopening for now, sorry if that is premature - but couldn't get Loco Translate / Say What to work, so we ended up using janky CSS workarounds and would like to know if there is something better we can tell folks.

- 4465007-zen - French.
- 4548546-zen - French. They say it was working until recently.

Sidenote: The name of the plugin under **WP Admin → Plugins** was in French before I uninstall/reinstalled during testing, and was in English afterwards. No idea if that is related or not.

**Comment by melek** [comment] 2021-11-30 20:46
I've narrowed this down to only occurring when the new checkout experience is enabled on the site. When it is not enabled, translation is perfect.

I believe the error is that the AJAX for the New Checkout Experience fails to translate the string, using a hardcoded value instead. I tried to work around this with a filter:
```
add_filter( 'woocommerce_gateway_title', 'translate_wcpay_payment_gateway_title', 100, 2 );
function translate_wcpay_payment_gateway_title( $title, $payment_id ){
    if( $title === 'Credit card / debit card' ) {
        $title = __( 'Credit card / debit card', 'woocommerce-payments' );
    }
    return $title;
}
```

But I got this buggy front-end behavior where the translated title would briefly appear, then the checkout form would reload with the untranslated string.

**Comment by htdat** [comment] 2021-12-01 07:04
This PR seems to fix this issue https://github.com/Automattic/woocommerce-payments/pull/3409

This build includes the fix https://github.com/Automattic/woocommerce-payments/releases/download/3.4.0-test-2/woocommerce-payments.zip

@melek - can you check if it helps? NOTE: this build is not ready for production.

> I tried to work around this with a filter:

This filter is a great workaround!

**Comment by melek** [comment] 2021-12-01 07:14
> @melek - can you check if it helps? NOTE: this build is not ready for production.

This worked great! With New Checkout Experience this build translated the string properly. 

> This filter is a great workaround!

The filter actually did not workaround the issue (an AJAX refresh of the checkout form wiped out the forced translation), but I did try ;)

**Comment by htdat** [comment] 2021-12-01 08:51
Thank you. I am going to close this issue, and marking this as a duplicate of #3299

Feel free to re-open it if it's still the case.

**Closed by htdat** 2021-12-01 08:51 UTC
Labels: type: bug, good first issue, priority: high, category: duplicate, needs feedback, category: i18n
