### ISSUE TITLE
In-Person Payments: new endpoint, register payment without capture

### ISSUE THREAD

**Issue by kalessil** [Automattic/woocommerce-payments#3803] opened 2022-02-15 08:03 UTC
Context: pdjVC1-i3-p2

Mobile teams requested the endpoint and it seems to be a blocker for them.
Requirements have been specified here: pdfdoF-rU-p2Please

Tasks:
- re-evaluate if we need the endpoint
- implement the endpoint if needed
- loopback mobile teams with P2 describing the endpoint (URL and etc)

**Comment by anu-rock** [comment] 2022-02-21 12:23
Duplicate of #3764

**Comment by anu-rock** [comment] 2022-02-22 13:08
After discussing with the mobile team, we've concluded that a new endpoint is not required. However, we'll update the existing capture terminal payment endpoint to support this use case.

**Closed** 2022-02-23 13:14 UTC
Labels: priority: high, component: card present, category: projects
