### ISSUE TITLE
Orders with only shipping line items cause level 3 errors

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#1463] opened 2021-03-31 12:19 UTC
**Tickets**
3868784-zen

**Issue**
Similar to issue 1190.
If a order only has a shipping line item, it causes an error like this when trying to check out:

> Error: Missing required param: level3[line_items].

**To replicate**
1. Create a new order in the admin.
2. Use _Add item(s)_ and then _Add shipping_.
3. Make sure the order status is _Pending payment_ and then create the order.
4. Use the _Customer payment page_ link to go to the checkout page for the order.
5. Attempt to checkout and you will receive the error.

**Possible fix**
The first thing that comes to mind is if `$level3_data['line_items']` is empty in the `get_level3_data_from_order` method, then add a zero cost line item to the line items...

From my logs when a $0 fee is added.
```
  'level3' => 
  array (
    'line_items' => 
    array (
      0 => 
      array (
        'discount_amount' => 0,
        'product_code' => '0-00-fee',
        'product_description' => '$0.00 fee',
        'quantity' => 1,
        'tax_amount' => 0,
        'unit_cost' => 0,
      ),
    ),
    'merchant_reference' => '78',
    'shipping_address_zip' => '34476',
    'shipping_amount' => 1000,
    'shipping_from_zip' => '34476',
  ),
```

**Work around**
Use _Add item(s)_ and then _Add fee_. Create a fee with a cost of 0, and then have the customer pay for the order. It will then go through.

**Comment by tpaksu** [comment] 2021-06-08 08:29
Hi @jessepearson,

Is this issue fixed? I couldn't reproduce the error you've mentioned above. The steps I've tried:

- Clicked the "Add Order" button in WooCommerce > Orders page
- Clicked "Add Item(s)" button, then "Add Shipping", "Save", then a shipping item with 0 price was added to the list
- Ensured that the Order Status is "Pending Payment" and the user is selected as "Admin"
- Clicked "Create" to create the order.

The "Customer payment page" link didn't show up, Also I navigated to the frontend and navigated to "My Account > Orders" page, and there wasn't a "Pay" button, but the order was still marked as "Pending Payment".

Also I've tried adding a non-zero shipping item to a new order, and it had the link, clicked and paid it without any errors.

Can you please confirm? Or tell me what I might have done wrong? If you need a screencast, I'll be happy to prepare one.

**Comment by tpaksu** [comment] 2021-06-08 08:43
Nevermind, I was using a different payment method 😬

**Comment by tpaksu** [comment] 2021-06-08 23:39
### Question

Will it be better if we handle this issue on the server side, add a zero priced dummy item to the list when the list is empty before proxy'ing the request to Stripe to prevent errors related to it? 

https://github.com/Automattic/woocommerce-payments-server/blob/c6f507f456b933191a08fc38e8671790adc115a2/server/wp-content/rest-api-plugins/endpoints/wcpay/class-intentions-controller.php#L295-L308

Or,

Will it be better to fix it on the client side, in the method below, before the request is sent to the WCPay server? In the future we may need to send it empty intentionally, and fixing it on the server will require additional development for that, but IMHO, I don't believe Stripe will allow it to be empty in the future, they'll instead add a Level 4 data.

https://github.com/Automattic/woocommerce-payments/blob/1d678c40e21c1cb16ba288d2d49d8c12f81cf36b/includes/wc-payment-api/class-wc-payments-api-client.php#L1182-L1184

I guess downgrading the list items to Level I or Level II when any items are present on the list, is not an option, since we also need to send the shipping costs and addresses too. Also would be an overkill for this issue.

**Closed** 2021-06-10 16:48 UTC
Labels: component: checkout, good first issue, priority: low, size: small, status: has PR, type: bug
