### ISSUE TITLE
Enabling Multi-Currency Exempts All Pages From Batcache

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/woocommerce-payments#8691] opened 2024-04-22 23:25 UTC
### Describe the bug
When the multi-currency option is enabled, a cookie is loaded on the site that causes batcache to abort. This makes all pages where the cookie loads uncacheable, which has a negative impact on performance.

![CleanShot 2024-04-22 at 17 15 07@2x](https://github.com/Automattic/woocommerce-payments/assets/42279181/b70f3044-e91e-42d7-ab03-9af7315ad9c7)

### To Reproduce

1. Enable mutl-currency on a site with batcache.
2. Load the homepage
3. See that the homepage is not cached, and a cached copy is not returned.

I expected to see the homepage cachable, and both set cache and return cache hits. This impacts other pages as well. (It's expected that products and cart, etc are not cachable, but other non-Woo pages should be.)

### Actual behavior
When the page loads, batcache is aborted. Every visit requires generation and we lose the performance benefit of batcache site wide. This appears to be the result of setting the `wcpay_currency` cookie.

Toggling multi-currency off in Woo Payment settings results in these pages becoming cachable again right away.

### Expected behavior
For non-Woo pages to remain cachable and be served via batcache.

### Additional context
This issue impacts all WordPress.com atomic and Pressable sites, as well as any other self-hosted sites using batcache and potentially other caching solutions.

### Posssible Solution
If we need to set the `wcpay_currency` cookie on all page loads, could we use `vary_cache_on_function` to cache a copy of the page in each availble currency so we can retain some of the benefits that caching offers?

### More Info
We encountered this on a special projects partner site at launch, and had to remove the multi-currency functionality for performance reasons.

p1713385603172719/1713362615.682899-slack-C9S5YKAHJ

**Comment by pierorocca** [comment] 2024-04-23 19:46
@bborman22 @c-shultz speaking of performance, this looks like a great find from @katiebethbrown. Given scope of impact, let's please treat this one with urgency. If I'm not mistake, mccy is enabled by default on new sites.

**Comment by bborman22** [comment] 2024-04-23 20:04
Yes, great find. This one would be addressed by a fix for https://github.com/Automattic/woocommerce-payments/issues/8679 which we're picking up now for the current sprint to address. @rafaelzaleski just noting the other option here of the `vary_cache_on_function` function as a possible solution and sounds more like what the original intent was of the cookie in the first place.

**Comment by otarhe** [comment] 2024-04-26 20:25
We're also seeing some customers here at Pressable experiencing this issue which leads to bad site performance when Enabling Multi-Currency option is enabled.

**Comment by pierorocca** [comment] 2024-04-27 00:08
@otarhe @katiebethbrown any way to quantify how many merchants are impacted and have opened tickets? My concern and case for a patch is that lack of caching can increase merchant hosting costs and slow performance which impacts conversion. 

cc @c-shultz

**Comment by bborman22** [comment] 2024-04-29 18:24
We'll be reverting the cookie change that causes this caching issue in WooPayments 7.6.0 releasing on May 8 and will reopen the https://github.com/Automattic/woocommerce-payments/issues/8130 as we look for a better solution.

**Comment by bborman22** [comment] 2024-05-21 13:24
With https://github.com/Automattic/woocommerce-payments/pull/8738 we reverted the cause of this issue, so closing this issue as we explore a better fix for #8130

**Closed as completed by bborman22** 2024-05-21 13:24 UTC
Labels: type: bug, priority: high, impact: high, component: customer multi-currency, focus: multi-currency
