### ISSUE TITLE
[SCA] Cannot checkout if Stripe authentication is not answered

### ISSUE THREAD

**Issue by millerf** [Automattic/woocommerce-payments#2232] opened 2021-06-16 12:05 UTC
Original thread [here](https://a8c.slack.com/archives/CGGCLBN58/p1623840272096700) 

### How to reproduce

-  Intent to pay with SCA-enabled card (ie. 4000002760003184`
- When you see the SCA authentication, do not accept nor fail , just *close the window*
- Now try to checkout again and you will get 
```The provided PaymentMethod is already attached to another object. You cannot reuse PaymentMethods without attaching them to a Customer object first.```

For some reason, it only works for the first payment for this customer with this card (or some combination of those), as if the card has had a previous payment, the error doesn’t appeared….

[This issue was found with the TumblrPay theme, but it shouldn't make a difference as we only changed some styling, but no flow was changed]

### Screenshots

<img width="911" alt="Screenshot 2021-06-16 at 12 32 26" src="https://user-images.githubusercontent.com/790558/122215537-9e918b00-ceab-11eb-91b7-5e1c251ea57c.png">
<img width="640" alt="screenshot_2021-06-16_at_12 42 55" src="https://user-images.githubusercontent.com/790558/122215622-b79a3c00-ceab-11eb-8194-547e662f882e.png">

**Comment by naman03malhotra** [comment] 2021-12-17 14:24
Hi @millerf, do we have data on the frequency of occurrence of this error for the users? Maybe based on that we can take a call on the priority of this issue.
FYI: I am in process of triaging the issues for the WCPay repo.

**Comment by millerf** [comment] 2021-12-17 14:32
I haven't looked into it in a while. I think it would be worth retrying
those steps and see if it still occurs.

AFAIK, no one complained about it so far.

El dv., 17 de des. 2021, 9:24, Naman Malhotra ***@***.***> va
escriure:

**Comment by naman03malhotra** [comment] 2021-12-21 12:38
Hey @millerf, I've tried and I am not able to reproduce this issue with the given set of steps. I'll go ahead and close this for now.

**Closed by naman03malhotra** 2021-12-21 12:38 UTC
