### ISSUE TITLE
Settings: PM fee 'from' pill is not calculating the fee for iDeal in US properly

### ISSUE THREAD

**Issue by kalessil** [Automattic/woocommerce-payments#6531] opened 2023-06-14 08:37 UTC
### Describe the bug

![Screenshot from 2023-06-14 10-31-53](https://github.com/Automattic/woocommerce-payments/assets/1577185/23436e65-4b12-4182-9e0d-2a9066bf2b39)

It's expected to be from $0.80, but 1% is getting into the rendering somehow.

### To Reproduce

Connect a US merchant account and re-check if the rendering is the same as on the screenshot.

**Comment by zmaglica** [comment] 2023-06-26 11:13
This issue impacts Fees, so assigning to team Pulsar (based on team responsibilities) @kalessil . Assigning as part of Gamma Triage process PcreKM-yM-p2

**Comment by KarlisJ** [comment] 2024-01-18 11:56
Easily replicated. The problem is that we use format that expects both fixed and percentage part
```JS
/* translators: %1: Percentage part of the fee. %2: Fixed part of the fee */
fee: __( '%1$f%% + %2$s per transaction', 'woocommerce-payments' ),
```

but there's no fixed rate for iDeal. Probably, the `0` is mapped to `1` by some JS magic.

We should first check for a fixed rate and use a different format if it's zero, but it happens in `formatAccountFeesDescription`, which is a long and hard-to-reason function. At first glance, why it's so long? Will take some time to investigate. It could be a lot of dead code in there as well.

**Comment by kalessil** [comment] 2024-01-18 12:00
Thanks for re-evaluating @KarlisJ! If it's minor efforts, feel free to work on it.

**Closed as completed** 2024-02-08 11:52 UTC
Labels: type: bug, component: application fees, category: core
